### ISSUE TITLE
Problem with Dimmer in HTTP Binding

### ISSUE THREAD

**Issue by MrTheBarbarian** [openhab/openhab#1015]
Sorry if I am in wrong, but I think there is a problem.
This work Fine when I used for switch:
{http=">[ON:PUT:http://192.168.100.177/1/2/3/ON] >[OFF:PUT:http://192.168.100.177/1/2/3/OFF]",autoupdate="false" }
But when I tried to control dimmer and I wrote:
http=">[CHANGED:POST:http://192.168.100.177/?status=%2$s&date=%1$tY-%1$tm-%1$td"
This not working. 
LOG:
01:40:52.560 ERROR o.o.m.i.i.GenericItemProvider[:343]- Binding configuration of type 'http' of item ‘Light_GF_Living_Table‘ could not be parsed correctly.
org.openhab.model.item.binding.BindingConfigParseException: bindingConfig '>[CHANGED:POST:http://192.168.100.177/?status=%2$s&date=%1$tY-%1$tm-%1$td' doesn't contain a valid binding configuration
	at org.openhab.binding.http.internal.HttpGenericBindingProvider.parseBindingConfig(HttpGenericBindingProvider.java:127)
	at org.openhab.binding.http.internal.HttpGenericBindingProvider.processBindingConfiguration(HttpGenericBindingProvider.java:101)
	at org.openhab.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:341)
	at org.openhab.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:317)
	at org.openhab.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:171)
	at org.openhab.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:379)

**Comment by teichsta** [comment]
closed due to inactivity or missing feedback …
