### ISSUE TITLE
MPD stops working after several days

### ISSUE THREAD

**Issue by Nadaron** [openhab/openhab#1042]
I'm running openHAB 1.4 and MPD on a Raspberry Pi. The MPD plays some streams and is controlled by a KNX sensor via MPD Binding. This works fine ... most of the time. Around one week after the last openHAB restart the Binding stops working every time.

My only MPD items are:
```
Switch MPDBadSender			{ mpd="ON:bad:next,OFF:bad:prev"}
Dimmer MPDBad 				{ mpd="ON:bad:play, OFF:bad:stop, INCREASE:bad:volume_increase, DECREASE:bad:volume_decrease"}
```
In the openhab.log I see this error sometimes, but I don't think it's connect to the issue because it's still working after the error occured:
```
2014-04-27 15:28:32 INFO  o.o.b.mpd.internal.MpdBinding[:194]- executed commandLine 'stop' for player 'bad'
2014-04-28 00:00:00 ERROR org.quartz.core.ErrorLogger[:2361]- An error occured instantiating job to be executed. job= 'MPD.Reconnect'
org.quartz.SchedulerException: Problem instantiating class 'org.openhab.binding.mpd.internal.MpdBinding$ReconnectJob'
        at org.quartz.simpl.SimpleJobFactory.newJob(SimpleJobFactory.java:58)
        at org.quartz.simpl.PropertySettingJobFactory.newJob(PropertySettingJobFactory.java:69)
        at org.quartz.core.JobRunShell.initialize(JobRunShell.java:134)
        at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:387)
Caused by: java.lang.InstantiationException: org.openhab.binding.mpd.internal.MpdBinding$ReconnectJob
        at java.lang.Class.newInstance0(Class.java:354)
        at java.lang.Class.newInstance(Class.java:321)
        at org.quartz.simpl.SimpleJobFactory.newJob(SimpleJobFactory.java:56)
        at org.quartz.simpl.PropertySettingJobFactory.newJob(PropertySettingJobFactory.java:69)
        at org.quartz.core.JobRunShell.initialize(JobRunShell.java:134)
        at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:387)
Caused by: java.lang.NoSuchMethodException: org.openhab.binding.mpd.internal.MpdBinding$ReconnectJob.<init>()
        at java.lang.Class.getConstructor0(Class.java:2720)
        at java.lang.Class.newInstance0(Class.java:339)
        at java.lang.Class.newInstance(Class.java:321)
        at org.quartz.simpl.SimpleJobFactory.newJob(SimpleJobFactory.java:56)
        at org.quartz.simpl.PropertySettingJobFactory.newJob(PropertySettingJobFactory.java:69)
        at org.quartz.core.JobRunShell.initialize(JobRunShell.java:134)
2014-04-28 07:56:18 INFO  o.o.b.mpd.internal.MpdBinding[:194]- executed commandLine 'play' for player 'bad'
```
This is an example how it looks like when it's failing (2014-05-03 09:53:10). The PollingDelayFilter is a random occurrance and also not connect to the error, I think.
```
2014-05-02 05:03:57 INFO  o.o.b.mpd.internal.MpdBinding[:194]- executed commandLine 'stop' for player 'bad'
2014-05-02 10:18:24 INFO  o.o.b.mpd.internal.MpdBinding[:194]- executed commandLine 'play' for player 'bad'
2014-05-02 10:48:13 INFO  o.o.b.mpd.internal.MpdBinding[:194]- executed commandLine 'stop' for player 'bad'
2014-05-02 22:10:28 ERROR o.o.i.r.i.f.PollingDelayFilter[:70]- null
2014-05-02 22:10:53 WARN  o.a.cpr.DefaultBroadcaster[:500]- This message Entry{message=org.openhab.io.rest.internal.resources.beans.PageBean@1780c9, type=RESOURCE, future=org.atmosphere.cpr.BroadcasterFuture@1cec25b} will be lost
2014-05-03 09:53:10 ERROR o.o.b.mpd.internal.MpdBinding[:184]- error while executing PLAY command: null
2014-05-03 09:53:10 INFO  o.o.b.mpd.internal.MpdBinding[:194]- executed commandLine 'play' for player 'bad'
2014-05-03 09:54:14 WARN  o.o.b.mpd.internal.MpdBinding[:187]- unknow playerCommand 'stop'
2014-05-03 09:54:14 INFO  o.o.b.mpd.internal.MpdBinding[:194]- executed commandLine 'stop' for player 'bad'
```

Any ideas what causes this? More data needed?

**Comment by Nadaron** [comment]
I did an update to openHAB 1.6.2 and updated Java to the latest Version available on the Raspi. It's working fine now since 7 weeks. I think it had something to do with the Java version, when I set up the Raspi I needed to manually install a special version, today it's available as Raspbian package.
