### ISSUE TITLE
RRD4J throws unhandled exeption since #643

### ISSUE THREAD

**Issue by NSchnitzler** [openhab/openhab#1127]
Error.log is full with this message:
ERROR org.quartz.core.JobRunShell[:222]- Job rrd4j.everyMinute threw an unhandled Exception: 
java.lang.IllegalArgumentException: null
	at java.nio.Buffer.position(Buffer.java:244)
	at org.rrd4j.core.RrdNioBackend.read(Unknown Source)
	at org.rrd4j.core.RrdBackend.readInt(Unknown Source)
	at org.rrd4j.core.RrdPrimitive.readInt(Unknown Source)
	at org.rrd4j.core.RrdInt.get(Unknown Source)
	at org.rrd4j.core.Archive.<init>(Unknown Source)

config is:
Strategies {
	everyMinute : "0 * * * * ?"
}

**Comment by teichsta** [comment]
does this is issue still apply?

**Comment by teichsta** [comment]
closed to inactivity or missing feedback …

**Comment by steve-bate** [comment]
Closing based on @teichsta last comment.
