### ISSUE TITLE
Long-term binding issues

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab#1150]
After running OH for several days/weeks I notice some bindings (seems to be especially KNX and my.openhab) don't work anymore or with problems.

The KNX binding introduces a delay of several seconds until events from the event bus are pushed to the knx bus. The other way round still works fine.

My.openhab still shows as online in the online control panel and habdroid searches a long time but it won't connect.

Refreshing the bindings works. However, there is a stack trace which is not there when refreshing the said bindings just after openhab started so this may lead to the origin:
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
        at org.eclipse.equinox.console.commands.EquinoxCommandsConverter.convert(EquinoxCommandsConverter.java:61)
        at org.apache.felix.gogo.runtime.CommandProcessorImpl.convert(CommandProcessorImpl.java:254)
        at org.apache.felix.gogo.runtime.CommandSessionImpl.convert(CommandSessionImpl.java:374)
        at org.apache.felix.gogo.runtime.Reflective.coerce(Reflective.java:389)
        at org.apache.felix.gogo.runtime.Reflective.coerce(Reflective.java:310)
        at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:110)
        at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)
        at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
        at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
        at org.apache.felix.gogo.shell.Console.run(Console.java:62)
        at org.apache.felix.gogo.shell.Shell.console(Shell.java:203)
        at org.apache.felix.gogo.shell.Shell.gosh(Shell.java:128)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)
        at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)
        at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
        at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
        at org.apache.felix.gogo.shell.Activator.run(Activator.java:75)
        at java.lang.Thread.run(Thread.java:744)

I'm running official 1.4 release on Wandboard DUAL ARM with java full version "1.8.0-b132".

Any ideas? 

-Thx

**Comment by cribskip** [comment]
After migrating to Raspberry 2 with whezzy all is fine, even after 30 days running.
So seemed to be a problem with the Wandboard :-(
