### ISSUE TITLE
Homematic binding throws exception when connecting to CCU1

### ISSUE THREAD

**Issue by dohnalj** [openhab/openhab#1303]
I get the following exception when connecting to my CCU1 with the latest build of Homematic binding. When I use the older version (from July 18) everything works perfectly.

22:03:32.863 INFO  o.o.b.h.i.c.HomematicCommunicator[:68]- Starting Homematic communicator
22:03:33.283 ERROR o.o.b.h.i.c.HomematicCommunicator[:95]- Could not start Homematic communicator: -1 getVersion: unknown method name (sending BinRpcRequest[methodName=getVersion,args={}])
org.openhab.binding.homematic.internal.communicator.client.HomematicClientException: -1 getVersion: unknown method name (sending BinRpcRequest[methodName=getVersion,args={}])
        at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:178)
        at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.getServerId(BinRpcClient.java:99)
        at org.openhab.binding.homematic.internal.communicator.HomematicCommunicator.start(HomematicCommunicator.java:79)
        at org.openhab.binding.homematic.internal.bus.HomematicBinding.updated(HomematicBinding.java:95)
        at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183)
        at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36)
Caused by: java.io.IOException: -1 getVersion: unknown method name
        at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:164)
        at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.getServerId(BinRpcClient.java:99)
        at org.openhab.binding.homematic.internal.communicator.HomematicCommunicator.start(HomematicCommunicator.java:79)
        at org.openhab.binding.homematic.internal.bus.HomematicBinding.updated(HomematicBinding.java:95)
        at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183)
        at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36)
22:03:33.303 INFO  o.o.b.h.i.c.HomematicCommunicator[:122]- Shutting down Homematic communicator

**Comment by teichsta** [comment]
fixed meanwhile. getVersion() is no longer used …
