### ISSUE TITLE
openhab jenkins build failed

### ISSUE THREAD

**Issue by HolgerHees** [openhab/openhab#1316]
the automatic jenkins build failed...

----------------

...g.openhab.binding.heatmiser/1.6.0-SNAPSHOT/org.openhab.binding.heatmiser-1.6.0-SNAPSHOT.deb
channel stopped
Sending e-mails to: xxx@gmail.com null
ERROR: 250 OK id=1XDbee-0005z1-A3

com.sun.mail.smtp.SMTPSendFailedException: 250 OK id=1XDbee-0005z1-A3
;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 501 <null>: recipient address must contain a domain

	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1112)
	at javax.mail.Transport.send0(Transport.java:195)
	at javax.mail.Transport.send(Transport.java:124)
	at hudson.tasks.MailSender.execute(MailSender.java:116)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.cleanUp(MavenModuleSetBuild.java:1038)
	at hudson.model.Run.execute(Run.java:1710)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:509)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:246)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 <null>: recipient address must contain a domain

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1686)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1098)
	... 8 more
Putting comment on the pull request
Finished: FAILURE

**Comment by teichsta** [comment]
i assume this can be closed now …
