### ISSUE TITLE
Unable to send attachment images from webcam

### ISSUE THREAD

**Issue by davidsuarez** [openhab/openhab#1324]
I want to send an email with the current frame registered by my webcam when a motion sensor is triggered. By now I'm able to send an email notification, but when I try to attach the image provided by my webcam it comes the next error message:

ERROR o.o.action.mail.internal.Mail[:97] - Error adding attachment to email.
org.apache.commons.mail.EmailException: Invalid URL set:http://admin:XXXXXX@192.168.0.17/image.jpg
        at org.apache.commons.mail.MultiPartEmail.attach(MultiPartEmail.java:367)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: http://admin:XXXXXX@192.168.0.17/image.jpg
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)

I guess there is some problem with this kind of formatted URL's because when I try with a different image from internet it works without any problem.

**Comment by 9037568** [comment]
setURL is attempting to pull the contents of the URL and failing with a 401 error code (Unauthorized).

**Comment by teichsta** [comment]
seem to be a configuration issue! Closed to due inactivity or missing feedback …

**Comment by Dan1001** [comment]
Hi,

Do you mind re-opening this? I have this same problem with an image from my webcam.

The rule reads: sendMail("me@address.com", "Doorbell ringing", "","http://admin:MYPASSWORD@192.168.1.145:80/dms.jpg")

I receive the same error (copied below). I don't think it can be a formatting issue, because the error is showing the correct url. And the URL definitely works, because a browser from the same PC running openhab displays the image correctly.

18:02:29.826 ERROR o.o.action.mail.internal.Mail[:97]- Error adding attachment to email.
org.apache.commons.mail.EmailException: Invalid URL set:http://admin:MYPASSWORD@192.168.1.145:80/dms.jpg
	at org.apache.commons.mail.MultiPartEmail.attach(MultiPartEmail.java:367)
	at org.apache.commons.mail.MultiPartEmail.attach(MultiPartEmail.java:311)
	at org.openhab.action.mail.internal.Mail.sendMail(Mail.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: http://admin:MYPASSWORD@192.168.1.145:80/dms.jpg
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at java.net.URL.openStream(URL.java:1037)
	at org.apache.commons.mail.MultiPartEmail.attach(MultiPartEmail.java:362)
	at org.apache.commons.mail.MultiPartEmail.attach(MultiPartEmail.java:311)
	at org.openhab.action.mail.internal.Mail.sendMail(Mail.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

Can I provide any more information?

thanks,

Dan

**Comment by Dan1001** [comment]
I've done some more testing - this works fine with unsecured images on the internal network - it's the username/password that causes the problem

Dan
