### ISSUE TITLE
OneWireBinding's retry doesn't work

### ISSUE THREAD

**Issue by PascalTurbo** [openhab/openhab#1399]
I'm working with a "weak" 1-Wire Setup so the system sometimes needs more than one try to gather values from the 1-Wire Module.
This shouldn't be a problem - simply increasing the "retry-count" and everything should work fine.

After increasing the retry-count to 100 I was getting more and more confused and have a look on the source code. The problem is, that a exception is thrown while reading:

    17:59:07.811 DEBUG o.o.b.o.i.OneWireBinding[:173]- reading from path 28.2FBD84050000 throws exception
    org.owfs.jowfsclient.OwfsException: Error received
	at org.owfs.jowfsclient.internal.OwfsClientImpl.readPacket(OwfsClientImpl.java:576)
	at org.owfs.jowfsclient.internal.OwfsClientImpl.exists(OwfsClientImpl.java:386)
	at org.openhab.binding.onewire.internal.OneWireBinding.execute(OneWireBinding.java:140)
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156)
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)

And in this case, the retry-mechanism doesn't work - because it stops trying after this exception.

Maybe it would additionally interesting to add a configuration for wating x ms between two retries.

**Comment by Dennis650** [comment]
Hi,

the problem is solved with this pull request: https://github.com/openhab/openhab/pull/2369

Greetings
Dennis

**Comment by Dennis650** [comment]
This can be closed: https://github.com/openhab/openhab/pull/2626
