### ISSUE TITLE
NPE when refresh item file

### ISSUE THREAD

**Issue by sebglon** [openhab/openhab#1419]
Openhab 1.5.0

When i change my item file, i get this error:

19:11:43.409 INFO  o.o.m.c.i.ModelRepositoryImpl[:97]- Refreshing model 'chaudiere.items'
19:11:43.526 ERROR o.o.m.c.i.f.FolderObserver[:105]- An unexpected exception has occured
java.lang.NullPointerException: null
	at org.openhab.model.item.binding.AbstractGenericBindingProvider.removeConfigurations(AbstractGenericBindingProvider.java:93)
	at org.openhab.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:164)
	at org.openhab.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:379)
	at org.openhab.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:158)
	at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:99)
	at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142)

**Comment by teichsta** [comment]
see also #736

**Comment by watou** [comment]
Just to note, PR #3016 might have corrected #2842, #3218, and this issue (#1419).  Could anyone run a recent nightly build and attempt to reproduce the problem?

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
