### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by bhelm** [openhab/openhab#1703]
i have too many open files on my openhab installation after ~5 days of continious running with openhab 1.5.1 (stable download) (with 1.6 hue and 1.6 maxcube plugin and 1.5.1 rfxcom and rrd4j, thats all).
i have dumped the lsof | grep java output to a file, its 11MB and has ~79000 entries:
http://rw23.de/openhab-openfiles
i noticed this because i were unable to open a new connection with the android remote.
also there are errors about this:
```
22:32:15.862 ERROR o.o.c.t.i.s.MapTransformationService[:75]- opening file 'de.map' throws exception
java.io.FileNotFoundException: configurations/transform/de.map (Too many open files)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:131)
        at java.io.FileInputStream.<init>(FileInputStream.java:87)
        at java.io.FileReader.<init>(FileReader.java:58)
        at org.openhab.core.transform.internal.service.MapTransformationService.transform(MapTransformationService.java:63)
        at org.openhab.ui.internal.items.ItemUIRegistryImpl.transform(ItemUIRegistryImpl.java:328)
22:32:15.873 ERROR o.o.u.i.i.ItemUIRegistryImpl[:330]- transformation throws exception [transformation=org.openhab.core.transform.internal.service.MapTransformationService@19c3976, value=OFF]
org.openhab.core.transform.TransformationException: opening file 'de.map' throws exception
        at org.openhab.core.transform.internal.service.MapTransformationService.transform(MapTransformationService.java:76)
        at org.openhab.ui.internal.items.ItemUIRegistryImpl.transform(ItemUIRegistryImpl.java:328)
        at org.openhab.ui.internal.items.ItemUIRegistryImpl.getLabel(ItemUIRegistryImpl.java:267)
        at org.openhab.io.rest.internal.resources.SitemapResource.createWidgetBean(SitemapResource.java:295)
        at org.openhab.io.rest.internal.resources.SitemapResource.createWidgetBean(SitemapResource.java:304)
        at org.openhab.io.rest.internal.resources.SitemapResource.createPageBean(SitemapResource.java:266)
Caused by: java.io.FileNotFoundException: configurations/transform/de.map (Too many open files)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:131)
        at java.io.FileInputStream.<init>(FileInputStream.java:87)
        at java.io.FileReader.<init>(FileReader.java:58)
        at org.openhab.core.transform.internal.service.MapTransformationService.transform(MapTransformationService.java:63)
        at org.openhab.ui.internal.items.ItemUIRegistryImpl.transform(ItemUIRegistryImpl.java:328)
```
it clearly ran out of file handles.

running on archlinux-arm on arm7h, hardware: cubietruck
java version "1.8.0_06"
Java(TM) SE Runtime Environment (build 1.8.0_06-b23)
Java HotSpot(TM) Client VM (build 25.6-b23, mixed mode)

if you need more informations, let me know.
thank you.

**Comment by bhelm** [comment]
the problem did disappear with openhab 1.6.1, my install ran fine for months!

**Comment by teichsta** [comment]
I would also assume this issue duplicates #1702 and is hence fixed in 1.7.0

**Comment by kaikreuzer** [comment]
> I guess, I see the same: this issue might be related to #1702.

Why do you think so? In the original issue description above, there is no my.openHAB involved at all. And besides this, my.openHAB does not open a single local file - so why should it cause "too many open files" error?

**Comment by teichsta** [comment]
because i didn't read the description carefully enough … changed milestone to 1.6.1
