### ISSUE TITLE
Weather Binding: Exception on Connection reset

### ISSUE THREAD

**Issue by juelicher** [openhab/openhab#1847]
Occasionally I get the following warning from the weather binding:
2014-12-15 04:34:00.163 ERROR o.o.b.w.i.p.AbstractWeatherProvider[:138]- YAHOO: Connection reset
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
2014-12-15 04:34:00.163 ERROR o.o.b.w.i.p.AbstractWeatherProvider[:138]- OPENWEATHERMAP: Connection reset
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)

The functionality seems to be OK, values get an update after the exception is thrown.

**Comment by sihui62** [comment]
Same here.
Siegfried

**Comment by teichsta** [comment]
could you please have a look at this @gerrieg? Thanks, Thomas E.-E.

**Comment by gerrieg** [comment]
fixed with https://github.com/openhab/openhab/pull/2607
