### ISSUE TITLE
InfluxDB bundle generates incomplete database queries at openHAB startup

### ISSUE THREAD

**Issue by hoalex** [openhab/openhab#1879]
I'm using the InfluxDB persistence bundle to store the temperature values of my FHT80b devices. I also have defined "restoreOnStartup" in "influxdb.persist", so that the last temperature values are set after restarting openHAB. Sadly, this does not work for me.

When restarting openHAB, I get the following messages at stdout for **every item that I have defined in influxdb.persist**:
```
17:39:46.018 [DEBUG] [i.i.InfluxDBPersistenceService:265  ] - got a query
17:39:46.019 [DEBUG] [i.i.InfluxDBPersistenceService:340  ] - got page size 1
17:39:46.019 [DEBUG] [i.i.InfluxDBPersistenceService:349  ] - query string: select value, time from FHT_AI where
17:39:46.038 [ERROR] [i.i.InfluxDBPersistenceService:354  ] - query failed with database error
17:39:46.041 [ERROR] [i.i.InfluxDBPersistenceService:211  ] - database connection error may be wrong password, username or dbname: {}
java.lang.RuntimeException: syntax error, unexpected $end
select value, time from FHT_AI where
                                    ^
	at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19) ~[na:na]
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242) ~[na:na]
	at org.influxdb.impl.$Proxy74.query(Unknown Source) ~[na:na]
	at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:110) ~[na:na]
	at org.openhab.persistence.influxdb.internal.InfluxDBPersistenceService.query(InfluxDBPersistenceService.java:352) [bundlefile:na]
	at org.openhab.core.persistence.internal.PersistenceManager.initialize(PersistenceManager.java:382) [org.openhab.core.persistence_1.7.0.201412230208.jar:na]
	at org.openhab.core.persistence.internal.PersistenceManager.initializeItems(PersistenceManager.java:212) [org.openhab.core.persistence_1.7.0.201412230208.jar:na]
	at org.openhab.core.persistence.internal.PersistenceManager.initializeItems(PersistenceManager.java:204) [org.openhab.core.persistence_1.7.0.201412230208.jar:na]
	at org.openhab.persistence.influxdb.internal.InfluxDBPersistenceService.updated(InfluxDBPersistenceService.java:258) [bundlefile:na]
	at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
	at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
```
Obviously, there is a part missing after the "where" clause. 
New temperature values are correctly saved in InfluxDB, and can be queried by the InfluxDB web interface and also Grafana, so the "saving" part works just fine. It's only the initial startup, i.e. the "restoreOnStartup" part, that fails.

I'm using the following versions:
openHAB: 1.7.0 nightly from 24/12/2014
InfluxDB persistence bundle: 1.7.0 nightly form 24/12/2014
InfluxDB: 0.8.7
running on Debian Wheezy 7.7 (64-bit)
```
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-2~deb7u1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
```

Any help on this?

**Comment by itheiss** [comment]
I can confirm the behaviour @hoalex has described. What has changed in 1.7?

**Comment by theoweiss** [comment]
I will have a look at it.

**Comment by theoweiss** [comment]
I found the bug. 
The bug is triggered by an inconsistent FilterCriteria as query() argument when restoreOnStartup is used:
23:58:56.439 [DEBUG] [i.i.InfluxDBPersistenceService:266  ] - got a query
23:58:56.439 [TRACE] [i.i.InfluxDBPersistenceService:293  ] - filter state: null
23:58:56.440 [TRACE] [i.i.InfluxDBPersistenceService:294  ] - filter operator: EQ
23:58:56.441 [TRACE] [i.i.InfluxDBPersistenceService:295  ] - filter getBeginDate: null
23:58:56.441 [TRACE] [i.i.InfluxDBPersistenceService:296  ] - filter getEndDate: null
23:58:56.441 [TRACE] [i.i.InfluxDBPersistenceService:297  ] - filter getPageSize: 1
23:58:56.441 [TRACE] [i.i.InfluxDBPersistenceService:298  ] - filter getPageNumber: 0
23:58:56.441 [DEBUG] [i.i.InfluxDBPersistenceService:347  ] - got page size 1

The State is null but the Operator is not null. Why?

I will prepare a Pull Request.

**Comment by teichsta** [comment]
fix merged into master

**Comment by hoalex** [comment]
Thanks @theoweiss. Just downloaded the compiled .jar from CloudBees, restoreOnStartup now works perfectly :+1:

**Comment by theoweiss** [comment]
Cool, thanks for testing.
