### ISSUE TITLE
Google Calendar binding throws an error on whole day events

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab#1884]
When entering a series of whole day events (e.g. school holidays), google calendar binding issues an error:
15:14:02.201 ERROR o.o.c.s.AbstractActiveService[:175]- Error while executing background thread Google Calender Event-Downloader
java.lang.NullPointerException: null
    at org.openhab.io.gcal.internal.GCalEventDownloader.createTriggerAndSchedule(GCalEventDownloader.java:455)
    at org.openhab.io.gcal.internal.GCalEventDownloader.processEntries(GCalEventDownloader.java:335)
    at org.openhab.io.gcal.internal.GCalEventDownloader.execute(GCalEventDownloader.java:177)
    at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)

Desired behavior:
Ignore these entries.

Desired extension of google calendar item:
Provide a binding that provides the title of the calendar entry as String item.
Use cases:
Whole day event processing like Birthdays, school holidays, etc..
Benefits: No tingering in the info field by the user.
Public informations source.e.g. school holidays can be used without rework by cut and paste.
##

**Comment by DocZoid** [comment]
Additional suggestion: The String item should be nulled after the whole day event has passed in order to have it always up-to-date (in case of multiple-days-events like holidays).

Still, I see difficulties if two or more whole-day-events occur on one day. In this case, it could be useful to set a switch to ON if the current day contains a whole-day-event of that type. E.g.: switch item holiday is switched ON on whole day events with title holiday (I would use that for reoccurring "bring waste bin down to road" reminder for multiple waste bin types).

**Comment by 9037568** [comment]
Is this still happening with the latest snapshot, @Marty56 ? There've been some changes made to gcal recently...

**Comment by Marty56** [comment]
I am now on OH2 pretty recent snapshot.
The binding is working quite reliable.
Sometimes after restart I am receiving an error message which I do not understand and which does not seem to have an affect.

`2016-12-18 12:00:12.095 [ERROR] [org.openhab.binding.caldav-personal ] - [org.openhab.binding.caldav_personal(150)] The addBindingProvider method has thrown an exception
java.lang.NullPointerException
	at org.openhab.binding.caldav_personal.internal.CalDavBinding.updateItemsForEvent(CalDavBinding.java:225)
	at org.openhab.binding.caldav_personal.internal.CalDavBinding.allBindingsChanged(CalDavBinding.java:134)
	at org.openhab.core.binding.AbstractBinding.addBindingProvider(AbstractBinding.java:61)
	at org.openhab.binding.caldav_personal.internal.CalDavBinding.addBindingProvider(CalDavBinding.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_112]`

It seems that there is not caldav.io anymore.
Under services I still have caldavCommand.cfg, caldavPersonal.cfg and caldavio.cfg.

I never understood why the user has to use so many different binding and configuration files.
Why not just one binding and one configuration.
I still find this confusing but somehow fiddled around to get it working in a trial and error approach.

**Comment by 9037568** [comment]
Glad to hear it's working.

**Comment by watou** [comment]
@9037568 Since there is an NPE in the log, should this issue be fixed?

**Comment by 9037568** [comment]
I would've said that should be a new ticket, but if @Marty56 can provide a full debug log and configuration info, we could look at it either way.

**Comment by watou** [comment]
Good point.  Upon re-reading this issue fully, I agree that it should be closed.  I was fixated on the NPE in the CaldavPersonal binding, but that's a different issue than the history.  Sorry!
