### ISSUE TITLE
Tellstick - Failed to init

### ISSUE THREAD

**Issue by Marvlis** [openhab/openhab#1926]
When I try to start OpenHAB I get the message 

```
"ERROR o.o.b.t.i.TellstickActivator[:50] - failed to init
java.lang.NullPointerException: null
        at org.openhab.binding.hdanywhere.internal.HDanywhereBinding.execute<HDanywhereBinding.java:243>"
```

I followed all the instructions on the wiki several times and on 2 different computers, but I'm obviously doing something wrong. Please let me know what I have to do to get this working.

Thanks,
          Aaron
##

**Comment by teichsta** [comment]
@Marvlis could you please provide some more lines of log! The statements seem to be mixed up.

If the logs are there, can anybody of you @jarlebh @seime help out?

**Comment by seime** [comment]
"ERROR o.o.b.t.i.TellstickActivator[:50] - failed to init" seems to be related to the native library wrapper (init of Tellstick libraries). 

Could you provide some more details about platform, installed Tellstick software etc? Full log since startup would also be helpful.

**Comment by Marvlis** [comment]
Hi Teichsta and Seime,
     Happy new year guys! Thanks for your help with this. Here is the text for log.

09:30:43.801 WARN  o.o.c.core.ConfigDispatcher[:172]- Main openHAB configuration file 'configurations/openhab.cfg' does not exist.
09:30:43.881 INFO  o.o.c.internal.CoreActivator[:61]- openHAB runtime has been started (v1.5.1).
09:30:46.809 INFO  o.o.i.s.i.DiscoveryServiceImpl[:72]- mDNS service has been started
09:30:48.375 INFO  o.o.io.rest.RESTApplication[:143]- Started REST API at /rest
09:30:57.241 INFO  o.o.u.w.i.s.WebAppServlet[:79]- Started Classic UI at /openhab.app
09:33:18.700 WARN  o.o.c.core.ConfigDispatcher[:172]- Main openHAB configuration file 'configurations/openhab.cfg' does not exist.
09:33:18.700 INFO  o.o.c.internal.CoreActivator[:61]- openHAB runtime has been started (v1.5.1).
09:33:21.084 INFO  o.o.i.s.i.DiscoveryServiceImpl[:72]- mDNS service has been started
09:33:22.116 INFO  o.o.io.rest.RESTApplication[:143]- Started REST API at /rest
09:33:31.460 INFO  o.o.u.w.i.s.WebAppServlet[:79]- Started Classic UI at /openhab.app
09:33:39.828 INFO  o.o.c.s.AbstractActiveService[:169]- Sonos Refresh Service has been started
09:33:39.950 INFO  o.o.b.t.AbstractSocketChannelBinding[:768]- The maximum buffer will be set to the default value of 1024
09:33:39.950 INFO  o.o.b.t.AbstractSocketChannelBinding[:775]- The interval to retry connection setups will be set to the default value of 5
09:33:39.950 INFO  o.o.b.t.AbstractSocketChannelBinding[:782]- The cron job to reset connections will be set to the default value of 0 0 0 * * ?
09:33:39.950 INFO  o.o.b.t.AbstractSocketChannelBinding[:789]- The setting to queue write operation until a channel gets connected will be set to the default value of true
09:33:39.950 INFO  o.o.b.t.AbstractSocketChannelBinding[:796]- The port to listen for incoming connections will be set to the default value of 0
09:33:39.950 INFO  o.o.b.t.AbstractSocketChannelBinding[:803]- The setting to share channels within an Item will be set to the default value of true
09:33:39.950 INFO  o.o.b.t.AbstractSocketChannelBinding[:810]- The setting to share channels between the items with the same direction will be set to the default value of true
09:33:39.950 INFO  o.o.b.t.AbstractSocketChannelBinding[:817]- The setting to share channels between directions will be set to the default value of true
09:33:39.950 INFO  o.o.b.t.AbstractSocketChannelBinding[:824]- The setting to use address masks for incoming connections will be set to the default value of true
09:33:39.950 INFO  o.o.b.t.p.internal.TCPBinding[:171]- The maximum time out for blocking write operations will be set to the default vaulue of 3000
09:33:39.950 INFO  o.o.b.t.p.internal.TCPBinding[:178]- The blocking nature of read/write operations will be set to the default vaulue of false
09:33:39.950 INFO  o.o.b.t.p.internal.TCPBinding[:185]- The preamble for all write operations will be set to the default vaulue of 
09:33:39.950 INFO  o.o.b.t.p.internal.TCPBinding[:192]- The postamble for all write operations will be set to the default vaulue of 

09:33:39.950 INFO  o.o.c.s.AbstractActiveService[:169]- TCP Refresh Service has been started
09:33:39.950 INFO  o.o.b.t.p.internal.TCPBinding[:199]- Updating states with returned values will be set to the default vaulue of true
09:33:39.950 INFO  o.o.b.t.p.internal.TCPBinding[:206]- The characterset will be set to the default vaulue of ASCII
09:33:40.079 INFO  o.o.c.s.AbstractActiveService[:169]- RME Refresh Service has been started
09:33:40.435 INFO  o.openhab.io.cv.CVApplication[:145]- Started Cometvisu API at /services/cv
09:33:40.834 INFO  o.o.b.s.internal.SonosBinding[:769]- Querying the network for any other Sonos device
09:33:45.835 INFO  o.o.c.s.AbstractActiveService[:169]- Oceanic Refresh Service has been started
09:33:45.835 ERROR o.o.b.b.i.BTDeviceDiscoveryService[:217]- Error while initializing local bluetooth device.
javax.bluetooth.BluetoothStateException: BlueCove libraries not available
	at com.intel.bluetooth.BlueCoveImpl.createDetectorOnWindows(BlueCoveImpl.java:922)
	at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:460)
	at com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:69)
	at com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1044)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged(BlueCoveImpl.java:1042)
09:33:45.899 INFO  o.o.c.s.AbstractActiveService[:169]- FritzBox refresh Service has been started
09:33:46.013 INFO  o.o.c.s.AbstractActiveService[:169]- HDanywhere Refresh Service has been started
09:33:46.015 ERROR o.o.c.s.AbstractActiveService[:175]- Error while executing background thread HDanywhere Refresh Service
java.lang.NullPointerException: null
	at org.openhab.binding.hdanywhere.internal.HDanywhereBinding.execute(HDanywhereBinding.java:243)
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156)
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)
09:33:46.663 INFO  o.o.b.w.i.a.WithingsAuthenticator[:255]- #########################################################################################
09:33:46.663 INFO  o.o.b.w.i.a.WithingsAuthenticator[:256]- # Withings Binding needs authentication.
09:33:46.663 INFO  o.o.b.w.i.a.WithingsAuthenticator[:257]- # Execute 'withings:startAuthentication' on OSGi console.
09:33:46.663 INFO  o.o.b.w.i.a.WithingsAuthenticator[:258]- #########################################################################################
09:33:46.766 ERROR o.o.i.g.internal.GPIOActivator[:51]- No supported operating system was found, GPIO service won't be available
09:33:46.786 INFO  o.o.b.p.i.PifaceActivator[:30]- Piface binding has been started.
09:33:46.925 WARN  o.o.b.f.i.FritzboxBinding[:633]- Could not get item state
java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(Unknown Source)
	at java.net.PlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
09:33:48.087 ERROR o.o.b.t.i.TellstickActivator[:50]- Failed to init 
java.lang.UnsatisfiedLinkError: Unable to load library 'TelldusCore': Native library (win32-x86-64/TelldusCore.dll) not found in resource path (C:\Users\Marvlis\Downloads\openHAB\server\plugins\org.eclipse.equinox.launcher_1.3.0.v20120522-1813.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at com.sun.jna.Native.loadLibrary(Native.java:391)
	at org.openhab.binding.tellstick.internal.JNA$CLibrary.<clinit>(JNA.java:93)
09:33:48.137 INFO  o.o.c.s.AbstractActiveService[:169]- Exec Refresh Service has been started
09:33:48.639 INFO  o.o.c.s.AbstractActiveService[:169]- VDR Monitor Service has been started
09:33:48.709 INFO  o.o.b.k.internal.k8055Binding[:347]- No config supplied - using default values
09:33:48.739 INFO  o.o.b.s.i.SysteminfoBinding[:397]- Using Sigar version 1.6.4.129
09:33:48.739 ERROR o.o.b.s.i.SysteminfoBinding[:416]- System monitor error: {}
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Sigar.getNetInterfaceList()[Ljava/lang/String;
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220)
	at $Proxy73.getNetInterfaceList(Unknown Source)
	at org.openhab.binding.systeminfo.internal.SysteminfoBinding.initializeSystemMonitor(SysteminfoBinding.java:400)
	at org.openhab.binding.systeminfo.internal.SysteminfoBinding.updated(SysteminfoBinding.java:384)
	at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183)
	at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36)
09:33:48.749 INFO  o.o.c.s.AbstractActiveService[:169]- Systeminfo Refresh Service has been started
09:33:51.025 ERROR o.o.c.s.AbstractActiveService[:175]- Error while executing background thread HDanywhere Refresh Service
java.lang.NullPointerException: null
	at org.openhab.binding.hdanywhere.internal.HDanywhereBinding.execute(HDanywhereBinding.java:243)
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156)
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)
09:33:53.908 INFO  o.o.c.s.AbstractActiveService[:169]- SNMP Refresh Service has been started
09:33:54.341 INFO  o.o.c.s.AbstractActiveService[:169]- XBMC Refresh Service has been started
09:33:54.341 INFO  o.o.b.i.InsteonPLMActivator[:41]- Insteon PLM binding has been started.
09:33:55.253 INFO  o.o.c.s.AbstractActiveService[:169]- HTTP Refresh Service has been started
09:33:56.033 ERROR o.o.c.s.AbstractActiveService[:175]- Error while executing background thread HDanywhere Refresh Service
java.lang.NullPointerException: null
	at org.openhab.binding.hdanywhere.internal.HDanywhereBinding.execute(HDanywhereBinding.java:243)
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156)
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)
09:33:57.423 ERROR o.o.b.t.i.TellstickActivator[:50]- Failed to init 
java.lang.NoClassDefFoundError: Could not initialize class org.openhab.binding.tellstick.internal.JNA$CLibrary
	at org.openhab.binding.tellstick.internal.TellstickActivator.start(TellstickActivator.java:45)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
09:33:57.423 ERROR o.o.b.t.i.TellstickActivator[:50]- Failed to init 
java.lang.NoClassDefFoundError: Could not initialize class org.openhab.binding.tellstick.internal.JNA$CLibrary
	at org.openhab.binding.tellstick.internal.TellstickActivator.start(TellstickActivator.java:45)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
09:33:59.473 ERROR o.o.b.t.i.TellstickActivator[:50]- Failed to init 
java.lang.NoClassDefFoundError: Could not initialize class org.openhab.binding.tellstick.internal.JNA$CLibrary
	at org.openhab.binding.tellstick.internal.TellstickActivator.start(TellstickActivator.java:45)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
09:33:59.483 ERROR o.o.b.t.i.TellstickActivator[:50]- Failed to init 
java.lang.NoClassDefFoundError: Could not initialize class org.openhab.binding.tellstick.internal.JNA$CLibrary
	at org.openhab.binding.tellstick.internal.TellstickActivator.start(TellstickActivator.java:45)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)

**Comment by jarlebh** [comment]
You seem to have a lot of issues, but if you want to use Telldus/Tellstick
you will have to use a 32 Bits Java and make sure Telldus Center is
installed in the default location (otherwise special config is needed).
Also I have only tested on Java 1.7


2015-01-12 20:59 GMT+01:00 Marvlis <notifications@github.com>:

**Comment by Marvlis** [comment]
I have no idea what Telldus/Tellstick is, could you please tell me what it is? What other problems do I need to fix?

**Comment by seime** [comment]
You have probably unpacked all available bindings/content from the addons distribtion to your "addon" folder. Suggestion: Start all over again and only add the demo package. Then from the addons distribution add only the ones you are going to use.
