### ISSUE TITLE
Homematic binding java error with pssibly memory exhaust

### ISSUE THREAD

**Issue by fasa01** [openhab/openhab#1956]
Hi,

following error came yesterday and hours later the memory was empty, i'm not shure if this has the same reson ... I must additional say that the battery of the 'Garagentor' Sensor goes empty, i feel here is no error needed ... The version is 1.7-snapshot from thuesday this week 6.1.2015.

2015-01-09 08:08:16.413 [INFO ] [openhab.model.script.Gargentor] - Garagentor auf/zu executed
2015-01-09 08:08:19.181 [INFO ] [penhab.model.script.Garagentor] - Garagentor ist geschlossen
2015-01-09 08:08:19.390 [INFO ] [openhab.model.script.Gargentor] - Garagentor schließt
2015-01-09 08:08:22.029 [ERROR] [.b.h.i.c.HomematicCommunicator] - -1 Failure (sending BinRpcRequest[methodName=setValue,args={KEQ0237515:1,STATE,false}])
org.openhab.binding.homematic.internal.communicator.client.HomematicClientException: -1 Failure (sending BinRpcRequest[methodName=setValue,args={KEQ0237515:1,STATE,false}])
        at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:224) ~[bundlefile:na]
        at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.setDatapointValue(BinRpcClient.java:158) ~[bundlefile:na]
        at org.openhab.binding.homematic.internal.communicator.client.BaseHomematicClient.setDatapointValue(BaseHomematicClient.java:72) ~[bundlefile:na]
        at org.openhab.binding.homematic.internal.communicator.client.CcuClient.setDatapointValue(CcuClient.java:228) ~[bundlefile:na]
        at org.openhab.binding.homematic.internal.communicator.HomematicCommunicator.publishToHomematicServer(HomematicCommunicator.java:306) [bundlefile:na]
        at org.openhab.binding.homematic.internal.communicator.HomematicCommunicator.receiveType(HomematicCommunicator.java:264) [bundlefile:na]
        at org.openhab.binding.homematic.internal.communicator.HomematicCommunicator.receiveCommand(HomematicCommunicator.java:231) [bundlefile:na]
        at org.openhab.binding.homematic.internal.bus.HomematicBinding.internalReceiveCommand(HomematicBinding.java:168) [bundlefile:na]
        at org.openhab.core.binding.AbstractBinding.receiveCommand(AbstractBinding.java:96) [org.openhab.core_1.7.0.201501051026.jar:na]
        at org.openhab.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:42) [org.openhab.core_1.7.0.201501051026.jar:na]
        at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197) [org.eclipse.equinox.event_1.2.200.v20120522-2049.jar:na]
        at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197) [org.eclipse.equinox.event_1.2.200.v20120522-2049.jar:na]
        at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1) [org.eclipse.equinox.event_1.2.200.v20120522-2049.jar:na]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
        at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135) [org.eclipse.equinox.event_1.2.200.v20120522-2049.jar:na]
        at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78) [org.eclipse.equinox.event_1.2.200.v20120522-2049.jar:na]
        at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39) [org.eclipse.equinox.event_1.2.200.v20120522-2049.jar:na]
        at org.openhab.core.internal.events.EventPublisherImpl.sendCommand(EventPublisherImpl.java:56) [org.openhab.core_1.7.0.201501051026.jar:na]
        at org.openhab.model.script.actions.BusEvent.sendCommand(BusEvent.java:101) [org.openhab.model.script_1.7.0.201501051026.jar:na]
        at sun.reflect.GeneratedMethodAccessor1157.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeOperation(XbaseInterpreter.java:729) [org.eclipse.xtext.xbase_2.3.0.v201206120633.jar:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._featureCallOperation(XbaseInterpreter.java:713) [org.eclipse.xtext.xbase_2.3.0.v201206120633.jar:na]
        at sun.reflect.GeneratedMethodAccessor1086.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
        at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) [org.eclipse.xtext.util_2.3.0.v201206120633.jar:na]
        at org.openhab.model.script.interpreter.ScriptInterpreter.internalFeatureCallDispatch(ScriptInterpreter.java:69) [org.openhab.model.script_1.7.0.201501051026.jar:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateAbstractFeatureCall(XbaseInterpreter.java:658) [org.eclipse.xtext.xbase_2.3.0.v201206120633.jar:na]
        at sun.reflect.GeneratedMethodAccessor1087.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
        at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) [org.eclipse.xtext.util_2.3.0.v201206120633.jar:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:218) [org.eclipse.xtext.xbase_2.3.0.v201206120633.jar:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateBlockExpression(XbaseInterpreter.java:321) [org.eclipse.xtext.xbase_2.3.0.v201206120633.jar:na]
        at sun.reflect.GeneratedMethodAccessor1100.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_51]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_51]
        at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) [org.eclipse.xtext.util_2.3.0.v201206120633.jar:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:218) [org.eclipse.xtext.xbase_2.3.0.v201206120633.jar:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluate(XbaseInterpreter.java:204) [org.eclipse.xtext.xbase_2.3.0.v201206120633.jar:na]
        at org.eclipse.xtext.xbase.interpreter.impl.ClosureInvocationHandler.doInvoke(ClosureInvocationHandler.java:46) [org.eclipse.xtext.xbase_2.3.0.v201206120633.jar:na]
        at org.eclipse.xtext.xbase.interpreter.impl.AbstractClosureInvocationHandler.invoke(AbstractClosureInvocationHandler.java:28) [org.eclipse.xtext.xbase_2.3.0.v201206120633.jar:na]
        at com.sun.proxy.$Proxy80.apply(Unknown Source) [na:na]
        at org.openhab.model.script.internal.actions.TimerExecutionJob.execute(TimerExecutionJob.java:44) [org.openhab.model.script_1.7.0.201501051026.jar:na]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-all-2.1.7.jar:na]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [quartz-all-2.1.7.jar:na]
Caused by: java.io.IOException: -1 Failure
        at org.openhab.binding.homematic.internal.communicator.client.BinRpcClient.sendMessage(BinRpcClient.java:210) ~[bundlefile:na]
        ... 48 common frames omitted

the memory problem came later with the sonos binding: (this are only a excerpt of the complete logfile)

2015-01-09 08:28:07.974 [WARN ] [.c.p.RetrieveRemoteDescriptors] - Device descriptor retrieval failed, no response: http://0.0.0.0/upnp/basic_dev.cgi
2015-01-09 09:28:11.894 [WARN ] [.c.p.RetrieveRemoteDescriptors] - Device descriptor retrieval failed, no response: http://0.0.0.0/upnp/basic_dev.cgi
2015-01-09 10:28:16.473 [WARN ] [.c.p.RetrieveRemoteDescriptors] - Device descriptor retrieval failed, no response: http://0.0.0.0/upnp/basic_dev.cgi
2015-01-09 10:58:18.573 [WARN ] [.c.p.RetrieveRemoteDescriptors] - Device descriptor retrieval failed, no response: http://0.0.0.0/upnp/basic_dev.cgi
2015-01-09 18:06:14.073 [WARN ] [sonos.internal.SonosZonePlayer] - Current state of service prevents invoking that action. Connection error or no response received.
2015-01-09 18:06:14.114 [WARN ] [sonos.internal.SonosZonePlayer] - Current state of service prevents invoking that action. Connection error or no response received.
2015-01-09 18:06:14.971 [WARN ] [.binding.ebus.parser.EBusUtils] - Unexpect ack value in EBus telegram, skip data!
2015-01-09 18:06:19.342 [WARN ] [sonos.internal.SonosZonePlayer] - Current state of service prevents invoking that action. Connection error or no response received.
2015-01-09 18:11:44.507 [WARN ] [sonos.internal.SonosZonePlayer] - Current state of service prevents invoking that action. Connection error or no response received.
2015-01-09 18:11:44.510 [WARN ] [sonos.internal.SonosZonePlayer] - Current state of service prevents invoking that action. Connection error or no response received.
2015-01-09 18:11:51.071 [WARN ] [.binding.ebus.parser.EBusUtils] - Unexpect ack value in EBus telegram, skip data!
2015-01-09 18:11:51.219 [WARN ] [sonos.internal.SonosZonePlayer] - Current state of service prevents invoking that action. Connection error or no response received.
2015-01-09 18:12:00.978 [WARN ] [sonos.internal.SonosZonePlayer] - Current state of service prevents invoking that action. Connection error or no response received.
2015-01-09 18:12:01.316 [WARN ] [sonos.internal.SonosZonePlayer] - Current state of service prevents invoking that action. Connection error or no response received.
2015-01-09 18:12:01.536 [WARN ] [.binding.ebus.parser.EBusUtils] - Unexpect ack value in EBus telegram, skip data!
2015-01-09 18:12:17.912 [WARN ] [sonos.internal.SonosZonePlayer] - Current state of service prevents invoking that action. Connection error or no response received.
2015-01-09 18:12:18.299 [WARN ] [efaultUpnpServiceConfiguration] - Thread terminated (SendingRenewal) abruptly with exception: java.lang.OutOfMemoryError: unable to create new native thread
2015-01-09 18:12:18.327 [WARN ] [efaultUpnpServiceConfiguration] - Thread terminated org.teleal.cling.protocol.sync.SendingRenewal$1@194f1b6 abruptly with exception: java.lang.OutOfMemoryError: unable to create new native thread
2015-01-09 18:12:18.312 [WARN ] [efaultUpnpServiceConfiguration] - Thread terminated (SendingRenewal) abruptly with exception: java.lang.OutOfMemoryError: unable to create new native thread
2015-01-09 18:12:18.332 [WARN ] [efaultUpnpServiceConfiguration] - Root cause: java.lang.OutOfMemoryError: unable to create new native thread
2015-01-09 18:12:18.304 [WARN ] [efaultUpnpServiceConfiguration] - Thread terminated (SendingRenewal) abruptly with exception: java.lang.OutOfMemoryError: unable to create new native thread
2015-01-09 18:12:18.303 [WARN ] [efaultUpnpServiceConfiguration] - Thread terminated (SendingRenewal) abruptly with exception: java.lang.OutOfMemoryError: unable to create new native thread
2015-01-09 18:12:18.357 [WARN ] [efaultUpnpServiceConfiguration] - Root cause: java.lang.OutOfMemoryError: unable to create new native thread
2015-01-09 18:12:18.358 [WARN ] [efaultUpnpServiceConfiguration] - Root cause: java.lang.OutOfMemoryError: unable to create new native thread
2015-01-09 18:12:18.303 [WARN ] [efaultUpnpServiceConfiguration] - Thread terminated (SendingRenewal) abruptly with exception: java.lang.OutOfMemoryError: unable to create new native thread
2015-01-09 18:12:18.359 [WARN ] [efaultUpnpServiceConfiguration] - Root cause: java.lang.OutOfMemoryError: unable to create new native thread
2015-01-09 18:12:18.341 [WARN ] [efaultUpnpServiceConfiguration] - Thread terminated (SendingRenewal) abruptly with exception: java.lang.OutOfMemoryError: unable to create new native thread
2015-01-09 18:12:18.369 [WARN ] [efaultUpnpServiceConfiguration] - Root cause: java.lang.OutOfMemoryError: unable to create new native thread
2015-01-09 18:12:18.340 [WARN ] [efaultUpnpServiceConfiguration] - Root cause: java.lang.OutOfMemoryError: unable to create new native thread

**Comment by teichsta** [comment]
@gerrieg any relation you could think of?

**Comment by gerrieg** [comment]
Hmm ... -1 Failure is a kind of 'catch all unknown errors' failure from the CCU. Hard to say what's wrong. I don't think the memory problem is from the Homematic-binding, all resources are released, even with a exception sending the BinRpc message.

**Comment by teichsta** [comment]
doesn't seem to apply anymore. Please feel free to reopen if this issue still applies to you …

**Comment by teichsta** [comment]
@fasa01 does still issue still apply?
