### ISSUE TITLE
Enocean temperature sensors cause NullPointerException in version 1.6.1 binding

### ISSUE THREAD

**Issue by wnagele** [openhab/openhab#2031]
Works fine when using version 1.5.1 of the binding. In 1.6.1 I get the following:
```
11:16:59.778 ERROR org.opencean.core.ESP3Host[:78]- Error
java.lang.NullPointerException: null
	at org.opencean.core.packets.RadioPacket4BS.parseData(RadioPacket4BS.java:25)
	at org.opencean.core.packets.BasicPacket.<init>(BasicPacket.java:44)
	at org.opencean.core.packets.RadioPacket.<init>(RadioPacket.java:22)
	at org.opencean.core.packets.RadioPacket4BS.<init>(RadioPacket4BS.java:18)
	at org.opencean.core.PacketFactory.createRadioPacket(PacketFactory.java:33)
	at org.opencean.core.PacketFactory.createFrom(PacketFactory.java:18)
```

**Comment by sabrine2020** [comment]
I have the same problem with openhab version 1.6.2
Any updates about this issue?
Thanks.

**Comment by wnagele** [comment]
This was fixed in the library here: https://github.com/thomasletsch/opencean/commit/48f4d12f5155f36d57b37d0628b64e9980c1a264

Will create a pull request with the updated lib in a bit.

**Comment by sabrine2020** [comment]
Thanks!
What to do to get the new updated library?

I downloaded OpenHab from the official website
http://www.openhab.org/downloads.html

**Comment by teichsta** [comment]
this release will be updated on next monday (May 25th). For now you could download a nightly build from here https://openhab.ci.cloudbees.com/job/openHAB/

**Comment by sabrine2020** [comment]
Thanks!
should I also use the recent version of the RunTime Core?
cause I noticed that my EnOcean contact sensor was not detected in this new plugin version
