### ISSUE TITLE
Exception unrecoverable for binding when someone disconnect ethernet cable.

### ISSUE THREAD

**Issue by fazioa** [openhab/openhab#2041]
23:54:24.304 ERROR o.o.b.s.i.n.u.SendDispatcherThread[:148]- Network is unreachable
...
...
00:09:03.840 WARN  j.j.i.tasks.state.DNSStateTask[:144]- Renewer(bananapi-local.local.).run() exception 
java.io.IOException: Invalid argument
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:671)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1536)
	at javax.jmdns.impl.tasks.state.DNSStateTask.run(DNSStateTask.java:131)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
00:09:03.850 WARN  javax.jmdns.impl.JmDNSImpl[:1716]- RECOVERING
00:09:03.877 WARN  j.j.i.tasks.state.DNSStateTask[:144]- Canceler(bananapi-local.local.).run() exception 
java.io.IOException: Invalid argument
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:671)
	at javax.jmdns.impl.JmDNSImpl.send(JmDNSImpl.java:1536)
	at javax.jmdns.impl.tasks.state.DNSStateTask.run(DNSStateTask.java:131)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
00:09:08.869 WARN  j.j.i.DNSStatefulObject$DefaultImplementation[:402]- Wait for canceled timed out: DNS: bananapi-local.local. state: canceling 1 task: null
00:09:13.870 WARN  j.j.i.DNSStatefulObject$DefaultImplementation[:402]- Wait for canceled timed out: DNS: bananapi-local.local. state: canceling 1 task: null
00:09:18.872 WARN  j.j.i.DNSStatefulObject$DefaultImplementation[:402]- Wait for canceled timed out: DNS: bananapi-local.local. state: canceling 1 task: null
00:09:19.884 WARN  javax.jmdns.impl.JmDNSImpl[:1760]- bananapi-local.local.recover() Could not recover we are Down!

**Comment by steve-bate** [comment]
It looks like the mDNS service is giving up after several attempt to communicate when the ethernet cable is disconnected. Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.
