### ISSUE TITLE
MySQL connection timeouts block other persistence services

### ISSUE THREAD

**Issue by c--r** [openhab/openhab#2071]
I am using rrd4j locally on a Raspberrry Pi running Openhab (1.5.1 in this case) and remote MySQL Server to persist a larger number of values (~40) every minute. 
If the MySQL server is offline for some reason, the connection from openhab fails and retries as expected. Each attempt to store the next value takes about 3 seconds (until the connection times out), and this adds up to a long period of time (>1 minute), as it tries to 40 values in a row. 
The problem is, that since I am persisting the values once per Minute, the rrd4j persistence never gets executed, because 1 minute is over before MySQL persistence is even finished. That means, that because of an MySQL server outage, I am also loosing the rrd4j values. 

The MySQL settings in openhab.cfg don't seem to solve that issue. Is there a way to configure the Persistence service in a way to store values in different data stores independently (and maybe in parallel, to save time)?

here is a log extract:

```
12:50:54.433 DEBUG o.o.p.m.i.MysqlPersistenceService[:359]- mySQL: Attempting to connect to database jdbc:mysql://192.168.1.102:3306/openhab
12:50:57.400 ERROR o.o.p.m.i.MysqlPersistenceService[:394]- mySQL: Failed connecting to the SQL database using: driverClass=com.mysql.jdbc.Driver, url=jdbc:mysql://192.168.1.102:3306/openhab, user=123, password=123
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at sun.reflect.GeneratedConstructorAccessor88.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1121)
        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:357)
Caused by: java.net.NoRouteToHostException: Keine Route zum Zielrechner
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
12:50:57.408 WARN  o.o.p.m.i.MysqlPersistenceService[:271]- mySQL: No connection to database. Can not persist item 'HF1_V_Temp39 (Type=NumberItem, State=36.375)'! Will retry connecting to database next time.
12:50:57.417 TRACE o.o.c.p.i.PersistItemsJob[:56]- Storing item 'HF1_V_Temp39' with persistence service 'mysql' took 2984ms
```

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community
