### ISSUE TITLE
Java.lang.ClassCastExeption when starting openhab

### ISSUE THREAD

**Issue by Zigulle** [openhab/openhab#2095]
Hallo,

every time I start openhab, I get the following exception:

java.lang.ClassCastException: org.eclipse.osgi.framework.internal.core.BundleURLConnection cannot be cast to java.net.JarURLConnection
        at org.atmosphere.util.annotation.AnnotationDetector.detect(AnnotationDetector.java:325)
        at org.atmosphere.cpr.DefaultAnnotationProcessor.scanForAnnotation(DefaultAnnotationProcessor.java:148)
        at org.atmosphere.cpr.DefaultAnnotationProcessor.configure(DefaultAnnotationProcessor.java:134)
        at org.atmosphere.cpr.AtmosphereFramework.autoConfigureService(AtmosphereFramework.java:2177)
        at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:655)
        at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:568)

I got this excetion till openhab 1.4, didn't know why. Openhab works fine, so it isn´t a big problem. But did you know, whats the problem?

**Comment by PyKaB** [comment]
i have the same problem with 1.6.2:

23:10:51.694 [INFO ] [cpr.DefaultAnnotationProcessor:131  ] - AnnotationProcessor class org.atmosphere.cpr.DefaultAnnotationProcessor$BytecodeBasedAnnotationProcessor being used
23:10:51.874 [ERROR] [sphere.cpr.AtmosphereFramework:2215 ] - 
java.lang.ClassCastException: org.eclipse.osgi.framework.internal.core.BundleURLConnection cannot be cast to java.net.JarURLConnection
	at org.atmosphere.util.annotation.AnnotationDetector.detect(AnnotationDetector.java:325) ~[atmosphere-runtime-2.0.9.jar:2.0.9]
	at org.atmosphere.cpr.DefaultAnnotationProcessor.scanForAnnotation(DefaultAnnotationProcessor.java:148) ~[atmosphere-runtime-2.0.9.jar:2.0.9]
	at org.atmosphere.cpr.DefaultAnnotationProcessor.configure(DefaultAnnotationProcessor.java:134) ~[atmosphere-runtime-2.0.9.jar:2.0.9]
	at org.atmosphere.cpr.AtmosphereFramework.autoConfigureService(AtmosphereFramework.java:2177) [atmosphere-runtime-2.0.9.jar:2.0.9]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:655) [atmosphere-runtime-2.0.9.jar:2.0.9]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:568) [atmosphere-runtime-2.0.9.jar:2.0.9]
	at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:91) [atmosphere-runtime-2.0.9.jar:2.0.9]
	at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:80) [atmosphere-runtime-2.0.9.jar:2.0.9]
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.init(ServletRegistration.java:49) [org.eclipse.equinox.http.servlet_1.1.300.v20120522-1841.jar:na]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.registerServlet(ProxyServlet.java:179) [org.eclipse.equinox.http.servlet_1.1.300.v20120522-1841.jar:na]
	at org.eclipse.equinox.http.servlet.internal.HttpServiceImpl.registerServlet(HttpServiceImpl.java:66) [org.eclipse.equinox.http.servlet_1.1.300.v20120522-1841.jar:na]
	at org.openhab.io.rest.RESTApplication.activate(RESTApplication.java:140) [org.openhab.io.rest_1.6.2.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.registerService(InstanceProcess.java:536) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:260) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70) [org.eclipse.equinox.util_1.0.400.v20120917-192807.jar:na]
23:10:51.896 [INFO ] [sphere.cpr.AtmosphereFramework:1506 ] - Auto detecting atmosphere handlers /WEB-INF/classes/
23:10:51.916 [WARN ] [sphere.cpr.AtmosphereFramework:1154 ] - Missing META-INF/atmosphere.xml but found the Jersey runtime. Starting Jersey
23:10:52.195 [INFO ] [sphere.cpr.AtmosphereFramework:434  ] - Installed AtmosphereHandler org.atmosphere.handler.ReflectorServletProcessor mapped to context-path: /*
23:10:52.196 [INFO ] [sphere.cpr.AtmosphereFramework:1561 ] - Auto detecting WebSocketHandler in /WEB-INF/classes/
23:10:52.199 [INFO ] [sphere.cpr.AtmosphereFramework:1259 ] - Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol

**Comment by teichsta** [comment]
has been addressed with 1.7.0 Snapshot which contains an upgrade of the Atmosphere framework. Best, Thomas E.-E.
