### ISSUE TITLE
KNX-Binding test fails: testAdd throws java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by watou** [openhab/openhab#2097]
```
  <testcase time="5.012" classname="org.openhab.binding.knx.internal.bus.KNXBusR
eaderSchedulerTest" name="testAdd">
    <error type="java.util.ConcurrentModificationException">java.util.Concurrent
ModificationException
        at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:761)
        at java.util.LinkedList$ListItr.next(LinkedList.java:696)
        at org.openhab.binding.knx.internal.bus.KNXBusReaderScheduler.scheduleRead(KNXBusReaderScheduler.java:199)
        at org.openhab.binding.knx.internal.bus.KNXBusReaderSchedulerTest.testAdd(KNXBusReaderSchedulerTest.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
...
```

This is occurring on OSX 10.10.2, java build 1.6.0_65-b14-466.1-11M4716.  It does *not* occur with java build 1.7.0_67-b01.  If it is known that this test should fail in this way on Java 1.6, then the test should fail to run for that reason.

**Comment by Snickermicker** [comment]
Found the issue. Iterrating over a list while removing items was implemented wrongly. Pull request #2099 supplied for 1.6 branch and #2100 for master branch.
