### ISSUE TITLE
DSMR binding does not work completly on an ISKRA MT382 3phase electric + Landis+Gyr E06140 gasmeter

### ISSUE THREAD

**Issue by SierraNL** [openhab/openhab#2121]
I have ISKRA MT382 3phase electric + Landis+Gyr E06140 gasmeter (V2.2)

Using the DSMR binding I get the following errors in the log:
2015-02-12 10:14:11.969 [ERROR] [.b.d.i.messages.OBISMsgFactory] - Failed to parse 0-0:17.0.0(0999.00*kW)
java.text.ParseException: Unit of 0999.00*kW is not A
	at org.openhab.binding.dsmr.internal.cosem.CosemValue.setValue(CosemValue.java:91) ~[bundlefile:na]
	at org.openhab.binding.dsmr.internal.messages.OBISMessage.parseCosemValues(OBISMessage.java:112) ~[bundlefile:na]
	at org.openhab.binding.dsmr.internal.messages.OBISMsgFactory.getMessage(OBISMsgFactory.java:114) ~[bundlefile:na]
	at org.openhab.binding.dsmr.internal.DSMRPort.read(DSMRPort.java:211) [bundlefile:na]
	at org.openhab.binding.dsmr.internal.DSMRBinding.execute(DSMRBinding.java:146) [bundlefile:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) [org.openhab.core_1.7.0.201501160310.jar:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) [org.openhab.core_1.7.0.201501160310.jar:na]
2015-02-12 10:14:12.000 [WARN ] [.b.d.i.messages.OBISMsgFactory] - Received OBIS unknown message:0-0:96.3.10(1)
2015-02-12 10:14:12.032 [WARN ] [.b.d.i.messages.OBISMsgFactory] - Received OBIS unknown message:0-1:24.1.0(3)
2015-02-12 10:14:12.094 [WARN ] [.b.d.i.messages.OBISMsgFactory] - Received OBIS unknown message:0-1:96.1.0(3238313031353431303038353332393132)
2015-02-12 10:14:12.141 [WARN ] [.b.d.i.messages.OBISMsgFactory] - Received OBIS unknown message:0-1:24.3.0(150212100000)(00)(60)(1)(0-1:24.2.1)(m3)
2015-02-12 10:14:12.172 [WARN ] [.b.d.i.messages.OBISMsgFactory] - Received OBIS unknown message:0-1:24.4.0(1)

The binding expects Amps instead of kW, maybe a specific meter type issue.
The warnings seems to be in part caused by the gas readout on a seperate line (there is already an issue for that I believe)
Most of the other values work fine (current usage, high and low tariff).

Full readout:
/ISk5\2MT382-1003

0-0:96.1.1(5A424244303035313238373636393132)
1-0:1.8.1(04003.447*kWh)
1-0:1.8.2(03338.439*kWh)
1-0:2.8.1(00000.001*kWh)
1-0:2.8.2(00000.001*kWh)
0-0:96.14.0(0001)
1-0:1.7.0(0000.54*kW)
1-0:2.7.0(0000.00*kW)
0-0:17.0.0(0999.00*kW)
0-0:96.3.10(1)
0-0:96.13.1()
0-0:96.13.0()
0-1:24.1.0(3)
0-1:96.1.0(3238313031353431303038353332393132)
0-1:24.3.0(150121210000)(00)(60)(1)(0-1:24.2.1)(m3)
(02613.019)
0-1:24.4.0(1)

**Comment by teichsta** [comment]
@mvolaart could you please have a look at this? Thanks, Thomas E.-E.

**Comment by SierraNL** [comment]
I've looked through the code of the binding and my output seems to be a mix of DSMR versions looking at OBISMsgType.java:
17.0.0 is in Amps for < V4.0 and in kWatt for >= V4.0
96.3.10 >= V3.0
24.1.0 >= V3.0
96.1.0 >= V3.0
24.3.0 = V3.0
24.4.0 >= V2.2 

Looking at the list above, there is no correct DSMR version :(

Googling at /ISk5\2MT382-1003 results in a lot of similar telegrams, so my meter seems ok ;)

**Comment by mvolaart** [comment]
Could you please send me an a raw output of the meter?

**Comment by SierraNL** [comment]
What do you mean exactly with raw?
I copy pasted it in the issue from my c# tool which I used before the binding existed, don't have any other way of getting the message itself.

**Comment by mvolaart** [comment]
My bad. It's already in your original post. I will look into this.

**Comment by mvolaart** [comment]
For the gas value i have a fix and will try to commit some changes this week. The other issue i'm still looking into.

**Comment by teichsta** [comment]
Fix #2158 has been merged into master
