### ISSUE TITLE
 vdr-binding throws exceptions

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab#2124]
#366 was original Issue, but since it is imported, I'm not able to reopen it.
So...

Every minute or so this error occurs:

    2015-02-12 19:06:32.512 [ERROR] [.service.AbstractActiveService] - Error while executing background thread VDR Monitor Service
    java.lang.NullPointerException: null
          at java.util.Hashtable.put(Hashtable.java:459) ~[na:1.8.0_25]
          at org.openhab.core.internal.events.EventPublisherImpl.createUpdateEvent(EventPublisherImpl.java:86) ~[na:na]
          at org.openhab.core.internal.events.EventPublisherImpl.postUpdate(EventPublisherImpl.java:78) ~[na:na]
          at org.openhab.binding.vdr.internal.VDRMonitor.execute(VDRMonitor.java:91) ~[na:na]
          at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]

The error occurs, if there is an Item for OSDMessages, wheter if the corresponding vdr is on or off. The message is shown anyway, but the error annoys me ;-)

**Comment by teichsta** [comment]
i'll better reopen #366
