### ISSUE TITLE
NPE at org.openhab.binding.maxcube.internal.message.Device.update(Device.java:103)

### ISSUE THREAD

**Issue by col-panic** [openhab/openhab#2147]
```
2015-02-17 11:28:31.717 [WARN ] [.o.b.m.internal.message.Device] - Can't create device from received message, returning NULL.
2015-02-17 11:28:31.718 [INFO ] [.o.b.m.internal.MaxCubeBinding] - Failed to process message received by MAX! protocol.
2015-02-17 11:28:31.720 [DEBUG] [.o.b.m.internal.MaxCubeBinding] - java.lang.NullPointerException
	at org.openhab.binding.maxcube.internal.message.Device.update(Device.java:103)
	at org.openhab.binding.maxcube.internal.message.Device.create(Device.java:98)
	at org.openhab.binding.maxcube.internal.message.L_Message.updateDevices(L_Message.java:75)
	at org.openhab.binding.maxcube.internal.MaxCubeBinding.execute(MaxCubeBinding.java:230)
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156)
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)
```

Version is 
openhab-addon-binding-maxcube         1.6.2                            all          openHAB MaxCube Binding 
on debian

**Comment by marcelrv** [comment]
hi,

Seems you get some invalid msg.

Can you provide a full trace log. pls use the latest version from cloudbees to ensure you have the latest version.

you can put it in trace mode by adding to your logback_debug.xml
<logger name="org.openhab.binding.maxcube" level="TRACE"/>

**Comment by col-panic** [comment]
Hy there, I swapped to 1.7.0 and everything works flawlessly there! So I am not sure whether its worth to do further investigation here!

**Comment by marcelrv** [comment]
No, then no need to look further.
Thx
