### ISSUE TITLE
MaxCubeBinding ends without further notice

### ISSUE THREAD

**Issue by col-panic** [openhab/openhab#2149]
I am running openhab 1.6.2 on Debian 7 on a MaxCube system. The system seems to generally work well, but I have to restart it every n hours, as the connection to the MaxCube always suddenly ends without any further notice, it just stops as can be seen in the resp. openhab.log file:
```
2015-02-17 14:01:56.620 [DEBUG] [.o.b.m.internal.MaxCubeBinding] - open new connection... to 192.168.0.245 port 62910
2015-02-17 14:01:56.620 [DEBUG] [.o.b.m.internal.MaxCubeBinding] - Sending state request #325 to Maxcube
2015-02-17 14:01:56.693 [DEBUG] [.o.b.m.internal.MaxCubeBinding] - === L_Message === 
2015-02-17 14:01:56.694 [DEBUG] [.o.b.m.internal.MaxCubeBinding] - 5 devices found.

2015-02-17 14:02:06.700 [DEBUG] [.o.b.m.internal.MaxCubeBinding] - open new connection... to 192.168.0.245 port 62910
2015-02-17 14:02:06.701 [DEBUG] [.o.b.m.internal.MaxCubeBinding] - Sending state request #326 to Maxcube
```
Restarting openhab resolves the problem for another n hours as can bee seen in the following logfile

```
2015-02-17 14:02:06.701 [DEBUG] [.o.b.m.internal.MaxCubeBinding] - Sending state request #326 to Maxcube
2015-02-17 16:48:33.612 [INFO ] [penhab.io.rest.RESTApplication] - Stopped REST API
2015-02-17 16:48:37.656 [INFO ] [.o.u.w.i.servlet.WebAppServlet] - Stopped Classic UI
2015-02-17 16:48:42.898 [INFO ] [.o.core.internal.CoreActivator] - openHAB runtime has been started (v1.6.2).
2015-02-17 16:48:44.398 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl] - mDNS service has been started
2015-02-17 16:48:44.512 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl] - Service Discovery initialization completed.
2015-02-17 16:48:47.602 [INFO ] [penhab.io.rest.RESTApplication] - Started REST API at /rest
2015-02-17 16:48:53.908 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'default.sitemap'
2015-02-17 16:48:54.053 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'rrd4j.persist'
2015-02-17 16:48:54.098 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'default.items'
2015-02-17 16:48:54.815 [INFO ] [.o.u.w.i.servlet.WebAppServlet] - Started Classic UI at /openhab.app
2015-02-17 16:48:59.244 [INFO ] [.service.AbstractActiveService] - MAX!Cube Refresh Service has been started
2015-02-17 16:48:59.250 [DEBUG] [.o.b.m.internal.MaxCubeBinding] - open new connection... to 192.168.0.245 port 62910
2015-02-17 16:48:59.251 [DEBUG] [.o.b.m.internal.MaxCubeBinding] - Sending state request #0 to Maxcube
2015-02-17 16:48:59.359 [DEBUG] [.o.b.m.internal.MaxCubeBinding] - === L_Message === 
2015-02-17 16:48:59.375 [WARN ] [.o.b.m.internal.message.Device] - Can't create device from received message, returning NULL.
2015-02-17 16:48:59.375 [INFO ] [.o.b.m.internal.MaxCubeBinding] - Failed to process message received by MAX! protocol.
2015-02-17 16:48:59.377 [DEBUG] [.o.b.m.internal.MaxCubeBinding] - java.lang.NullPointerException
	at org.openhab.binding.maxcube.internal.message.Device.update(Device.java:103)
	at org.openhab.binding.maxcube.internal.message.Device.create(Device.java:98)
	at org.openhab.binding.maxcube.internal.message.L_Message.updateDevices(L_Message.java:75)
	at org.openhab.binding.maxcube.internal.MaxCubeBinding.execute(MaxCubeBinding.java:230)
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156)
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)
```
could it be that the MAX!Cube Refresh Service somehow crashes?

**Comment by col-panic** [comment]
The NPE is opened as separate issue in https://github.com/openhab/openhab/issues/2147

**Comment by col-panic** [comment]
Okay, it seems like this has been already solved with 1.7 I guess that https://github.com/openhab/openhab/commit/7a1aae2d0fc5ff3f0d05bf033b8776474ba57ba9 might be solving it.

**Comment by teichsta** [comment]
good to know! Thanks for the update …

**Comment by col-panic** [comment]
I am not entirely sure, whether this fixes the bug. I ported to 1.6.2 and created the resp. jar, it does however not work then, it just stops at another point - why is it that he says a second reader? I replaced the maxcube binding addon with the patched jar.. ?! 
```
2015-02-18 10:11:07.001 [INFO ] [.o.u.w.i.servlet.WebAppServlet] - Started Classic UI at /openhab.app
2015-02-18 10:11:11.239 [INFO ] [.service.AbstractActiveService] - MAX!Cube Refresh Service (patched) has been started
2015-02-18 10:11:11.245 [DEBUG] [.o.b.m.internal.MaxCubeBinding] - open new connection... to 192.168.0.245 port 62910
2015-02-18 10:11:11.245 [DEBUG] [.o.b.m.internal.MaxCubeBinding] - Sending state request #0 to Maxcube
2015-02-18 10:11:11.251 [WARN ] [i.internal.GenericItemProvider] - Attempted to register a second BindingConfigReader of type 'maxcube'. The primaraly reader will remain active!
2015-02-18 10:11:11.267 [INFO ] [.service.AbstractActiveService] - NTP Refresh Service has been started
2015-02-18 10:11:11.267 [DEBUG] [.o.b.m.internal.MaxCubeBinding] - === L_Message === 
```
