### ISSUE TITLE
DSMR ClassCastException

### ISSUE THREAD

**Issue by ODINServ** [openhab/openhab#2164]
I'm running DSMR-1.7.0-SNAPSHOT (Compiled 2015-02-20 03:24) with openhab 1.6.2

I've set the version to 4.0 according to: OBIS message type:P1_VERSION_OUTPUT_V4, values:[40]

Edit: Pulled the source my self, and rebuild the DSMR module. Now i'll get logging witch matches the current source code.

The ClassCast exception is gone, but i'll get an index out of range exception instead

2015-02-21 10:50:50.417 [DEBUG] [.b.d.i.messages.OBISMsgFactory] - Received obisIdString 0-0:96.7.9, obisId:0-0:96.7.9, values:[00000]
2015-02-21 10:50:50.418 [DEBUG] [.b.d.i.messages.OBISMsgFactory] - Found 1 compatible message type(s)
2015-02-21 10:50:50.419 [DEBUG] [.b.d.i.messages.OBISMsgFactory] - Parse values for OBIS Message type:EMETER_LONG_POWER_FAILURES
2015-02-21 10:50:50.419 [DEBUG] [o.o.b.d.i.messages.OBISMessage] - Received items:1, Needed items:1
2015-02-21 10:50:50.420 [DEBUG] [o.o.b.d.i.p.P1TelegramParser  ] - Parsed:OBISDataLine [OBIS id:0-0:96.7.9, obis values:[00000], to:OBIS Message(type:EMETER_LONG_POWER_FAILURES, description:Number of Long Power failures, openHABValues:[0])
2015-02-21 10:50:50.421 [DEBUG] [.b.d.i.messages.OBISMsgFactory] - Received obisIdString 1-0:99.97.0, obisId:1-0:99.97.0, values:[0, 0-0:96.7.19]
2015-02-21 10:50:50.422 [DEBUG] [.b.d.i.messages.OBISMsgFactory] - Found 1 compatible message type(s)
2015-02-21 10:50:50.423 [DEBUG] [.b.d.i.messages.OBISMsgFactory] - Parse values for OBIS Message type:EMETER_POWER_FAILURE_LOG
2015-02-21 10:50:50.423 [DEBUG] [o.o.b.d.i.messages.OBISMessage] - Received items:2, Needed items:22
2015-02-21 10:50:50.424 [DEBUG] [o.o.b.d.i.messages.OBISMessage] - postProcessKaifaE0003
2015-02-21 10:50:50.434 [ERROR] [.service.AbstractActiveService] - Error while executing background thread DSMR Binding
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:638) ~[na:1.8.0_06]
	at java.util.ArrayList.get(ArrayList.java:414) ~[na:1.8.0_06]
	at org.openhab.binding.dsmr.internal.messages.OBISMessage.postProcessKaifaE0003(OBISMessage.java:181) ~[na:na]
	at org.openhab.binding.dsmr.internal.messages.OBISMessage.parseCosemValues(OBISMessage.java:137) ~[na:na]
	at org.openhab.binding.dsmr.internal.messages.OBISMsgFactory.getMessage(OBISMsgFactory.java:97) ~[na:na]
	at org.openhab.binding.dsmr.internal.p1telegram.P1TelegramParser.handleEndP1Telegram(P1TelegramParser.java:215) ~[na:na]
	at org.openhab.binding.dsmr.internal.p1telegram.P1TelegramParser.parseData(P1TelegramParser.java:182) ~[na:na]
	at org.openhab.binding.dsmr.internal.DSMRPort.read(DSMRPort.java:202) ~[na:na]
	at org.openhab.binding.dsmr.internal.DSMRBinding.execute(DSMRBinding.java:150) ~[na:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
2015-02-21 10:50:55.281 [DEBUG] [.b.r.internal.RFXComConnection] - Data received:

**Comment by teichsta** [comment]
@mvolaart could you take care of this? Appreciate your support! Best, Thomas E.-E.

**Comment by mvolaart** [comment]
I can confirm this is a bug. I'm working on a fix
