### ISSUE TITLE
Howto use URLendcode

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2209]
Hello,

I tried a rule like this to URL encode a string, which should be sent as http-request:
import org.openhab.core.library.types.*
import org.openhab.model.script.actions.*
import java.net.URLEncoder

    rule Test
    when
     Time cron "0 * * * * ?"
    then

    var String text = URLEncoder.encode("Anruf von " + Active_Call_No.state.toString, "UTF-8")
    url = "http://192.168.2.5:9000/status?p0=display&p1=&p2=" + text + "&p3=60&player=00:04:20:06:21:aa" //WZ  
    
    sendHttpGetRequest(url)
    
    end

I get the folling error message:
java.lang.RuntimeException: The name 'URLEncoder' cannot be resolved to an item or type.
        at org.openhab.model.script.interpreter.ScriptInterpreter.internalFeatureCallDispatch(ScriptInterpreter.java:67) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateAbstractFeatureCall(XbaseInterpreter.java:658) ~[na:na]
        at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
        at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:218) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateMemberFeatureCall(XbaseInterpreter.java:545) ~[na:na]
        at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
        at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:218) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateVariableDeclaration(XbaseInterpreter.java:601) ~[na:na]
        at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
        at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:218) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateBlockExpression(XbaseInterpreter.java:321) ~[na:na]
        at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
        at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:218) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluate(XbaseInterpreter.java:204) ~[na:na]
        at org.openhab.model.script.internal.engine.ScriptImpl.execute(ScriptImpl.java:59) ~[na:na]
        at org.openhab.model.rule.internal.engine.ExecuteRuleJob.execute(ExecuteRuleJob.java:55) ~[na:na]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-all-2.1.7.jar:na]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [quartz-all-2.1.7.jar:na]

What am I doing wrong? Thanks, for your assistance!!

Kind regards,
Michael

**Comment by mrguessed** [comment]
Change `URLEncoder.encode(...)` to `URLEncoder::encode(...)`.

The `::` convention is used when calling static methods.

Alternatively, the String representation in Rules has been overloaded to support the `encode(<charset>)` method.  With this, you can just do something like:

```
rule "Test"
when
    Time cron "0 * * * * ?"
then
    var String text = "Anruf von " + Active_Call_No.state.toString
    var String url = "http://192.168.2.5:9000/status?p0=display&p1=&p2=" + text.encode("UTF-8")  + "&p3=60&player=00:04:20:06:21:aa" //WZ  

    sendHttpGetRequest(url)
end
```

**Comment by staehler** [comment]
Thanks, a lot. Now it works :-)

**Comment by teichsta** [comment]
again a question, that should have better discussed on the Goolge Group in order to "teach" the whole community …
