### ISSUE TITLE
How to get time from DateTime

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2283]
Hello,
I've some items definition like
DateTime OfficeCalTime01 "[%1$tH:%1$tM Uhr]" <calendar>	{ caldavPersonal="calendar:dienstlich type:ACTIVE eventNr:1 value:START" }
and need to extract the time.
The content is like this 2015-03-12T21:04:00, which means, it's really DateTime.
But any tries to get the time like 21:04 were without success.
I tried SimpleDateFormat and things like String::format("%1$tH:%1$tM", OfficeCalTime01) and some other tries (without java knowledge) but the only response is 
==> /opt/usr/openhab/logs/openhab.log <==
2015-03-12 21:20:00.098 [ERROR] [.o.m.r.i.engine.ExecuteRuleJob] - Error during the execution of rule StartupDelay
java.util.IllegalFormatConversionException: H != org.joda.time.DateTime
        at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4045) ~[na:1.7.0_75]
        at java.util.Formatter$FormatSpecifier.printDateTime(Formatter.java:2787) ~[na:1.7.0_75]
        at java.util.Formatter$FormatSpecifier.print(Formatter.java:2695) ~[na:1.7.0_75]
        at java.util.Formatter.format(Formatter.java:2494) ~[na:1.7.0_75]
        at java.util.Formatter.format(Formatter.java:2423) ~[na:1.7.0_75]
        at java.lang.String.format(String.java:2790) ~[na:1.7.0_75]
        at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeOperation(XbaseInterpreter.java:729) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._featureCallOperation(XbaseInterpreter.java:713) ~[na:na]
        at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
        at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) ~[na:na]
        at org.openhab.model.script.interpreter.ScriptInterpreter.internalFeatureCallDispatch(ScriptInterpreter.java:69) ~[na:na]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateAbstractFeatureCall(XbaseInterpreter.java:658) ~[na:na]
        at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source) ~[na:na]

I give it up. Is anybody there, who can help me? I'm just a openhab user, without java experience :-(

This type declarations makes me cracy and are annoying, it wastes so much time  ...
 
Best regards,
Michael

**Comment by watou** [comment]
The time 2015-03-12T21:04:00 is in [ISO 8601 format](http://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations), and in Java you can parse it with something like this:

```java
String input = "2015-03-12T21:04:00";
java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
java.util.Date d = sdf.parse(input, new java.text.ParsePosition(0));
```
 
(By the way, the Google Group is a better place to be asking questions, in my opinion.)

**Comment by teichsta** [comment]
technical questions should indeed be discussed on the Google Group. Will close this issue since this seem to only contain a question. Best, Thomas E.-E.
