### ISSUE TITLE
issue with nightly #879: This message null will be lost...

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab#2303]
with update to Nightly #879 (from #877) I get the following WARN:

    2015-03-14 11:15:53.808 [WARN ] [osphere.cpr.DefaultBroadcaster] - This message null will be lost for AtmosphereResource null, adding it to the BroadcasterCache
    2015-03-14 11:15:53.809 [WARN ] [osphere.cpr.DefaultBroadcaster] - Failed to execute a write operation for Broadcaster /sitemaps/daheim/0005
    java.lang.NullPointerException: null
        at org.atmosphere.cache.UUIDBroadcasterCache.clearCache(UUIDBroadcasterCache.java:199) ~[na:na]
        at org.atmosphere.cpr.DefaultBroadcaster.executeAsyncWrite(DefaultBroadcaster.java:867) ~[na:na]
        at org.atmosphere.cpr.DefaultBroadcaster$3.run(DefaultBroadcaster.java:519) ~[na:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_31]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]

This warn appears every ~5 Seconds.

**Comment by udo1toni** [comment]
Disappeared in newer Snapshots, so I'll Close this...

**Comment by teichsta** [comment]
thanks @udo1toni
