### ISSUE TITLE
CUL broken under Mac OS X Yosemite (1.7.0 Snapshot)

### ISSUE THREAD

**Issue by bytedealer** [openhab/openhab#2428]
Hello,

first the specs:
Mac Mini Mid 2009 Server Edition, 3GB RAM
CUL V3 Busware OEM Stick
Aeon Z-Stick S2

I tried the nightly build snapshot from yesterday (2015-04-08): Everything works fine except my CUL. With openhab 1.6.1 I had no problems. I upgraded to 1.7.0 and it stops working.

From the error log I got these lines:
```
19:18:48.851 ERROR o.o.b.i.i.CULIntertechnoBinding[:105]- Can't open CUL
org.openhab.io.transport.cul.CULDeviceException: Can't instantiate CULHandler object
	at org.openhab.io.transport.cul.CULManager.createNewHandler(CULManager.java:187)
	at org.openhab.io.transport.cul.CULManager.getOpenCULHandler(CULManager.java:89)
	at org.openhab.io.transport.cul.CULManager.getOpenCULHandler(CULManager.java:54)
	at org.openhab.binding.intertechno.internal.CULIntertechnoBinding.bindCULHandler(CULIntertechnoBinding.java:101)
	at org.openhab.binding.intertechno.internal.CULIntertechnoBinding.setNewDeviceName(CULIntertechnoBinding.java:94)
	at org.openhab.binding.intertechno.internal.CULIntertechnoBinding.updated(CULIntertechnoBinding.java:208)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.openhab.io.transport.cul.CULManager.createNewHandler(CULManager.java:161)
	at org.openhab.io.transport.cul.CULManager.getOpenCULHandler(CULManager.java:89)
Caused by: java.lang.NullPointerException: null
	at org.openhab.io.transport.cul.internal.CULSerialHandlerImpl.<init>(CULSerialHandlerImpl.java:118)
	at org.openhab.io.transport.cul.internal.CULSerialHandlerImpl.<init>(CULSerialHandlerImpl.java:93)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
19:18:48.852 INFO  o.o.c.s.AbstractActiveService[:169]- CULIntertechno Refresh Service has been started
```

Then I tried 1.7.0 with org.openhab.io.transport.cul-1.6.1.jar - no problems. So the error was definitely introduced after 1.6.1 

If I can help with further information, feel free to contact me.

Thank you for the fantastic piece of software!

Bye
bytedealer

**Comment by teichsta** [comment]
@gernoteger could you please have a look at this? Thanks, Thomas E.-E.

**Comment by gernoteger** [comment]
@bytedealer can you please attach the configs you are using (from openhab.cfg and items).

**Comment by bytedealer** [comment]
items:
```
/** CULS */
Switch	Wallplugs_i1	"KiZi Hase"				<message_socket>	{culintertechno="type=classic;group=I;address=1"}
Switch	Wallplugs_i2	"ElZi Lampe Fenster"	<message_socket>	{culintertechno="type=classic;group=I;address=2"}
Switch	Wallplugs_i3	"WoZi Fernsehen"		<message_socket>	{culintertechno="type=classic;group=I;address=3"}
```

cfg:
```
############################## CUL INTERTECHNO #######################################
#

culintertechno:device=serial:/dev/cu.usbmodem431
cul:itrepetitions=6
cul:itwavelength=420
```

Or do you need the complete files?

Thanks!

**Comment by gernoteger** [comment]
1. could reproduce on WIndows8
2. seems to be introduced by Commit: "10272d4eda89f51cdbaf8d5f9dcae3869f196365:* Max binding cul config":  CULSerialHandlerImpl(String deviceName, CULMode mode) calls CULSerialHandlerImpl(String deviceName, CULMode mode,
			Map<String, ?> properties) with null properties, which doesn't work.
I will provide a fix, but I can't really retest it since I connect m CULs over the network; will need help here

**Comment by bytedealer** [comment]
I can do that. :-)

**Comment by gernoteger** [comment]
I provided a preliminary solution in my forka at https://github.com/gernoteger/openhab_contributions/tree/fix%232428. It also contains a newly created unittest module for the CUL transport.

It needs a little rework for a PR since it also contains small fixes to get the Eclispe working (this is another matter), but you can build from that and test.
regards, & happy testing , Gernot

**Comment by bytedealer** [comment]
Hi Gernot,

Sorry for my late reply. I am on work travel, but I can test on weekend.

Bye
