### ISSUE TITLE
Absolute path doesn't work in Systeminfo binding on Windows

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab#2430]
When attempting to get file system information via the Systeminfo binding, if the configuration attempts to specify the directory using an absolute path on a windows system like this:

    Number DirFiles " # of files: [%d]" { systeminfo="DirFiles:60000:f:\stuff" }

the method will fail in the 1.6.2 release, but be flagged as a configuration error in the most recent snapshot.

1.7.0 yields this configuration error: Systeminfo binding must contain 2-3 parts separated by ':'
1.6.2 yields this trace:

    01:39:36.183 [DEBUG] [b.s.internal.SysteminfoBinding:102  ] - item 'DirUsage' is about to be refreshed now
    01:39:36.183 [ERROR] [b.s.internal.SysteminfoBinding:267  ] - Error occured while reading KPI's
    org.hyperic.sigar.SigarException: There are no more files.
    : f
        at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220) ~[sigar-1.6.4.jar:na]
        at com.sun.proxy.$Proxy74.getDirUsage(Unknown Source) ~[na:na]
        at org.openhab.binding.systeminfo.internal.SysteminfoBinding.getData(SysteminfoBinding.java:222) [bundlefile:na]
        at org.openhab.binding.systeminfo.internal.SysteminfoBinding.execute(SysteminfoBinding.java:108) [bundlefile:na]
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) [org.openhab.core_1.6.2.jar:na]
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) [org.openhab.core_1.6.2.jar:na]

I have begun working on a fix for this.  I'm thinking the binding should allow absolute paths to be specified by replacing the colon with a pipe (eg. "f:\stuff" becomes "f|\stuff")

OH: OpenHAB 1.6.2/1.7.0 (SNAPSHOT)
Platform: Windows XP
Related to #2392 / #2393

**Comment by teichsta** [comment]
@paulianttila could you have a look at this, please? Thanks, Thomas E.-E.

**Comment by paulianttila** [comment]
Currently colon character is a separator character for binding configuration, so yes it's true that colon is not accepted on the directory paths. It's tricky to fix so that colon is accepted in paths as well.  Pipe hack isn't very nice, but at least it's easy workaround for the problem.

@9037568: you will generate fix (PR) for this?

**Comment by 9037568** [comment]
Created #2443.  I went back and implemented a solution to allow for the "C:\blah" syntax instead of using the 'pipe hack'.

Also included a package of unit tests for the systeminfo binding.
