### ISSUE TITLE
RFXCOM How to configure Motion sensor Nexa LMDT-609

### ISSUE THREAD

**Issue by norsoa** [openhab/openhab#2453]
I have a Nexa Motion sensor LMDT-609 and I cant work out how to specify the item specification.

I have tried
Number Sensor "Sensor [%s]"	 (gNexa)		{ rfxcom="<019426A:Motion" }
And I have tried
Number Sensor "Sensor [%s]"	 (gNexa)          { rfxcom="<019426A.10:LIGHTING2.AC:Command"

I can see the data from the motion sensor in RFXmngr below

Packettype       = Lighting2
subtype            = AC
Sequence nbr  = 42
ID                     = 019426A
Unit                  = 10
Command        = On
Signal level      = 7

But I cant get the data in to the item. Does any body have an idea?

**Comment by paulianttila** [comment]
Correct syntax for in binding is following

Number Sensor "Sensor [%s]" (gNexa) { rfxcom="<1655402.10:Command" }

Binding accept only decimal numbers for device id, so 0x019426A = 1655402.

When you enable debug logging for openhab, you can see similar data in
openhab log as you can see from RFXmngr as well.

-Pali


2015-04-14 0:08 GMT+03:00 norsoa <notifications@github.com>:

**Comment by norsoa** [comment]
Thank you for your answer, but I still have problem. I get these messages in the openhab.log

2015-04-14 22:29:28.506 [ERROR] [i.internal.GenericItemProvider] - Binding configuration of type 'rfxcom' of item ?Sensor? could not be parsed correctly.
org.openhab.model.item.binding.BindingConfigParseException: Invalid item type for value selector 'Command'!
	at org.openhab.binding.rfxcom.internal.RFXComGenericBindingProvider.processBindingConfiguration(RFXComGenericBindingProvider.java:146) ~[na:na]
	at org.openhab.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:341) [org.openhab.model.item_1.6.2.jar:na]
	at org.openhab.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:317) [org.openhab.model.item_1.6.2.jar:na]
	at org.openhab.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:171) [org.openhab.model.item_1.6.2.jar:na]
	at org.openhab.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:379) [org.openhab.model.item_1.6.2.jar:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:158) [org.openhab.model.core_1.6.2.jar:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:99) [org.openhab.model.core_1.6.2.jar:na]
	at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) [org.openhab.model.core_1.6.2.jar:na]
	at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) [org.openhab.model.core_1.6.2.jar:na]

**Comment by paulianttila** [comment]
Sorry, I just copied your item configurations and forgotten to change item type accordingly. Command value selector supports only Switch items, so correct syntax is

**Switch** Sensor "Sensor [%s]" (gNexa) { rfxcom="<1655402.10:Command" }

See more information from rfxcom binding wiki page.

**Comment by norsoa** [comment]
OK, now its working. Thank you Paulianttila
