### ISSUE TITLE
Philips Hue Binding crashes on refresh

### ISSUE THREAD

**Issue by mstolt** [openhab/openhab#2504]
Since a recent update of the hue bridge Philips enabled deleting items on the bridge.
This results in non continuous item numbers in the datastore lights section.

The current implementation requires a continuous numbering of the lights. 
The error is the loop in HueBinding.java method "execute" (line 101 and following)

The current code throws an NPE if a light was deleted and e.g. only the lights 1,2 and 4 remain in the bridge.

```
18:41:45.850 [ERROR] [.service.AbstractActiveService:175  ] - Error while executing background thread Hue Refresh Service
java.lang.NullPointerException: null
        at org.openhab.binding.hue.internal.data.HueSettings$SettingsTree.node(HueSettings.java:216) ~[na:na]
        at org.openhab.binding.hue.internal.data.HueSettings.isBulbOn(HueSettings.java:71) ~[na:na]
        at org.openhab.binding.hue.internal.hardware.HueBulb.getStatus(HueBulb.java:74) ~[na:na]
        at org.openhab.binding.hue.internal.hardware.HueBulb.<init>(HueBulb.java:62) ~[na:na]
        at org.openhab.binding.hue.internal.HueBinding.execute(HueBinding.java:104) ~[na:na]
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
```

I currently try to setup a development environment and give it a try to fix the issue. Since a am a novice to OpenHAB, Java and GIT it may take a while to fix it.

Greetings
  Matthias

**Comment by mstolt** [comment]
So far i programmed a solution. Now i have to deal with git and create a "push/pull"-Request :)

**Comment by mstolt** [comment]
This issue can be closed.
