### ISSUE TITLE
org.openhab.binding.rfxcom.internal.RFXComException: Message TEMPERATURE_HUMIDITY_BAROMETRIC not implemented

### ISSUE THREAD

**Issue by notoriousbdg** [openhab/openhab#2557]
I'm receiving this errror for my Oregon Scientific BTHR968.  Is it possible to get support added?

```
2015-05-06 19:51:03.393 [DEBUG] [.b.r.internal.RFXComConnection] - Unknown data received, data: 0D540278E300010B230203580480
2015-05-06 19:51:03.401 [ERROR] [.rfxcom.internal.RFXComBinding] - Error occured during packet receiving, data: 0D540278E300010B230203580480
org.openhab.binding.rfxcom.internal.RFXComException: Message TEMPERATURE_HUMIDITY_BAROMETRIC not implemented
        at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:121) ~[bundlefile:na]
        at org.openhab.binding.rfxcom.internal.RFXComBinding$MessageLister.packetReceived(RFXComBinding.java:231) ~[bundlefile:na]
        at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector$SerialReader.run(RFXComSerialConnector.java:202) [bundlefile:na]
Caused by: java.lang.ClassNotFoundException: org.openhab.binding.rfxcom.internal.messages.RFXComTemperatureHumidityBarometricMessage
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[na:na]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) ~[na:na]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[na:na]
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107) ~[na:na]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0]
        at java.lang.Class.forName0(Native Method) ~[na:1.8.0]
        at java.lang.Class.forName(Class.java:259) ~[na:1.8.0]
        at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:116) ~[bundlefile:na]
        ... 2 common frames omitted
```

**Comment by teichsta** [comment]
@AlexF12004Roma @juri8 @ericbottard @paulianttila @engineergreen can anybody you help?

**Comment by juri8** [comment]
I just checked the code (pull #2566) and found that there are plenty of messages that are not yet implemented. I hope I find some time soon to at least implement the one you need.

**Comment by Speederc** [comment]
Hi @notoriousbdg,
I tried to generate a new version with this TEMPERATURE_HUMIDITY_BAROMETRIC support : http://dr-petelot-marion.chirurgiens-dentistes.fr/temp/org.openhab.binding.rfxcom_1.9.0.201601221259.jar .
It should work with the following item declarations : 
Number temperature{rfxcom=">SensorId:Temperature"}
Number humidity {rfxcom=">SensorId:Humidity"}
String humidityStatus {rfxcom=">SensorId:HumidityStatus"}
Number pressure {rfxcom=">SensorId:Pressure"}
String forecast {rfxcom=">SensorId:Forecast"}

Can you test it and give me your feedback ?
Thanks

**Comment by skyscape321** [comment]
Hi @Speederc,
I can confirm that the code works with Oregon  BTHGN129. The values for temp, hum, humstat and pressure are correct. As far as I can see the BTHGN129 don't send forecast (yet). Thank you for your efforts!

**Comment by Speederc** [comment]
Hi @skyscape321 , thank you for your feedback ! This will be included in a global pull request with other new messages.
