### ISSUE TITLE
RFXCOM: RFXSensor not implemented

### ISSUE THREAD

**Issue by big-col** [openhab/openhab#2621]
Would it be possible to have RFXSensor added to the RFXCOM binding please?

Thanks
Colin

**Comment by teichsta** [comment]
@Speederc @paulianttila could have a look at this one please?

**Comment by Speederc** [comment]
PR created. Can be closed.

**Comment by teichsta** [comment]
Thanks @Speederc we'll close this Issue once the PR has been merged!

**Comment by teichsta** [comment]
@big-col have you had a chance to test @Speederc changes?

**Comment by teichsta** [comment]
@big-col any news? Have you had the chance to test the changes by @Speederc?

**Comment by big-col** [comment]
hi teichsta, I haven't had chance to take a look, but I will do early next week when I'm home :)

many thanks for your help and support.  apologies for the delay in replying, a lot going on at the moment.

Colin

**Comment by big-col** [comment]
teichsta, is there an updated rfxcom.jar file available?  I'm not sure where to get it from...

Thanks

**Comment by Speederc** [comment]
You can download the last Openhab build : https://openhab.ci.cloudbees.com/job/openHAB1-Addons/ and then select the latest build, openHAB RFXCOM Binding and download the .jar .
Damien

**Comment by big-col** [comment]
Thanks Damien

**Comment by big-col** [comment]
I'm using 1.9.0-SNAPSHOT with 1.8.1 runtime.
I'm getting an error...

12:22:46.222 [DEBUG] [.b.r.internal.RFXComConnection:149  ] - Unknown data received, data: 0770002708067E80
12:22:46.232 [ERROR] [.rfxcom.internal.RFXComBinding:273  ] - Error occured during packet receiving, data: 0770002708067E80
org.openhab.binding.rfxcom.internal.RFXComException: Message RFXSENSOR(112) not implemented
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:121) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.RFXComBinding$MessageLister.packetReceived(RFXComBinding.java:236) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector$SerialReader.run(RFXComSerialConnector.java:218) [bundlefile:na]
Caused by: java.lang.ClassNotFoundException: org.openhab.binding.rfxcom.internal.messages.RFXComRFXSensorMessage
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[na:na]
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107) ~[na:na]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_71]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_71]
	at java.lang.Class.forName(Unknown Source) ~[na:1.8.0_71]
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:116) ~[bundlefile:na]
	... 2 common frames omitted

**Comment by Speederc** [comment]
Hi @big-col , Sorry for this test, I didn't see that my PR wasn't merged yet (awaiting for your feedback). Thus it is not contained in the snapshot version. It was probably merged inside this test version : http://dr-petelot-marion.chirurgiens-dentistes.fr/temp/org.openhab.binding.rfxcom_1.9.0.201601301041.jar . Can you test with it ?
If it is not the case, it will require a manual compilation of this PR.
Regards,

**Comment by big-col** [comment]
I will test this weekend :-)

**Comment by big-col** [comment]
hi guys, I'm still getting a 'not implemented' message.

17:30:30.586 [DEBUG] [.b.r.internal.RFXComConnection:147  ] - Unknown data received, data: 0770015D0800F180
17:30:30.595 [ERROR] [.rfxcom.internal.RFXComBinding:284  ] - Error occured during packet receiving, data: 0770015D0800F180
org.openhab.binding.rfxcom.internal.RFXComException: Message RFXSENSOR not implemented
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:120) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.RFXComBinding$MessageLister.packetReceived(RFXComBinding.java:247) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector$SerialReader.run(RFXComSerialConnector.java:209) [bundlefile:na]
Caused by: java.lang.ClassNotFoundException: org.openhab.binding.rfxcom.internal.messages.RFXComRFXSensorMessage
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[na:na]
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107) ~[na:na]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_71]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_71]
	at java.lang.Class.forName(Unknown Source) ~[na:1.8.0_71]
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:115) ~[bundlefile:na]
	... 2 common frames omitted

**Comment by Speederc** [comment]
Hi @big-col , I found a bug in the class naming (Rfxsensor instead of RFXSensor). It should be fixed with this one : http://dr-petelot-marion.chirurgiens-dentistes.fr/temp/org.openhab.binding.rfxcom_1.9.0.201603242337.jar . Sorry !

**Comment by big-col** [comment]
Please don't apologise :)
Is that the only change? The reason I ask is that the previous version had a file size of 188k, whereas this new version has a file size of 224k.

I'll give it a go :)

**Comment by Speederc** [comment]
This version adds also a lot (~10) of new message types.

**Comment by big-col** [comment]
I'm getting an occasional error: (Message = ERROR: Unknown message) is this anything to worry about?



2016-03-31 10:59:10.102 [DEBUG] [.b.r.internal.RFXComConnection] - Data received:
Raw data = 0770002E08085980
 - Packet type = RFXSENSOR
 - Seq number = 46
 - Sub type = RFXSENSORTEMP
 - Id = 8
 - Temperature = 21.37
 - Voltage (mV) = 2137.0
 - Message = ERROR: Unknown message
 - Signal level = 8
 - Battery level = 0
2016-03-31 11:02:16.370 [DEBUG] [.b.r.internal.RFXComConnection] - Data received:
Raw data = 0770002F08086680
 - Packet type = RFXSENSOR
 - Seq number = 47
 - Sub type = RFXSENSORTEMP
 - Id = 8
 - Temperature = 21.5
 - Voltage (mV) = 2150.0
 - Message = ERROR: Unknown message
 - Signal level = 8
 - Battery level = 0
2016-03-31 11:02:16.658 [DEBUG] [.b.r.internal.RFXComConnection] - Data received:
Raw data = 077001300800E080
 - Packet type = RFXSENSOR
 - Seq number = 48
 - Sub type = RFXSENSORAD
 - Id = 8
 - Voltage (mV) = 224.0
 - Message = ERROR: Unknown message
 - Signal level = 8
 - Battery level = 0
2016-03-31 11:03:18.967 [DEBUG] [.b.r.internal.RFXComConnection] - Data received:
Raw data = 077001310800DE80
 - Packet type = RFXSENSOR
 - Seq number = 49
 - Sub type = RFXSENSORAD
 - Id = 8
 - Voltage (mV) = 222.0
 - Message = ERROR: Unknown message
 - Signal level = 8
 - Battery level = 0

**Comment by big-col** [comment]
could you please tell me how the Items for the RFXSENSOR should be configured

Thanks :) :)

**Comment by WiredLife** [comment]
hello is there any new version?
i got this https://openhab.ci.cloudbees.com/job/openHAB1-Addons/1305/artifact/bundles/binding/org.openhab.binding.rfxcom/target/ to get my revolt energy meter working but after some time i got errors

`2016-10-03 04:25:49.963 [ERROR] [.rfxcom.internal.RFXComBinding] - Error occured during packet receiving, data: 32700F5C011C0558EA003B043E02FE4F32700F5C011D0558EB003B043C02FE4F32700F5C011E0558E9003B044702FE4F32700F
org.openhab.binding.rfxcom.internal.RFXComException: Message RFXSENSOR(112) not implemented
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:121) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.RFXComBinding$MessageLister.packetReceived(RFXComBinding.java:236) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector$SerialReader.run(RFXComSerialConnector.java:218) [bundlefile:na]
Caused by: java.lang.ClassNotFoundException: org.openhab.binding.rfxcom.internal.messages.RFXComRFXSensorMessage
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[na:na]
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107) ~[na:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_91]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_91]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_91]
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:116) ~[bundlefile:na]
	... 2 common frames omitted
2016-10-03 04:26:10.391 [ERROR] [.rfxcom.internal.RFXComBinding] - Error occured during packet receiving, data: 32700F5C0125216FEA0102089904545C32700F5C01260558E9003B043902FE4F32700F5C0127216FEA010308A804545C32700F
org.openhab.binding.rfxcom.internal.RFXComException: Message RFXSENSOR(112) not implemented
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:121) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.RFXComBinding$MessageLister.packetReceived(RFXComBinding.java:236) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector$SerialReader.run(RFXComSerialConnector.java:218) [bundlefile:na]
Caused by: java.lang.ClassNotFoundException: org.openhab.binding.rfxcom.internal.messages.RFXComRFXSensorMessage
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[na:na]
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107) ~[na:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_91]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_91]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_91]
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:116) ~[bundlefile:na]
	... 2 common frames omitted
2016-10-03 04:26:26.603 [ERROR] [.rfxcom.internal.RFXComBinding] - Error occured during packet receiving, data: 32700F5C012E216FEA0102089304545C32700F5C012F0558EA003B043D02FE4F327004020131000F5C01300558E9003B043F02
org.openhab.binding.rfxcom.internal.RFXComException: Message RFXSENSOR(112) not implemented
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:121) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.RFXComBinding$MessageLister.packetReceived(RFXComBinding.java:236) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector$SerialReader.run(RFXComSerialConnector.java:218) [bundlefile:na]
Caused by: java.lang.ClassNotFoundException: org.openhab.binding.rfxcom.internal.messages.RFXComRFXSensorMessage
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[na:na]
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107) ~[na:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_91]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_91]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_91]
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:116) ~[bundlefile:na]
	... 2 common frames omitted
2016-10-03 04:26:29.071 [ERROR] [.rfxcom.internal.RFXComBinding] - No acknowledge received from RFXCOM controller, timeout 5000ms due to java.util.concurrent.TimeoutException: waiting timed out
2016-10-03 04:26:35.759 [ERROR] [.rfxcom.internal.RFXComBinding] - Error occured during packet receiving, data: 4F32700F5C0131216FEA0102089704545C32700F5C01320558E9003B043B02FE4F32700F5C0133216FE9010308A304545C32700F5C01340558EA003B044002FE4F32700F5C01350558EA003B044502FE
org.openhab.binding.rfxcom.internal.RFXComException: Message UNKNOWN(50) not implemented
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:121) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.RFXComBinding$MessageLister.packetReceived(RFXComBinding.java:236) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector$SerialReader.run(RFXComSerialConnector.java:218) [bundlefile:na]
Caused by: java.lang.ClassNotFoundException: org.openhab.binding.rfxcom.internal.messages.null
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[na:na]
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107) ~[na:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_91]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_91]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_91]
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:116) ~[bundlefile:na]
	... 2 common frames omitted
2016-10-03 04:26:45.155 [ERROR] [.rfxcom.internal.RFXComBinding] - Error occured during packet receiving, data: 4F32700F5C0136216FEA010408C304545C32700F5C01370558EA003B044102FE4F32700F5C01380558EA003B044902FE4F32700F5C01390558EA003B044802FE4F32700F5C013A216FE9010308A90454
org.openhab.binding.rfxcom.internal.RFXComException: Message UNKNOWN(50) not implemented
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:121) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.RFXComBinding$MessageLister.packetReceived(RFXComBinding.java:236) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector$SerialReader.run(RFXComSerialConnector.java:218) [bundlefile:na]
Caused by: java.lang.ClassNotFoundException: org.openhab.binding.rfxcom.internal.messages.null
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[na:na]
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107) ~[na:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_91]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_91]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_91]
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:116) ~[bundlefile:na]
	... 2 common frames omitted
2016-10-03 04:27:01.621 [ERROR] [.rfxcom.internal.RFXComBinding] - Error occured during packet receiving, data: 5C32700F5C013B216FEA0102089804545C32700F5C013C216FEA010308A304545C32700F5C013D0558E9003C044B02FE4F32700F5C013E216FEB0102089304545C32700F5C013F216FEA0102089804545C32700F5C01400558EA003B04
org.openhab.binding.rfxcom.internal.RFXComException: Message UNKNOWN(50) not implemented
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:121) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.RFXComBinding$MessageLister.packetReceived(RFXComBinding.java:236) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector$SerialReader.run(RFXComSerialConnector.java:218) [bundlefile:na]
Caused by: java.lang.ClassNotFoundException: org.openhab.binding.rfxcom.internal.messages.null
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[na:na]
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107) ~[na:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_91]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_91]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_91]
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:116) ~[bundlefile:na]
	... 2 common frames omitted
2016-10-03 04:27:12.616 [WARN ] [rfxcom.internal.ResultRegistry] - Transmitter response received for sequence 79 but no listener is registered:
Raw data = 4402FE4F32700F5C0141216FEA0102089804545C32700F5C0142216FEA0102089904545C32700F5C0143216FEA010308A504545C32700F5C0144216FEB0102089D04545C32
 - Packet type = TRANSMITTER_MESSAGE
 - Seq number = 79
 - Sub type = UNKNOWN
 - Response = UNKNOWN
2016-10-03 04:27:28.155 [ERROR] [.rfxcom.internal.RFXComBinding] - Error occured during packet receiving, data: 700F5C01450558E9003B044002FE4F32700F5C0146216FEB010208A204545C32700F5C01470558EA003B044702FE4F32700F5C0148216FEA0102088D04555C32700F5C0149216FEB0101088F04555C32700F5C014A216FEA0102089004555C32700F5C014B0558EB003B044002FE4F3270
org.openhab.binding.rfxcom.internal.RFXComException: Message UNKNOWN(15) not implemented
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:121) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.RFXComBinding$MessageLister.packetReceived(RFXComBinding.java:236) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector$SerialReader.run(RFXComSerialConnector.java:218) [bundlefile:na]
Caused by: java.lang.ClassNotFoundException: org.openhab.binding.rfxcom.internal.messages.null
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[na:na]
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107) ~[na:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_91]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_91]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_91]
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:116) ~[bundlefile:na]
	... 2 common frames omitted`
