### ISSUE TITLE
Check for null leads to NullPointerException

### ISSUE THREAD

**Issue by PascalTurbo** [openhab/openhab#2638]
Hi there,

I created this simple rule:

    rule "Update External Current Consumption"
        when
          Item PowerConsumption_Meter_External changed
        then
            var lastValue = PowerConsumption_Meter_External.state
        if (lastValue != null) {
            logInfo("Power: ", lastValue)
        } 
    end

Leads to this error:

    21:47:41.398 ERROR o.o.c.s.ScriptExecutionThread[:48]- Error during the execution of rule 'Update      External Current Consumption'
    java.lang.NullPointerException: null
      at org.openhab.model.script.lib.NumberExtensions.operator_notEquals(NumberExtensions.java:89)
      at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:606)
      at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeOperation(XbaseInterpreter.java:729)
      at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._featureCallOperation(XbaseInterpreter.java:713)

Even more strange: When using the .previousState() instead of .state (I only used state for some testing)

    rule "Update External Current Consumption"
        when
          Item PowerConsumption_Meter_External changed
        then
            var lastValue = PowerConsumption_Meter_External.previousState()
        if (lastValue != null) {
            logInfo("Power: ", lastValue)
        } 
    end

    Error during the execution of rule 'Update External Current Consumption': Could not invoke method: org.openhab.model.script.actions.LogAction.logInfo(java.lang.String,java.lang.String,java.lang.Object[]) on instance: null

This is totally strange: It passes the null-check but then the logInfo Method tells me, that lastValue is null. WTF?

Any ideas what went wrong here?

**Comment by steve-bate** [comment]
Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.
