### ISSUE TITLE
HABDroid: sitemap fails to display - generates exception - build #60

### ISSUE THREAD

**Issue by xsnrg** [openhab/openhab#2648]
I have a sitemap that contains:

	Frame {
		Group item=motion
		Group item=battery
		Text label=HVAC icon="temperature" {
			Setpoint item=HVAC_HeatSetPoint label="Heat setpoint" icon="temperature" minValue=50 maxValue=90 step=1
			Setpoint item=HVAC_CoolSetPoint label="Cool setpoint" icon="temperature" minValue=60 maxValue=90 step=1
			Selection item=HVAC_Mode label="HVAC mode" icon="temperature" mappings=[0="Off",1="Heating",2="Cooling",3="Auto"]
			Text item=HVAC_Temperature
			Text item=HVAC_Humidity
			Text item=HVAC_Fan_Mode
			Text item=HVAC_Operating_State
		}

This frame used to generate correctly in habdroid, but in the last couple builds, it does not work, and displays a blank page.  With debug enabled in openHAB2, I receive the following exception:

2015-05-25 23:00:29 [WARN ] [lipse.jetty.server.HttpChannel:395  ] - /rest/sitemaps/jim/0202javax.servlet.ServletException: javax.servlet.ServletException: java.util.IllegalFormatConversionException: d != java.lang.String
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:130)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: java.util.IllegalFormatConversionException: d != java.lang.String
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:421)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:222)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
Caused by: java.util.IllegalFormatConversionException: d != java.lang.String
        at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4045)
        at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2748)
        at java.util.Formatter$FormatSpecifier.print(Formatter.java:2702)
        at java.util.Formatter.format(Formatter.java:2488)
        at java.util.Formatter.format(Formatter.java:2423)
        at java.lang.String.format(String.java:2790)
        at org.eclipse.smarthome.core.transform.TransformationHelper.transform(TransformationHelper.java:80)
        at org.eclipse.smarthome.io.rest.core.util.BeanMapper.considerTransformation(BeanMapper.java:114)
        at org.eclipse.smarthome.io.rest.core.util.BeanMapper.fillProperties(BeanMapper.java:90)
        at org.eclipse.smarthome.io.rest.core.util.BeanMapper.mapItemToBean(BeanMapper.java:37)
        at org.eclipse.smarthome.io.rest.sitemap.internal.SitemapResource.createWidgetBean(SitemapResource.java:266)

2015-05-25 23:00:29 [WARN ] [lipse.jetty.server.HttpChannel:481  ] - Could not send response error 500: javax.servlet.ServletException: javax.servlet.ServletException: java.util.IllegalFormatConversionException: d != java.lang.String

The frame generates successfully in a web browser.

Thanks
Jim

**Comment by xsnrg** [comment]
Figuring out how to best move this to the right place.  OpenHAB.android

**Comment by xsnrg** [comment]
Moved to OpenHAB.android
