### ISSUE TITLE
Designer 1.7.0 cannot open my sitemap

### ISSUE THREAD

**Issue by PelicanHu** [openhab/openhab#2656]
I've just download the new designer (ver. 1.7.0) and when I try to open my sitemap it fails:
"Failed to create the part's controls"
![image](https://cloud.githubusercontent.com/assets/5656824/7841911/03e555ea-04a0-11e5-8f36-79117fc7724c.png)

The previous version of designers (e.g. 1.6.2) can load the same sitemap without any problem.
My sitemap:
sitemap  Logodi label="Logodi" {
	Frame {
//Text item=BananaBoard
		Text item=Date
		Text item=Power_Cons	visibility=[Power_Cons>0] valuecolor=[>1000="red", <300="green"]
		Switch item=Switch_Power
		Switch item=Switch_Pump
		Group item=GrLights {
//			Frame label="All lights" {
//     	  		Switch item=GrLights mappings=[OFF="All Off"]
//   	  		}
   	  		Frame label="MiLight" {
   	  			Group item=GrMiLight  {
    				Group item=GrML_All {
	    	            Slider item=MiLightDim_All
	    	            Switch item=MiLightNight_All
	    	            Switch item=MiLightWhite_All
	 		  			Colorpicker item=MiLightRGB_All
		                Switch item=MiLightDmode_All mappings=[INCREASE='On']
	    	            Switch item=MiLightDspeed_All mappings=[DECREASE='-', INCREASE='+']
	 		  		}	 
    				Group item=GrML_Office {
					  	Switch item=MiLight_Office
					  	Switch item=MiLightNight_Office mappings=[ON='On']
		   				Slider item=MiLightDim_Office 
					  	Switch item=MiLightWhite_Office mappings=[ON='On']
	 		  			Colorpicker item=MiLightRGB_Office
		                Switch item=MiLightDmode_Office mappings=[INCREASE='On']
	    	            Switch item=MiLightDspeed_Office mappings=[DECREASE='-', INCREASE='+']
 		  			} 
    				Group item=GrML_Living {
		   				Slider item=MiLightDim_Living 
					  	Switch item=MiLightWhite_Living mappings=[ON='On']
 	  					Colorpicker item=MiLightRGB_Living
		                Switch item=MiLightDmode_Living mappings=[INCREASE='On']
	    	            Switch item=MiLightDspeed_Living mappings=[DECREASE='-', INCREASE='+']
 	  				} 
    				Group item=GrML_Living3 {
		   				Slider item=MiLightDim_Living3 
					  	Switch item=MiLightWhite_Living3 mappings=[ON='On']
 	  					Colorpicker item=MiLightRGB_Living3 
		                Switch item=MiLightDmode_Living3 mappings=[INCREASE='On']
	    	            Switch item=MiLightDspeed_Living3 mappings=[DECREASE='-', INCREASE='+']
 	  				} 
    				Group item=GrML_Bedroom {
		   				Slider item=MiLightDim_Bedroom 
					  	Switch item=MiLightWhite_Bedroom mappings=[ON='On']
 	  					Colorpicker item=MiLightRGB_Bedroom
		                Switch item=MiLightDmode_Bedroom mappings=[INCREASE='On']
	    	            Switch item=MiLightDspeed_Bedroom mappings=[DECREASE='-', INCREASE='+']
 	  				} 
 	  			}
   	  		} 
			Frame label="Power" 	visibility=[Power_Cons>0] {
				Text item=Power_Cons	visibility=[Power_Cons>0] valuecolor=[>1000="red", <300="green"]
			}
			Frame label="Living room" {
			  	Switch item=Light_Living 
			  	Switch item=Light_Living2
			  	Switch item=Light_Living3
			}
			Frame label="Office" {
			  	Switch item=Light_Office 
//			  	Switch item=MiLight_Office 
//			  	Switch item=MiLightWhite_Office 
//   				Slider item=MiLightDim_Office label="Ceiling light" sendFrequency=300 switchSupport //visibility=[Light_Office==ON]
			}
			Frame label="Bedroom" {
			  	Switch item=Light_Bedroom
			}
			Frame label="Kitchen" {
			  	Switch item=Light_Kitchen 
			  	Switch item=Light_Kitchen2 
			  	Switch item=Light_Kitchen3 
			}
			Frame label="Bathroom" {
			  	Switch item=Light_Bathroom 
			  	Switch item=Light_Bathroom2 
			  	Switch item=Light_Bathroom3 
			}
			Frame label="Hall" {
			  	Switch item=Light_Hall 
			  	Switch item=Light_Hall2 
			}
			Frame label="Relays" {
Text item=Relay1
Text item=Relay2
Text item=Relay3
            }
		}
		Group item=GrTempPresets { 
			  	Setpoint item=TempPreset_Living minValue=15 maxValue=27 step=0.5
			  	Setpoint item=TempPreset_Office minValue=15 maxValue=27 step=0.5
			  	Setpoint item=TempPreset_Bedroom minValue=15 maxValue=27 step=0.5
			  	Setpoint item=TempPreset_Bathroom minValue=15 maxValue=27 step=0.5
		}
		Group item=GrInnerTemp
		Group item=GrOuterTemp
		Group item=GrAlarm 
		    icon="shield" {
			Frame label="Alarm state" {
			  	Text item=Alarm_Status
			}
			Frame label="Door status" {
			 	Text item=Door_Maindoor labelcolor=[1="red"] valuecolor=[1="red" ,0="green"]
			}
			Frame label="Motion sensors" {
			 	Text item=Motion_Living labelcolor=[1="blue" ] valuecolor=[1="blue" ]
			 	Text item=Motion_Office labelcolor=[1="blue" ] valuecolor=[1="blue" ]
			 	Text item=Motion_Bedroom labelcolor=[1="blue" ] valuecolor=[1="blue" ]
			 	Text item=Motion_Bathroom labelcolor=[1="blue" ] valuecolor=[1="blue" ]
			 	Text item=Motion_Kitchen labelcolor=[1="blue" ] valuecolor=[1="blue" ]
			}
			Frame label="Power status" {
			 	Text item=Power_240V labelcolor=[0="red"] valuecolor=[0="red" ,1="green"]
			 	Text item=Power_12V labelcolor=[0="red"] valuecolor=[0="red" ,1="green"] 
			 	Text item=Power_Battery labelcolor=[0="red"] valuecolor=[0="red" ,1="green"]
			}
		}	
	   	Group item=GrSensors {
			Frame label="Power" 	{
   				Text item=Power_Cons	visibility=[Power_Cons>0] valuecolor=[>1000="red", <300="green"]
			 	Text item=Power_Voltage labelcolor=[0="red"] valuecolor=[0="red" ,>0="green"]
			 	Text item=Power_240V labelcolor=[0="red"] valuecolor=[0="red" ,1="green"]
			 	Text item=Power_12V labelcolor=[0="red"] valuecolor=[0="red" ,1="green"] 
			 	Text item=Power_Battery labelcolor=[0="red"] valuecolor=[0="red" ,1="green"]
			}
			Frame label="Door" {
			 	Text item=Door_Maindoor labelcolor=[1="red"] valuecolor=[1="red" ,0="green"]
			}
			Frame label="Temperature sensors" visibility=[Temp_BalconyS>-100] {
				Text item=Temp_Living 	visibility=[Temp_Living>0]
				Text item=Temp_Office 	visibility=[Temp_Office>0]
				Text item=Temp_Bedroom	visibility=[Temp_Bedroom>0]
				Text item=Temp_Bathroom visibility=[Temp_Bathroom>0]
				Text item=Temp_BalconyN visibility=[Temp_BalconyN>-100]
				Text item=Temp_BalconyS visibility=[Temp_BalconyS>-100]
			}
			Frame label="Humidity sensors" visibility=[RH_BalconyS>0] {
				Text item=RH_Living		visibility=[RH_Living>0]
				Text item=RH_Office		visibility=[RH_Office>0]
				Text item=RH_Bedroom	visibility=[RH_Bedroom>0]
				Text item=RH_Bathroom	visibility=[RH_Bathroom>0]
				Text item=RH_BalconyN	visibility=[RH_BalconyN>0]	
				Text item=RH_BalconyS	visibility=[RH_BalconyS>0]
			}
			Frame label="Light sensors" visibility=[Alight_BalconyS>-1] { 
				Text item=Alight_BalconyN 	visibility=[Alight_BalconyN>-1]
				Text item=Alight_BalconyS	visibility=[Alight_BalconyS>-1]
			}
			Frame label="Pressure sensor" {
				Text item=Air_Pressure 	visibility=[Air_Pressure>0]
			}
			Frame label="Motion sensors" {
			 	Text item=Motion_Living labelcolor=[1="blue" ] valuecolor=[1="blue" ]
			 	Text item=Motion_Office labelcolor=[1="blue" ] valuecolor=[1="blue" ]
			 	Text item=Motion_Bedroom labelcolor=[1="blue" ] valuecolor=[1="blue" ]
			 	Text item=Motion_Bathroom labelcolor=[1="blue" ] valuecolor=[1="blue" ]
			 	Text item=Motion_Kitchen labelcolor=[1="blue" ] valuecolor=[1="blue" ]
			}
		}
		Group item=GrCameras {
			Frame label="Office" {
		      	Image url="http://192.168.0.22:8081/" refresh=1
		    }
		}      	
		      		
	}
}

**Comment by Marinek** [comment]
Hi, 
did you try to delete your workspace folder in your designer? Please exit the designer first. There seems to be a problem with your current workspace. This is the place where  the designer stores his application settings. 
After restarting the designer you need to select your config folder again.

Martin

**Comment by PelicanHu** [comment]
Hi,
I deleted the workspace folder, started designer and it creates the workspace folder again.
When I try to open my sitemap it fails again. :(

In the newly created log file this is the last entry:

!ENTRY org.eclipse.e4.ui.workbench 4 0 2015-06-13 21:34:47.941
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.eclipse.xtext.EcoreUtil2.getContainerOfType(EcoreUtil2.java:100)
	at org.eclipse.xtext.GrammarUtil.containingAssignment(GrammarUtil.java:95)
	at org.eclipse.xtext.resource.DefaultLocationInFileProvider.findNodeFor(DefaultLocationInFileProvider.java:321)
	at org.eclipse.xtext.resource.DefaultLocationInFileProvider.doGetTextRegion(DefaultLocationInFileProvider.java:77)
	at org.eclipse.xtext.resource.DefaultLocationInFileProvider.getTextRegion(DefaultLocationInFileProvider.java:56)
	at org.eclipse.xtext.resource.DefaultLocationInFileProvider.getFullTextRegion(DefaultLocationInFileProvider.java:52)
	at org.eclipse.xtext.ui.editor.folding.DefaultFoldingRegionProvider.computeObjectFolding(DefaultFoldingRegionProvider.java:101)
	at org.eclipse.xtext.ui.editor.folding.DefaultFoldingRegionProvider.computeObjectFolding(DefaultFoldingRegionProvider.java:86)
	at org.eclipse.xtext.ui.editor.folding.DefaultFoldingRegionProvider.doGetFoldingRegions(DefaultFoldingRegionProvider.java:68)
	at org.eclipse.xtext.ui.editor.folding.DefaultFoldingRegionProvider$1.exec(DefaultFoldingRegionProvider.java:60)
	at org.eclipse.xtext.ui.editor.folding.DefaultFoldingRegionProvider$1.exec(DefaultFoldingRegionProvider.java:1)
	at org.eclipse.xtext.util.concurrent.AbstractReadWriteAcces.readOnly(AbstractReadWriteAcces.java:32)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:78)
	at org.eclipse.xtext.ui.editor.folding.DefaultFoldingRegionProvider.getFoldingRegions(DefaultFoldingRegionProvider.java:56)
	at org.eclipse.xtext.ui.editor.folding.DefaultFoldingStructureProvider.calculateProjectionAnnotationModel(DefaultFoldingStructureProvider.java:114)
	at org.eclipse.xtext.ui.editor.folding.DefaultFoldingStructureProvider.initialize(DefaultFoldingStructureProvider.java:58)
	at org.eclipse.xtext.ui.editor.folding.DefaultFoldingStructureProvider.handleProjectionEnabled(DefaultFoldingStructureProvider.java:99)
	at org.eclipse.xtext.ui.editor.folding.DefaultFoldingStructureProvider$ProjectionChangeListener.projectionEnabled(DefaultFoldingStructureProvider.java:186)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.fireProjectionEnabled(ProjectionViewer.java:487)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.enableProjection(ProjectionViewer.java:535)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.doOperation(ProjectionViewer.java:1414)
	at org.eclipse.xtext.ui.editor.XtextEditor.installFoldingSupport(XtextEditor.java:476)
	at org.eclipse.xtext.ui.editor.XtextEditor.createPartControl(XtextEditor.java:457)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:138)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:96)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:313)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:861)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:841)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:113)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:321)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:242)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:161)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:102)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:71)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:53)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:141)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:894)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:629)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:731)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$2(PartRenderingEngine.java:702)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$7.run(PartRenderingEngine.java:696)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:681)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1115)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.postProcess(LazyStackRenderer.java:98)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:731)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$2(PartRenderingEngine.java:702)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$7.run(PartRenderingEngine.java:696)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:681)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:59)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:641)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$6.run(PartRenderingEngine.java:520)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:505)
	at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(ElementReferenceRenderer.java:74)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:894)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:629)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:731)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$2(PartRenderingEngine.java:702)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$7.run(PartRenderingEngine.java:696)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:681)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:59)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:641)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:731)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$2(PartRenderingEngine.java:702)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$7.run(PartRenderingEngine.java:696)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:681)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:59)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:641)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:731)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$2(PartRenderingEngine.java:702)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$7.run(PartRenderingEngine.java:696)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:681)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:59)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveRenderer.processContents(PerspectiveRenderer.java:59)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:641)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:731)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$2(PartRenderingEngine.java:702)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$7.run(PartRenderingEngine.java:696)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:681)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveStackRenderer.showTab(PerspectiveStackRenderer.java:103)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.postProcess(LazyStackRenderer.java:98)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveStackRenderer.postProcess(PerspectiveStackRenderer.java:77)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:731)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$2(PartRenderingEngine.java:702)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$7.run(PartRenderingEngine.java:696)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:681)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:59)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:641)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:731)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$2(PartRenderingEngine.java:702)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$7.run(PartRenderingEngine.java:696)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:681)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:59)
	at org.eclipse.e4.ui.workbench.renderers.swt.WBWRenderer.processContents(WBWRenderer.java:644)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:641)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:731)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$2(PartRenderingEngine.java:702)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$7.run(PartRenderingEngine.java:696)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:681)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:987)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:942)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:588)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:543)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.openhab.designer.ui.internal.application.Application.start(Application.java:28)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)

**Comment by Marinek** [comment]
Hello again,
I searched the problem and it seems that this problem is related with xText. This is used to validate the sitemap grammar (e.g. where you have to put { or }). I can reproduce this in my 1.7 Designer downloaded from the latest stable version.  
I removed from your sitemap above some parts until I could finally open your sitemap. I had to remove all occurrences of comparison with negative numbers. 
This line is ok:
Frame label="Temperature sensors" visibility=[Temp_BalconyS>100] { 
This line triggers the above error:
Frame label="Temperature sensors" visibility=[Temp_BalconyS>-100] {
If you remove this comparisons you should be able to open your sitemap. The designer shows an error if you then add the negative numbers.
Multiple markers at this line

- mismatched character ']' expecting '.'
- no viable alternative at input '{'

You could try to use decimal values (-100.0) as a workaround.
Martin

**Comment by PelicanHu** [comment]
You are great! :-)
Changed to decimal values and it works!
Thank you very much!
I really appreciate your help.

**Comment by teichsta** [comment]
@Marinek thanks for tracking this down! Any idea how to solve this problem? Best, Thomas E.-E.

**Comment by Marinek** [comment]
Hi,
I will have a closer look at this. Currently I have some trouble setting up my development environment.
If someone knows how to fix this, please do it and don’t wait for me ;)
However I'd like to check two possibilities here: 
- The grammar has to be extended to accept negative integers here
- The editor is basically able to show the content of the sitemap and its “error” but the xtext is throwing a null pointer exception due to a missing reduction in the grammar. This Nullpointer is not handled so it is shown to the user as a big text suppressing the editor at all.

Best regards ;)
Martin

**Comment by Testato** [comment]
This problem appear also if you use the negative sign on an icon name "clock-on.png"

**Comment by CWempe** [comment]
I just had the same issue.

This line produced the error:
> String	CastDown	"Volume down"		{exec=">[TOGGLE:/opt/castnow_control/castnow_send_command.sh down]"	"autoupdate"="false"}

When adding a comma after the binding config it works again.
> String	CastDown	"Volume down"		{exec=">[TOGGLE:/opt/castnow_control/castnow_send_command.sh down]",	"autoupdate"="false"}

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
