### ISSUE TITLE
Concurrent access to CUL transport binding is not working >= 1.7.0

### ISSUE THREAD

**Issue by andreheuer** [openhab/openhab#2671]
Hi all,

I have a RPi 2 using an CUL stick and the FS20, Intertechno and S300TH binding. All bindings are using my CUL stick. Everything is running fine in OH 1.6.0, 1.6.1 and 1.6.2. After updating to 1.7.0, the log reports the following errors:
```
2015-05-30 17:07:09.216 [ERROR] [.o.b.i.i.CULIntertechnoBinding] - Can't open CUL
org.openhab.io.transport.cul.CULDeviceException: The device serial:/dev/ttyACM0 is already open in mode SLOW_RF
        at org.openhab.io.transport.cul.CULManager.getOpenCULHandler(CULManager.java:85) ~[bundlefile:na]
        at org.openhab.io.transport.cul.CULManager.getOpenCULHandler(CULManager.java:54) ~[bundlefile:na]
        at org.openhab.binding.intertechno.internal.CULIntertechnoBinding.bindCULHandler(CULIntertechnoBinding.java:101) [bundlefile:na]
        at org.openhab.binding.intertechno.internal.CULIntertechnoBinding.setNewDeviceName(CULIntertechnoBinding.java:94) [bundlefile:na]
        at org.openhab.binding.intertechno.internal.CULIntertechnoBinding.updated(CULIntertechnoBinding.java:208) [bundlefile:na]
        at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
        at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
```

So I did the following: first, removing all bindings using the CUL device and then successively adding the removed bindings. Thereby, I observed that the first binding I added is working fine. All functions of the binding are ok. After adding a second binding, the binding produces the upper exception. This exception is produced by every binding added after the first binding. Thereby, it doesn´t matter which binding is the first one. Only this binding works with the CUL device.

Best regards
André

**Comment by andreheuer** [comment]
@gernoteger Maybe you have an idea? I have made some tests (https://groups.google.com/forum/#!category-topic/openhab/discussions/430B_IhTXDw) and found the problem introduced by the properties of the serial connection :-/
