### ISSUE TITLE
OneWire binding: java.lang.NullPointerException on parse binding

### ISSUE THREAD

**Issue by jazzdabbler** [openhab/openhab#2685]
Setup OneWire network on RaspberryPi with owfs and ensure that it works corrrctly
owserver running on 127.0.0.1:4304
``` text
pi@aqua ~/ $ cat /etc/owfs.conf 
# With this setup, any client (but owserver) uses owserver on the
# local machine...
! server: server = 127.0.0.1:4304
# USB device: DS9490
server: usb = all
http: port = 192.168.0.111:2121
ftp: port = 2120
server: port = 127.0.0.1:4304
```

owhttp working, we may see one DS18B20 temperature sensor

![owhttp](https://cloud.githubusercontent.com/assets/865292/7959263/4bc83f0c-0a00-11e5-89c4-dac19428ca14.png)

OpenHab owfs config below

```text
############################## OneWire Binding ########################################
# 
# OwServer IP address.
onewire:ip=127.0.0.1

# OwServer Port (optional, defaults to 4304)
onewire:port=4304

# the retry count in case no valid value was returned.
# upon read (optional, defaults to 3)
#onewire:retry=

# defines which temperature scale owserver should return temperatures in. Valid
# values are CELSIUS, FAHRENHEIT, KELVIN, RANKIN (optional, defaults to CELSIUS).
#onewire:tempscale=

# only changed values are posted to the event-bus, (optinal, defaults to true - values true or false)
#onewire:post_only_changed_values=
```

item config below

```text
Group All
Group All_Sensors
Group Internal_Aqua_Sensors   (All_Sensors)
Group External_Room_Sensors (All_Sensors)

/* Aquarium Temperature */
Number Temperature_Internal_Aqua "Температура [%.1f °C]" <temperature> ( Internal_Aqua_Sensors ) { onewire="deviceId=28.E47BB2020000;propertyName=temperature;refreshinterval=10;ignore85CPowerOnResetValues“ }

```

Full startup log below 
``` text
pi@aqua /opt/openhab $ ./start.sh 
Launching the openHAB runtime...
osgi> 2015-06-03 14:51:36.257 [INFO ] [.o.core.internal.CoreActivator] - openHAB runtime has been started (v1.7.0).
2015-06-03 14:51:56.315 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl] - mDNS service has been started
2015-06-03 14:51:57.334 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl] - Service Discovery initialization completed.
2015-06-03 14:52:01.853 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'rrd4j.persist'
2015-06-03 14:52:05.827 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'exec.persist'
2015-06-03 14:52:05.985 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'db4o.persist'
2015-06-03 14:52:06.115 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'logging.persist'
2015-06-03 14:52:06.739 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'onewire.items'
2015-06-03 14:52:07.242 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'demo.items'
2015-06-03 14:52:21.169 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'demo.script'
2015-06-03 14:52:35.593 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'default.sitemap'
2015-06-03 14:52:44.446 [INFO ] [penhab.io.rest.RESTApplication] - Started REST API at /rest
2015-06-03 14:52:50.596 [INFO ] [.o.u.w.i.servlet.WebAppServlet] - Started Classic UI at /openhab.app
2015-06-03 14:53:00.097 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'demo.rules'
2015-06-03 14:53:16.674 [ERROR] [m.r.internal.engine.RuleEngine] - Error during the execution of startup rule 'Initialize light states': Could not invoke method: org.openhab.model.script.actions.BusEvent.postUpdate(org.openhab.core.items.Item,java.lang.Number) on instance: null
2015-06-03 14:53:19.800 [ERROR] [m.r.internal.engine.RuleEngine] - Error during the execution of startup rule 'Initialize heating states': Could not invoke method: org.openhab.model.script.actions.BusEvent.postUpdate(org.openhab.core.items.Item,java.lang.Number) on instance: null
2015-06-03 14:53:22.213 [ERROR] [m.r.internal.engine.RuleEngine] - Error during the execution of startup rule 'Initialize contact states': Could not invoke method: org.openhab.model.script.actions.BusEvent.postUpdate(org.openhab.core.items.Item,java.lang.Number) on instance: null
2015-06-03 14:53:27.451 [WARN ] [.o.c.p.e.PersistenceExtensions] - There is no queryable persistence service registered with the name 'rrd4j'
2015-06-03 14:53:27.473 [ERROR] [m.r.internal.engine.RuleEngine] - Error during the execution of startup rule 'Update max and min temperatures': cannot invoke method public abstract org.openhab.core.types.State org.openhab.core.persistence.HistoricItem.getState() on null
2015-06-03 14:53:27.680 [ERROR] [i.internal.GenericItemProvider] - Binding configuration of type 'onewire' of item ‘Temperature_Internal_Aqua‘ could not be parsed correctly.
java.lang.NullPointerException: null
	at org.openhab.binding.onewire.internal.deviceproperties.AbstractOneWireDevicePropertyBindingConfig.parseBindingConfig(AbstractOneWireDevicePropertyBindingConfig.java:79) ~[na:na]
	at org.openhab.binding.onewire.internal.deviceproperties.AbstractOneWireDevicePropertyBindingConfig.<init>(AbstractOneWireDevicePropertyBindingConfig.java:75) ~[na:na]
	at org.openhab.binding.onewire.internal.deviceproperties.AbstractOneWireDevicePropertyWritableBindingConfig.<init>(AbstractOneWireDevicePropertyWritableBindingConfig.java:28) ~[na:na]
	at org.openhab.binding.onewire.internal.deviceproperties.OneWireDevicePropertyNumberBindingConfig.<init>(OneWireDevicePropertyNumberBindingConfig.java:46) ~[na:na]
	at org.openhab.binding.onewire.internal.OneWireBindingConfigFactory.createOneWireDeviceProperty(OneWireBindingConfigFactory.java:52) ~[na:na]
	at org.openhab.binding.onewire.internal.OneWireGenericBindingProvider.processBindingConfiguration(OneWireGenericBindingProvider.java:66) ~[na:na]
	at org.openhab.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:348) [org.openhab.model.item_1.7.0.jar:na]
	at org.openhab.model.item.internal.GenericItemProvider.dispatchBindingsPerType(GenericItemProvider.java:309) [org.openhab.model.item_1.7.0.jar:na]
	at org.openhab.model.item.internal.GenericItemProvider.addBindingConfigReader(GenericItemProvider.java:106) [org.openhab.model.item_1.7.0.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0]
	at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:376) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:444) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.dynamicBind(InstanceProcess.java:416) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:334) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.registerService(InstanceProcess.java:536) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:260) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70) [org.eclipse.equinox.util_1.0.400.v20120917-192807.jar:na]
2015-06-03 14:53:27.974 [INFO ] [runtime.busevents             ] - DemoLocation state updated to 52,52°N, 13,40°W, 0,00 m
2015-06-03 14:53:28.016 [INFO ] [runtime.busevents             ] - Temperature_GF_Corridor state updated to 17.70000000
2015-06-03 14:53:28.061 [INFO ] [runtime.busevents             ] - Temperature_GF_Toilet state updated to 21.30000000
2015-06-03 14:53:28.074 [INFO ] [runtime.busevents             ] - Temperature_GF_Living state updated to 17.60000000
2015-06-03 14:53:28.111 [INFO ] [runtime.busevents             ] - Temperature_GF_Kitchen state updated to 18.80000000
2015-06-03 14:53:28.136 [INFO ] [runtime.busevents             ] - Temperature_FF_Bath state updated to 19.50000000
2015-06-03 14:53:28.164 [INFO ] [runtime.busevents             ] - Temperature_FF_Office state updated to 20.10000000
2015-06-03 14:53:28.192 [INFO ] [runtime.busevents             ] - Temperature_FF_Child state updated to 21.60000000
2015-06-03 14:53:28.235 [INFO ] [runtime.busevents             ] - Temperature_FF_Bed state updated to 17.70000000
2015-06-03 14:53:28.301 [INFO ] [o.o.b.o.i.c.OneWireConnection ] - Connected to owserver [IP '127.0.0.1' Port '4304']
2015-06-03 14:53:30.138 [INFO ] [runtime.busevents             ] - Weather_Temp_Max state updated to 22
2015-06-03 14:53:30.999 [INFO ] [.service.AbstractActiveService] - HTTP Refresh Service has been started
2015-06-03 14:53:31.998 [INFO ] [runtime.busevents             ] - Weather_LastUpdate state updated to 2015-06-03T14:53:31
2015-06-03 14:53:32.393 [INFO ] [.service.AbstractActiveService] - NTP Refresh Service has been started
2015-06-03 14:53:33.116 [INFO ] [runtime.busevents             ] - Date state updated to 2015-06-03T14:53:33
2015-06-03 14:53:35.109 [INFO ] [runtime.busevents             ] - Weather_Temp_Min state updated to 19
2015-06-03 14:53:40.772 [INFO ] [g.openhab.model.script.Weather] - Temperature evolved of null degrees.
2015-06-03 14:53:40.802 [ERROR] [o.o.c.s.ScriptExecutionThread ] - Error during the execution of rule 'Compute humidex': Cannot cast org.openhab.core.types.UnDefType to org.openhab.core.library.types.DecimalType
2015-06-03 14:53:41.473 [INFO ] [runtime.busevents             ] - Weather_Humidity state updated to 53
2015-06-03 14:53:42.479 [INFO ] [runtime.busevents             ] - Weather_Temperature state updated to 22
2015-06-03 14:53:42.524 [INFO ] [runtime.busevents             ] - Weather_LastUpdate state updated to 2015-06-03T14:53:42
2015-06-03 14:53:45.669 [INFO ] [runtime.busevents             ] - Weather_Humidex state updated to 24.2164873788430100
2015-06-03 14:54:42.061 [INFO ] [runtime.busevents             ] - Weather_Humidity state updated to 53
2015-06-03 14:54:43.402 [INFO ] [runtime.busevents             ] - Weather_Temperature state updated to 22
2015-06-03 14:54:43.432 [INFO ] [runtime.busevents             ] - Weather_LastUpdate state updated to 2015-06-03T14:54:43
2015-06-03 14:55:00.453 [INFO ] [runtime.busevents             ] - Temperature_GF_Corridor state updated to 22.20000000
2015-06-03 14:55:00.664 [INFO ] [runtime.busevents             ] - Temperature_GF_Toilet state updated to 20.90000000
2015-06-03 14:55:00.861 [INFO ] [runtime.busevents             ] - Temperature_GF_Living state updated to 17.80000000
2015-06-03 14:55:00.978 [INFO ] [runtime.busevents             ] - Temperature_GF_Kitchen state updated to 21.00000000
2015-06-03 14:55:01.115 [INFO ] [runtime.busevents             ] - Temperature_FF_Bath state updated to 20.90000000
2015-06-03 14:55:01.249 [INFO ] [runtime.busevents             ] - Temperature_FF_Office state updated to 20.90000000
2015-06-03 14:55:01.400 [INFO ] [runtime.busevents             ] - Temperature_FF_Child state updated to 22.20000000
2015-06-03 14:55:01.578 [INFO ] [runtime.busevents             ] - Temperature_FF_Bed state updated to 21.70000000
2015-06-03 14:55:02.227 [INFO ] [o.model.script.PersistenceDemo] - 2 minutes ago, the temperature was null degrees.
2015-06-03 14:55:43.092 [INFO ] [runtime.busevents             ] - Weather_Humidity state updated to 53
2015-06-03 14:55:44.463 [INFO ] [runtime.busevents             ] - Weather_Temperature state updated to 22
2015-06-03 14:55:44.503 [INFO ] [runtime.busevents             ] - Weather_LastUpdate state updated to 2015-06-03T14:55:44
2015-06-03 14:56:44.246 [INFO ] [runtime.busevents             ] - Weather_Humidity state updated to 53
2015-06-03 14:56:45.704 [INFO ] [runtime.busevents             ] - Weather_Temperature state updated to 22
2015-06-03 14:56:45.733 [INFO ] [runtime.busevents             ] - Weather_LastUpdate state updated to 2015-06-03T14:56:45
2015-06-03 14:57:45.290 [INFO ] [runtime.busevents             ] - Weather_Humidity state updated to 53
2015-06-03 14:57:46.646 [INFO ] [runtime.busevents             ] - Weather_Temperature state updated to 22
2015-06-03 14:57:46.719 [INFO ] [runtime.busevents             ] - Weather_LastUpdate state updated to 2015-06-03T14:57:46
2015-06-03 14:58:46.465 [INFO ] [runtime.busevents             ] - Weather_Humidity state updated to 53
2015-06-03 14:58:47.772 [INFO ] [runtime.busevents             ] - Weather_Temperature state updated to 22
2015-06-03 14:58:47.805 [INFO ] [runtime.busevents             ] - Weather_LastUpdate state updated to 2015-06-03T14:58:47
2015-06-03 14:59:47.286 [INFO ] [runtime.busevents             ] - Weather_Humidity state updated to 53
2015-06-03 14:59:48.633 [INFO ] [runtime.busevents             ] - Weather_Temperature state updated to 22
2015-06-03 14:59:48.666 [INFO ] [runtime.busevents             ] - Weather_LastUpdate state updated to 2015-06-03T14:59:48
```

**Comment by jazzdabbler** [comment]
I solve the problem
String with item description was incorrect
``` text
Number Temperature_Internal_Aqua "Температура [%.1f °C]" <temperature> ( Internal_Aqua_Sensors ) { onewire="deviceId=28.E47BB2020000;propertyName=temperature;refreshinterval=10;ignore85CPowerOnResetValues“ }
```
Quotes " changed to “
Now its work correctly, please, close ticket

**Comment by jazzdabbler** [comment]
Actually, it's broken in OpenHAB Wiki
``` text
Number OneWireTempSensor "Temp [%.1f °C]“ {onewire="deviceId=28.67C6697351FF;propertyName=temperature;add=0.8;tukeyfilter;refreshinterval=10“}
```
Look at ```"Temp [%.1f °C]“ ``` and ```0“} ```parts

**Comment by teichsta** [comment]
> Actually, it's broken in OpenHAB Wiki

would you mind changing it accordingly? You should have write permission yourself …

Thanks, Thomas E.-E.

**Comment by jazzdabbler** [comment]
Done
