### ISSUE TITLE
Lot of exceptions from onewire binding since update to 1.7

### ISSUE THREAD

**Issue by PascalTurbo** [openhab/openhab#2691]
Hi There,

My Log is full of this kind of exceptions:

    2015-06-05 09:44:40.014 [INFO ] [o.o.b.o.i.c.OneWireConnection ] - Trying to reconnect to owserver...
    2015-06-05 09:44:40.027 [INFO ] [o.o.b.o.i.c.OneWireConnection ] - Connected to owserver [IP '127.0.0.1' Port '4304']
    2015-06-05 09:44:40.084 [ERROR] [o.o.b.o.i.c.OneWireConnection ] - reading from path 28.FD6685050000/temperature attempt 2 throws exception
    org.owfs.jowfsclient.OwfsException: Error -1
      at org.owfs.jowfsclient.internal.OwfsConnectionImpl.readPacket(OwfsConnectionImpl.java:264) ~[org.owfs.jowfsclient-1.2.6.jar:na]
      at org.owfs.jowfsclient.internal.OwfsConnectionImpl.exists(OwfsConnectionImpl.java:159) ~[org.owfs.jowfsclient-1.2.6.jar:na]
      at org.openhab.binding.onewire.internal.connection.OneWireConnection.checkIfDeviceExists(OneWireConnection.java:187) ~[bundlefile:na]
      at org.openhab.binding.onewire.internal.connection.OneWireConnection.readFromOneWire(OneWireConnection.java:203) ~[bundlefile:na]
      at org.openhab.binding.onewire.internal.OneWireBinding.updateItemFromOneWire(OneWireBinding.java:259) [bundlefile:na]
      at org.openhab.binding.onewire.internal.OneWireBinding.devicePropertyWantsUpdate(OneWireBinding.java:216) [bundlefile:na]
      at org.openhab.binding.onewire.internal.scheduler.OneWireUpdateTask.run(OneWireUpdateTask.java:59) [bundlefile:na]

Is this a serious error - then how to fix it?
or is this "normal behaviour" - then how to suppress these messages?

Bests
Chris

**Comment by teichsta** [comment]
could you please take care of this @Dennis650? Thanks, Thomas E.-E.

**Comment by Dennis650** [comment]
Hi,

this is a normal behavior of the binding. Owls can't read your item, so this exception is thrown. I have about 20 devices and i can see those exceptions only if i disconnect one from the bus.

Is your configuration correct? Is 28.FD6685050000 a valid one wire device that you can read directly with owfs?

If it is a valid item, it seems that your onewire bus is not stable. Which adapter is used? How many devices? Do you habe an external 5V power supply? Do u use 100nf condenser with each device?

You can set onewire:retry=1 to minimize those exception, but it solves not the problem of the bus.

Maybe you can suppress this exceptions with a configuration in logbook.xml. But the best way is to solve the problems.

Greetings
Dennis

**Comment by Dennis650** [comment]
Hi Thomas,

>>it would be great if you could also accept the pending invitation to the openHAB organisation

Where can i find the invitation?

Greetings
Dennis

**Comment by PascalTurbo** [comment]
Hi Denis,

I got such Bus-Problems since the first day but I can live with them (got only 2 Wires so no chance for external power supply).

I'll have a look at the logbook.xml

So as I understand you it's not a bug, it's a feature. I'm going to close this Issue.
