### ISSUE TITLE
Refreshing model items don't work on my raspberry pi, I need to restart.

### ISSUE THREAD

**Issue by ludodoucet** [openhab/openhab#2711]
I did the update from version 1.6 to 1.7, since I have a problem when editing my file ( samba or SFTP )
All 10s I have an alert log .

Java 1.8.0
Java runtime: build 1.8.0-b132
	
Weezy, 3.18.11+ on raspberry pi
```
	at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:100) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:159) ~[na:na]
	at org.openhab.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:390) ~[na:na]
	at org.openhab.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:164) ~[na:na]
	at org.openhab.model.item.binding.AbstractGenericBindingProvider.removeConfigurations(AbstractGenericBindingProvider.java:97) ~[na:na]
java.lang.NullPointerException: null
01:11:32.229 [ERROR] [.o.m.c.i.folder.FolderObserver:105  ] - An unexpected exception has occured
01:11:32.204 [DEBUG] [i.internal.GenericItemProvider:154  ] - Processing binding configs for items from model 'yoann.items'
01:11:32.057 [INFO ] [c.internal.ModelRepositoryImpl:98   ] - Refreshing model 'yoann.items'
01:11:30.501 [INFO ] [.service.AbstractActiveService:181  ] - Systeminfo Refresh Service has been shut down
01:11:23.273 [DEBUG] [o.i.m.i.t.MyOpenHABTransportV2:55   ] - Transport.EVENT_REQUEST_HEADERS
01:11:22.990 [DEBUG] [o.i.m.i.t.MyOpenHABTransportV2:55   ] - Transport.EVENT_REQUEST_HEADERS
	at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:100) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:159) ~[na:na]
	at org.openhab.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:390) ~[na:na]
	at org.openhab.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:164) ~[na:na]
	at org.openhab.model.item.binding.AbstractGenericBindingProvider.removeConfigurations(AbstractGenericBindingProvider.java:97) ~[na:na]
java.lang.NullPointerException: null
01:11:21.967 [ERROR] [.o.m.c.i.folder.FolderObserver:105  ] - An unexpected exception has occured
01:11:21.942 [DEBUG] [i.internal.GenericItemProvider:154  ] - Processing binding configs for items from model 'yoann.items'
01:11:21.751 [INFO ] [c.internal.ModelRepositoryImpl:98   ] - Refreshing model 'yoann.items'
01:11:13.973 [WARN ] [ipse.jetty.client.HttpExchange:1013 ] - EXPIRED MyOHExchange@2f86b0=GET//localhost:8080/rest/sitemaps/yoann/0005?_=1433891445599#WAITING(30012ms)->EXPIRED(0ms)sent=30013ms
	at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:100) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:159) ~[na:na]
	at org.openhab.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:390) ~[na:na]
	at org.openhab.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:164) ~[na:na]
	at org.openhab.model.item.binding.AbstractGenericBindingProvider.removeConfigurations(AbstractGenericBindingProvider.java:97) ~[na:na]
java.lang.NullPointerException: null
01:11:11.663 [ERROR] [.o.m.c.i.folder.FolderObserver:105  ] - An unexpected exception has occured
01:11:11.639 [DEBUG] [i.internal.GenericItemProvider:154  ] - Processing binding configs for items from model 'yoann.items'
01:11:11.417 [INFO ] [c.internal.ModelRepositoryImpl:98   ] - Refreshing model 'yoann.items'
	at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:100) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:159) ~[na:na]
	at org.openhab.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:390) ~[na:na]
	at org.openhab.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:164) ~[na:na]
	at org.openhab.model.item.binding.AbstractGenericBindingProvider.removeConfigurations(AbstractGenericBindingProvider.java:97) ~[na:na]
java.lang.NullPointerException: null
01:11:01.343 [ERROR] [.o.m.c.i.folder.FolderObserver:105  ] - An unexpected exception has occured
01:11:01.318 [DEBUG] [i.internal.GenericItemProvider:154  ] - Processing binding configs for items from model 'yoann.items'
01:11:01.045 [INFO ] [c.internal.ModelRepositoryImpl:98   ] - Refreshing model 'yoann.items'
```

**Comment by teichsta** [comment]
can you confirm that yoann.items is syntactically correct (checked with Designer)?

**Comment by ludodoucet** [comment]
Designer (1.7.0) does not tell me for error in my file. But the demo.items refreshing without error. Do you think the designer can pass next to an error?

**Comment by ludodoucet** [comment]
I change the name of the file to yoann2, it's work.
I do not know why, but my problem is solved this way

**Comment by ludodoucet** [comment]
The manipulation that I did correct the problem, it's a bug unimportant. I close
