### ISSUE TITLE
build error: java.lang.OutOfMemoryError: PermGen space

### ISSUE THREAD

**Issue by berndpfrommer** [openhab/openhab#2716]
I got a fairly late version of the 1.8.0 master, and I'm seeing this build error when building with mvn install on ubuntu 12.04:

---------------------------------------------------
constituent[0]: file:/usr/share/maven/lib/commons-cli.jar
constituent[1]: file:/usr/share/maven/lib/maven-settings-3.0.4.jar
constituent[2]: file:/usr/share/maven/lib/aether-api.jar
constituent[3]: file:/usr/share/maven/lib/sisu-guice.jar
constituent[4]: file:/usr/share/maven/lib/commons-httpclient.jar
constituent[5]: file:/usr/share/maven/lib/sisu-inject-bean.jar
constituent[6]: file:/usr/share/maven/lib/aether-connector-wagon.jar
constituent[7]: file:/usr/share/maven/lib/maven-repository-metadata-3.0.4.jar
constituent[8]: file:/usr/share/maven/lib/sisu-inject-plexus.jar
constituent[9]: file:/usr/share/maven/lib/maven-compat-3.0.4.jar
constituent[10]: file:/usr/share/maven/lib/aether-util.jar
constituent[11]: file:/usr/share/maven/lib/maven-model-builder-3.0.4.jar
constituent[12]: file:/usr/share/maven/lib/maven-plugin-api-3.0.4.jar
constituent[13]: file:/usr/share/maven/lib/commons-codec.jar
constituent[14]: file:/usr/share/maven/lib/plexus-cipher.jar
constituent[15]: file:/usr/share/maven/lib/plexus-interpolation.jar
constituent[16]: file:/usr/share/maven/lib/plexus-sec-dispatcher.jar
constituent[17]: file:/usr/share/maven/lib/maven-model-3.0.4.jar
constituent[18]: file:/usr/share/maven/lib/wagon-file.jar
constituent[19]: file:/usr/share/maven/lib/maven-artifact-3.0.4.jar
constituent[20]: file:/usr/share/maven/lib/aether-impl.jar
constituent[21]: file:/usr/share/maven/lib/plexus-component-annotations.jar
constituent[22]: file:/usr/share/maven/lib/maven-core-3.0.4.jar
constituent[23]: file:/usr/share/maven/lib/wagon-provider-api.jar
constituent[24]: file:/usr/share/maven/lib/aether-spi.jar
constituent[25]: file:/usr/share/maven/lib/maven-embedder-3.0.4.jar
constituent[26]: file:/usr/share/maven/lib/wagon-http-shared.jar
constituent[27]: file:/usr/share/maven/lib/maven-aether-provider-3.0.4.jar
constituent[28]: file:/usr/share/maven/lib/commons-logging.jar
constituent[29]: file:/usr/share/maven/lib/maven-settings-builder-3.0.4.jar
constituent[30]: file:/usr/share/maven/lib/guava.jar
constituent[31]: file:/usr/share/maven/lib/plexus-utils.jar
constituent[32]: file:/usr/share/maven/lib/wagon-http.jar
---------------------------------------------------
Exception in thread "main" java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:386)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:545)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

What has changed? Anybody else struggling with this?

**Comment by digitaldan** [comment]
Do you have your mvn memory settings correct?  

https://github.com/openhab/openhab/wiki/IDE-Setup

```Create Environment Variable MAVEN_OPTS and set it to -Xms512m -Xmx1024m -XX:PermSize=256m -XX:MaxPermSize=512m in order to avoid memory problems during the build process.```

**Comment by teichsta** [comment]
yep, that should solve the problem (you could also try to build with java 8)

(feel free to reopen if this didn't solve your problem)

**Comment by berndpfrommer** [comment]
It used to work fine without MAVEN_OPTS, until it didn't ....
Is there a way this option can be set within the build environment so as to reduce the number of steps necessary to build openhab?
