### ISSUE TITLE
Potential NPE in RRD4jService

### ISSUE THREAD

**Issue by Brhett** [openhab/openhab#2744]
https://github.com/openhab/openhab/blob/master/bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jService.java#L348 should take care of "config" as https://github.com/openhab/openhab/blob/master/bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jService.java#L344 indicates it might be *null*

**Comment by dominicdesu** [comment]
This is not only potential, I can see it everytime during startup of openHAB :-)
It is normally not displayed because the OSGi logger is set to OFF by default. Setting it to ERROR (`<logger name="OSGi" level="ERROR" />`) will show the error in the log:
```
2015-06-15 07:19:44.958 [ERROR] [OSGi] - null
java.lang.NullPointerException: null
	at org.openhab.persistence.rrd4j.internal.RRD4jService.updated(RRD4jService.java:348) ~[na:na]
	at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183) ~[na:na]
	at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36) ~[na:na]
```

**Comment by J-N-K** [comment]
I'll take care of that.

**Comment by teichsta** [comment]
thanks @J-N-K!
