### ISSUE TITLE
Cannot start openhab-runtime demo on Xbian distro RPi2

### ISSUE THREAD

**Issue by Liukkjan** [openhab/openhab#2775]
Hi,

I have a problem with openhab-runtime. I have tried several days now install via different methods (.deb package, zips, different versions or snapshots). It all comes down to these weird eclipse osgi errors. I have also tried googling them, a lot, but can't find anything.

Do you guys have any ideas what these mean? 

uname -a:
Linux xbian 3.18.8+ #1 SMP PREEMPT Thu Mar 5 03:13:36 CET 2015 armv7l GNU/Linux

cat server/configuration/1434912072093.log

!SESSION 2015-06-21 18:41:11.194 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=arm, WS=gtk, NL=en_US
Command-line arguments:  -console

!ENTRY org.eclipse.osgi 4 0 2015-06-21 18:41:12.760
!MESSAGE Startup error
!STACK 1
java.lang.ExceptionInInitializerError
        at org.eclipse.osgi.framework.internal.core.Framework.initializeProperties(Framework.java:380)
        at org.eclipse.osgi.framework.internal.core.Framework.<init>(Framework.java:202)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:262)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:176)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
Caused by: java.security.ProviderException: setSeed() failed
        at sun.security.provider.NativePRNG$RandomIO.implSetSeed(NativePRNG.java:458)
        at sun.security.provider.NativePRNG$RandomIO.access$300(NativePRNG.java:329)
        at sun.security.provider.NativePRNG.engineSetSeed(NativePRNG.java:212)
        at java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:203)
        at java.security.SecureRandom.<init>(SecureRandom.java:184)
        at org.eclipse.osgi.framework.internal.core.UniversalUniqueIdentifier.computeNodeAddress(UniversalUniqueIdentifier.java:127)
        at org.eclipse.osgi.framework.internal.core.UniversalUniqueIdentifier.<clinit>(UniversalUniqueIdentifier.java:35)
        ... 12 more
Caused by: java.io.IOException: Invalid argument
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:294)
        at sun.security.provider.NativePRNG$RandomIO.implSetSeed(NativePRNG.java:456)
        ... 18 more

EDIT: It might be libjna. Didn't see that as a requirement. -- Didn't work.
EDIT2: Found out about flag " -Djava.security.egd=/dev/random". Added it and at moment, I think, it starts. Just a moment

**Comment by Liukkjan** [comment]
It was the extra JAVA ARGS "-Djava.security.egd=/dev/random". I added it to the start.sh and init script. Closing the issue.
