### ISSUE TITLE
Error when refreshing the item file

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab#2842]
While openHAB server is running, if I save my item file, I get this error again and again:

2015-07-02 22:32:23.802 [INFO ] [c.internal.ModelRepositoryImpl] - Refreshing model 'maison.items'
2015-07-02 22:32:24.705 [ERROR] [.o.m.c.i.folder.FolderObserver] - An unexpected exception has occured
java.lang.NullPointerException: null
        at org.openhab.model.item.binding.AbstractGenericBindingProvider.removeConfigurations(AbstractGenericBindingProvider.java:97) ~[na:na]
        at org.openhab.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:164) ~[na:na]
        at org.openhab.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:390) ~[na:na]
        at org.openhab.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:159) ~[na:na]
        at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:100) ~[na:na]
        at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) ~[na:na]
        at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) ~[na:na]

It occurs with openHAB 1.7.

**Comment by watou** [comment]
Looks like it might be the same as #1419.

**Comment by hmerk** [comment]
See comment on #1419
