### ISSUE TITLE
Exception loading default.items in 1.7.0 (not in 1.6.2)

### ISSUE THREAD

**Issue by StefanBertels** [openhab/openhab#2874]
After upgrading to 1.7.0 I get some strange exceptions. Error message itself has no info for me what line might be the cause.

I'm not aware of config errors and it worked without exception in previously running 1.6.2. I just downgraded back to 1.6.2 and error is away again.

Some lines cut out of my default.items:
```
Switch Steckdose_Test "Teststeckdosen" (Testgruppe, Information) { knx="<1/2/3", mqtt=">[mosquitto:/openhab/notification/info:command:ON:Teststeckdosen eingeschaltet.]"}

Group Praesenz "Präsenz" <present> (All)

Group Location "Lokalisierung" (Control)

Group:Contact:OR(OPEN, CLOSED) PersonDa "Person anwesend [(%d)]" (Location)
Contact Status_Handy1 "Handy 1" (Praesenz, Location, PersonDa)
Contact Status_Nexus9 "Nexus 9" (Location)
Contact Status_Handy2 "Handy 2" (Praesenz, Location, PersonDa)
```

Error message (normal log):
```
2015-07-08 03:56:26.473 [ERROR] [.o.m.c.i.folder.FolderObserver] - An unexpected exception has occured
java.lang.NullPointerException: null
        at org.openhab.core.internal.items.ItemRegistryImpl.isValidItemName(ItemRegistryImpl.java:144) ~[na:na]
        at org.openhab.core.internal.items.ItemRegistryImpl.initializeItem(ItemRegistryImpl.java:252) ~[na:na]
        at org.openhab.core.internal.items.ItemRegistryImpl.allItemsChanged(ItemRegistryImpl.java:195) ~[na:na]
        at org.openhab.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:393) ~[na:na]
        at org.openhab.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:159) ~[na:na]
        at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:100) ~[na:na]
        at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) ~[na:na]
        at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) ~[na:na]
```

Logging (TRACE):
```
2015-07-08 04:19:39.586 [TRACE] [i.internal.GenericItemProvider] - Created item 'Steckdose_Test' of type 'Switch'
2015-07-08 04:19:39.588 [TRACE] [i.internal.GenericItemProvider] - Created item 'null' of type 'Location'
2015-07-08 04:19:39.589 [TRACE] [i.internal.GenericItemProvider] - Created item 'PersonDa' of type 'Contact'
2015-07-08 04:19:39.590 [TRACE] [i.internal.GenericItemProvider] - Created item 'null' of type 'Location'
2015-07-08 04:19:39.591 [TRACE] [i.internal.GenericItemProvider] - Created item 'Status_Handy1' of type 'Contact'
2015-07-08 04:19:39.592 [TRACE] [i.internal.GenericItemProvider] - Created item 'PersonDa' of type 'Location'
2015-07-08 04:19:39.698 [ERROR] [.o.m.c.i.folder.FolderObserver] - An unexpected exception has occured
java.lang.NullPointerException: null
        at org.openhab.core.internal.items.ItemRegistryImpl.isValidItemName(ItemRegistryImpl.java:144) ~[na:na]
        at org.openhab.core.internal.items.ItemRegistryImpl.initializeItem(ItemRegistryImpl.java:252) ~[na:na]
        at org.openhab.core.internal.items.ItemRegistryImpl.allItemsChanged(ItemRegistryImpl.java:195) ~[na:na]
        at org.openhab.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:393) ~[na:na]
        at org.openhab.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:159) ~[na:na]
        at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:85) ~[na:na]
        at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) ~[na:na]
        at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) ~[na:na]
```

**Comment by teichsta** [comment]
Hi @StefanBertels,

some questions:

* which platform is openHAB installed on? 
* does this error occur ALWAYS? Did you try to restart several times? On various small embedded systems there are problems with the starting sequence of some of the core bundles which could cause similar error
* which JDK are you using?

Best, Thomas E.-E.

**Comment by StefanBertels** [comment]
Platform: Raspberry Pi 2 (Raspbian)

ALWAYS: Yes, I restarted many times. I downgraded to 1.6.2 twice, so I'm quite sure 1.7.0 makes the difference. 1.7.0 => error, 1.6.2 => works (same configurations).

JDK: oracle-java8-jdk. I didn't change this since using openhab (beginning with 1.5).

I suggest adding more information when rasing this exception at that code line so one can see the reason. And log seems a bit buggy when printing: Created item 'null' of type 'Location'. What does this mean? I have a group with name Location. Or is this a new item type (conflicting with my group definition)?

Stefan

**Comment by StefanBertels** [comment]
Just tested regarding "Location": Yes, there is a new Location item type. After changing my definition from `Group Location` to `Group Lokalisierung` everything seems to work fine with 1.7.0.

There should be a more specific error message.

Nevertheless I will close my issue for now because solved.
