### ISSUE TITLE
Add siren ZM1601EU-5 to the database

### ISSUE THREAD

**Issue by anordvall** [openhab/openhab#2892]
Please add "ZM1601EU-5 Vision Siren & Strobe Alarm Battery Power" with device ID "508" to the database. 

I see ZM1601 is already listed in the products database and has the same device type "2005" as my ZM1601EU-5, but the latter one has device ID "508"

Z-wave Alliance link: http://products.z-wavealliance.org/products/1009

Thanks in advance!

**Comment by SkynetHome** [comment]
I will get this done today!

**Comment by anordvall** [comment]
That's much quicker than I hoped for :) I suspect the lack of the correct products DB entry is why I can not see any device configuration parameters or association groups through habmin currently. Is this correct understanding?

**Comment by cdjackson** [comment]
> 
>  Is this correct understanding?
> 
> 
Yes - that’s correct - we need the database entry as the config parameters are not self described in the device...

**Comment by cdjackson** [comment]
Please confirm this is ok so we can close this request - it should be in tomorrows snapshot.

**Comment by anordvall** [comment]
So, this is the first time I'm trying to use a snapshot... I have taken below steps to try this. Please let me know if I'm missing anything or if it's completely wrong.

1. Download distribution-1.8.0-SNAPSHOT-addons.zip from https://openhab.ci.cloudbees.com/job/openHAB/
2. Move away the old org.openhab.binding.zwave-1.7.0.jar from the addons folder
3. Copy org.openhab.binding.zwave-1.8.0-SNAPSHOT.jar to the addons folder
4. Start openHAB

I now see the device configuration parameters in HABmin but when I try to update parameter 0 Siren Strobe Mode I get the following printsouts in normal mode:

2015-07-12 16:37:55.248 [ERROR] [b.z.i.protocol.ZWaveController] - Exception during Z-Wave thread: Input.
java.lang.ArrayIndexOutOfBoundsException: 7
        at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveCommandClass.extractValue(ZWaveCommandClass.java:293) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveConfigurationCommandClass.processConfigurationReport(ZWaveConfigurationCommandClass.java:113) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveConfigurationCommandClass.handleApplicationCommandRequest(ZWaveConfigurationCommandClass.java:88) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.serialmessage.ApplicationCommandMessageClass.handleRequest(ApplicationCommandMessageClass.java:80) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingRequestMessage(ZWaveController.java:221) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingMessage(ZWaveController.java:194) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.access$6(ZWaveController.java:189) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveInputThread.run(ZWaveController.java:1213) ~[na:na]

When I run in debug mode I get this:

16:48:46.388 [DEBUG] [eController$ZWaveReceiveThread:1528 ] - Receive Message = 01 07 00 13 5A 00 00 7F CE
16:48:46.392 [DEBUG] [eController$ZWaveReceiveThread:1452 ] - Receive queue ADD: Length=1
16:48:46.392 [DEBUG] [b.z.i.protocol.ZWaveController:1210 ] - Receive queue TAKE: Length=0
16:48:46.400 [DEBUG] [o.b.z.i.protocol.SerialMessage:233  ] - Assembled message buffer = 01 09 00 13 5A 00 00 7F 00 00 C0
16:48:46.403 [DEBUG] [b.z.i.protocol.ZWaveController:1211 ] - Process Message = 01 09 00 13 5A 00 00 7F 00 00 C0
16:48:46.407 [DEBUG] [b.z.i.protocol.ZWaveController:190  ] - Message: class = SendData (0x13), type = Request (0x00), payload = 5A 00 00 7F
16:48:46.410 [DEBUG] [b.z.i.p.s.SendDataMessageClass:74   ] - NODE 16: SendData Request. CallBack ID = 90, Status = Transmission complete and ACK received(0)
16:48:46.413 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:63   ] - Sent message Message: class = SendData (0x13), type = Request (0x00), payload = 10 03 70 05 00
16:48:46.415 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:64   ] - Recv message Message: class = SendData (0x13), type = Request (0x00), payload = 5A 00 00 7F
16:48:46.417 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:65   ] - Checking transaction complete: class=SendData, expected=ApplicationCommandHandler, cancelled=false
16:48:46.419 [DEBUG] [eController$ZWaveReceiveThread:1528 ] - Receive Message = 01 0A 00 04 00 10 04 70 06 00 00 93
16:48:46.421 [DEBUG] [eController$ZWaveReceiveThread:1452 ] - Receive queue ADD: Length=1
16:48:46.422 [DEBUG] [b.z.i.protocol.ZWaveController:1210 ] - Receive queue TAKE: Length=0
16:48:46.426 [DEBUG] [o.b.z.i.protocol.SerialMessage:233  ] - Assembled message buffer = 01 0A 00 04 00 10 04 70 06 00 00 93
16:48:46.428 [DEBUG] [b.z.i.protocol.ZWaveController:1211 ] - Process Message = 01 0A 00 04 00 10 04 70 06 00 00 93
16:48:46.429 [DEBUG] [b.z.i.protocol.ZWaveController:190  ] - Message: class = ApplicationCommandHandler (0x04), type = Request (0x00), payload = 00 10 04 70 06 00 00
16:48:46.431 [DEBUG] [ApplicationCommandMessageClass:38   ] - NODE 16: Application Command Request (ALIVE:PING)
16:48:46.433 [DEBUG] [ApplicationCommandMessageClass:56   ] - NODE 16: Incoming command class CONFIGURATION
16:48:46.435 [DEBUG] [ZWaveConfigurationCommandClass:76   ] - NODE 16: Received Configuration Request
16:48:46.440 [ERROR] [b.z.i.protocol.ZWaveController:1220 ] - Exception during Z-Wave thread: Input.
java.lang.ArrayIndexOutOfBoundsException: 7
        at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveCommandClass.extractValue(ZWaveCommandClass.java:293) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveConfigurationCommandClass.processConfigurationReport(ZWaveConfigurationCommandClass.java:113) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveConfigurationCommandClass.handleApplicationCommandRequest(ZWaveConfigurationCommandClass.java:88) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.serialmessage.ApplicationCommandMessageClass.handleRequest(ApplicationCommandMessageClass.java:80) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingRequestMessage(ZWaveController.java:221) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingMessage(ZWaveController.java:194) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.access$6(ZWaveController.java:189) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveInputThread.run(ZWaveController.java:1213) ~[na:na]

**Comment by cdjackson** [comment]
Interesting - I've not seen this before...

It looks like the device is sending back corrupted data - it's sent size=0 which can't be right... I'll add a check into the binding to avoid the NPE, but I would say there are 2 possibilities...

1) That the device sent rubbish data!
2) That this is a new feature of ZWave Plus and in fact param 0 doesn't exist. In the past, if you requested a parameter that didn't exist, the device just never responded which was a right pain as it locks the binding until it times out. Maybe they've changed this to return 0 size which owuld be excelent!

@SkynetHome it looks like the definition in the XML isn't correct - I think it should be param 1 and 2, not 0 and 1... I found the manual in the link a the top of this page... Are you able to confirm this and update the XML please?

**Comment by SkynetHome** [comment]
Working on this now. Sorry again for the delay in response!

**Comment by SkynetHome** [comment]
@anordvall I have made the necessary changes and committed to be merged! I apologize for the delay and any frustration my error may have caused! Hopefully this will get you up and running and thank you for the quick feedback!

**Comment by cdjackson** [comment]
Merged - thanks.

**Comment by anordvall** [comment]
Mike, no apologises needed. I'm very happy I'm getting this kind of
excellent and quick support! I've now tested with the latest snapshot and
everything works just fine. I can now update the device configurations as
expected.

Thanks both of you!

2015-07-13 7:46 GMT+02:00 Chris Jackson <notifications@github.com>:

**Comment by SkynetHome** [comment]
I'm glad to read that the device is working properly and thanks again for
your patience and rapid feedback! Feel free to tag me in any future device
additon requests you may have. Openhab 2 is coming and should make adding
new devices even more fluid but in the meantime I am happy to help out
where I can! Enjoy!

**Comment by SkynetHome** [comment]
@cdjackson  I think this should be good to close. Got confirmation that its working above.

**Comment by cdjackson** [comment]
Thanks.
