### ISSUE TITLE
Scheduler stops running

### ISSUE THREAD

**Issue by eddjlewis** [openhab/openhab#2972]
Since I've upgraded to 1.7.0 from 1.6.2 I seem to have an issue where the scheduler stops running.

There are no ERRORs and running at debug nothing appears amiss

```
12:30:07.636 [DEBUG] [o.o.b.w.i.scheduler.WeatherJob:43   ] - Starting Weather job for location 'ForecastIo'
12:35:00.003 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
12:40:00.002 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
12:40:07.637 [DEBUG] [impl.PropertySettingJobFactory:51   ] - Producing instance of Job 'Weather.weatherJob-ForecastIo', class=org.openhab.binding.weather.internal.scheduler.WeatherJob
12:40:07.637 [DEBUG] [o.o.b.w.i.scheduler.WeatherJob:43   ] - Starting Weather job for location 'ForecastIo'
12:41:08.402 [ERROR] [o.o.b.w.i.scheduler.WeatherJob:53   ] - Read timed out
	at org.openhab.binding.weather.internal.scheduler.WeatherJob.execute(WeatherJob.java:49) ~[na:na]
	at org.openhab.binding.weather.internal.scheduler.WeatherJob.execute(WeatherJob.java:54) ~[na:na]
	at org.openhab.binding.weather.internal.scheduler.WeatherJob.execute(WeatherJob.java:49) ~[na:na]
12:45:00.001 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
12:46:57.709 [DEBUG] [.r.i.engine.RuleTriggerManager:460  ] - Removed scheduled cron job 'demo.rules#[WINDOW] ForecastIO stale data or problem processing rules#0 0/5 * * * ?'
12:50:00.002 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
12:50:07.635 [DEBUG] [impl.PropertySettingJobFactory:51   ] - Producing instance of Job 'Weather.weatherJob-ForecastIo', class=org.openhab.binding.weather.internal.scheduler.WeatherJob
12:50:07.636 [DEBUG] [o.o.b.w.i.scheduler.WeatherJob:43   ] - Starting Weather job for location 'ForecastIo'
12:55:00.002 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
13:00:00.011 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
13:00:07.635 [DEBUG] [impl.PropertySettingJobFactory:51   ] - Producing instance of Job 'Weather.weatherJob-ForecastIo', class=org.openhab.binding.weather.internal.scheduler.WeatherJob
13:00:07.636 [DEBUG] [o.o.b.w.i.scheduler.WeatherJob:43   ] - Starting Weather job for location 'ForecastIo'
13:05:00.002 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
13:10:00.002 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
13:10:07.636 [DEBUG] [impl.PropertySettingJobFactory:51   ] - Producing instance of Job 'Weather.weatherJob-ForecastIo', class=org.openhab.binding.weather.internal.scheduler.WeatherJob
13:10:07.636 [DEBUG] [o.o.b.w.i.scheduler.WeatherJob:43   ] - Starting Weather job for location 'ForecastIo'
13:15:00.001 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
13:20:00.002 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
13:20:07.636 [DEBUG] [impl.PropertySettingJobFactory:51   ] - Producing instance of Job 'Weather.weatherJob-ForecastIo', class=org.openhab.binding.weather.internal.scheduler.WeatherJob
13:20:07.636 [DEBUG] [o.o.b.w.i.scheduler.WeatherJob:43   ] - Starting Weather job for location 'ForecastIo'
13:25:00.002 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
13:30:00.003 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
13:30:07.636 [DEBUG] [impl.PropertySettingJobFactory:51   ] - Producing instance of Job 'Weather.weatherJob-ForecastIo', class=org.openhab.binding.weather.internal.scheduler.WeatherJob
13:30:07.636 [DEBUG] [o.o.b.w.i.scheduler.WeatherJob:43   ] - Starting Weather job for location 'ForecastIo'
13:30:38.199 [ERROR] [o.o.b.w.i.scheduler.WeatherJob:53   ] - Read timed out
	at org.openhab.binding.weather.internal.scheduler.WeatherJob.execute(WeatherJob.java:49) ~[na:na]
	at org.openhab.binding.weather.internal.scheduler.WeatherJob.execute(WeatherJob.java:54) ~[na:na]
	at org.openhab.binding.weather.internal.scheduler.WeatherJob.execute(WeatherJob.java:49) ~[na:na]
13:35:00.002 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
13:40:00.002 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
13:40:07.636 [DEBUG] [impl.PropertySettingJobFactory:51   ] - Producing instance of Job 'Weather.weatherJob-ForecastIo', class=org.openhab.binding.weather.internal.scheduler.WeatherJob
13:40:07.636 [DEBUG] [o.o.b.w.i.scheduler.WeatherJob:43   ] - Starting Weather job for location 'ForecastIo'
13:45:00.002 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
13:50:00.001 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
13:50:07.635 [DEBUG] [impl.PropertySettingJobFactory:51   ] - Producing instance of Job 'Weather.weatherJob-ForecastIo', class=org.openhab.binding.weather.internal.scheduler.WeatherJob
13:50:07.636 [DEBUG] [o.o.b.w.i.scheduler.WeatherJob:43   ] - Starting Weather job for location 'ForecastIo'
13:55:00.015 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
14:00:00.027 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule '[WINDOW] ForecastIO stale data or problem processing rules'
14:00:07.635 [DEBUG] [impl.PropertySettingJobFactory:51   ] - Producing instance of Job 'Weather.weatherJob-ForecastIo', class=org.openhab.binding.weather.internal.scheduler.WeatherJob
14:00:07.636 [DEBUG] [o.o.b.w.i.scheduler.WeatherJob:43   ] - Starting Weather job for location 'ForecastIo'
```
I've attached a stack trace
https://www.dropbox.com/s/lifa6cw37mko74k/stacktrace.txt?dl=0

Where should I look next?

**Comment by dominicdesu** [comment]
Here is a similar issue where the scheduler stopped working: #2761.
Can you see some similarities in the openHAB setup?

**Comment by eddjlewis** [comment]
No, it looks like quite a different setup. I've since reduced my use of the Weather binding to just ForecastIo and the issue seems to have gone away. 

I think it might have been a transient issue with one of Wunderground or Weatheronline, for example, could be an issue parsing response from them at certain times? Conjecture, could be loads of things.

However, whatever the issue, the cause of the scheduler stopping didn't produce an exception in the logs even though I'm logging at debug level. Some exception being thrown, caught, but not logged somewhere?
