### ISSUE TITLE
RFXCom: Error with UV sensor

### ISSUE THREAD

**Issue by Tscherno** [openhab/openhab#3101]
2015-08-27 15:58:53.873 [ERROR] [.rfxcom.internal.RFXComBinding:292 ]- Error occured during packet receiving, data: 095702DBD1000AF42C79
org.openhab.binding.rfxcom.internal.RFXComException: Message UV not implemented
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:121) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.RFXComBinding$MessageLister.packetReceived(RFXComBinding.java:253) ~[bundlefile:na]
	at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector$SerialReader.run(RFXComSerialConnector.java:211) [bundlefile:na]
Caused by: java.lang.ClassNotFoundException: org.openhab.binding.rfxcom.internal.messages.RFXComUVMessage
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.fhttp://www.amazon.de/dp/B001593W1E/ref=pe_386171_51767411_TE_dp_1indClass(BundleLoader.java:421) ~[na:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[na:na]
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107) ~[na:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_79]
	at java.lang.Class.forName0(Native Method) ~[na:1.7.0_79]
	at java.lang.Class.forName(Class.java:191) ~[na:1.7.0_79]
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:116) ~[bundlefile:na]
	... 2 common frames omitted
2015-08-27 15:58:53.879 [DEBUG] [.b.r.internal.RFXComConnection:151 ]- Unknown data received, data: 095702DBD1000AF42C79

Device is a Oregon UV Sensor:
http://www.amazon.de/dp/B001593W1E/ref=pe_386171_51767411_TE_dp_1

**Comment by Speederc** [comment]
Please test with this version : http://marionpetelot.fr/temp/org.openhab.binding.rfxcom_1.8.0.201508312140.jar . It adds UV, attributes of TFA_WIND and Chime messages. If it works, I will add it in official binding.

**Comment by Speederc** [comment]
I forgot to mention that you can use "uv" and "temperature" types as numbers in your item declaration

**Comment by teichsta** [comment]
any update on this? @Speederc did you send a PR meanwhile? Admittedly i didn't remember …

**Comment by Speederc** [comment]
As I didn't get any feedback from Tscherno and I don't have this sensor to test the modification, I didn't create a PR. We can bet to win and add it directly. What do you think ?

**Comment by Speederc** [comment]
In fact, it is already merged by PR #3137 with other new messages.
It wasn't really clear for me neither...

**Comment by teichsta** [comment]
ok, feel free to reopen @Tscherno if @Speederc assumption isn't correct.
