### ISSUE TITLE
RFXcom error with Siemens door chime

### ISSUE THREAD

**Issue by jacobtomlinson** [openhab/openhab#3142]
I get the following error in the debug console when I use my Siemens door chime.

```
org.openhab.binding.rfxcom.internal.RFXComException: Message CHIME not implemented
        at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:121) ~[bundlefile:na]
        at org.openhab.binding.rfxcom.internal.RFXComBinding$MessageLister.packetReceived(RFXComBinding.java:253) ~[bundlefile:na]
        at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector$SerialReader.run(RFXComSerialConnector.java:211) [bundlefile:na]
Caused by: java.lang.ClassNotFoundException: org.openhab.binding.rfxcom.internal.messages.RFXComChimeMessage
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[na:na]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) ~[na:na]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[na:na]
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107) ~[na:na]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_51]
        at java.lang.Class.forName0(Native Method) ~[na:1.8.0_51]
        at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_51]
        at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:116) ~[bundlefile:na]
        ... 2 common frames omitted
```

**Comment by Speederc** [comment]
Please test with this latest version (future 1.8.0) : https://openhab.ci.cloudbees.com/job/openHAB/lastSuccessfulBuild/artifact/distribution/target/distribution-1.8.0-SNAPSHOT-addons.zip . The new rfxcom binding adds UV, attributes of TFA_WIND and Chime messages.

**Comment by jacobtomlinson** [comment]
Great thanks. I'll try it when I get home tonight.

**Comment by jacobtomlinson** [comment]
Perfect
```
Raw data = 0716000200FB0180
 - Packet type = CHIME
 - Seq number = 2
 - Sub type = BYRONSX
 - Id = 251
 - Chime Sound = 1
 - Signal level = 8
 - Battery level = 0
```
