### ISSUE TITLE
MQTT Binding unreliable??

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#3144]
Hi,

sometimes MQTT cant connect to the broker, which is show with the folloing error messages. As it sometimes works as designed, I assume an error in the binding than in my configuration. Which information do you need to find the issue? I use openhab 1.8 snapshot 1016.
```
2015-09-09 09:05:36.110 [INFO ] [o.i.t.m.i.MqttBrokerConnection] - Starting MQTT broker co                                                         nnection 'mysensor'
2015-09-09 09:05:36.144 [ERROR] [o.i.t.m.i.MqttBrokerConnection] - Error starting consumer
org.eclipse.paho.client.mqttv3.MqttException: Unerwarteter Fehler
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:11                                                         5) ~[na:na]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]
2015-09-09 09:05:36.147 [ERROR] [o.i.t.m.i.MqttBrokerConnection] - Error starting consumer
org.eclipse.paho.client.mqttv3.MqttException: Keine Verbindung zu Client
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(Exc                                                         eptionHelper.java:27) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java                                                         :132) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:6                                                         57) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:282) ~[mqtt                                                         -client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:275) ~[mqtt                                                         -client-0.4.0.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.startConsumer(MqttB                                                         rokerConnection.java:480) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.start(MqttBrokerCon                                                         nection.java:124) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnectionHelper.run(MqttBroke                                                         rConnectionHelper.java:37) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_79]
        at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_79]
2015-09-09 09:05:36.149 [ERROR] [o.i.t.m.i.MqttBrokerConnection] - Error starting consumer
org.eclipse.paho.client.mqttv3.MqttException: Keine Verbindung zu Client
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(Exc                                                         eptionHelper.java:27) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java                                                         :132) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:6                                                         57) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:282) ~[mqtt                                                         -client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:275) ~[mqtt                                                         -client-0.4.0.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.startConsumer(MqttB                                                         rokerConnection.java:480) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.start(MqttBrokerCon                                                         nection.java:124) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnectionHelper.run(MqttBroke                                                         rConnectionHelper.java:37) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_79]
        at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_79]
2015-09-09 09:05:36.151 [ERROR] [o.i.t.m.i.MqttBrokerConnection] - Error starting consumer
org.eclipse.paho.client.mqttv3.MqttException: Keine Verbindung zu Client
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(Exc                                                         eptionHelper.java:27) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java                                                         :132) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:6                                                         57) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:282) ~[mqtt                                                         -client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:275) ~[mqtt                                                         -client-0.4.0.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.startConsumer(MqttB                                                         rokerConnection.java:480) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.start(MqttBrokerCon                                                         nection.java:124) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnectionHelper.run(MqttBroke                                                         rConnectionHelper.java:37) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_79]
        at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_79]
2015-09-09 09:05:36.153 [ERROR] [o.i.t.m.i.MqttBrokerConnection] - Error starting consumer
org.eclipse.paho.client.mqttv3.MqttException: Keine Verbindung zu Client
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(Exc                                                         eptionHelper.java:27) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java                                                         :132) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:6                                                         57) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:282) ~[mqtt                                                         -client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:275) ~[mqtt                                                         -client-0.4.0.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.startConsumer(MqttB                                                         rokerConnection.java:480) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.start(MqttBrokerCon                                                         nection.java:124) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnectionHelper.run(MqttBroke                                                         rConnectionHelper.java:37) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_79]
        at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_79]
2015-09-09 09:05:36.154 [ERROR] [o.i.t.m.i.MqttBrokerConnection] - Error starting consumer
org.eclipse.paho.client.mqttv3.MqttException: Keine Verbindung zu Client
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(Exc                                                         eptionHelper.java:27) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java                                                         :132) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:6                                                         57) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:282) ~[mqtt                                                         -client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:275) ~[mqtt                                                         -client-0.4.0.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.startConsumer(MqttB                                                         rokerConnection.java:480) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.start(MqttBrokerCon                                                         nection.java:124) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnectionHelper.run(MqttBroke                                                         rConnectionHelper.java:37) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_79]
        at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_79]
2015-09-09 09:05:36.156 [ERROR] [o.i.t.m.i.MqttBrokerConnection] - Error starting consumer
org.eclipse.paho.client.mqttv3.MqttException: Keine Verbindung zu Client
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(Exc                                                         eptionHelper.java:27) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java                                                         :132) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:6                                                         57) ~[mqtt-client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:282) ~[mqtt                                                         -client-0.4.0.jar:na]
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:275) ~[mqtt                                                         -client-0.4.0.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.startConsumer(MqttB                                                         rokerConnection.java:480) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.start(MqttBrokerCon                                                         nection.java:124) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnectionHelper.run(MqttBroke                                                         rConnectionHelper.java:37) [org.openhab.io.transport.mqtt_1.8.0.201509070137.jar:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_79]
        at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_79]
2015-09-09 09:05:36.159 [ERROR] [o.i.t.m.i.MqttBrokerConnection] - MQTT connection to brok                                                         er was lost
org.eclipse.paho.client.mqttv3.MqttException: Unerwarteter Fehler
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:11                                                         5) ~[na:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
2015-09-09 09:05:36.160 [ERROR] [o.i.t.m.
i.MqttBrokerConnection] - MQTT connection to 'mys                                                         ensor' was lost: Unerwarteter Fehler : ReasonCode 6 : Cause : Unknown
2015-09-09 09:05:36.160 [INFO ] [o.i.t.m.i.MqttBrokerConnection] - Starting connection hel                                                         per to periodically try restore connection to broker 'mysensor'
```

Kind regards Michael

**Comment by staehler** [comment]
Sorry, my mistake. It seems, that the 
  mosquitto_sub -d ...
to the broker block the connection for openhab mqtt binding. I cant understand this, but closing the above mosquitto subscription solves the problem.

**Comment by teichsta** [comment]
no clue about the broker but i would assume discussion this issue at community.openhab.org would engage more people than here …

**Comment by staehler** [comment]
I think, this issue can be closed. This behaviour disappeared,no idea why, but I cannot exclude any faults on my side.

**Comment by kaikreuzer** [comment]
ok, thanks for the update!
