### ISSUE TITLE
New DBMS Persistence Service for derby, h2, hsqldb, mariadb, mysql, postgresql, Sqlite and others

### ISSUE THREAD

**Issue by lewie** [openhab/openhab#3147]
### This is a new DBMS Persistence Service 
Uses MyBatis and JDBC.

#### Keys:
- Tablenames are more readable
- Tablenames can be reconfigured
- Can work with original Databasemodel of MySQL- Service
- Currently supports the following databases:
derby, h2, hsqldb, mariadb, mysql, postgresql, Sqlite
- DBMS clearly separates the database-specific part of openhab logic.
To integrate a new database is fairly simple.
-  The JDBC drivers are not compiled with in the bundle, there is one "Driver Bundle" per Database. Driver files do not increase the main DBMS Service Bundle.

#### What is the benefit of a 'per Item' table layout?
What is the benefit to manage 500,000 Integer, Numbers or Strings per item, instead of 10,000,000 Strings in one table? An attempt to explain:
 1. Data Mass searching: 500,000 to 10,000,000.
 2. It is expensive to search for average, min, max, etc., especially in a bunch of strings.
 3. There are Items which generates only some Data and other millions of datasets per Year, and others are often queried per Minute. On Item level, these different requirements are easier to handle.
 4. Clarity
 5. Delete an Items Table and start over in a second.

In short, with a 'per Item' layout, the scalability and easy maintenance of the database is ensured, even if large amounts of data must be managed.

#### For Testing:
[Pre-Build] (https://github.com/lewie/openhab/tree/dbms-new-service/bundles/persistence/org.openhab.persistence.dbms/build)
[Drivers and Configuration](https://github.com/lewie/openhab/tree/dbms-new-service/bundles/persistence/org.openhab.persistence.dbms/drivers)

#### Older Discussions:
https://github.com/openhab/openhab/pull/2805
https://github.com/openhab/openhab/pull/2670

#### Configuration:
```
######################## DBMS Persistence Service #############################
# I N S T A L L   D B M S   P E R S I S T E N C E   S E R V I C E 
# To use this DBMS-service-bundle (org.openhab.persistence.dbms-X.X.X.jar),
# a appropriate JDBC database-driver is needed in OpenHab addons Folder.
# Prepared matching Bundles with JDBC database-driver embedded can be found in DBMS project. 
# Use: '/drivers/org.openhab.persistence.dbms.jdbc.[databaseName]-X.X.X.jar'.
# Copy both (DBMS-service-bundle and a JDBC database-driver) to your OpenHab '[OpenHab]/addons' Folder to make it work. 
#
# A special case is the driver for H2, it ONLY works by copying "h2-X.X.XXX.jar" to your '[OpenHab]/addons' folder directly.
# Alternatively copying the driver directly may work for some other JDBC database-driver Files too. 
#
# Tested databases/url-prefix: jdbc:derby, jdbc:h2, jdbc:hsqldb, jdbc:mariadb, jdbc:mysql, jdbc:postgresql, jdbc:sqlite
# If using a not known url like jdbc:XXX, configuration is falling back to the default mysql profile and SQL.
# 
# derby, h2, hsqldb, sqlite can be embedded, 
# If no database is available, for Example the url 'jdbc:h2:./testH2' creates a new DB in OpenHab Folder. 

# D A T A B A S E  C O N F I G
# Some URL-Examples, 'service' identifies and activates internally the correct jdbc driver.
# required database url like 'jdbc:<service>:<host>[:<port>;<attributes>]'
# dbms:url=jdbc:derby:./testDerby;create=true
# dbms:url=jdbc:h2:./testH2
# dbms:url=jdbc:hsqldb:./testHsqlDb
# dbms:url=jdbc:mariadb://192.168.0.1:3306/testMariadb
# dbms:url=jdbc:mysql://192.168.0.1:3306/testMysql
# dbms:url=jdbc:postgresql://192.168.0.1:5432/testPostgresql
# dbms:url=jdbc:sqlite:./testSqlite.db

# required database user
#dbms:user=
dbms:user=test

# required database password
#dbms:password=
dbms:password=test

# E R R O R   H A N D L I N G
# optional when Service is deactivated (optional, default: 0 -> ignore) 
#dbms:errReconnectThreshold=

# I T E M   O P E R A T I O N S
# optional tweaking SQL datatypes
# see: https://mybatis.github.io/mybatis-3/apidocs/reference/org/apache/ibatis/type/JdbcType.html        
# see: http://www.h2database.com/html/datatypes.html
# see: http://www.postgresql.org/docs/9.3/static/datatype.html
# defaults:
#dbms:sqltype.CALL			=	VARCHAR(200)
#dbms:sqltype.COLOR			=	VARCHAR(70)
#dbms:sqltype.CONTACT		=	VARCHAR(6)
#dbms:sqltype.DATETIME		=	DATETIME
#dbms:sqltype.DIMMER		=	TINYINT
#dbms:sqltype.LOCATION		=	VARCHAR(30)
#dbms:sqltype.NUMBER		=	DOUBLE
#dbms:sqltype.ROLLERSHUTTER	=	TINYINT
#dbms:sqltype.STRING		=	VARCHAR(65500)
#dbms:sqltype.SWITCH		=	VARCHAR(6)

# For Itemtype "Number" default decimal digit count (optional, default: 3) 
#dbms:numberDecimalcount=

# T A B L E   O P E R A T I O N S
# Tablename Prefix generation, using Item real names or "item" (optional, default: false -> "item") 
#dbms:tableUseRealItemNames=
dbms:tableUseRealItemNames=true

# Tablename Suffix length (optional, default: 4 -> 0001-9999) 
#dbms:tableIdDigitCount=

# Rename existing Tables using tableUseRealItemNames and tableIdDigitCount (optional, default: false) 
# USE WITH CARE! Deactivate after Renaming is done!
#dbms:rebuildTableNames=
#dbms:rebuildTableNames=true

# D A T A B A S E / M Y B A T I S   C O N N E C T I O N S
# Some embeded Databases can handle only one Connection (optional, default: 1) 
# dbms.maxActiveConnections = 1
# dbms.maxIdleConnections = 1
```
Please test the bundle of functionality, stability, robustness and Java specialists for possible improvements (thread safety, synchronization problems ...).

...and of course the openhab2 Compatibility.

Thanks and Have Fun!

[Go to Pullrequest](https://github.com/openhab/openhab/pull/3146)

Rgds
Helmut

**Comment by lewie** [comment]
Hello @teichsta, @kaikreuzer, @watou, @cdjackson,

I push this now a little bit.

After the discussions with @teichsta ([to avoid code duplication](https://github.com/openhab/openhab/pull/2805#issuecomment-117443156)), @cdjackson ([has to be fast](https://github.com/openhab/openhab/pull/2670#issuecomment-138092191)) and @watou ([a more generic JDBC persistence bundle](https://github.com/openhab/openhab/pull/2805#issuecomment-117643846))

I started to disconnect the database logic from openhab part. 

So now there would be two ways to compile the Database Bundle (needs minor adjustments in the code) :
1. One DBMS-Bundle which uses depending on configuration the required JDBC driver. (only JDBC driver is swapped externally, in DBMS-Bundle exists one Classes file per Database which holds differences to default)
2. One Bundle per Database, which uses the classes of the externalized DBMS-Bundle for OpenHab logic. (Driver and database logic in a Bundle, DBMS-Bundle which is used by all Database Bundles)

What is your favorite version?

In both cases, code duplication is largely avoided and get the "[MySQL-](https://github.com/openhab/openhab/wiki/MySQL-Persistence), [H2-](https://github.com/openhab/openhab/pull/2670), [Postgres-Bundle](https://github.com/openhab/openhab/pull/2805)" similar logic and table structure.

It is fast it is robust. (through my small glasses)

I need your constructive feedback, please ;-]



Thank You
Helmut

**Comment by watou** [comment]
My preference is to have fewer configuration steps, which I think might mean there being no separate handling of JDBC driver JAR files.  The ones tested and known to work would be included in the persistence bundle, upgraded over time as needed. 

On another front, would it be better to call this the JDBC Persistence bundle, since that's its specific function?  Calling it DBMS possibly suggests a broader scope than just those things for which JDBC drivers have been tested and included.  One might accidentally think that all DBMSs, like MongoDB, are covered by this bundle. I also think that having the thinnest layer possible to accommodate the slight differences between databases would keep the focus to JDBC-accessible databases.

**Comment by lewie** [comment]
Hi @watou,

Thank You for your feedback!

Minimal configuration:
dbms:url=jdbc:mysql://192.168.0.1:3306/testMysql
dbms:user=test
dbms:password=test

Copy JDBC driver and Bundle to addons folder, thats it.

if OpenHab could load jdbc Driver/jars by maven in real time, this would be cool. ;-)

Or the Bundle could be organized as described in Option 2, then the JDBC-Driver always is included.(but DBMS-Bundle is needed too or is delivered by default in OpenHab)

You are right, "JDBC Persistence" would be more clear at the moment! (That was my first choice)
But why not extend DBMS-Bundle to work with MongoDB and other noSQL-DBs in the future?
To rename it would be no act.

Rgds
Helmut

**Comment by watou** [comment]
@lewie, by "configuration" I include handling JDBC driver JAR files in the process of making persistence work.  If it were possible to be as straightforward by default, from the user's perspective, as the current MySQL bundle, I would see that as a good thing.  Why not include every tested JDBC driver in your persistence JAR's lib directory (unless licensing is the issue)?  I think having users put together pieces that weren't tested together before is asking for maintenance and support problems.

Any reason you didn't go with "JDBC" instead of "DBMS," since it was your first choice?  I see the common theme being the use of JDBC, so expanding the bundle to consider underlying databases that don't map well to JDBC, or don't have JDBC drivers that result in sensible databases, to be "mission creep."  Just my opinion...

**Comment by lewie** [comment]
@watou, no problem to put all together! 
But, Licensing is one Problem (example GPL of mariadb), and then the Bundle would grow with every Database we include (derby, h2, hsqldb, mariadb, mysql, postgresql, Sqlite about 15 MB!).

Alternatively, I could do a main Bundle which is then added to the specific Database Bundle. Means a a hierarchy order, one Bundle per Database which includes/imports JDBC/DBMS Bundle Classes/jar over lib Folder or in another way.

**Main Bundle:** (includes myBatis jar, OH logic classes)
org.openhab.persistence.jdbc

**Per Database Bundles:** (includes Main Bundle, specific database classes and JDBC-Driver)
org.openhab.persistence.jdbc.derby
org.openhab.persistence.jdbc.h2
org.openhab.persistence.jdbc.hsqldb
org.openhab.persistence.jdbc.mariadb
org.openhab.persistence.jdbc.mysql
org.openhab.persistence.jdbc.postgresql
org.openhab.persistence.jdbc.Sqlite 

From the user's perspective then there would be one Bundle per Database in distribution-X:X:X-addons.zip

Only the licensing Problem stays.

**Comment by hakan42** [comment]
Stupid question, doesn't the already existing MySQL add on already bundle the jdbc driver? 

Could we move that into a generic "lib" directory where the user has to download jdbc drivers into, like how it is done with tomcat? Or is this against the OSGI rules?

**Comment by hakan42** [comment]
Also, for the record, I would prefer the per-database bundles. Extra cool if they could be used from other add-ons  (I need to read up on what is possible with OSGI one of these days )

**Comment by lewie** [comment]
@hakan42,
Why not download jdbc drivers into addons folder as in my current solution presented? 
Most JDBC drivers are supplied as a OSGI-Bundle (but No rule without an exception :-(). 
User has to copy Main [DBMS-Bundle](https://github.com/lewie/openhab/tree/dbms-new-service/bundles/persistence/org.openhab.persistence.dbms/build) plus one of these [pre-bundled JDBC-drivers](https://github.com/lewie/openhab/tree/dbms-new-service/bundles/persistence/org.openhab.persistence.dbms/drivers). Alternatively most JDBC-drivers could be copied without pre-bundling into addons folder.


And yes, as explained it is a working solution to bundle per-database, there is no OSGI Problem! When we use this per-database way, it would make sense for me to bundle JDBC-driver into the per-database Bundle too. see: https://github.com/openhab/openhab/issues/3147#issuecomment-142184758

From OSGI perspective, the per-database solution would be the most robust way because actually JDBC drivers are bound to Main-Bundle "optional" (example from MANIFEST.MF: "Import-Package: org.sqlite;resolution:=optional") an this can cause Problems.

I think too now, per-Database would be the best solution.

Thank You for your feedback!
Rgds
helmut

**Comment by hakan42** [comment]
@lewie , licensing would be the only reason. For example, we cannot distribute an Oracle bundle.

For the packaging, must they be named org.openhab.persistence.dbms.jdbc.<foo>.jar or could we have a bundle like org.openhab.persistence.jdbcdriver.<foo>.jar ?

In case I write an addon that wants to work with its own database tables, it would be nice if I could just reference the drivers already present in the system instead of every addon bringing its own copy of the driver (possibly leading to version incompabilities etc. etc. etc.)

**Comment by lewie** [comment]
@hakan42 , 

You mean to store jdbcdrivers more general each in a separated bundle which provides then for all other Bundles? 

Nearly this Is what I'm testing yet, this bundle then includes one more class to run with main-Bundle org.openhab.persistence.jdbc (was org.openhab.persistence.dbms as @watou prefers "jdbc").
Sub-Bundles name which includes the driver is then for example in org.openhab.persistence.jdbc.h2 (org.openhab.persistence.jdbc.h2-1.8.0.jar) would that be general enough for you?

I'm testing this at the moment, but it seams to work to reference the drivers then: 1. in eclipse environment/buildpath, 2. while building/runing OSGI Bundle in OpenHab

If this does not work, JDBC-Drivers can be copied by maven to a new addon /lib folder.

But the bundle which contains the driver definitively always needs to be copied to a Path directory like ./addons or ./server/plugins. Alternatively it can be included to the general Target Platform (OpenHab.target).
For such an intervention are Kai and Thomas the right contact, they can estimate the side-effects.

**Comment by hakan42** [comment]
sounds perfect to me :smile: , the name "jdbc" is cool too.

**Comment by grzech1983** [comment]
Hello,

has anyone tried to use this bundle with OpenHAB2? I've placed bundle with mysql part in addons folder, created dbms.conf file in services directory and I see that items are being added to MySQL DB but I just can't use Charts in sitemap. Chart URL is being generated like this one:

    ...../chart?items=HEM_E&period=D&random=1&service=dbms

and it is generating this error:
```
HTTP ERROR 500

Problem accessing /chart. Reason:

Server Error
Caused by:

java.lang.NoSuchMethodError: java.sql.Timestamp.toInstant()Ljava/time/Instant;
	at org.openhab.persistence.dbms.config.db.DbmsBaseDB$ItemResultHandler.objectAsDate(DbmsBaseDB.java:303)
	at org.openhab.persistence.dbms.config.db.DbmsBaseDB$ItemResultHandler.handleResult(DbmsBaseDB.java:256)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.callResultHandler(DefaultResultSetHandler.java:314)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.storeObject(DefaultResultSetHandler.java:307)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForSimpleResultMap(DefaultResultSetHandler.java:299)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:273)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:249)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:160)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:78)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:303)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:154)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:102)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:82)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.select(DefaultSqlSession.java:142)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.select(DefaultSqlSession.java:130)
	at org.apache.ibatis.binding.MapperMethod.executeWithResultHandler(MapperMethod.java:111)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:61)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53)
	at com.sun.proxy.$Proxy35.doGetHistItemFilterQuery(Unknown Source)
	at org.openhab.persistence.dbms.internal.DbmsMyBatisMapper.getHistItemFilterQuery(DbmsMyBatisMapper.java:184)
	at org.openhab.persistence.dbms.internal.DbmsPersistenceService.query(DbmsPersistenceService.java:612)
	at org.openhab.core.persistence.internal.QueryablePersistenceServiceDelegate.query(QueryablePersistenceServiceDelegate.java:49)
	at org.eclipse.smarthome.ui.internal.chart.DefaultChartProvider.addItem(DefaultChartProvider.java:251)
	at org.eclipse.smarthome.ui.internal.chart.DefaultChartProvider.createChart(DefaultChartProvider.java:171)
	at org.eclipse.smarthome.ui.internal.chart.ChartServlet.doGet(ChartServlet.java:171)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

There is no error in openhab log file when I'm trying to see charts from sitemap file. When accessing chart URL directly it looks like there is some kind of timeout because page loads about 5-10 seconds before returning error. I've also enabled separate file loggin and I don't see there any error related to chart data fetching.

**Comment by lewie** [comment]
@grzech1983,

it seems to be a timeout.

Did you test this with start_debug.bat or start_debug.sh?
If yes, please would you send me your log entries with **DBMS:**? 
Like:
````
13:10:24.328 [DEBUG] [.jdbc.config.JdbcConfiguration:187  ] - DBMS:updateConfig...
````

Then will have a look at.

Thanks
Helmut

**Comment by grzech1983** [comment]
Should I look for it in dbms.log or openhab.log? I have logging set to TRACE for my DBMS log file but for now I'm starting openhab2 as a system service on Ubuntu system. If you want I can send you whole dbms.log file but just tell me where I should upload it/send it.

**Comment by grzech1983** [comment]
Ok I've started with debug file and here you have init part for DBMS:

```

2015-09-25 14:04:12 [DEBUG] [o.p.d.i.DbmsPersistenceService:166  ] - DBMS::activate  persistence service activated
2015-09-25 14:04:12 [DEBUG] [o.p.d.i.DbmsPersistenceService:632  ] - DBMS:  updateConfig called. configuration.size = 7
2015-09-25 14:04:12 [DEBUG] [.dbms.config.DbmsConfiguration:65   ] - DBMS::DbmsConfiguration
2015-09-25 14:04:12 [DEBUG] [.dbms.config.DbmsConfiguration:73   ] - DBMS::updateConfig called. configuration.size = 7
2015-09-25 14:04:12 [DEBUG] [.dbms.config.DbmsConfiguration:77   ] - DBMS:  url=jdbc:mysql://127.0.0.1/openhab
2015-09-25 14:04:12 [DEBUG] [.dbms.config.DbmsConfiguration:86   ] - DBMS:  found serviceName = mysql
2015-09-25 14:04:12 [DEBUG] [.dbms.config.DbmsConfiguration:94   ] - DBMS: Init Class for mysql = org.openhab.persistence.dbms.config.db.DbmsMysql
2015-09-25 14:04:12 [DEBUG] [.o.p.dbms.config.db.DbmsBaseDB:103  ] - DBMS: initSqlTypes: Initialize the type array
2015-09-25 14:04:12 [DEBUG] [o.o.p.dbms.config.db.DbmsMysql:35   ] - DBMS::initEtendedSqlTypes: Initialize the type array sqlTypes=[DOUBLE, VARCHAR(70), TINYINT, VARCHAR(6), VARCHAR(30), VARCHAR(65500), TINYINT, DATET$
2015-09-25 14:04:12 [DEBUG] [.o.p.dbms.config.db.DbmsBaseDB:88   ] - DBMS: setDriverClass: com.mysql.jdbc.Driver
2015-09-25 14:04:12 [DEBUG] [.dbms.config.DbmsConfiguration:98   ] - DBMS::dBConfig done dBDAOClass=org.openhab.persistence.dbms.config.db.DbmsMysql$DbDAO
2015-09-25 14:04:12 [DEBUG] [.dbms.config.DbmsConfiguration:138  ] - DBMS:  user=openhab
2015-09-25 14:04:12 [DEBUG] [.dbms.config.DbmsConfiguration:145  ] - DBMS:  password=...
2015-09-25 14:04:13 [DEBUG] [.dbms.config.DbmsConfiguration:182  ] - DBMS:updateConfig. maxActiveConnections 1
2015-09-25 14:04:13 [DEBUG] [.o.p.dbms.config.db.DbmsBaseDB:93   ] - DBMS: getDriverClass: com.mysql.jdbc.Driver
2015-09-25 14:04:13 [DEBUG] [.dbms.config.DbmsConfiguration:206  ] - DBMS:updateConfig. Try to load JDBC-driver for com.mysql.jdbc.Driver
2015-09-25 14:04:13 [DEBUG] [.o.p.dbms.config.db.DbmsBaseDB:93   ] - DBMS: getDriverClass: com.mysql.jdbc.Driver
2015-09-25 14:04:13 [DEBUG] [.o.p.dbms.config.db.DbmsBaseDB:93   ] - DBMS: getDriverClass: com.mysql.jdbc.Driver
2015-09-25 14:04:13 [DEBUG] [.dbms.config.DbmsConfiguration:210  ] - DBMS:updateConfig. Could load JDBC-driver for com.mysql.jdbc.Driver
2015-09-25 14:04:13 [DEBUG] [.dbms.config.DbmsConfiguration:220  ] - DBMS:updateConfig DbmsConnectionFactory.setConf
2015-09-25 14:04:13 [DEBUG] [.o.p.dbms.config.db.DbmsBaseDB:93   ] - DBMS: getDriverClass: com.mysql.jdbc.Driver
2015-09-25 14:04:13 [DEBUG] [d.config.DbmsConnectionFactory:31   ] - DBMS::setConf driver=com.mysql.jdbc.Driver
2015-09-25 14:04:13 [DEBUG] [.dbms.config.DbmsConfiguration:224  ] - DBMS:updateConfig configuration complete. service=dbms
2015-09-25 14:04:13 [DEBUG] [p.d.internal.DbmsMyBatisMapper:46   ] - DBMS::pingDB
2015-09-25 14:04:13 [DEBUG] [p.d.internal.DbmsMyBatisMapper:212  ] - DBMS: useMapperClass added Mapper BaseInnerDAO
2015-09-25 14:04:13 [DEBUG] [p.d.internal.DbmsMyBatisMapper:217  ] - DBMS: useInnerMapperClass mc.getName=org.openhab.persistence.dbms.config.db.DbmsMysql$DbDAO, mc.getSimpleName=DbDAO
2015-09-25 14:04:13 [DEBUG] [p.d.internal.DbmsMyBatisMapper:220  ] - DBMS: useMapperClass added Mapper Dynamic getInnerDBMapperClass=
2015-09-25 14:04:13 [DEBUG] [c.x.o.XmlDocumentBundleTracker:118  ] - Reading the XML document '/ESH-INF/config/config.xml' in module 'org.openhab.binding.astro'...
2015-09-25 14:04:14 [DEBUG] [.s.core.internal.CoreActivator:30   ] - Core bundle has been started.
2015-09-25 14:04:14 [DEBUG] [c.x.o.XmlDocumentBundleTracker:159  ] - Create an empty XmlDocumentProvider for the module 'org.openhab.binding.astro'.
2015-09-25 14:04:15 [INFO ] [p.d.internal.DbmsMyBatisMapper:245  ] - DBMS::commitAndClose 'pingDB':
```

**Comment by grzech1983** [comment]
Hello, do you see anything wrong here which could cause issues with charts?

**Comment by lewie** [comment]
Hy @grzech1983 ,
Not yet, I hope I can test charts tomorrow. 
I'm just going to clean up the bundle code and rename from "DBMS" to "JDBC", then I can test.

Rgds
Helmut

**Comment by grzech1983** [comment]
Great. Let me know when you will update builds so I will also test it for you.

**Comment by grzech1983** [comment]
Hello, have you maybe managed to check charts issue (or not?) ?

**Comment by lewie** [comment]
Hi @grzech1983 ,
I work hard on the JDBC Binding, while some time-consuming changes have occurred.

Please give me some time yet!
The JDBC Binding is then the basis for further tests.

A short Test shows, no Errors with JDBC-Binding:
Used code:
````
Frame {
   Webview url="http://localhost:8080/chart?items=Dimmer_Item&period=h&random=1&service=jdbc" height=6
   Chart item=Dimmer_Item period=h refresh=30000
}
````

Rgds
Helmut

**Comment by grzech1983** [comment]
Great. If you will have published version of JDBC then let me know and I will test it on my end.

**Comment by lewie** [comment]
DBMS is deprecated!
Please use and test 'New generic JDBC Persistence Service': https://github.com/openhab/openhab/pull/3248
