### ISSUE TITLE
Error with Systeminfo Binding on openhab 1.7.1

### ISSUE THREAD

**Issue by fmatray** [openhab/openhab#3217]
Hello,
I use openhab 1.7.1 on a raspberry with debian jessie using the debian repository.
While trying Systeminfo, I get a java exception with any kind of system item.
Does someone cas help me ?

Here an example
items :
```
Group System
Number uptime   "Uptime [%.1f]" (System) { systeminfo="Uptime:5000" }
```

openhab.log : 
```
2015-09-30 01:09:38.259 [ERROR] [b.s.internal.SysteminfoBinding] - Error occured while reading KPI's
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Uptime.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220) ~[sigar-1.6.4.jar:na]
	at com.sun.proxy.$Proxy88.getUptime(Unknown Source) ~[na:na]
	at org.openhab.binding.systeminfo.internal.SysteminfoBinding.getData(SysteminfoBinding.java:158) [bundlefile:na]
	at org.openhab.binding.systeminfo.internal.SysteminfoBinding.execute(SysteminfoBinding.java:108) [bundlefile:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) [org.openhab.core_1.7.1.jar:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) [org.openhab.core_1.7.1.jar:na]
2015-09-30 01:09:38.292 [ERROR] [b.s.internal.SysteminfoBinding] - Error occured while reading KPI's
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Uptime.gather(Lorg/hyperic/sigar/Sigar;)V
	at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220) ~[sigar-1.6.4.jar:na]
	at com.sun.proxy.$Proxy88.getUptime(Unknown Source) ~[na:na]
	at org.openhab.binding.systeminfo.internal.SysteminfoBinding.getData(SysteminfoBinding.java:155) [bundlefile:na]
	at org.openhab.binding.systeminfo.internal.SysteminfoBinding.execute(SysteminfoBinding.java:108) [bundlefile:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) [org.openhab.core_1.7.1.jar:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) [org.openhab.core_1.7.1.jar:na]
```

**Comment by 9037568** [comment]
Sounds like the link library is missing or wasn't found for some reason.
Did you follow all of the setup advice on the wiki? (
https://github.com/openhab/openhab/wiki/Systeminfo-Binding)

**Comment by steve-bate** [comment]
Just FYI, it works for me on Raspberry Pi 2, openHAB 1.7.1 and Raspbian.

**Comment by fmatray** [comment]
Thanks a lot :-)
