### ISSUE TITLE
Netatmo Welcome Binding

### ISSUE THREAD

**Issue by napoleonmm83** [openhab/openhab#3225]
Netatmo Welcome has now a api 
https://github.com/Netatmo/Netatmo-API-PHP#netatmo-welcome-api-client-implementation---php-sdk

Maybe some one can make a Binding?

**Comment by wep4you** [comment]
Yes would be great to use the presence Information for the Home Automation!

**Comment by wep4you** [comment]
Based on the Netatmo Binding i implemented a Binding for Netatmo Welcome. At the moment it will get all Informations from the Netatmo API GetHomeData. Till now i haven't pushed something to GIT so if somebody else is also interested i will try it.

**Comment by skycryer** [comment]
I am interested, how hard is it to add new faces that have been detected?

**Comment by wep4you** [comment]
@skycryer What do you mean, in the netatmo app or in the API? If you mean the app, than its really easy, just tap the unknown face on the phone, click identify. Then you get all unknown faces, and could check them and say to witch user they belong or create a new one ...
Also have a look at the state of he implementation in the netatmo binding #3841

**Comment by RosaEinhorn** [comment]
Hi,
I just got a Netatmo Welcome and installed it (already had a weather station).
I followed all the steps of netatmo pre-setup and requested access to the welcome camera, the acces token seems to work, I can receive updated for the weather station.
Unfortunately, when I try to request information of the camera, I am getting the following error:

`Binding configuration of type 'netatmo' of item ‘Welcome_Carina_AtHome‘ could not be parsed correctly.
java.lang.IllegalArgumentException: Invalid measure: OutOfSight
	at org.openhab.binding.netatmo.internal.NetatmoMeasureType.fromString(NetatmoMeasureType.java:65) ~[na:na]
	at org.openhab.binding.netatmo.internal.NetatmoGenericBindingProvider.processBindingConfiguration(NetatmoGenericBindingProvider.java:190) ~[na:na]
	at org.openhab.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:348) [org.openhab.model.item_1.8.3.jar:na]
	at org.openhab.model.item.internal.GenericItemProvider.dispatchBindingsPerType(GenericItemProvider.java:309) [org.openhab.model.item_1.8.3.jar:na]
	at org.openhab.model.item.internal.GenericItemProvider.addBindingConfigReader(GenericItemProvider.java:106) [org.openhab.model.item_1.8.3.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_60]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_60]
	at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:376) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:444) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.dynamicBind(InstanceProcess.java:416) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:334) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433) [org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.registerService(InstanceProcess.java:536) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:260) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70) [org.eclipse.equinox.util_1.0.400.v20120917-192807.jar:na]`

Item configuration is taken from the wiki:
String 	Welcome_Home         		"Home [%s]"							<house>         (Welcome) 				{netatmo="camera=5752ee8c49c75f1e618b475e#Name"}
Switch   	Welcome_P2_AtHome     	"Carina is home [%s]"               <home_away>		(Welcome)       		{netatmo="camera=if-of-the-house#person-id#OutOfSight"}
Switch   	Welcome_P2_AtHome     	"Philipp is home [%s]"              <home_away>		(Welcome)        		{netatmo="camera=id-of-the-house#person2-id#OutOfSight"}

Any idea on this?
As there was no documentation on how to get the home ID and person ID, I used the netatmo API documentation: https://dev.netatmo.com/dev/resources/technical/reference/welcome/gethomedata

Thanks a lot in advance!

**Comment by 9037568** [comment]
Please open a new ticket for this, to keep a clean history.
