### ISSUE TITLE
Denon Binding: Encoding error in get javax.xml.bind.UnmarshalException: null

### ISSUE THREAD

**Issue by nesys** [openhab/openhab#3243]
Hi Team,

just updated from 1.6.2 to 1.7.1 (Binding 1.7.1, but also tried with 1.8.0 snapshot) and during startup the log is saying:

2015-10-03 22:41:34.863 [WARN ] [.denon.internal.DenonConnector] - Encoding error in get
javax.xml.bind.UnmarshalException: null
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.handleStreamException(UnmarshallerImpl.java:468) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:402) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:371) ~[na:1.8.0_31]
    at org.openhab.binding.denon.internal.DenonConnector.getDocument(DenonConnector.java:549) [bundlefile:na]
    at org.openhab.binding.denon.internal.DenonConnector.setConfigProperties(DenonConnector.java:474) [bundlefile:na]
    at org.openhab.binding.denon.internal.DenonConnector.getInitialState(DenonConnector.java:189) [bundlefile:na]
    at org.openhab.binding.denon.internal.DenonConnector.connect(DenonConnector.java:147) [bundlefile:na]
    at org.openhab.binding.denon.internal.DenonBinding.updated(DenonBinding.java:189) [bundlefile:na]
    at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
    at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
Caused by: com.sun.istack.internal.SAXParseException2: unexpected element (uri:"", local:"html"). Expected elements are <{}device_Info>
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:726) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:247) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:242) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:109) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1131) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:556) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.InterningXmlVisitor.startElement(InterningXmlVisitor.java:60) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXStreamConnector.handleStartElement(StAXStreamConnector.java:231) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXStreamConnector.bridge(StAXStreamConnector.java:165) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:400) ~[na:1.8.0_31]
    ... 8 common frames omitted
Caused by: javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"html"). Expected elements are <{}device_Info>
    ... 19 common frames omitted
2015-10-03 22:41:35.077 [WARN ] [.denon.internal.DenonConnector] - Encoding error in post
javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"html"). Expected elements are <{}cmd>,<{}rx>,<{}text>
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:726) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:247) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:242) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:109) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1131) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:556) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153) ~[na:1.8.0_31]
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509) ~[na:1.8.0_31]
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:379) ~[na:1.8.0_31]
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:605) ~[na:1.8.0_31]
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3138) ~[na:1.8.0_31]
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:880) ~[na:1.8.0_31]
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606) ~[na:1.8.0_31]
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117) ~[na:1.8.0_31]
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510) ~[na:1.8.0_31]
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848) ~[na:1.8.0_31]
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777) ~[na:1.8.0_31]
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:1.8.0_31]
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[na:1.8.0_31]
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243) ~[na:1.8.0_31]
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214) ~[na:1.8.0_31]
    at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157) ~[na:1.8.0_31]
    at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:204) ~[na:1.8.0_31]
    at org.openhab.binding.denon.internal.DenonConnector.postDocument(DenonConnector.java:573) [bundlefile:na]
    at org.openhab.binding.denon.internal.DenonConnector.updateDisplayInfo(DenonConnector.java:460) [bundlefile:na]
    at org.openhab.binding.denon.internal.DenonConnector.refreshHttpProperties(DenonConnector.java:496) [bundlefile:na]
    at org.openhab.binding.denon.internal.DenonConnector.updateState(DenonConnector.java:199) [bundlefile:na]
    at org.openhab.binding.denon.internal.DenonConnector.getInitialState(DenonConnector.java:190) [bundlefile:na]
    at org.openhab.binding.denon.internal.DenonConnector.connect(DenonConnector.java:147) [bundlefile:na]
    at org.openhab.binding.denon.internal.DenonBinding.updated(DenonBinding.java:189) [bundlefile:na]
    at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
    at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]

I'm trying to use telnet, because seems more responsive than http method. Both methods seem working, actually.

AVR 3311 here. Please let me know if you need more data.

Thanks

Andrea
##

**Comment by nesys** [comment]
@idserda can you please have a look, or suggest how to modify the configuration as appropriate? thank you very much. Ready for testing, if necessary.

**Comment by nesys** [comment]
@teichsta @watou sorry to bother, do you know if Jeroen is still supporting this Binding? Thank you very much

**Comment by idserda** [comment]
Yes, I'm still supporting this binding. 

What you're seeing is only a warning. It seems some receivers do not support all the http URL's the binding is using to determine the capabilities/initial state of the receiver. I'll update the binding to better handle this. Also see this post: https://groups.google.com/d/msg/openhab/bSTEfSRt0RU/v4KuiQKMAwAJ

**Comment by nesys** [comment]
Thank you Jeroen, I appreciate your support here. Please let me know when you'll have something to test. More than happy to assist.

**Comment by KWOAD** [comment]
I have a similar error:
2015-10-15 21:13:03.369 [WARN ] [.denon.internal.DenonConnector] - Encoding error in get
javax.xml.bind.UnmarshalException: null
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.handleStreamException(UnmarshallerImpl.java:468) ~[na:1.8.0]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:402) ~[na:1.8.0]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:371) ~[na:1.8.0]
	at org.openhab.binding.denon.internal.DenonConnector.getDocument(DenonConnector.java:549) [bundlefile:na]
	at org.openhab.binding.denon.internal.DenonConnector.setConfigProperties(DenonConnector.java:474) [bundlefile:na]
	at org.openhab.binding.denon.internal.DenonConnector.getInitialState(DenonConnector.java:189) [bundlefile:na]
	at org.openhab.binding.denon.internal.DenonConnector.connect(DenonConnector.java:147) [bundlefile:na]
	at org.openhab.binding.denon.internal.DenonBinding.updated(DenonBinding.java:189) [bundlefile:na]
	at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
	at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
Caused by: com.sun.istack.internal.SAXParseException2: unexpected element (uri:"", local:"html"). Expected elements are <{}device_Info>
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:681) ~[na:1.8.0]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:247) ~[na:1.8.0]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:242) ~[na:1.8.0]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:109) ~[na:1.8.0]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1086) ~[na:1.8.0]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:510) ~[na:1.8.0]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:492) ~[na:1.8.0]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.InterningXmlVisitor.startElement(InterningXmlVisitor.java:60) ~[na:1.8.0]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXStreamConnector.handleStartElement(StAXStreamConnector.java:231) ~[na:1.8.0]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXStreamConnector.bridge(StAXStreamConnector.java:165) ~[na:1.8.0]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:400) ~[na:1.8.0]
	... 8 common frames omitted
Caused by: javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"html"). Expected elements are <{}device_Info>
	... 19 common frames omitted

The device is an Denon AVR 1912. Maybe also because my receiver is something older and doesn't accept the newer http URL's?

**Comment by nesys** [comment]
@idserda please give us a shout when you will have a snapshot to test. A Denon 3311 here. Thanks.

**Comment by nesys** [comment]
In the meantime I've modified my logback.xml accordingly:

	
	<logger name="org.openhab.binding.denon" level="ERROR" />

Please let us know when a new snapshot with a fix will be available.

Thanks @idserda  for your support on this
Kind Regards

**Comment by bruxi** [comment]
I get the same errors when I set to http. Also when I use telnet I won't get any usable results.
My receiver is a 7 year old Denon AVR3808.

Kind regards,
Jens

**Comment by mhett** [comment]
I have an issue where the binding is not starting correctly. I can send commands to the receiver (X1200W) but do not receive anything from it. All these http URLs deliver date when putting them in the browser:
http://192.168.1.70/goform/formMainZone_MainZoneXml.xml
http://192.168.1.70/goform/formMainZone_MainZoneXmlStatus.xml
http://192.168.1.70/goform/formZone2_Zone2XmlStatusLite.xml
http://192.168.1.70/goform/formZone3_Zone3XmlStatusLite.xml
http://192.168.1.70/goform/formZone3_Zone4XmlStatusLite.xml
http://192.168.1.70/goform/Deviceinfo.xml
http://192.168.1.70/goform/AppCommand.xml
http://192.168.1.70/goform/formiPhoneAppDirect.xml

When I remove the file org.openhab.binding.denon-1.7.1.jar in my addons folder and put it back in again the binding seems to start. From this point I receive data from the receiver within openhab.

Can somebody help me?

**Comment by idserda** [comment]
@mhett Please open a separate issue for your problem.

**Comment by mhett** [comment]
Done:
https://community.openhab.org/t/denon-binding-no-input-data-from-the-av-receiver-within-openhab/4816

**Comment by Osmii** [comment]
@idserda  Could you support older networked Denon receivers. I own Denon AVR3808.
At the moment only status updates over telnet works!
Thanks

**Comment by 9037568** [comment]
[This test jar](https://github.com/openhab/openhab/files/671657/org.openhab.binding.denon-1.9.0-SNAPSHOT.zip) should quiet the logging.

**Comment by 9037568** [comment]
This should be fixed by https://github.com/openhab/openhab/pull/4952
