### ISSUE TITLE
Getting Error when trying to bind more than one Datapoint to ntp

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab#3282]
I think this is associated with https://github.com/openhab/openhab/pull/3251 ...
I use an Item to update the Clocks in knx System:

    DateTime Date "Zeit [%1$tA, %1$td. %1$tB %1$tY %1$tT]" <calendar> (All) {ntp="Europe/Berlin:de_DE",knx="11.001:15/7/11, 10.001:15/7/10" } 

This has worked as expected until I updated to 1.8.0-1034 (my last nightly Version was 1.8.0-1009, so it's uncertain when this Bug exactly rised)

Now I'm getting an Error:

```
2015-10-12 07:04:04.464 [ERROR] [i.internal.GenericItemProvider] - Binding configuration of type 'knx' of item  ^ ^ Date ^ ^  could not be parsed correctly.
org.openhab.model.item.binding.BindingConfigParseException: No more than 1 datapoint definitions are allowed for this item.
        at org.openhab.binding.knx.internal.config.KNXGenericBindingProvider.parseBindingConfigString(KNXGenericBindingProvider.java:429) ~[na:na]
        at org.openhab.binding.knx.internal.config.KNXGenericBindingProvider.processBindingConfiguration(KNXGenericBindingProvider.java:106) ~[na:na]
        at org.openhab.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:348) [org.openhab.model.item_1.8.0.201510100138.jar:na]
        at org.openhab.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:324) [org.openhab.model.item_1.8.0.201510100138.jar:na]
        at org.openhab.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:171) [org.openhab.model.item_1.8.0.201510100138.jar:na]
        at org.openhab.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:390) [org.openhab.model.item_1.8.0.201510100138.jar:na]
        at org.openhab.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:159) [org.openhab.model.core_1.8.0.201510100138.jar:na]
        at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:100) [org.openhab.model.core_1.8.0.201510100138.jar:na]
        at 
org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) [org.openhab.model.core_1.8.0.201510100138.jar:na]
        at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) [org.openhab.model.core_1.8.0.201510100138.jar:na]
```
But knx uses two different DPT for Time and Date, where 10.001 represents DoW, hh:mm:ss and 11.001 represents DDMMYY. It really should be possible to set both DPT.

**Comment by 9037568** [comment]
A bit of digging shows the exception is being thrown from line 338.  Not
sure why, as it looks like this code hasn't change in a good long time...

   java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[na:1.8.0_45]
        at java.util.ArrayList.get(Unknown Source) ~[na:1.8.0_45]
        at
org.openhab.binding.knx.internal.config.KNXGenericBindingProvider.parseBindingConfigString(KNXGenericBindingProvider.java:338)
~[na:na]
        at
org.openhab.binding.knx.internal.config.KNXGenericBindingProvider.processBindingConfiguration(KNXGenericBindingProvider.java:106)
~[na:na]

Line 338 is the middle line in this block:

                Class<? extends Type> typeClass =
item.getAcceptedCommandTypes().size() > 0 ?
                        item.getAcceptedCommandTypes().get(i) :
item.getAcceptedDataTypes().size() > 1 ?
                                item.getAcceptedDataTypes().get(i) :
item.getAcceptedDataTypes().get(0);

**Comment by watou** [comment]
After looking at the code, I also believe it is a side effect of #3251.  The fix should be to the binding code.

**Comment by udo1toni** [comment]
As a temporary workaround, one could double bind knx to the item:

    DateTime Date "Zeit [%1$tA, %1$td. %1$tB %1$tY %1$tT]" <calendar> (All) {ntp="Europe/Berlin:de_DE", knx="11.001:15/7/11", knx="10.001:15/7/10" }

**Comment by sercasyr** [comment]
The workaround seems to work!
Thanks.

**Comment by watou** [comment]
Agreeing with @9037568's analysis, if a seasoned KNX binding maintainer were to sort out the logic around [this line](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/KNXGenericBindingProvider.java#L386), I believe this bug would be solved.

**Comment by 9037568** [comment]
I don't have any KNX devices, so I can't verify if the above patch works in a real environment, but it eliminates the index out of bounds exception which causes the "BindingConfigParseException: No more than 1 datapoint definitions are allowed for this item." error to be thrown.
