### ISSUE TITLE
More explicit logs

### ISSUE THREAD

**Issue by fmatray** [openhab/openhab#3353]
Hello,
It would be great to have more explicit logs in openhab.log.
Exceptions on errors are very difficult to understand. 
At least, having the file name and line would make debugging much more easy.

Exemple

```
2015-10-25 21:39:11.096 [ERROR] [org.quartz.core.ErrorLogger   ] - Job (DEFAULT.2015-10-25T21:39:10.579+01:00: Proxy for org.eclipse.xtext.xbase.lib.Procedures$Procedure0: org.eclipse.xtext.xbase.impl.XClosureImplCustom@71e4ad (explicitSyntax: true) threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
    at org.quartz.core.JobRunShell.run(JobRunShell.java:224) ~[quartz-all-2.1.7.jar:na]
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [quartz-all-2.1.7.jar:na]
Caused by: java.lang.RuntimeException: The name '<unkown>' cannot be resolved to an item or type.
    at org.openhab.model.script.interpreter.ScriptInterpreter.internalFeatureCallDispatch(ScriptInterpreter.java:67) ~[na:na]
    at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateAbstractFeatureCall(XbaseInterpreter.java:658) ~[na:na]
```

Another exemple : This time I understand it's a problem with the rule 'Set Week Alarm' but which line ?

```
2015-10-25 20:50:25.659 [ERROR] [o.o.c.s.ScriptExecutionThread ] - Error during the execution of rule 'Set Week Alarm': The name '<XFeatureCallImplCustom> + <XStringLiteralImpl>' cannot be resolved to an item or type.
```

Another example

```
2015-10-25 20:45:00.133 [ERROR] [.o.m.r.i.engine.ExecuteRuleJob] - Error during the execution of rule Heating
java.lang.NullPointerException: cannot invoke method public org.openhab.core.types.State org.openhab.core.items.GenericItem.getState() on null
    at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeOperation(XbaseInterpreter.java:724) ~[na:na]
    at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._featureCallOperation(XbaseInterpreter.java:713) ~[na:na]
    at sun.reflect.GeneratedMethodAccessor284.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0]
```

Thanks a lot.

Regards
##

**Comment by steve-bate** [comment]
To clarify, you want the *rule* filename and line number in the log, right? The Java file name and line number is already there.

**Comment by randomname872634** [comment]
+1

It would be really helpful to get the rule' filename and line number!

For example, I have no idea where to look when I see this:

```2015-12-13 18:18:45.359 [ERROR] [org.quartz.core.JobRunShell   ] - Job DEFAULT.2015-12-13T18:18:45.325+01:00: Proxy for org.eclipse.xtext.xbase.lib.Procedures$Procedure0: org.eclipse.xtext.xbase.impl.XClosureImplCustom@161163a (explicitSyntax: true) threw an unhandled Exception:
java.lang.RuntimeException: The name '<unkown>(<XStringLiteralImpl>,<XStringLiteralImpl>)' cannot be resolved to an item or type. [..]```

**Comment by 9037568** [comment]
Modifying logging of errors from rules would require changes to the core, which no longer exists in OH1.
