### ISSUE TITLE
Trying to connect to database before configuration is loaded

### ISSUE THREAD

**Issue by msfunty** [openhab/openhab#3360]
With mySQL (and most likely all other databases) OH2 tries to connect to the database as soon as the binding is loaded but before OH2 loaded configuration file for that DB.
This results in error messages in logfile:

```
2015-10-27 14:20:21 [DEBUG] [sqlPersistenceServiceActivator:32   ] - mySQL persistence bundle has been started.
2015-10-27 14:20:22 [WARN ] [.p.m.i.MysqlPersistenceService:151  ] - The SQL database URL is missing - please configure the sql:url parameter in openhab.cfg
2015-10-27 14:20:22 [WARN ] [.p.m.i.MysqlPersistenceService:156  ] - The SQL user is missing - please configure the sql:user parameter in openhab.cfg
2015-10-27 14:20:22 [WARN ] [.p.m.i.MysqlPersistenceService:161  ] - The SQL password is missing. Attempting to connect without password. To specify a password configure the sql:password parameter in openhab.cfg.
2015-10-27 14:20:22 [DEBUG] [.p.m.i.MysqlPersistenceService:472  ] - mySQL: Attempting to connect to database null
2015-10-27 14:20:22 [DEBUG] [s.m.i.r.i.ItemRuntimeActivator:23   ] - Registered 'item' configuration parser
2015-10-27 14:20:22 [ERROR] [.p.m.i.MysqlPersistenceService:506  ] - mySQL: Failed connecting to the SQL database using: driverClass=com.mysql.jdbc.Driver, url=null, user=null, password=nulljava.sql.SQLException: The url cannot be null
    at java.sql.DriverManager.getConnection(DriverManager.java:649)
    at java.sql.DriverManager.getConnection(DriverManager.java:247)
    at org.openhab.persistence.mysql.internal.MysqlPersistenceService.connectToDatabase(MysqlPersistenceService.java:474)
    at org.openhab.persistence.mysql.internal.MysqlPersistenceService.activate(MysqlPersistenceService.java:176)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)
    at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
    at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)

2015-10-27 14:20:22 [DEBUG] [.p.m.i.MysqlPersistenceService:181  ] - mySQL configuration complete.
[...]
2015-10-27 14:20:36 [DEBUG] [.c.d.internal.ConfigDispatcher:222  ] - Processing config file 'mysql.cfg'
[...]
2015-10-27 14:20:36 [DEBUG] [.p.m.i.MysqlPersistenceService:185  ] - mySQL persistence bundle stopping. Disconnecting from database.
2015-10-27 14:20:36 [DEBUG] [.p.m.i.MysqlPersistenceService:472  ] - mySQL: Attempting to connect to database jdbc:mysql://localhost:3306/openhab
[...]
2015-10-27 14:20:38 [DEBUG] [.p.m.i.MysqlPersistenceService:475  ] - mySQL: Connected to database jdbc:mysql://localhost:3306/openhab
2015-10-27 14:20:38 [DEBUG] [.p.m.i.MysqlPersistenceService:181  ] - mySQL configuration complete.
```

IMHO connection to databases must not to done before full config file is processed.
According to Kai issue must be in binding for OH1 (http://github.com/openhab/openhab2/issues/446)
##

**Comment by kaikreuzer** [comment]
I guess this might be linked to #2661. If the mySQL service requires a configuration for startup, it should use the require policy in the component descriptor, so that it is ensured that a configuration is passed in already in the activate() method.

**Comment by lewie** [comment]
@msfunty, I think this can be closed!
