### ISSUE TITLE
Persistence Exception when using CallItem

### ISSUE THREAD

**Issue by gitbock** [openhab/openhab#3380]
# Problem
Hi,
As soon as I integrated my CallItems I receive persistence exeptions in my logfile about all 10 seconds, when changing the items file while openHAB is running.

```
2015-11-02 21:22:55.835 [ERROR] [.o.m.c.i.folder.FolderObserver] - An unexpected exception has occured
com.db4o.ext.Db4oException: JDKField org.openhab.core.types.State:state
        at com.db4o.reflect.jdk.JdkField.handleException(JdkField.java:82) ~[na:na]
        at com.db4o.reflect.jdk.JdkField.set(JdkField.java:64) ~[na:na]
        at com.db4o.internal.reflect.StrictFieldAccessor.set(StrictFieldAccessor.java:17) ~[na:na]
        at com.db4o.internal.FieldMetadata.set(FieldMetadata.java:830) ~[na:na]
        at com.db4o.internal.FieldMetadata.activate(FieldMetadata.java:641) ~[na:na]
        at com.db4o.internal.handlers.StandardReferenceTypeHandler$2.processAspect(StandardReferenceTypeHandler.java:92) ~[na:na]
        at com.db4o.internal.metadata.MarshallingInfoTraverseAspectCommand.processAspect(MarshallingInfoTraverseAspectCommand.java:52) ~[na:na]
        at com.db4o.internal.metadata.StandardAspectTraversalStrategy.traverseAllAspects(StandardAspectTraversalStrategy.java:24) ~[na:na]
        at com.db4o.internal.ClassMetadata.traverseAllAspects(ClassMetadata.java:2083) ~[na:na]
        at com.db4o.internal.handlers.StandardReferenceTypeHandler.traverseAllAspects(StandardReferenceTypeHandler.java:257) ~[na:na]
        at com.db4o.internal.handlers.StandardReferenceTypeHandler.activateAspects(StandardReferenceTypeHandler.java:95) ~[na:na]
        at com.db4o.internal.handlers.StandardReferenceTypeHandler.activate(StandardReferenceTypeHandler.java:118) ~[na:na]
        at com.db4o.internal.Handlers4.activate(Handlers4.java:300) ~[na:na]
        at com.db4o.internal.ClassMetadata.instantiateFields(ClassMetadata.java:1317) ~[na:na]
        at com.db4o.internal.ClassMetadata.activate(ClassMetadata.java:1251) ~[na:na]
        at com.db4o.internal.ClassMetadata.instantiate(ClassMetadata.java:1199) ~[na:na]
        at com.db4o.internal.marshall.UnmarshallingContext.read(UnmarshallingContext.java:70) ~[na:na]
        at com.db4o.internal.ObjectReference.read(ObjectReference.java:306) ~[na:na]
        at com.db4o.internal.ObjectReference.read(ObjectReference.java:292) ~[na:na]
        at com.db4o.internal.ObjectContainerBase$8.apply(ObjectContainerBase.java:897) ~[na:na]
        at com.db4o.internal.ObjectContainerBase$8.apply(ObjectContainerBase.java:895) ~[na:na]
        at com.db4o.internal.ObjectContainerBase.asTopLevelCall(ObjectContainerBase.java:427) ~[na:na]
        at com.db4o.internal.ObjectContainerBase.readActivatedObjectNotInCache(ObjectContainerBase.java:895) ~[na:na]
        at com.db4o.internal.query.result.AbstractQueryResult.activatedObject(AbstractQueryResult.java:34) ~[na:na]
        at com.db4o.internal.query.result.IdListQueryResult.get(IdListQueryResult.java:40) ~[na:na]
        at com.db4o.internal.query.result.StatefulQueryResult.get(StatefulQueryResult.java:24) ~[na:na]
        at com.db4o.internal.query.ObjectSetFacade.get(ObjectSetFacade.java:83) ~[na:na]
        at java.util.AbstractList$Itr.next(AbstractList.java:358) ~[na:1.8.0]
        at java.util.SubList$1.next(AbstractList.java:707) ~[na:1.8.0]
        at org.openhab.core.persistence.internal.PersistenceManager.initialize(PersistenceManager.java:385) ~[na:na]
        at org.openhab.core.persistence.internal.PersistenceManager.initializeItems(PersistenceManager.java:212) ~[na:na]
        at org.openhab.core.persistence.internal.PersistenceManager.startEventHandling(PersistenceManager.java:184) ~[na:na]
        at org.openhab.core.persistence.internal.PersistenceManager.modelChanged(PersistenceManager.java:168) ~[na:na]
        at org.openhab.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:159) ~[na:na]
        at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:100) ~[na:na]
        at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) ~[na:na]
        at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) ~[na:na]
Caused by: java.lang.IllegalArgumentException: Can not set org.openhab.core.types.State field org.openhab.persistence.db4o.internal.Db4oItem.state to com.db4o.reflect.generic.GenericObject
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[na:1.8.0]
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[na:1.8.0]
        at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[na:1.8.0]
        at java.lang.reflect.Field.set(Field.java:758) ~[na:1.8.0]
        at com.db4o.reflect.jdk.JdkField.set(JdkField.java:62) ~[na:na]
        ... 35 common frames omitted
```
This seems to happen only when item's file is changed during openHAB runtime. At the first start, no exception is rised.

# Item Example
```
Call    fboxIncomingCall 	"Incoming call: [%1$s to %2$s]"	   <phone>   {fritzboxtr064="callmonitor_ringing:resolveName" } 
```

# Persistence configuration dbo4.persistence
```
// Configuration file for "db4o" persistence module
Strategies {
    everyHour : "0 0 * * * ?"
    everyDay  : "0 0 0 * * ?"
	every5Min : "0 */5 * * * ?"

    // if no strategy is specified for an item entry below, the default list will be used
    default = everyChange
}

Items {
    // persist all items once a day and on every change and restore them from the db at startup
    * : strategy = everyChange, everyDay, restoreOnStartup
	
	//TempWerte alle 5 Min
   thermostate* : strategy = every5Min
}
```

# Reproduce
* Insert the item example code in your items file
* Start openHAB
* change any item in your items file while openHAB is running, so that the file is reloaded by the folder observer
* watch your logfile

# Reference
I found a similar error description in 2012 which could be related to this: http://knx-user-forum.de/forum/supportforen/openhab/22656-%E2%88%9A-databaseclosedexception-nach-server-reset

# Possible workaround
Perhaps you can configure the strategy to NOT do persistence on CallItems. Does not make sense anyway. But could not accomplish this. Tried it like this

```
// Configuration file for "db4o" persistence module
Strategies {
   [...]
	none : ""

}

Items {
	[...]
   fboxIncomingCall : strategy = none
   [...]
}
```
but this seems not to make a difference.

# Environment
* Raspberry Pi 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux
* openHAB 1.7.1

**Comment by steve-bate** [comment]
@gitbock Is this a duplicate of #294? If so, I'll tag this issue as a duplicate.

**Comment by gitbock** [comment]
@steve-bate 
Yes, it seems so. Sorry, I did not search well enough :(
I will close this one.
