### ISSUE TITLE
Denon Binding: Graceful handling of connection timouts

### ISSUE THREAD

**Issue by Keelhaul** [openhab/openhab#3412]
Hi,

When the receiver has no power supply (Denon AVR-X1100 in my case), the binding cannot connect and logs a timeout stack trace:
```
2015-11-13 13:17:35.729 [ERROR] [b.denon.internal.DenonListener] - Error connecting to 192.168.1.10
java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_65]
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_65]
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_65]
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_65]
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_65]
        at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_65]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_65]
        at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_65]
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:175) ~[org.apache.commons.net_3.2.0.v201305141515.jar:3.2]
        at org.apache.commons.net.SocketClient.connect(SocketClient.java:196) ~[org.apache.commons.net_3.2.0.v201305141515.jar:3.2]
        at org.openhab.binding.denon.internal.DenonListener.connectTelnetClient(DenonListener.java:81) [bundlefile:na]
        at org.openhab.binding.denon.internal.DenonListener.run(DenonListener.java:52) [bundlefile:na]
```
It think it would be more log friendly to handle timeouts like an OFF status instead.

**Comment by watou** [comment]
Makes sense, unless there is some network issue between openHAB and the Denon (which would usually not be the case).  In the meantime, you could add `%nopex` to your `logback.xml` to suppress stack traces in the log.  Change the `<pattern>`:
```
<pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%-30.30logger{36}] - %msg%nopex%n</pattern>
```

**Comment by rene54321** [comment]
Hi,
 
I also like this idea. As the standby power is about 20W if the network is still available. I have disabled the standby LAN functionality in the DENON Receiver and get this error also every time until the Denon is powered on again.

**Comment by teichsta** [comment]
@Keelhaul would you volunteer to send this proposal as PR?

**Comment by Keelhaul** [comment]
@teichsta Theoretically, but I'm afraid it might take a while as the Maven part of the dev environment for openHAB has been somewhat of a learning curve for me.

**Comment by idserda** [comment]
I'd be happy to look into this. Seems the binding also does not detect a power off of the receiver after the telnet client is connected.

**Comment by idserda** [comment]
I've submitted a pull request to fix this. 

What receiver needs 20W in standby by the way? My X2000 only uses about 2.6W.
