### ISSUE TITLE
Jetty : Could not send response error 500: javax.servlet.ServletException: javax.servlet.ServletException: java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab#3459]
I have the following in .sitemap:

Text item=TechnicalFacilitiesAudioCurrent label="Technical Facilities - Audio [%.0f mA]" visibility=[TechnicalFacilitiesAudioCurrent>0] icon="energy" {
Chart item=TechnicalFacilitiesAudioCurrent label="rrd4j" service="rrd4j" period=D refresh=5000
}

Selecting the Chart in any UI generates the following errors:

2015-11-23 22:19:45 [WARN ] [e.jetty.servlet.ServletHandler:620  ] - javax.servlet.ServletException: java.lang.StringIndexOutOfBoundsException: String index out of range: 14
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:423)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 14
	at java.lang.String.substring(String.java:1963)
	at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.getWidget(ItemUIRegistryImpl.java:477)
	at org.eclipse.smarthome.io.rest.sitemap.internal.SitemapResource.getPageBean(SitemapResource.java:149)
	at org.eclipse.smarthome.io.rest.sitemap.internal.SitemapResource.getPageData(SitemapResource.java:138)
	at sun.reflect.GeneratedMethodAccessor206.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)

2015-11-23 22:19:45 [WARN ] [lipse.jetty.server.HttpChannel:395  ] - /rest/sitemaps/kalideux/0900010101187javax.servlet.ServletException: javax.servlet.ServletException: java.lang.StringIndexOutOfBoundsException: String index out of range: 14
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:130)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: java.lang.StringIndexOutOfBoundsException: String index out of range: 14
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:423)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 14
	at java.lang.String.substring(String.java:1963)
	at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.getWidget(ItemUIRegistryImpl.java:477)
	at org.eclipse.smarthome.io.rest.sitemap.internal.SitemapResource.getPageBean(SitemapResource.java:149)
	at org.eclipse.smarthome.io.rest.sitemap.internal.SitemapResource.getPageData(SitemapResource.java:138)
	at sun.reflect.GeneratedMethodAccessor206.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)

**Comment by steve-bate** [comment]
Looks like the relevant part of the stack trace is:

    Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 14
    at java.lang.String.substring(String.java:1963)
    at org.eclipse.smarthome.ui.internal.items.ItemUIRegistryImpl.getWidget(ItemUIRegistryImpl.java:477)

The code around that line is:
```java
    w = sitemap.getChildren().get(Integer.valueOf(id.substring(0, 2)));
    for(int i = 2; i < id.length(); i+=2) {
        w = ((LinkableWidget)w).getChildren().get(Integer.valueOf(id.substring(i, i+2)));
    }
```

It looks like it may be throwing an exception on the second substring. i don't know anything about this code, but it appears it's drilling down the widget tree and that the widget id somehow encodes a path to a child widget. It seems like maybe the depth is too much and the id encoding isn't long enough.

Is the Text widget at the top level or is it nested in another widget? If nested, how deep?

**Comment by kgoderis** [comment]
Not counting the root, it is the 5th level deep.

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
