### ISSUE TITLE
Exception during Z-Wave thread ... OnOffType cannot be cast to DecimalType

### ISSUE THREAD

**Issue by unicornis-pl** [openhab/openhab#3481]
After putting freshly compiled binding (cloned from github on 28th on Nov 2016, around 10:00 CET) to the addons, I get the following error:
2015-11-28 10:35:35.602 [ERROR] [b.z.i.protocol.ZWaveController] - Exception during Z-Wave thread: Input.
java.lang.ClassCastException: org.openhab.core.library.types.OnOffType cannot be cast to org.openhab.core.library.types.DecimalType
	at org.openhab.binding.zwave.internal.converter.ZWaveMultiLevelSwitchConverter.handleEvent(ZWaveMultiLevelSwitchConverter.java:110) ~[na:na]
	at org.openhab.binding.zwave.internal.converter.ZWaveConverterHandler.handleEvent(ZWaveConverterHandler.java:369) ~[na:na]
	at org.openhab.binding.zwave.internal.ZWaveActiveBinding.handleZWaveCommandClassValueEvent(ZWaveActiveBinding.java:461) ~[na:na]
	at org.openhab.binding.zwave.internal.ZWaveActiveBinding.ZWaveIncomingEvent(ZWaveActiveBinding.java:437) ~[na:na]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController.notifyEventListeners(ZWaveController.java:638) ~[na:na]
	at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveMultiLevelSwitchCommandClass.handleApplicationCommandRequest(ZWaveMultiLevelSwitchCommandClass.java:116) ~[na:na]
	at org.openhab.binding.zwave.internal.protocol.serialmessage.ApplicationCommandMessageClass.handleRequest(ApplicationCommandMessageClass.java:80) ~[na:na]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingRequestMessage(ZWaveController.java:223) ~[na:na]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingMessage(ZWaveController.java:196) ~[na:na]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController.access$6(ZWaveController.java:191) ~[na:na]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveInputThread.run(ZWaveController.java:1166) ~[na:na]

After restoring the older version of binding (cloned on 14th of Nov) the error dissapers.

**Comment by cdjackson** [comment]
Please try this again tomorrow and let me know if the problem still exists...

**Comment by unicornis-pl** [comment]
Now it is OK. Works fine with the compile as of 30th of Nov 18:30 CET.
