### ISSUE TITLE
Denon Binding: No input data from the AV-Receiver

### ISSUE THREAD

**Issue by mhett** [openhab/openhab#3513]
I have an issue where the binding is not starting correctly. I can send commands to the receiver (X1200W) but do not receive anything from it. All these http URLs deliver data when putting them in the browser:
http://192.168.1.70/goform/formMainZone_MainZoneXml.xml
http://192.168.1.70/goform/formMainZone_MainZoneXmlStatus.xml
http://192.168.1.70/goform/formZone2_Zone2XmlStatusLite.xml
http://192.168.1.70/goform/formZone3_Zone3XmlStatusLite.xml
http://192.168.1.70/goform/formZone3_Zone4XmlStatusLite.xml
http://192.168.1.70/goform/Deviceinfo.xml
http://192.168.1.70/goform/AppCommand.xml
http://192.168.1.70/goform/formiPhoneAppDirect.xml

When I remove the file org.openhab.binding.denon-1.7.1.jar in my addons folder and put it back in again the binding seems to start. From this point I receive data from the receiver within openhab. I am using OH 1 runtime.

Can somebody help me?

**Comment by steve-bate** [comment]
Have asked this question in the community forum? If so, can you add the link to the discussion. Thanks.

**Comment by mhett** [comment]
Yes, here is the link:
https://community.openhab.org/t/denon-binding-no-input-data-from-the-av-receiver-within-openhab/4816
in addidion there are some error logs...

**Comment by idserda** [comment]
@mhett Thanks for reporting this, I've just submitted a pull request to fix this.

**Comment by mhett** [comment]
@idserda I still have troubles with the connection to the receiver. Sometimes it is working, sometimes not. Can you see something in this log?

2015-12-19 19:37:27.892 [DEBUG] [.denon.internal.DenonActivator] - Denon binding has been started.
2015-12-19 19:37:27.910 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonPower bound to property PW
2015-12-19 19:37:27.913 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonMainZone bound to property ZM
2015-12-19 19:37:27.913 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonVolume bound to property MV
2015-12-19 19:37:27.913 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonMute bound to property MU
2015-12-19 19:37:27.914 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonCommand bound to property COMMAND
2015-12-19 19:37:27.914 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonCurrentTrack bound to property TRACK
2015-12-19 19:37:27.914 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonCurrentArtist bound to property ARTIST
2015-12-19 19:37:27.914 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonCurrentAlbum bound to property ALBUM
2015-12-19 19:37:27.915 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInput bound to property INPUT
2015-12-19 19:37:27.915 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputUSBIPOD bound to property SIUSB/IPOD
2015-12-19 19:37:27.915 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputNet bound to property SINET
2015-12-19 19:37:27.916 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputFavorites bound to property SIFAVORITES
2015-12-19 19:37:27.916 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputFVP bound to property SIFVP
2015-12-19 19:37:27.916 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputIRadio bound to property SIIRADIO
2015-12-19 19:37:27.916 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputServer bound to property SISERVER
2015-12-19 19:37:27.917 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputTuner bound to property SITUNER
2015-12-19 19:37:27.917 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputDVD bound to property SIDVD
2015-12-19 19:37:27.917 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputBluray bound to property SIBD
2015-12-19 19:37:27.918 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputTV bound to property SITV
2015-12-19 19:37:27.918 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputSATCBL bound to property SISAT/CBL
2015-12-19 19:37:27.919 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputMplay bound to property SIMPLAY
2015-12-19 19:37:27.919 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputGame bound to property SIGAME
2015-12-19 19:37:27.919 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputAux1 bound to property SIAUX1
2015-12-19 19:37:27.928 [DEBUG] [.b.denon.internal.DenonBinding] - Denon all bindings changed
2015-12-19 19:37:27.930 [DEBUG] [.b.denon.internal.DenonBinding] - Denon binding updated
2015-12-19 19:37:27.932 [DEBUG] [.b.denon.internal.DenonBinding] - Denon receiver configured at 192.168.0.20
2015-12-19 19:37:28.143 [DEBUG] [.denon.internal.DenonConnector] - Refreshing URL: http://192.168.0.20:80/goform/Deviceinfo.xml
2015-12-19 19:37:28.615 [DEBUG] [.denon.internal.DenonConnector] - Denon avr1200 zones: 2
2015-12-19 19:37:28.826 [INFO ] [.service.AbstractActiveService] - Denon Refresh Service has been started
2015-12-19 19:37:29.596 [DEBUG] [.denon.internal.DenonActivator] - Denon binding has been started.
2015-12-19 19:37:29.617 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonPower bound to property PW
2015-12-19 19:37:29.618 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonMainZone bound to property ZM
2015-12-19 19:37:29.618 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonVolume bound to property MV
2015-12-19 19:37:29.618 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonMute bound to property MU
2015-12-19 19:37:29.619 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonCommand bound to property COMMAND
2015-12-19 19:37:29.619 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonCurrentTrack bound to property TRACK
2015-12-19 19:37:29.619 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonCurrentArtist bound to property ARTIST
2015-12-19 19:37:29.620 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonCurrentAlbum bound to property ALBUM
2015-12-19 19:37:29.620 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInput bound to property INPUT
2015-12-19 19:37:29.620 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputUSBIPOD bound to property SIUSB/IPOD
2015-12-19 19:37:29.621 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputNet bound to property SINET
2015-12-19 19:37:29.621 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputFavorites bound to property SIFAVORITES
2015-12-19 19:37:29.621 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputFVP bound to property SIFVP
2015-12-19 19:37:29.622 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputIRadio bound to property SIIRADIO
2015-12-19 19:37:29.622 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputServer bound to property SISERVER
2015-12-19 19:37:29.622 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputTuner bound to property SITUNER
2015-12-19 19:37:29.623 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputDVD bound to property SIDVD
2015-12-19 19:37:29.623 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputBluray bound to property SIBD
2015-12-19 19:37:29.623 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputTV bound to property SITV
2015-12-19 19:37:29.624 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputSATCBL bound to property SISAT/CBL
2015-12-19 19:37:29.625 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputMplay bound to property SIMPLAY
2015-12-19 19:37:29.625 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputGame bound to property SIGAME
2015-12-19 19:37:29.625 [DEBUG] [.i.DenonGenericBindingProvider] - denon:avr1200 item DenonInputAux1 bound to property SIAUX1
2015-12-19 19:37:29.634 [DEBUG] [.b.denon.internal.DenonBinding] - Denon all bindings changed
2015-12-19 19:37:29.635 [DEBUG] [.b.denon.internal.DenonBinding] - Denon binding updated
2015-12-19 19:37:29.637 [DEBUG] [.b.denon.internal.DenonBinding] - Denon receiver configured at 192.168.0.20
2015-12-19 19:37:29.818 [DEBUG] [.denon.internal.DenonConnector] - Refreshing URL: http://192.168.0.20:80/goform/Deviceinfo.xml
2015-12-19 19:37:30.196 [DEBUG] [.denon.internal.DenonConnector] - Denon avr1200 zones: 2
2015-12-19 19:37:30.341 [INFO ] [.service.AbstractActiveService] - Denon Refresh Service has been started
2015-12-19 19:37:41.574 [ERROR] [g.openhab.io.net.http.HttpUtil] - Fatal transport error: java.net.SocketTimeoutException: Read timed out
2015-12-19 19:37:41.583 [ERROR] [.service.AbstractActiveService] - Error while executing background thread Denon Refresh Service
java.lang.NullPointerException: null
	at org.apache.commons.io.IOUtils.toInputStream(IOUtils.java:769) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.getDocument(DenonConnector.java:545) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.updateMain(DenonConnector.java:421) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.refreshHttpProperties(DenonConnector.java:493) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.updateState(DenonConnector.java:199) ~[na:na]
	at org.openhab.binding.denon.internal.DenonBinding.execute(DenonBinding.java:71) ~[na:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
2015-12-19 19:37:43.271 [ERROR] [g.openhab.io.net.http.HttpUtil] - Fatal transport error: java.net.SocketTimeoutException: Read timed out
2015-12-19 19:37:43.280 [ERROR] [.service.AbstractActiveService] - Error while executing background thread Denon Refresh Service
java.lang.NullPointerException: null
	at org.apache.commons.io.IOUtils.toInputStream(IOUtils.java:769) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.getDocument(DenonConnector.java:545) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.updateMain(DenonConnector.java:421) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.refreshHttpProperties(DenonConnector.java:493) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.updateState(DenonConnector.java:199) ~[na:na]
	at org.openhab.binding.denon.internal.DenonBinding.execute(DenonBinding.java:71) ~[na:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
2015-12-19 19:37:49.596 [ERROR] [g.openhab.io.net.http.HttpUtil] - Fatal transport error: java.net.SocketTimeoutException: Read timed out
2015-12-19 19:37:49.606 [ERROR] [.service.AbstractActiveService] - Error while executing background thread Denon Refresh Service
java.lang.NullPointerException: null
	at org.apache.commons.io.IOUtils.toInputStream(IOUtils.java:769) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.getDocument(DenonConnector.java:545) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.updateMain(DenonConnector.java:421) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.refreshHttpProperties(DenonConnector.java:493) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.updateState(DenonConnector.java:199) ~[na:na]
	at org.openhab.binding.denon.internal.DenonBinding.execute(DenonBinding.java:71) ~[na:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
2015-12-19 19:37:55.766 [ERROR] [g.openhab.io.net.http.HttpUtil] - Fatal transport error: java.net.SocketTimeoutException: Read timed out
2015-12-19 19:37:55.778 [ERROR] [.service.AbstractActiveService] - Error while executing background thread Denon Refresh Service
java.lang.NullPointerException: null
	at org.apache.commons.io.IOUtils.toInputStream(IOUtils.java:769) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.getDocument(DenonConnector.java:545) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.updateSecondaryZones(DenonConnector.java:446) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.refreshHttpProperties(DenonConnector.java:495) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.updateState(DenonConnector.java:199) ~[na:na]
	at org.openhab.binding.denon.internal.DenonBinding.execute(DenonBinding.java:71) ~[na:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
2015-12-19 19:37:57.612 [ERROR] [g.openhab.io.net.http.HttpUtil] - Fatal transport error: java.net.SocketTimeoutException: Read timed out
2015-12-19 19:37:57.620 [ERROR] [.service.AbstractActiveService] - Error while executing background thread Denon Refresh Service
java.lang.NullPointerException: null
	at org.apache.commons.io.IOUtils.toInputStream(IOUtils.java:769) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.getDocument(DenonConnector.java:545) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.updateMain(DenonConnector.java:421) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.refreshHttpProperties(DenonConnector.java:493) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.updateState(DenonConnector.java:199) ~[na:na]
	at org.openhab.binding.denon.internal.DenonBinding.execute(DenonBinding.java:71) ~[na:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
2015-12-19 19:38:03.788 [ERROR] [g.openhab.io.net.http.HttpUtil] - Fatal transport error: java.net.SocketTimeoutException: Read timed out
2015-12-19 19:38:03.796 [ERROR] [.service.AbstractActiveService] - Error while executing background thread Denon Refresh Service
java.lang.NullPointerException: null
	at org.apache.commons.io.IOUtils.toInputStream(IOUtils.java:769) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.getDocument(DenonConnector.java:545) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.updateMain(DenonConnector.java:421) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.refreshHttpProperties(DenonConnector.java:493) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.updateState(DenonConnector.java:199) ~[na:na]
	at org.openhab.binding.denon.internal.DenonBinding.execute(DenonBinding.java:71) ~[na:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
2015-12-19 19:38:05.626 [ERROR] [g.openhab.io.net.http.HttpUtil] - Fatal transport error: java.net.SocketTimeoutException: Read timed out
2015-12-19 19:38:05.634 [ERROR] [.service.AbstractActiveService] - Error while executing background thread Denon Refresh Service
java.lang.NullPointerException: null
	at org.apache.commons.io.IOUtils.toInputStream(IOUtils.java:769) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.getDocument(DenonConnector.java:545) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.updateMain(DenonConnector.java:421) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.refreshHttpProperties(DenonConnector.java:493) ~[na:na]
	at org.openhab.binding.denon.internal.DenonConnector.updateState(DenonConnector.java:199) ~[na:na]
	at org.openhab.binding.denon.internal.DenonBinding.execute(DenonBinding.java:71) ~[na:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]

**Comment by idserda** [comment]
Are you using the latest nightly build of the binding? The code was merged last night, maybe there's no build yet.

**Comment by mhett** [comment]
Oh you are too fast for me. I just updated my previous comment. ;-)
I have tried with the latest build from cloudbees (# 1096 (19.12.2015 03:31:30). I think the changes are in there.

**Comment by mhett** [comment]
I am afraid the changes are not in there. There is no green "lamp" at build # 1096.

**Comment by mhett** [comment]
I have now tried with build 1104 from cloudbees. Works great. Many thanks.
