### ISSUE TITLE
Heatmiser - support TM-N1 Thermostat

### ISSUE THREAD

**Issue by andylockran** [openhab/openhab#3521]
Hey guys,

Apologies if this isn't the right place for this; I could do with help on enabling heatmiser comms with the TM-N1 thermostat.  It uses the same protocol as the PRT that's used in the example, but when connecting to thermostat id 5 I get the following error:

4:35:52.019 [DEBUG] [.b.h.internal.HeatmiserBinding:129  ] - HEATMISER execute() method is called!
14:35:52.020 [DEBUG] [.b.h.internal.HeatmiserBinding:160  ] - HEATMISER: polling 5
14:35:52.218 [ERROR] [.h.internal.HeatmiserConnector:231  ] - Event listener error
java.lang.NullPointerException: null
        at org.openhab.binding.heatmiser.internal.HeatmiserBinding$MessageListener.packetReceived(HeatmiserBinding.java:268) ~[na:na]
        at org.openhab.binding.heatmiser.internal.HeatmiserConnector$InputReader.run(HeatmiserConnector.java:226) ~[na:na]

The thermostat with ID 5 I have set to ONOFF, HEATMODE & WATERSTATE all with the same result.

It seems that WATERSTATE 'held at address 42' is the right address, but I can't debug this further as I don't know java (but the same sort of command works on both the PRT and TM-N1 in a python example I can provide.

My items and sitemap files are below:

http://paste.ubuntu.com/13824897/
http://paste.ubuntu.com/13824898/

**Comment by watou** [comment]
I think the binding just doesn't know your model, and the error is the result of that.  [This code](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.heatmiser/src/main/java/org/openhab/binding/heatmiser/internal/thermostat/HeatmiserThermostat.java#L120) leaves the `dcbModel` variable `null`, which is kind of a bug in the binding to have an incompletely defined object:
```
		switch (data[13]) {
		case 0:
			dcbModel = Models.DT;
			break;
		case 1:
			dcbModel = Models.DTE;
			break;
		case 2:
			dcbModel = Models.PRT;
			break;
		case 3:
			dcbModel = Models.PRTE;
			break;
		case 4:
			dcbModel = Models.PRTHW;
			break;
		}
```
In an ideal world, these differences would be represented in an external database, sort of like how the Z-Wave binding does it (which @cdjackson knows *all* about :)).

**Comment by andylockran** [comment]
Ok, this is neat.

So I know the model is compatible with Heatmiser protocol v3 (which is what the code appears to be using).  I kinda need to to match PRTHW if it's my model, howdo I catch the data[13] value of my dcb?

**Comment by watou** [comment]
I've built a [binding JAR](https://dl.dropboxusercontent.com/u/4286376/heatmiser-thermostat/org.openhab.binding.heatmiser-1.8.0-SNAPSHOT.jar) for you to run so it should hopefully log 
```
[WARN] Unknown dcbModel <number that corresponds to your model>
```
by this change:
```diff
@@ -117,6 +117,9 @@ public class HeatmiserThermostat {
                case 4:
                        dcbModel = Models.PRTHW;
                        break;
+               default:
+                       logger.warn("Unknown dcbModel {}", data[13]);
+                       return false;
                }
 
                return true;
```

I don't know much beyond that, though.  Do you know how this model compares to other models?

**Comment by watou** [comment]
I recommend that you discuss this at https://community.openhab.org to bring in other Heatmiser users who could shed some light on the subject.

**Comment by andylockran** [comment]
Hey @watou,

Thanks for this - i tested it out and it's model 5 - TM1.

It's got a slightly shorter DCB than the other thermostats, but I should be able to clone an existing model and pull it back in.  Would you be happy to review once I've written it?

**Comment by watou** [comment]
A quick Google says that the TM1 is not a thermostat, it's a timing clock.  Could you open a discussion about this at https://community.openhab.org, where other Heatmiser users could offer their insights?
