### ISSUE TITLE
[Plex] Getting 400 Bad Request with PSM >= 0.9.12.3

### ISSUE THREAD

**Issue by daniellueddecke** [openhab/openhab#3525]
Hi,

as reported in [1], [2] and [3] there seems to be an issue with sending commands to Plex Media Servers starting with version 0.9.12.3.

So my question would go to @idserda if there are any plans to fix this issue?

Thanks and best regards,
Daniel

[1] - https://community.openhab.org/t/plex-binding-and-new-plex-media-server-with-https-bad-request/2860
[2] - https://groups.google.com/forum/m/#!topic/openhab/eSDfQO1RUpI
[3] - http://knx-user-forum.de/forum/supportforen/openhab/852671-plex-mit-openhab-steuern

**Comment by idserda** [comment]
Yes! I almost have a fix ready. Everything seems to work again but the code needs some tidying up. 

Here's an intermediate version if you want to test: https://www.dropbox.com/s/12ouydq7rlm9gmy/org.openhab.binding.plex_1.8.0.201511062054.jar?dl=0

**Comment by daniellueddecke** [comment]
Cool! I'll test it right away tomorrow.

Thanks for your quick reply and your work on this binding! Appreciate!


Best
Daniel

**Comment by daniellueddecke** [comment]
Hi,

I still get a 400 Bad Request.

I think they changed the way of how playback controls like play and pause are handled: those have to be sent to the player and not to the server. Are you aware of that?

In my case the player has an other IP address and port than the server. It can be retrieved by parsing https://server-ip:server-port/clients .

Let me know if you need help or additional information.


Best
Daniel

```
2015-12-10 17:45:14.954 [ERROR] [.b.plex.internal.PlexConnector] - Error while sending command to Plex: Internal Server Error
<?xml version='1.0' encoding='utf-8'?>
<Response code="2000" status="HTTPError: ">
  <Traceback>Traceback (most recent call last):
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-f38ac80/System.bundle/Contents/Code/playerservice.py", line 67, in process_legacy_remote_command
    result = cmd(**kwargs)
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 19, in _apply
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/api/playerkit.py", line 395, in f
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 263, in content
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 241, in __str__
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 444, in open
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 557, in http_response
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 482, in error
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 565, in http_error_default
HTTPError: HTTP Error 400: Bad Request
</Traceback>
</Response>
```

**Comment by idserda** [comment]
Could you turn on debug for the binding and see which URL is being called when you issue a command?

**Comment by daniellueddecke** [comment]
Sure. It tries to reach the server (192.168.178.27).
However, it seems to know where my client is (.133).


Best
Daniel

```
2015-12-10 18:04:39.156 [DEBUG] [tty.server.AsyncHttpConnection] - Disabled read interest while writing response SSL NOT_HANDSHAKING i/o/u=0/0/0 ishut=false oshut=false {AsyncHttpConnection@6c104f,g=HttpGenerator{s=0,h=-1,b=-1,c=-1},p=HttpParser{s=0,l=13,c=0},r=4}
2015-12-10 18:04:39.157 [DEBUG] [tty.server.AsyncHttpConnection] - suspended AsyncHttpConnection@6c104f,g=HttpGenerator{s=0,h=-1,b=-1,c=-1},p=HttpParser{s=0,l=13,c=0},r=4
2015-12-10 18:04:39.544 [DEBUG] [h.c.p.n.NettyAsyncHttpProvider] - 

Request DefaultHttpRequest(chunked: false)
GET /system/players/192.168.178.133/playback/pause HTTP/1.1
Host: 192.168.178.27:32400
X-Plex-Token: 
X-Plex-Target-Client-Identifier: MyIdentifier
X-Plex-Client-Identifier: MyIdentifier
X-Plex-Product: openHAB
X-Plex-Version: 1.8.0.201511062054
X-Plex-Device: Java(TM) SE Runtime Environment
X-Plex-Device-Name: openHAB
X-Plex-Provides: controller
X-Plex-Platform: Java
X-Plex-Platform-Version: 1.8.0
Connection: keep-alive
Accept: */*
User-Agent: NING/1.0

Response DefaultHttpResponse(chunked: false)
HTTP/1.1 500 Internal Server Error
Content-Length: 1879
Content-Type: application/xml
Connection: Keep-Alive
Keep-Alive: timeout=20
X-Plex-Protocol: 1.0
Cache-Control: no-cache

2015-12-10 18:04:39.554 [DEBUG] [c.p.netty.NettyConnectionsPool] - Adding uri: http://192.168.178.27:32400 for channel [id: 0x37ba6e16, /192.168.178.132:53216 => /192.168.178.27:32400]
2015-12-10 18:04:39.566 [DEBUG] [org.eclipse.jetty.util.Scanner] - scanned [/etc/openhab/jetty/contexts]: {}
2015-12-10 18:04:39.567 [ERROR] [.b.plex.internal.PlexConnector] - Error while sending command to Plex: Internal Server Error
<?xml version='1.0' encoding='utf-8'?>
<Response code="2000" status="HTTPError: ">
  <Traceback>Traceback (most recent call last):
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-f38ac80/System.bundle/Contents/Code/playerservice.py", line 67, in process_legacy_remote_command
    result = cmd(**kwargs)
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 19, in _apply
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/api/playerkit.py", line 395, in f
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 263, in content
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 241, in __str__
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 444, in open
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 557, in http_response
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 482, in error
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 565, in http_error_default
HTTPError: HTTP Error 400: Bad Request
</Traceback>
</Response>
```

**Comment by idserda** [comment]
Thanks again for testing! I think the problem is the empty X-Plex-Token header. If you're not using Plex Home you don't have a username/password or token configured, so this header should not be send. 

Could you try again with this version? https://www.dropbox.com/s/unkf74uahavseki/org.openhab.binding.plex_1.8.0.201512101956.jar?dl=0 .

**Comment by daniellueddecke** [comment]
Dropbox says file is still uploading...

**Comment by idserda** [comment]
Try again :)

**Comment by daniellueddecke** [comment]
Sorry, still no success.

```
2015-12-10 21:26:42.725 [DEBUG] [.b.plex.internal.PlexConnector] - Calling url http://192.168.178.27:32400/system/players/192.168.178.133/playback/pause
2015-12-10 21:26:42.901 [ERROR] [.b.plex.internal.PlexConnector] - Error while sending command to Plex: Internal Server Error
<?xml version='1.0' encoding='utf-8'?>
<Response code="2000" status="HTTPError: ">
  <Traceback>Traceback (most recent call last):
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-f38ac80/System.bundle/Contents/Code/playerservice.py", line 67, in process_legacy_remote_command
    result = cmd(**kwargs)
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 19, in _apply
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/api/playerkit.py", line 395, in f
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 263, in content
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 241, in __str__
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 444, in open
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 557, in http_response
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 482, in error
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 565, in http_error_default
HTTPError: HTTP Error 400: Bad Request
</Traceback>
</Response>
```

**Comment by idserda** [comment]
Really strange.. The empty header is gone now right? It works fine here on PMS 0.9.12.19 with Plex Home enabled or disabled. What version of PMS are you on?

**Comment by daniellueddecke** [comment]
I'm also on 0.9.12.19. I don't know whether the header is gone. I can't see the request any longer...

What do you get when you request http://localhost:32400/system/players? I receive a 404 then...

What definitely works is connecting to the player directly. In my case a call at `http://192.168.178.133:32500/player/playback/pause?type=video` pauses the video.


Best
Daniel

**Comment by daniellueddecke** [comment]
It may related to the kind of player as well. I'm using iOS and tvOS players.

**Comment by idserda** [comment]
Ah yes that explains it. Controlling RasPlex/PHT on OS X works, sending commands to an iOS client fails.

**Comment by daniellueddecke** [comment]
Okay, let me know if you have an idea how to fix it or when I can test something.

Best
Daniel

**Comment by joshughes** [comment]
@idserda I can confirm that your build works with the issues I was seeing with plex. When you open a PR can you link it to this issue? I would be curious to see and help test the code! 

Thanks!

**Comment by idserda** [comment]
I've made a few changes, all commands go directly to the client now. This also works with iOS clients. New jar at https://www.dropbox.com/s/ff8zdktuoe4e012/org.openhab.binding.plex_1.8.0.201512131111.jar?dl=0

@joshughes Code is at https://github.com/idserda/openhab/commits/plex-update, I'll open a pull request soon.

**Comment by daniellueddecke** [comment]
Cool! I can confirm this working with iOS and tvOS Plex Clients.

However, there currently is a known issue with pausing video from any Plex remote control (including the official Plex app itself) as mentioned [here](https://forums.plex.tv/discussion/191778/planned-features-known-issues). Just if anybody wonders...

Thanks again!

Best
Daniel

**Comment by skycryer** [comment]
Where and when can i get the updated version? The stuff in the 1.8 addons bundle is not working, so it is not the last version, right?

**Comment by idserda** [comment]
This fix is incorporated in the 1.8 release. What's not working? There's a known issue with Plex servers that require https (#3715), I'll submit a pull request to fix this in the next few days.

**Comment by skycryer** [comment]
ok sorry i missed that. After changing to prefered instead of recommended for secure connection i get status of the player, only sending is not working. Maybe it is because of the player (Plex Media Player on Raspberry)

**Comment by idserda** [comment]
I'm using Plex on a Raspberry Pi too, so that should work :smiley: Can you turn on debug logging for the binding and see what is going on? Please create a new issue for this and add the logs.

**Comment by skycryer** [comment]
@idserda, sorry about my late answer. Tried it again and controls are working now. No idea why, they are hard to use but that is an openhab problem.

When and where can i get the updated binding for Plex Https Server? I use my Server in Https only mode.
