### ISSUE TITLE
pilight: repeated exception was filling openhab.log

### ISSUE THREAD

**Issue by stefanroellin** [openhab/openhab#3531]
While openhab was running, I edited some items. Some minutes afterwards, I observed that the pilight binding threw constantly one exception (several thousand times per second!). The openhab.log grew over 4 GB in size. I only could stop openhab to stop the exception.

The last two lines before it all started were:

```
2015-12-07 22:08:35.418 [INFO ] [.b.p.internal.PilightConnector] - Updating pilight config
2015-12-07 22:08:35.419 [ERROR] [.b.p.internal.PilightConnector] - Error in pilight listener thread
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:209) ~[na:1.8.0_66]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_66]
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[na:1.8.0_66]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[na:1.8.0_66]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[na:1.8.0_66]
        at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.8.0_66]
        at java.io.BufferedReader.fill(BufferedReader.java:161) ~[na:1.8.0_66]
        at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[na:1.8.0_66]
        at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[na:1.8.0_66]
        at org.openhab.binding.pilight.internal.PilightConnector.run(PilightConnector.java:115) ~[na:na]
```

After those lines, the following exception was repeated forever (quite similar to exception before, but started at a different line in PilightConnector.java):

```
2015-12-07 22:08:35.420 [ERROR] [.b.p.internal.PilightConnector] - Error in pilight listener thread
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:154) ~[na:1.8.0_66]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_66]
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[na:1.8.0_66]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[na:1.8.0_66]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[na:1.8.0_66]
        at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.8.0_66]
        at java.io.BufferedReader.fill(BufferedReader.java:161) ~[na:1.8.0_66]
        at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[na:1.8.0_66]
        at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[na:1.8.0_66]
        at org.openhab.binding.pilight.internal.PilightConnector.run(PilightConnector.java:93) ~[na:na]
```

**Comment by idserda** [comment]
Oops, that's not good. I'll change the logging on connection errors a bit.

**Comment by stefanroellin** [comment]
Thanks for taking care of this issue.

I am not sure, whether it is only a logging issue. Why was the thread constantly throwing an exception without being able to recover?

Shouldn't the connections be explicitly closed in PilightBinding::updated, before they are overwritten? In other words similar to the pull request #3512 for the modbus binding?

**Comment by idserda** [comment]
I've submitted a pull request to fix this.
