### ISSUE TITLE
Netatmo Binding - Could not parse JSON from URL Error

### ISSUE THREAD

**Issue by sambuca231** [openhab/openhab#3548]
I tried to run the Netatmo Binding, but I receive an error. I've already updated the version (1.8.0-Snapshot). I've checked the Netatmo credentials more then once. Can someone help me?

```
2015-12-14 16:47:39.660 [WARN ] [g.openhab.io.net.http.HttpUtil] - Method failed: HTTP/1.1 400 Bad Request
2015-12-14 16:47:39.804 [ERROR] [.service.AbstractActiveService] - Error while executing background thread Netatmo Refresh Service
org.openhab.binding.netatmo.internal.NetatmoException: Could not parse JSON from URL 'https://api.netatmo.net/oauth2/token': {"error":"invalid_grant"}
        at org.openhab.binding.netatmo.internal.messages.AbstractRequest.newException(AbstractRequest.java:46) ~[na:na]
        at org.openhab.binding.netatmo.internal.messages.RefreshTokenRequest.execute(RefreshTokenRequest.java:63) ~[na:na]
        at org.openhab.binding.netatmo.internal.NetatmoBinding$OAuthCredentials.refreshAccessToken(NetatmoBinding.java:612) ~[na:na]
        at org.openhab.binding.netatmo.internal.NetatmoBinding.execute(NetatmoBinding.java:105) ~[na:na]
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
Caused by: org.codehaus.jackson.map.JsonMappingException: Can not instantiate value of type [simple type, class org.openhab.binding.netatmo.internal.messages.NetatmoError] from JSON String; no single-String constructor/factory method (through reference chain: org.openhab.binding.netatmo.internal.messages.RefreshTokenResponse["error"])
        at org.codehaus.jackson.map.deser.std.StdValueInstantiator._createFromStringFallbacks(StdValueInstantiator.java:379) ~[na:na]
        at org.codehaus.jackson.map.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:268) ~[na:na]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromString(BeanDeserializer.java:759) ~[na:na]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:585) ~[na:na]
        at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299) ~[na:na]
        at org.codehaus.jackson.map.deser.SettableBeanProperty$FieldProperty.deserializeAndSet(SettableBeanProperty.java:579) ~[na:na]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697) ~[na:na]
        at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580) ~[na:na]
        at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2723) ~[na:na]
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1854) ~[na:na]
        at org.openhab.binding.netatmo.internal.messages.RefreshTokenRequest.execute(RefreshTokenRequest.java:58) ~[na:na]
        ... 4 common frames omitted
```
##

**Comment by vsaw** [comment]
I just got a Netatmo weather station working with version 1.8.1 of the plugin. So the code seems to be working. The [Netatmo documentation](https://dev.netatmo.com/doc/authentication/authcode) states that the `invalid_grant` error is shown  *"In case of error (invalid code, expired code, missing args)"*

**Comment by vsaw** [comment]
FYI The Netatmo Plugin documentation was a bit mileading as important steps where not mentioned. I improved it which should help you get your Netatmo addon running https://github.com/openhab/openhab/wiki/Netatmo-Binding

**Comment by hmerk** [comment]
@sambuca231 does your issue still exist, or can we close this?
