### ISSUE TITLE
Add zwave device to database: Everspring HAC01

### ISSUE THREAD

**Issue by pehon** [openhab/openhab#3591]
Hello!

Please add this z-wave device to the database:

Everspring [ID:1,Type:10]

NODE 19: Node advancer: SET_ASSOCIATION - Unknown device: 60:10:1

http://my-domotique.com/store/index.php?controller=attachment&id_attachment=58
http://www.pepper1.net/zwavedb/device/493

Thanks,
Peter

**Comment by pehon** [comment]
can I do something to speed up this process?
Thanks,
Peter

**Comment by cdjackson** [comment]
Yes, but give me a day or so to sort everything out. I've been working on an online database editor that should make it easier for people to add data to the database.

**Comment by pehon** [comment]
Hello Chris

Thanks for your answer! Good to know that someone is working on it.

Thanks,
Peter
-----Original message-----

**Comment by cdjackson** [comment]
Hi. We now have an online database editor - it would be really appreciated if you could take a look at this to see if you can add this device. The entry should be reasonably straight forward (although I can say that as I wrote it! :) ).

The information is here -: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

You will need to register and email me to get edit access, but if you can have a look at this it would really be appreciated - any questions, please let me know.

**Comment by tunichtviel** [comment]
I also have an HAC01 device. Looking here, it seems to me that the binding information was not yet added: [Everspring devices](https://github.com/openhab/openhab/tree/master/bundles/binding/org.openhab.binding.zwave/database/everspring) 

Right now the device is rather cumbersome for me, because I am not able to receive status updates that are triggered by the device (Z-Wave novice here ;) I think I would need to add the target node to the association group 1, is that correct?). 

As a quick try I locally updated products.xml, created hac01.xml and copied that to org.openhab.binding.zwave-1.8.1.jar. Well, the zwave binding would not start any more ...

Anyway, I just wanted to ask whether the HAC01 database update is 'still in process'?

Thanks!
Gert

**Comment by cdjackson** [comment]
As far as I know, it’s not been added - please feel free as described above :)

**Comment by cdjackson** [comment]
I’ve created the database entry here (http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/270 <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/270>). Please advise the device ID/ Type (as described by HABmin). if you already have the XML file for this node (as generated by the binding in the /etc/zwave/nodeX.xml folder) then you can upload it to the database and then you’ll need to add the parameters. It doesn’t look like there are too many, so it should be easy.

If no-one wants to do it, I’ll do it at some stage, but as I’m busy getting the OH2 binding running it might take another week or three...

**Comment by tunichtviel** [comment]
I will do the update of the database entry.

I registered at your 'openHAB zwave database update service'. Could you provide edit rights to me?
Gert

**Comment by cdjackson** [comment]
Thanks Gert - you have access now :)

Cheers
Chris

**Comment by tunichtviel** [comment]
Great tool!

I submitted the HAC01 entry for review.

Besides, i think an "import from pepper1/xyz-system XML" feature could be nice, yes?

Gert

**Comment by cdjackson** [comment]
> 
> Besides, i think an "import from pepper1/xyz-system XML" feature could be nice, yes?
> 
I agree - and have considered this. I’m just a bit worried about copyright if we directly go around importing other peoples data so need to check this out...

**Comment by tunichtviel** [comment]
I just tested the latest 1.9.0 snapshot at [https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.zwave/target/](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.zwave/target/).

But there are plenty exceptions. 

I am using openHAB 1.8.0. Guess I need to update that to something else?

```
2016-02-08 20:58:58.339 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor] - Checking transaction complete: class=SendData, expected=ApplicationCommandHandler, cancelled=false
2016-02-08 20:58:59.159 [DEBUG] [eController$ZWaveReceiveThread] - Receive Message = 01 09 00 04 00 04 03 26 03 63 B3 
2016-02-08 20:58:59.172 [TRACE] [o.b.z.i.protocol.SerialMessage] - NODE 255: Creating new SerialMessage from buffer = 01 09 00 04 00 04 03 26 03 63 B3 
2016-02-08 20:58:59.175 [WARN ] [e.jetty.servlet.ServletHandler] - /services/habmin/zwave/nodes/node10/
java.lang.RuntimeException: java.lang.ClassCastException: org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveAssociationCommandClass cannot be cast to org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveConfigurationCommandClass
	at org.atmosphere.handler.ReflectorServletProcessor.onRequest(ReflectorServletProcessor.java:163) ~[na:na]
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:206) ~[na:na]
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:105) ~[na:na]
	at org.atmosphere.container.Jetty7CometSupport.service(Jetty7CometSupport.java:57) ~[na:na]
	at org.atmosphere.container.JettyAsyncSupportWithWebSocket.service(JettyAsyncSupportWithWebSocket.java:67) ~[na:na]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2076) ~[na:na]
	at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:211) ~[na:na]
	at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:197) ~[na:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[na:na]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) ~[na:na]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) ~[na:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598) ~[org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486) [org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413) [org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.server.Server.handle(Server.java:350) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630) [org.eclipse.jetty.http_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230) [org.eclipse.jetty.http_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606) [org.eclipse.jetty.io_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46) [org.eclipse.jetty.io_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603) [org.eclipse.jetty.util_8.1.3.v20120522.jar:8.1.3.v20120522]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538) [org.eclipse.jetty.util_8.1.3.v20120522.jar:8.1.3.v20120522]
	at java.lang.Thread.run(Unknown Source) [na:1.7.0_40]
Caused by: java.lang.ClassCastException: org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveAssociationCommandClass cannot be cast to org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveConfigurationCommandClass
	at org.openhab.binding.zwave.internal.config.ZWaveConfiguration.getConfiguration(ZWaveConfiguration.java:387) ~[na:na]
	at org.openhab.io.habmin.services.zwave.ZWaveConfigResource.getConfig(ZWaveConfigResource.java:73) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_40]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[na:na]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[na:na]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[na:na]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[na:na]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[na:na]
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[na:na]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[na:na]
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[na:na]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) ~[na:na]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) ~[na:na]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) ~[na:na]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) ~[na:na]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) ~[na:na]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) ~[na:na]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715) ~[na:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
	at org.atmosphere.util.AtmosphereFilterChain.doFilter(AtmosphereFilterChain.java:135) ~[na:na]
	at org.atmosphere.util.AtmosphereFilterChain.invokeFilterChain(AtmosphereFilterChain.java:96) ~[na:na]
	at org.atmosphere.handler.ReflectorServletProcessor$FilterChainServletWrapper.service(ReflectorServletProcessor.java:317) ~[na:na]
	at org.atmosphere.handler.ReflectorServletProcessor.onRequest(ReflectorServletProcessor.java:160) ~[na:na]
	... 36 common frames omitted
``

**Comment by cdjackson** [comment]
Please try tomorrows version.

**Comment by tunichtviel** [comment]
I tested the current version of org.openhab.binding.zwave-1.9.0-SNAPSHOT.jar, size 1.242.691 bytes (I think that should be Build #1155 10.02.2016 03:09:23).

Still there are plenty of ClassCastExceptions:

> java.lang.ClassCastException: org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveWakeUpCommandClass cannot be cast to org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveConfigurationCommandClass
> 	at org.openhab.binding.zwave.internal.config.ZWaveConfiguration.getConfiguration(ZWaveConfiguration.java:393) ~[bundlefile:na]
> 	at org.openhab.io.habmin.services.zwave.ZWaveConfigResource.getConfig(ZWaveConfigResource.java:73) ~[na:na]
> 	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[na:na]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_71]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_71]
> 	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.18.1.jar:1.18.1]
> 	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-server-1.18.1.jar:1.18.1]
> 	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.18.1.jar:1.18.1]
> 	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[jersey-server-1.18.1.jar:1.18.1]
> 	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.18.1.jar:1.18.1]
> 	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[jersey-server-1.18.1.jar:1.18.1]
> 	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.18.1.jar:1.18.1]
> 	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[jersey-server-1.18.1.jar:1.18.1]
> 	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) [jersey-server-1.18.1.jar:1.18.1]
> 	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [jersey-server-1.18.1.jar:1.18.1]
> 	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [jersey-server-1.18.1.jar:1.18.1]
> 	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [jersey-server-1.18.1.jar:1.18.1]
> 	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [jersey-servlet-1.18.1.jar:1.18.1]
> 	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) [jersey-servlet-1.18.1.jar:1.18.1]
> 	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715) [jersey-servlet-1.18.1.jar:1.18.1]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [javax.servlet_3.0.0.v201112011016.jar:na]
> 	at org.atmosphere.util.AtmosphereFilterChain.doFilter(AtmosphereFilterChain.java:135) [atmosphere-runtime-2.2.5.jar:2.2.5]
> 	at org.atmosphere.util.AtmosphereFilterChain.invokeFilterChain(AtmosphereFilterChain.java:96) [atmosphere-runtime-2.2.5.jar:2.2.5]
> 	at org.atmosphere.handler.ReflectorServletProcessor$FilterChainServletWrapper.service(ReflectorServletProcessor.java:317) [atmosphere-runtime-2.2.5.jar:2.2.5]
> 	at org.atmosphere.handler.ReflectorServletProcessor.onRequest(ReflectorServletProcessor.java:160) [atmosphere-runtime-2.2.5.jar:2.2.5]
> 	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:206) [atmosphere-runtime-2.2.5.jar:2.2.5]
> 	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:105) [atmosphere-runtime-2.2.5.jar:2.2.5]
> 	at org.atmosphere.container.Jetty7CometSupport.service(Jetty7CometSupport.java:57) [atmosphere-runtime-2.2.5.jar:2.2.5]
> 	at org.atmosphere.container.JettyAsyncSupportWithWebSocket.service(JettyAsyncSupportWithWebSocket.java:67) [atmosphere-runtime-2.2.5.jar:2.2.5]
> 	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2076) [atmosphere-runtime-2.2.5.jar:2.2.5]
> 	at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:211) [atmosphere-runtime-2.2.5.jar:2.2.5]
> 	at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:197) [atmosphere-runtime-2.2.5.jar:2.2.5]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) [javax.servlet_3.0.0.v201112011016.jar:na]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [javax.servlet_3.0.0.v201112011016.jar:na]
> 	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) [org.eclipse.equinox.http.servlet_1.1.300.v20120522-1841.jar:na]
> 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) [org.eclipse.equinox.http.servlet_1.1.300.v20120522-1841.jar:na]
> 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) [org.eclipse.equinox.http.servlet_1.1.300.v20120522-1841.jar:na]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [javax.servlet_3.0.0.v201112011016.jar:na]
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598) [org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486) [org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413) [org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.server.Server.handle(Server.java:350) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630) [org.eclipse.jetty.http_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230) [org.eclipse.jetty.http_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606) [org.eclipse.jetty.io_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46) [org.eclipse.jetty.io_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603) [org.eclipse.jetty.util_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538) [org.eclipse.jetty.util_8.1.3.v20120522.jar:8.1.3.v20120522]
> 	at java.lang.Thread.run(Unknown Source) [na:1.8.0_71]

**Comment by tunichtviel** [comment]
I just copied products.xml and hac01.xml from 1.9.0-snapshot to the zwave binding version 1.8.1. Now I can configure my HAC01 device and it works well :)

Though, I wanted to note:
- neither the "Description" nor the "Overview" of Configuration Parameters and Association Groups made it to the hac01.xml file.
- in habmin "Configuration Parameters" the two configuration parameters are shown, but no values for these parameters were shown initially (the values were shown after I entered values).

Anyway, I am happy with that :)

Regards,
Gert

**Comment by cdjackson** [comment]
It would be good if you can confirm that this works in the latest binding - otherwise if it doesn't work you will need to keep using this version you have built rather than the released versions?

Cheers
Chris

**Comment by tunichtviel** [comment]
Just tell me when there is a 1.9.0 version where that ClassCastExceptions are resolved.

**Comment by cdjackson** [comment]
Please try the latest daily snapshot on cloudbees.

**Comment by tunichtviel** [comment]
Tested the current version (#1156) and the HAC01 works well :)

**Comment by cdjackson** [comment]
Brilliant - thanks

**Comment by pehon** [comment]
I can confirm that, working great!
