### ISSUE TITLE
Plex binding is hardcoded to use http, fails to connect to server via https

### ISSUE THREAD

**Issue by matrixagent** [openhab/openhab#3715]
Hi there,

@idserda, after a quick glance at the code it seems to me that the Plex binding is building the URL to connect to the Plex server with a hardcoded "http". I've configured my server to require HTTPS:

<img width="1157" alt="7w39o2016mc12n016e95006ab7ii17irgod48" src="https://cloud.githubusercontent.com/assets/309726/12147212/0f0b085e-b498-11e5-8db4-5913270a053b.png">

If possible, I'd really prefer to not change that. Do you think it's possible to make an option for using https or not? It might be not as trivial as changing the string to actually allow for HTTPS connections, due to how their SSL certificates work: https://blog.filippo.io/how-plex-is-doing-https-for-all-its-users/
That means, that when connecting via HTTPS from a local machine, the cert will fail:
```
user@test:/opt/openhab$ curl https://192.168.1.111:32400/
curl: (51) SSL: certificate subject name '*.8124bf18d3ae4c7c97712v4a48b1d5d2.plex.direct' does not match target host name '192.168.1.111'
```

With curl I can use the **--insecure** option to allow the connection to happen:
```
user@test:/opt/openhab$ curl --insecure https://192.168.1.111:32400/
<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
```

So you'd probably have set a similar option in Java.

Thanks in any case, happy to help with anything I might have left unclear, or beta-testing. :)

**Comment by idserda** [comment]
Thanks for looking into this! This definitely should be supported. The use of certificates looks 'interesting', I'll see what I can do.

**Comment by idserda** [comment]
Seems it's possible to get the 'correct' URI for the server that corresponds with the certificate by requesting an URL at plex.tv. Commit that does this: https://github.com/idserda/openhab/commit/e1da11f5debbd933f54222d52b9a4454ec3b23cb

Here's an updated jar, would you test this? https://www.dropbox.com/s/yzijc1v5xvtane7/org.openhab.binding.plex_1.8.0.201601062158.jar?dl=0 . Thanks!

**Comment by matrixagent** [comment]
It definitely changed, looks like now the websocket is the problem. With 1.7.1 this was the first error in the log:

```
17:02:29.393 [DEBUG] [.o.b.plex.internal.PlexBinding:159  ] - Plex binding updated
17:02:29.394 [DEBUG] [.o.b.plex.internal.PlexBinding:183  ] - Plex config, server at 192.168.2.44:32400
17:02:29.594 [DEBUG] [.b.plex.internal.PlexConnector:353  ] - Connecting web socket to Plex
17:02:29.594 [INFO ] [.service.AbstractActiveService:169  ] - Plex Refresh Service has been started
17:02:29.698 [DEBUG] [.b.plex.internal.PlexConnector:392  ] - [192.168.2.44]: Websocket error: Remotely Closed
17:02:29.711 [DEBUG] [.b.plex.internal.PlexConnector:363  ] - Error connecting to Plex
java.util.concurrent.ExecutionException: java.io.IOException: Remotely Closed
```

With 1.8.0 from your Dropbox-Link this is the error I'm getting:
```
22:09:25.781 [DEBUG] [.b.plex.internal.PlexActivator:34   ] - Plex binding has been started.
22:09:25.791 [DEBUG] [i.internal.GenericItemProvider:419  ] - Couldn't find ItemFactory for item 'PlexTVPower' of type 'tch'
22:09:25.792 [DEBUG] [i.internal.GenericItemProvider:341  ] - Start processing binding configuration of Item 'null' with 'PlexGenericBindingProvider' reader.
22:09:25.806 [DEBUG] [.o.b.plex.internal.PlexBinding:174  ] - Plex config, server at 192.168.2.44:32400
22:09:27.115 [DEBUG] [.b.plex.internal.PlexConnector:426  ] - Connecting web socket to Plex
22:09:27.117 [INFO ] [.service.AbstractActiveService:169  ] - Plex Refresh Service has been started
22:09:27.119 [DEBUG] [.b.http.internal.HttpActivator:34   ] - HTTP binding has been started.
22:09:27.128 [WARN ] [i.internal.GenericItemProvider:108  ] - Attempted to register a second BindingConfigReader of type 'plex'. The primaraly reader will remain active!
22:09:27.141 [INFO ] [.service.AbstractActiveService:169  ] - HTTP Refresh Service has been started
22:09:42.206 [DEBUG] [.b.plex.internal.PlexConnector:568  ] - 192-168-2-44.9124ef18d3ae4c7c9dc12a4a47b1d5d3.plex.direct
java.net.UnknownHostException: 192-168-2-44.9124ef18d3ae4c7c9dc12a4a47b1d5d3.plex.direct
```

I have attached the full log as well: [openhab.log.zip](https://github.com/openhab/openhab/files/80370/openhab.log.zip)

Thanks a lot for the blazing fast response! :+1:

**Comment by idserda** [comment]
Looks like you have both versions installed? If so, first remove the 1.7.1 version from the addons directory.

**Comment by matrixagent** [comment]
No, it's just 1.8.0:
```
user@test:/opt/openhab/addons$ ls -al
total 2264
drwxr-xr-x  2 manu manu    4096 Jan  6 22:08 .
drwxr-xr-x 14 manu manu   36864 Jan  6 16:48 ..
-rw-r--r--  1 manu manu   19558 Jan  6 16:47 org.openhab.binding.http-1.7.1.jar
-rw-rw-r--  1 manu manu 1605913 Jan  6 22:06 org.openhab.binding.plex_1.8.0.201601062158.jarorg.openhab.binding.plex_1.8.0.201601062158.jar
-rw-r--r--  1 manu manu    6163 Jan  6 16:46 org.openhab.persistence.exec-1.7.1.jar
-rw-r--r--  1 manu manu    7386 Jan  6 16:46 org.openhab.persistence.logging-1.7.1.jar
-rw-r--r--  1 manu manu  624538 Jan  6 16:46 org.openhab.persistence.rrd4j-1.7.1.jar
-rw-r--r--  1 manu manu     126 Aug  1 00:02 README
```

The log just contains the entries from earlier of yesterday when I testes with 1.7.1 as well. You can see at the timestamps, it's only 1.8.0 after 22:00 and before that it was just 1.7.1

**Comment by idserda** [comment]
Ah seems we also need to use the secure websocket URL (wss:// vs ws://). There's a new build at the dropbox link in the previous comment.

**Comment by matrixagent** [comment]
Huh, still not working, I'm afraid. But now it is getting pretty odd. The error:
```
...
10:08:29.664 [DEBUG] [.b.plex.internal.PlexActivator:34   ] - Plex binding has been started.
10:08:29.677 [DEBUG] [i.internal.GenericItemProvider:419  ] - Couldn't find ItemFactory for item 'PlexTVPower' of type 'tch'
10:08:29.678 [DEBUG] [i.internal.GenericItemProvider:341  ] - Start processing binding configuration of Item 'null' with 'PlexGenericBindingProvider' reader.
10:08:29.691 [DEBUG] [.o.b.plex.internal.PlexBinding:174  ] - Plex config, server at 192.168.2.44:32400
10:08:30.994 [DEBUG] [.b.plex.internal.PlexConnector:427  ] - Connecting web socket to Plex
10:08:30.998 [INFO ] [.service.AbstractActiveService:169  ] - Plex Refresh Service has been started
10:08:31.005 [DEBUG] [.i.LoggingPersistenceActivator:31   ] - Logging persistence bundle has been started.
10:08:31.043 [DEBUG] [.p.internal.PersistenceManager:147  ] - Initializing logging persistence service.
10:08:31.045 [DEBUG] [c.internal.ModelRepositoryImpl:64   ] - Configuration model 'logging.persist' can not be found
10:08:46.096 [DEBUG] [.b.plex.internal.PlexConnector:569  ] - 192-168-2-44.9124ef18d3ae4c7c9dc12a4a47b1d5d3.plex.direct
java.net.UnknownHostException: 192-168-2-44.9124ef18d3ae4c7c9dc12a4a47b1d5d3.plex.direct
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_66]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_66]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_66]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) ~[na:1.8.0_66]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_66]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_66]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_66]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[na:1.8.0_66]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[na:1.8.0_66]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.8.0_66]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105) ~[na:1.8.0_66]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[na:1.8.0_66]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.8.0_66]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513) ~[na:1.8.0_66]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_66]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[na:1.8.0_66]
	at org.openhab.binding.plex.internal.PlexConnector.doHttpRequest(PlexConnector.java:559) [bundlefile:na]
	at org.openhab.binding.plex.internal.PlexConnector.getDocument(PlexConnector.java:536) [bundlefile:na]
	at org.openhab.binding.plex.internal.PlexConnector.refresh(PlexConnector.java:529) [bundlefile:na]
	at org.openhab.binding.plex.internal.PlexBinding.execute(PlexBinding.java:60) [bundlefile:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) [org.openhab.core_1.7.1.jar:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) [org.openhab.core_1.7.1.jar:na]
10:08:46.139 [DEBUG] [.b.plex.internal.PlexConnector:462  ] - [192.168.2.44]: Websocket connection error
10:08:46.140 [DEBUG] [.b.plex.internal.PlexConnector:437  ] - Error connecting to Plex
java.util.concurrent.ExecutionException: java.net.ConnectException: wss://192-168-2-44.9124ef18d3ae4c7c9dc12a4a47b1d5d3.plex.direct:32400/:/websockets/notifications
	at com.ning.http.client.providers.netty.NettyResponseFuture.abort(NettyResponseFuture.java:341) ~[async-http-client-1.8.4.jar:na]
	at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:107) ~[async-http-client-1.8.4.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427) ~[netty-3.9.0.Final.jar:na]
...
```

This now looked to me as if it should work, however I really can't connect to the host **192-168-2-44.9124ef18d3ae4c7c9dc12a4a47b1d5d3.plex.direct**:
```
user@test:/opt/openhab$ host 192-168-2-44.9124ef18d3ae4c7c9dc12a4a47b1d5d3.plex.direct
;; connection timed out; no servers could be reached
user@test:/opt/openhab$ host 217-95-124-45.9124ef18d3ae4c7c9dc12a4a47b1d5d3.plex.direct
217-95-124-45.9124ef18d3ae4c7c9dc12a4a47b1d5d3.plex.direct has address 217.95.124.45
```

The second one is using my WAN IP, i.e. the one my home router got from my provider for the internet connection. So it seems that the hostname thingy from Plex is not able to resolve local IPs.
This seems to be in line with what I see in the console when using PlexWeb:

<img width="1339" alt="ffhku2016pytw101ho24y07rijba13ecojp58" src="https://cloud.githubusercontent.com/assets/309726/12170419/ac600056-b541-11e5-8f77-acfdd7a803d9.png">

Apparently even PlexWeb can't/won't connect to the PlexServer via the local IP but instead is using the WAN IP. While I'm certain that playing media is done using the local connection in PlexWeb, I'm surprised to learn that the same is not true for navigating the interface, apparently. (By the way, this screenshot is from using plex.tv/web, but the same happened when I was testing it locally on 192.168.2.44:32400/web/)

I'm not quite sure how to proceed, as this feels like either a bug on Plex' side or maybe networking fubar on my end. I think I will ask about why PlexWeb is not able to connect to **192-168-2-44.9124ef18d3ae4c7c9dc12a4a47b1d5d3.plex.direct** in the Plex forums, as it seems to be the missing key to solving this as well. Your changes now seem to produce the correct URIs, but for some reason they are not resolvable.

**Comment by idserda** [comment]
Weird stuff, seems to resolve fine here:

```
MBP:~ $ host 192-168-2-44.9124ef18d3ae4c7c9dc12a4a47b1d5d3.plex.direct 
192-168-2-44.9124ef18d3ae4c7c9dc12a4a47b1d5d3.plex.direct has address 192.168.2.44
```

Maybe there's a solution here? https://support.plex.tv/hc/en-us/articles/206225077-How-to-Use-Secure-Server-Connections

**Comment by matrixagent** [comment]
That was it, my router prevented the *DNS Rebinding*, and once I added an exception for the plex.direct domain it worked. :see_no_evil: 

Thanks again for all your help!
