### ISSUE TITLE
Raspberry pi problem

### ISSUE THREAD

**Issue by albertovm** [openhab/openhab#3775]
Is there any way to solve this? It appears that BlueCove/Bluez has a BUG with latest Raspberry's Debian. It does not allow installation of both, but my bluetooth works perfectly.

13:52:25.324 ERROR o.o.b.b.i.BTDeviceDiscoveryService[:217]- Error while initializing local bluetooth device.
javax.bluetooth.BluetoothStateException: BlueCove com.intel.bluetooth.BluetoothStackBlueZ|com.intel.bluetooth.BluetoothStackBlueZDBus not available
	at com.intel.bluetooth.BlueCoveImpl.loadStackClass(BlueCoveImpl.java:363)
	at com.intel.bluetooth.BlueCoveImpl.detectStack(BlueCoveImpl.java:454)
	at com.intel.bluetooth.BlueCoveImpl.access$500(BlueCoveImpl.java:70)
	at com.intel.bluetooth.BlueCoveImpl$1.run(BlueCoveImpl.java:1085)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.intel.bluetooth.BlueCoveImpl.detectStackPrivileged(BlueCoveImpl.java:1083)

**Comment by steve-bate** [comment]
> Is there any way to solve this?

You may get more feedback by discussing this at the [community forum](https://community.openhab.org/). Please update this issue once you have more information. Thanks.

**Comment by teichsta** [comment]
closing this issue for now. Feel free to reopen once you've discussed this issue in more detail …
