### ISSUE TITLE
Tinkerforge binding does not work for IO16 bricklet

### ISSUE THREAD

**Issue by zgantar** [openhab/openhab#4030]
I have a sensor that is connected to a input port on a IO16 bricklet. When I view the state of this port using the brick viewer I can see it changing depending on the sensor output but when looking in the Events.log there are no events for this port. I have switched the IO16 bricklet with a IO4 and everything works. The problem is definitely not in the configuration since I've checked it several times and tried it two different ways, below:

example I:
openhab.cfg

> #test io16
> #tinkerforge:movementLR.uid=spm
> #tinkerforge:movementLR.subid=inb7
> #tinkerforge:movementLR.type=bricklet_io16
> #tinkerforge:movementLR.pullUpResistorEnabled=true

*.items

> Contact Dnevna                  "Dnevna soba [MAP(si.map):MOTION-%s]" <motion> { tinkerforge="name=movementLR" }

example II:

> Contact Dnevna                  "Dnevna soba [MAP(si.map):MOTION-%s]" <motion> { tinkerforge="uid=spm, subid=inb7" }

The strangest thing is that sometimes I received an error that is appended below but most of the time I didn't. 

> 2016-02-10 10:14:12.929 [ERROR] [.service.AbstractActiveService] - Error while executing background thread Tinkerforge Refresh Service
> java.lang.NullPointerException: null
>         at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.getBindingProviders(TinkerforgeBinding.java:564) ~[na:na]
>         at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.postUpdate(TinkerforgeBinding.java:664) ~[na:na]
>         at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.processValue(TinkerforgeBinding.java:510) ~[na:na]
>         at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.processTFDeviceValues(TinkerforgeBinding.java:416) ~[na:na]
>         at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.access$2(TinkerforgeBinding.java:411) ~[na:na]
>         at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding$1.notifyChanged(TinkerforgeBinding.java:246) ~[na:na]
>         at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374) ~[na:na]
>         at org.openhab.binding.tinkerforge.internal.model.impl.MBrickletTemperatureImpl.setSensorValue(MBrickletTemperatureImpl.java:686) ~[na:na]
>         at org.openhab.binding.tinkerforge.internal.model.impl.MBrickletTemperatureImpl.fetchSensorValue(MBrickletTemperatureImpl.java:837) ~[na:na]
>         at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.updateItemValues(TinkerforgeBinding.java:645) ~[na:na]
>         at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.execute(TinkerforgeBinding.java:608) ~[na:na]
>         at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
>         at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
>

**Comment by theoweiss** [comment]
@zgantar Thanks for reporting this. I'll check this issue, but it will need some time because I'm quite busy these days.

**Comment by zgantar** [comment]
Hello Theo,
No problem, it seems I have made myself some extra time http://www.tinkerunity.org/forum/index.php?topic=3544.msg21501#msg21501.

Best regards,
Žiga

**Comment by theoweiss** [comment]
That's bad :-(( . But the Tinkerforge guys are very helpful as always.

**Comment by watou** [comment]
Hi @theoweiss, please also take a look at [this NullPointerException](https://community.openhab.org/t/tinkerforge-symbolic-names-in-1-8-1-dont-seem-to-work/7993/6?u=watou), that [seems to be due to the instance variable `ohConfig` not having been set](https://github.com/openhab/openhab/blob/1.8/bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/TinkerforgeBinding.java#L765)  (the only place it's set is in the `updated` method when a non-null config is passed in).

**Comment by theoweiss** [comment]
@watou thanks for your support.
