### ISSUE TITLE
zwave java.lang.ArrayIndexOutOfBounds exception for DYNAMIC_VALUES

### ISSUE THREAD

**Issue by TheKorn2** [openhab/openhab#4124]
When receiving zwave DYNAMIC_VALUES events from an aeon smartswitch energy, often will get an ArrayIndexOutOfBounds exception:

2016-03-01 23:41:45.395 [DEBUG] [.z.internal.ZWaveActiveBinding:449 ]- ZwaveIncomingEvent
2016-03-01 23:41:45.396 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1034]- NODE 23: Node advancer - DYNAMIC_VALUES: Transaction complete (SendData:Request) success(true)
2016-03-01 23:41:45.396 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:202 ]- NODE 23: Node advancer - checking initialisation queue. Queue size 4.
2016-03-01 23:41:45.397 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:208 ]- NODE 23: Node advancer - message removed from queue. Queue size 3.
2016-03-01 23:41:45.397 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:267 ]- NODE 23: Node advancer - DYNAMIC_VALUES: queue length(3), free to send(true)
2016-03-01 23:41:45.398 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1158]- NODE 23: Initialisation retry timer started 5000
2016-03-01 23:41:45.399 [DEBUG] [b.z.i.protocol.ZWaveController:947 ]- Callback ID = 193
2016-03-01 23:41:45.399 [DEBUG] [b.z.i.protocol.ZWaveController:632 ]- Enqueueing message. Queue length = 108
2016-03-01 23:41:45.400 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:240 ]- NODE 23: Node advancer - queued packet. Queue length is 3
2016-03-01 23:41:45.401 [DEBUG] [WaveController$ZWaveSendThread:1364]- NODE 23: Response processed after 149ms/1877ms.
2016-03-01 23:41:45.402 [DEBUG] [WaveController$ZWaveSendThread:1241]- Took message from queue for sending. Queue length = 107
2016-03-01 23:41:45.402 [DEBUG] [o.b.z.i.protocol.SerialMessage:243 ]- Assembled message buffer = 01 09 00 13 17 02 31 04 25 C1 21
2016-03-01 23:41:45.403 [DEBUG] [WaveController$ZWaveSendThread:1301]- NODE 23: Sending REQUEST Message = 01 09 00 13 17 02 31 04 25 C1 21
2016-03-01 23:41:45.412 [DEBUG] [eController$ZWaveReceiveThread:1530]- Receive Message = 01 04 01 13 01 E8
2016-03-01 23:41:45.413 [DEBUG] [eController$ZWaveReceiveThread:1446]- Receive queue ADD: Length=1
2016-03-01 23:41:45.413 [DEBUG] [b.z.i.protocol.ZWaveController:1194]- Receive queue TAKE: Length=0
2016-03-01 23:41:45.414 [DEBUG] [o.b.z.i.protocol.SerialMessage:243 ]- Assembled message buffer = 01 04 01 13 01 E8
2016-03-01 23:41:45.414 [DEBUG] [b.z.i.protocol.ZWaveController:1195]- Process Message = 01 04 01 13 01 E8
2016-03-01 23:41:45.414 [DEBUG] [b.z.i.protocol.ZWaveController:194 ]- Message: class = SendData (0x13), type = Response (0x01), payload = 01
2016-03-01 23:41:45.415 [DEBUG] [b.z.i.p.s.SendDataMessageClass:38  ]- NODE 23: Sent Data successfully placed on stack.
2016-03-01 23:41:45.442 [DEBUG] [eController$ZWaveReceiveThread:1530]- Receive Message = 01 09 00 04 00 17 03 25 03 FF 3F
2016-03-01 23:41:45.444 [DEBUG] [eController$ZWaveReceiveThread:1446]- Receive queue ADD: Length=1
2016-03-01 23:41:45.444 [DEBUG] [b.z.i.protocol.ZWaveController:1194]- Receive queue TAKE: Length=0
2016-03-01 23:41:45.445 [DEBUG] [o.b.z.i.protocol.SerialMessage:243 ]- Assembled message buffer = 01 09 00 04 00 17 03 25 03 FF 3F
2016-03-01 23:41:45.445 [DEBUG] [b.z.i.protocol.ZWaveController:1195]- Process Message = 01 09 00 04 00 17 03 25 03 FF 3F
2016-03-01 23:41:45.446 [DEBUG] [b.z.i.protocol.ZWaveController:194 ]- Message: class = ApplicationCommandHandler (0x04), type = Request (0x00), payload = 00 17 03 25 03 FF
2016-03-01 23:41:45.446 [DEBUG] [ApplicationCommandMessageClass:40  ]- NODE 23: Application Command Request (ALIVE:DYNAMIC_VALUES)
2016-03-01 23:41:45.446 [DEBUG] [ApplicationCommandMessageClass:58  ]- NODE 23: Incoming command class SWITCH_BINARY
2016-03-01 23:41:45.447 [DEBUG] [.ZWaveBinarySwitchCommandClass:79  ]- Received Switch Binary Request for Node ID = 23
2016-03-01 23:41:45.447 [DEBUG] [.ZWaveBinarySwitchCommandClass:114 ]- NODE 23: Switch Binary report, value = 0xFF
2016-03-01 23:41:45.447 [DEBUG] [b.z.i.protocol.ZWaveController:648 ]- Notifying event listeners: ZWaveCommandClassValueEvent
2016-03-01 23:41:45.448 [DEBUG] [.z.internal.ZWaveActiveBinding:449 ]- ZwaveIncomingEvent
2016-03-01 23:41:45.448 [DEBUG] [.z.internal.ZWaveActiveBinding:466 ]- NODE 23: Got a value event from Z-Wave network, endpoint = 0, command class = SWITCH_BINARY, value = 255
2016-03-01 23:41:45.585 [DEBUG] [eController$ZWaveReceiveThread:1530]- Receive Message = 01 07 00 13 C1 00 00 12 38
2016-03-01 23:41:45.586 [DEBUG] [eController$ZWaveReceiveThread:1446]- Receive queue ADD: Length=1
2016-03-01 23:41:45.586 [DEBUG] [b.z.i.protocol.ZWaveController:1194]- Receive queue TAKE: Length=0
2016-03-01 23:41:45.587 [DEBUG] [o.b.z.i.protocol.SerialMessage:243 ]- Assembled message buffer = 01 09 00 13 C1 00 00 12 00 00 36
2016-03-01 23:41:45.587 [DEBUG] [b.z.i.protocol.ZWaveController:1195]- Process Message = 01 09 00 13 C1 00 00 12 00 00 36
2016-03-01 23:41:45.587 [DEBUG] [b.z.i.protocol.ZWaveController:194 ]- Message: class = SendData (0x13), type = Request (0x00), payload = C1 00 00 12
2016-03-01 23:41:45.588 [DEBUG] [b.z.i.p.s.SendDataMessageClass:73  ]- NODE 23: SendData Request. CallBack ID = 193, Status = Transmission complete and ACK received(0)
2016-03-01 23:41:45.588 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:66  ]- Sent message Message: class = SendData (0x13), type = Request (0x00), payload = 17 02 31 04
2016-03-01 23:41:45.589 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:67  ]- Recv message Message: class = SendData (0x13), type = Request (0x00), payload = C1 00 00 12
2016-03-01 23:41:45.589 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:68  ]- Checking transaction complete: class=SendData, expected=ApplicationCommandHandler, cancelled=false
2016-03-01 23:41:45.770 [DEBUG] [eController$ZWaveReceiveThread:1530]- Receive Message = 01 09 00 04 00 17 03 31 05 04 D6
2016-03-01 23:41:45.772 [DEBUG] [eController$ZWaveReceiveThread:1446]- Receive queue ADD: Length=1
2016-03-01 23:41:45.772 [DEBUG] [b.z.i.protocol.ZWaveController:1194]- Receive queue TAKE: Length=0
2016-03-01 23:41:45.773 [DEBUG] [o.b.z.i.protocol.SerialMessage:243 ]- Assembled message buffer = 01 09 00 04 00 17 03 31 05 04 D6
2016-03-01 23:41:45.773 [DEBUG] [b.z.i.protocol.ZWaveController:1195]- Process Message = 01 09 00 04 00 17 03 31 05 04 D6
2016-03-01 23:41:45.773 [DEBUG] [b.z.i.protocol.ZWaveController:194 ]- Message: class = ApplicationCommandHandler (0x04), type = Request (0x00), payload = 00 17 03 31 05 04
2016-03-01 23:41:45.774 [DEBUG] [ApplicationCommandMessageClass:40  ]- NODE 23: Application Command Request (ALIVE:DYNAMIC_VALUES)
2016-03-01 23:41:45.774 [DEBUG] [ApplicationCommandMessageClass:58  ]- NODE 23: Incoming command class SENSOR_MULTILEVEL
2016-03-01 23:41:45.774 [DEBUG] [veMultiLevelSensorCommandClass:95  ]- NODE 23: Received Sensor Multi Level Request
2016-03-01 23:41:45.775 [DEBUG] [veMultiLevelSensorCommandClass:130 ]- NODE 23: Sensor Multi Level REPORT received
2016-03-01 23:41:45.780 [ERROR] [b.z.i.protocol.ZWaveController:1202]- Exception during Z-Wave thread: Input.
java.lang.ArrayIndexOutOfBoundsException: 6
        at org.openhab.binding.zwave.internal.protocol.SerialMessage.getMessagePayloadByte(SerialMessage.java:329) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveMultiLevelSensorCommandClass.handleApplicationCommandRequest(ZWaveMultiLevelSensorCommandClass.java:133) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.serialmessage.ApplicationCommandMessageClass.handleRequest(ApplicationCommandMessageClass.java:84) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingRequestMessage(ZWaveController.java:225) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingMessage(ZWaveController.java:198) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.access$6(ZWaveController.java:193) ~[na:na]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveInputThread.run(ZWaveController.java:1197) ~[na:na]

Doesn't happen on every DYNAMIC_VALUES received, only sometimes.
##

**Comment by TheKorn2** [comment]
Not sure if same or different bug than #4123 .

**Comment by cdjackson** [comment]
I think the issue here is the message is corrupt (it is 0 length). I’ll look to add a check for this to avoid the error, but the device seems to be sending rubbish :(

**Comment by TheKorn2** [comment]
What!??  My devices aren't perfect!??  (/s....  heavily /s!  :D)

**Comment by cdjackson** [comment]
I’m afraid not - we’ve seen this before on some Aeon devices. In this case, the frame doesn’t have all of the command class header (well, what I would call the header anyway - the bit that says what sensor type etc it it).

**Comment by 9037568** [comment]
Closed via merged PR #4131
