### ISSUE TITLE
CalDav OH2 - caldavio.cfg seems to be ignored

### ISSUE THREAD

**Issue by gerwinbrunner** [openhab/openhab#4135]
Hi,

I'm using OH2 and added openhab-binding-caldav-command.

Then I configured `services/caldavCommand.cfg` like:
```
readCalendars=mycal
```

And `services/caldavio.cfg` like:
```
mycal:url=https://www.google.com/calendar/dav/CALENDERID@group.calendar.google.com
mycal:username=USERNAME
mycal:password=PASSWORD
mycal:reloadInterval=1
mycal:preloadTime=1440
mycal:disableCertificateVerification=true
mycal:timeZone=Europe/Vienna
```

In the log I get the following entry:
```
2016-03-05 23:05:16.725 [DEBUG] [.io.caldav.internal.CalDavLoaderImpl] - calendar id mycal not found
2016-03-05 23:05:16.726 [DEBUG] [.io.caldav.internal.CalDavLoaderImpl] - return event list for CalDavQuery [calendarIds=[mycal], from=2016-03-05T23:05:16.725+01:00, to=2016-03-05T23:05:16.725+01:00, sort=null] with 0 entries
2016-03-05 23:05:16.727 [DEBUG] [.io.caldav.internal.CalDavLoaderImpl] - calendar id mycal not found
2016-03-05 23:05:16.728 [DEBUG] [.io.caldav.internal.CalDavLoaderImpl] - return event list for CalDavQuery [calendarIds=[mycal], from=2016-03-05T23:05:16.727+01:00, to=null, sort=null] with 0 entries
```

The strange thing is, that a change to the `services/caldavio.cfg` files does not trigger a reload.
It just seems that this file is totally ignored.

Has anybody got an idea what is wrong here?

Thanks,
Gerwin

**Comment by teichsta** [comment]
could you please try to replace the `:` by a `.` before the equality sign?

@querdenker2k any other idea?

**Comment by gerwinbrunner** [comment]
That did not really work:
```
2016-03-07 14:54:07.064 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.cm.ManagedService, org.openhab.io.caldav.CalDavLoader, id=117, bundle=183/mvn:org.openhab.io/org.openhab.io.caldav/1.9.0-SNAPSHOT]: Updating property mycal.url of configuration org.openhab.caldavio caused a problem: unknown identifier
org.osgi.service.cm.ConfigurationException: mycal.url : unknown identifier
	at org.openhab.io.caldav.internal.CalDavLoaderImpl.updated(CalDavLoaderImpl.java:163)[183:org.openhab.io.caldav:1.9.0.201603050212]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.ConfigurationManager$UpdateConfiguration.run(ConfigurationManager.java:1753)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)[7:org.apache.felix.configadmin:1.8.8]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_74]


```

**Comment by gerwinbrunner** [comment]
The config now looks like this:
```
mycal.url=https://www.google.com/calendar/dav/CALENDERID@group.calendar.google.com
mycal.username=USERNAME
mycal.password=PASSWORD
mycal.reloadInterval=1
mycal.preloadTime=1440
mycal.disableCertificateVerification=true
mycal.timeZone=Europe/Vienna
```

**Comment by querdenker2k** [comment]
As described here: [https://github.com/openhab/openhab/wiki/CalDAV](url)
You have to use ":" instead of "."

**Comment by gerwinbrunner** [comment]
@querdenker2k: I had it this way. So we are back to the initial problem.

**Comment by querdenker2k** [comment]
Sorry, didn't read the full thread...
You've got the same problem like me.
It's currently not running with OH2.
[https://github.com/openhab/openhab/issues/4074](url)
I would like to fix it, but dont't know how.

**Comment by steve-bate** [comment]
Closing because this issue appears to duplicate #4074.
