### ISSUE TITLE
CalDav: error while loading calendar entries: java.lang.RuntimeException: Could not generate DH keypair

### ISSUE THREAD

**Issue by marbon87** [openhab/openhab#4195]
Hi there,

i am trying to configure the caldav binding for my calendar at mailbox.org (They are using openxchange).
I have the following configuration:
```
caldavio:holiday:url=https://dav.mailbox.org/caldav/99
caldavio:holiday:username=myuser@mailbox.org
caldavio:holiday:password=PASSWORD
```
I am using Java-Version: 1.8.0_73

When i start openhab i get the folowing exception:
```
2016-03-20 15:33:34.005 [DEBUG] [org.openhab.io.caldav.internal.job.EventReloaderJob] - reload cached events for config: holiday
2016-03-20 15:33:34.487 [DEBUG] [org.openhab.io.caldav.internal.job.EventReloaderJob] - loading events for config: holiday
2016-03-20 15:33:36.499 [ERROR] [org.openhab.io.caldav.internal.job.EventReloaderJob] - error while loading calendar entries: java.lang.RuntimeException: Could not generate DH keypair
javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[na:1.8.0_73]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949) ~[na:1.8.0_73]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906) ~[na:1.8.0_73]
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889) ~[na:1.8.0_73]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410) ~[na:1.8.0_73]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) ~[na:1.8.0_73]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275) ~[na:na]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:254) ~[na:na]
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123) ~[na:na]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318) ~[na:na]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363) ~[na:na]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219) ~[na:na]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195) ~[na:na]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86) ~[na:na]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108) ~[na:na]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[na:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[na:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214) ~[na:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160) ~[na:na]
	at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:962) ~[na:na]
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:417) ~[na:na]
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:409) ~[na:na]
	at com.github.sardine.impl.SardineImpl.list(SardineImpl.java:386) ~[na:na]
	at org.openhab.io.caldav.internal.job.EventReloaderJob.loadEvents(EventReloaderJob.java:217) ~[na:na]
	at org.openhab.io.caldav.internal.job.EventReloaderJob.execute(EventReloaderJob.java:118) ~[na:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-all-2.1.7.jar:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [quartz-all-2.1.7.jar:na]
Caused by: java.lang.RuntimeException: Could not generate DH keypair
	at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:142) ~[na:1.8.0_73]
	at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:114) ~[na:1.8.0_73]
	at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:708) ~[na:1.8.0_73]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:268) ~[na:1.8.0_73]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[na:1.8.0_73]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914) ~[na:1.8.0_73]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062) ~[na:1.8.0_73]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[na:1.8.0_73]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[na:1.8.0_73]
	... 22 common frames omitted
Caused by: java.security.InvalidAlgorithmParameterException: Prime size must be multiple of 64, and can only range from 512 to 2048 (inclusive)
	at com.sun.crypto.provider.DHKeyPairGenerator.initialize(DHKeyPairGenerator.java:120) ~[sunjce_provider.jar:1.8.0_71]
	at java.security.KeyPairGenerator$Delegate.initialize(KeyPairGenerator.java:674) ~[na:1.8.0_73]
	at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:128) ~[na:1.8.0_73]
	... 30 common frames omitted
```

The result is that no entries are loaded

**Comment by steve-bate** [comment]
This is a Java limitation on prime size. See: http://stackoverflow.com/questions/6851461/java-why-does-ssl-handshake-give-could-not-generate-dh-keypair-exception

**Comment by marbon87** [comment]
Hm. If i unterstand it correct, there is no solution for this and i have to wait, correct?

**Comment by steve-bate** [comment]
Yes, unfortunately. It's a Java limitation that may be removed at some point. https://bugs.openjdk.java.net/browse/JDK-8072452
