### ISSUE TITLE
Openhab 1.8.2 z-wave binding problem

### ISSUE THREAD

**Issue by easypl** [openhab/openhab#4209]
Zwave stop working after upgrading from 1.8.1 to 1.8.2 (debian deb package).
Zwave aeon S2 USB stick.
I have errors in openhab.log:

2016-03-23 18:52:29.453 [WARN ] [e.jetty.servlet.ServletHandler] - /services/habmin/zwave/products/
java.lang.RuntimeException: java.lang.NullPointerException
        at org.atmosphere.handler.ReflectorServletProcessor.onRequest(ReflectorServletProcessor.java:163) ~[na:na]
        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:206) ~[na:na]
        at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:105) ~[na:na]
        at org.atmosphere.container.Jetty7CometSupport.service(Jetty7CometSupport.java:57) ~[na:na]
        at org.atmosphere.container.JettyAsyncSupportWithWebSocket.service(JettyAsyncSupportWithWebSocket.java:67) ~[na:na]
        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2076) ~[na:na]
        at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:211) ~[na:na]
        at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:197) ~[na:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[javax.servlet_3.0.0.v201112011016.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) ~[na:na]
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) ~[na:na]
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) ~[na:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:598) ~[org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:486) [org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:413) [org.eclipse.jetty.servlet_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.server.Server.handle(Server.java:350) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:454) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:890) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:944) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630) [org.eclipse.jetty.http_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230) [org.eclipse.jetty.http_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77) [org.eclipse.jetty.server_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606) [org.eclipse.jetty.io_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46) [org.eclipse.jetty.io_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603) [org.eclipse.jetty.util_8.1.3.v20120522.jar:8.1.3.v20120522]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538) [org.eclipse.jetty.util_8.1.3.v20120522.jar:8.1.3.v20120522]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
Caused by: java.lang.NullPointerException: null
        at org.openhab.binding.zwave.internal.config.ZWaveConfiguration.getConfiguration(ZWaveConfiguration.java:127) ~[na:na]
        at org.openhab.io.habmin.services.zwave.ZWaveConfigResource.getConfig(ZWaveConfigResource.java:73) ~[na:na]
        at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_80]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_80]

**Comment by teichsta** [comment]
@cdjackson can you help? Or could this be an permission problem @theoweiss?

**Comment by LeoVe** [comment]
Same problem here, I think.

Upgraded to OpenHAB 1.8.2 on a Synology NAS, this is in openhab.stdout when openening the zwave binding settings in habmin:

2016-03-24 15:06:54.441 [ERROR] [.s.container.ContainerResponse] - The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
java.lang.NullPointerException: null
        at org.openhab.binding.zwave.internal.config.ZWaveConfiguration.getConfiguration(ZWaveConfiguration.java:127) ~[bundlefile:na]
        at org.openhab.io.habmin.services.zwave.ZWaveConfigResource.getConfig(ZWaveConfigResource.java:73) ~[na:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]

**Comment by cdjackson** [comment]
It looks like there must be a problem with the database update :(

Thomas - how do you want to handle this - do we do a 1.8.3?

**Comment by teichsta** [comment]
since there seem to be at least to more critical issue (#4214 #4230), i am afraid, yes …

**Comment by LeoVe** [comment]
I have a RPi installed with OpenHAB 1.8.2, Razberry Z-wave controller and a Fibaro multisensor in an installation.

I think it might be a 1.8.2 problem I have, it seems quite difficult for OpenHAB with the zwave binding to connect to the Fibaro multisensor, the sensor's parameters are not shown in habmin and at healtime, at 4 am, this is in the log:

----------------------------------------------------------
2016-03-28 23:33:46.511 [WARN ] [o.b.w.i.parser.CommonIdHandler] - CommonId not found: CommonIdHandler[provider=YAHOO,id=<null>,icon=<null>]
2016-03-29 00:16:47.668 [ERROR] [eController$ZWaveReceiveThread] - Message is not valid, discarding
2016-03-29 00:16:47.683 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x00. Sending NAK.
2016-03-29 00:16:47.703 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x9A. Sending NAK.
2016-03-29 04:00:06.282 [ERROR] [WaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 2 attempts left!
2016-03-29 04:00:11.312 [ERROR] [WaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 1 attempts left!
2016-03-29 04:00:16.461 [ERROR] [WaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 0 attempts left!
2016-03-29 04:00:20.743 [ERROR] [NodeNeighborUpdateMessageClass] - NODE 1: NodeNeighborUpdate FAILED
2016-03-29 04:00:20.783 [ERROR] [NodeNeighborUpdateMessageClass] - NODE 1: NodeNeighborUpdate FAILED
2016-03-29 04:00:20.824 [ERROR] [NodeNeighborUpdateMessageClass] - NODE 1: NodeNeighborUpdate FAILED
2016-03-29 04:00:20.863 [ERROR] [NodeNeighborUpdateMessageClass] - NODE 1: NodeNeighborUpdate FAILED
2016-03-29 04:17:21.526 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x00. Sending NAK.
2016-03-29 04:17:21.542 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x02. Sending NAK.
2016-03-29 04:17:21.562 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x00. Sending NAK.
2016-03-29 04:17:21.582 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x02. Sending NAK.
2016-03-29 04:17:21.602 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x81. Sending NAK.
2016-03-29 04:17:21.622 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x1A. Sending NAK.
2016-03-29 04:17:21.642 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0xEC. Sending NAK.
2016-03-29 04:17:23.018 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x00. Sending NAK.
2016-03-29 04:17:23.032 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x02. Sending NAK.
2016-03-29 04:17:23.052 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x00. Sending NAK.
2016-03-29 04:17:23.072 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x0A. Sending NAK.
2016-03-29 04:17:23.092 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x81. Sending NAK.
2016-03-29 04:17:23.112 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x1A. Sending NAK.
2016-03-29 04:17:23.132 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0xEC. Sending NAK.
2016-03-29 04:17:24.518 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x00. Sending NAK.
2016-03-29 04:17:24.532 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x02. Sending NAK.
2016-03-29 04:17:24.552 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x00. Sending NAK.
2016-03-29 04:17:24.572 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x0A. Sending NAK.
2016-03-29 04:17:24.592 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x81. Sending NAK.
2016-03-29 04:17:24.612 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x1A. Sending NAK.
2016-03-29 04:17:24.632 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0xEC. Sending NAK.
2016-03-29 04:17:26.018 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x00. Sending NAK.
2016-03-29 04:17:26.032 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x02. Sending NAK.
2016-03-29 04:17:26.052 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x00. Sending NAK.
2016-03-29 04:17:26.072 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x0A. Sending NAK.
2016-03-29 04:17:26.092 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x81. Sending NAK.
2016-03-29 04:17:26.112 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x1A. Sending NAK.
2016-03-29 04:17:26.132 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0xEC. Sending NAK.
2016-03-29 04:17:32.569 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x80. Sending NAK.
2016-03-29 04:17:32.592 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x02. Sending NAK.
2016-03-29 04:17:32.612 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x00. Sending NAK.
2016-03-29 04:17:32.632 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x0A. Sending NAK.
2016-03-29 04:17:32.652 [WARN ] [eController$ZWaveReceiveThread] - Protocol error (OOF). Got 0x41. Sending NAK.
2016-03-29 08:58:09.674 [ERROR] [.s.container.ContainerResponse] - The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
java.lang.NullPointerException: null
        at org.openhab.binding.zwave.internal.config.ZWaveConfiguration.getConfiguration(ZWaveConfiguration.java:127) ~[bundlefile:na]
        at org.openhab.io.habmin.services.zwave.ZWaveConfigResource.getConfig(ZWaveConfigResource.java:73) ~[na:na]
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) [jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [jersey-server-1.18.1.jar:1.18.1]
------------------------------------------
Could this be related to the dump at startup of habmin or not?

**Comment by cdjackson** [comment]
No - this doesn’t look related. This looks like a COM port issue - I’d suggest discussing this on the forum as I suspect you might have some settings wrong.

**Comment by LeoVe** [comment]
Thanks,
OK CDJackson I'll dig further. It is quite cumbersome to get the com port connected on a RPi 3.

**Comment by cdjackson** [comment]
I recall seeing something on the forum that COM ports have changed between RPi1 and 3, and the zwave daughterboard now connects to a different port…  I can’t find it now, but you might find it, or add another post and someone should be able to help.

**Comment by MarkJonas** [comment]
Regarding the COM port changes on Raspberry Pi 3 vs. Pi 1 and 2 have a look at https://community.openhab.org/t/openhab-on-raspberry-pi-3-with-razberry-z-wave-comm-problem/8815/4 . Leo and I got the port working by applying a device tree overlay.

**Comment by LeoVe** [comment]
Bought a RPi 2, undid all Pi 3 specifics. The comms with the Razberry is better now.
In the log I have these entries regarding the newest Fibaro motion detector FGMS-001 (z-wave plus):

2016-04-04 21:27:23.062 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 52, ignoring report.
2016-04-04 21:27:23.121 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 53, ignoring report.
2016-04-04 21:27:23.191 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 54, ignoring report.
2016-04-04 21:32:54.219 [WARN ] [o.b.w.i.parser.CommonIdHandler] - CommonId not found: CommonIdHandler[provider=YAHOO,id=<null>,icon=<null>]
2016-04-04 21:41:10.425 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 52, ignoring report.
2016-04-04 21:41:12.068 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 53, ignoring report.
2016-04-04 21:41:12.092 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 53, ignoring report.
2016-04-04 21:41:12.112 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 54, ignoring report.
2016-04-04 21:41:14.214 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 2: Unsupported command class ZWAVE_PLUS_INFO
2016-04-04 21:41:14.217 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 2: Unsupported command class DEVICE_RESET_LOCALLY
2016-04-04 21:41:14.218 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 2: Unsupported command class ASSOCIATION_GROUP_INFO
2016-04-04 21:41:14.221 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 2: Unsupported command class POWERLEVEL
2016-04-04 21:41:14.227 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 2: Unsupported command class MULTI_INSTANCE_ASSOCIATION
2016-04-04 21:41:14.232 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 2: Unsupported command class SECURITY
2016-04-04 21:41:14.234 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 2: Unsupported command class FIRMWARE_UPDATE_MD
2016-04-04 21:41:15.683 [ERROR] [z.i.p.i.ZWaveNodeStageAdvancer] - NODE 2: Node advancer: Retries exceeded at DYNAMIC_VALUES
2016-04-04 21:41:48.442 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 52, ignoring report.
2016-04-04 21:41:48.502 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 53, ignoring report.
2016-04-04 21:41:48.572 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 54, ignoring report.
2016-04-04 21:42:19.445 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 52, ignoring report.
2016-04-04 21:42:19.522 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 53, ignoring report.
2016-04-04 21:42:19.592 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 54, ignoring report.
2016-04-04 21:47:17.660 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@1794f34] - Set int - assuming LONG
2016-04-04 21:47:17.664 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@1cf58ee] - Set int - assuming LONG
2016-04-04 21:47:17.667 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@8c320a] - Set int - assuming LONG
2016-04-04 21:47:17.670 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@859bb4] - Set int - assuming LONG
2016-04-04 21:47:17.672 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@10c763f] - Set int - assuming LONG
2016-04-04 21:47:17.673 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@574598] - Set int - assuming LONG
2016-04-04 21:47:17.675 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@19822fa] - Set int - assuming LONG
2016-04-04 21:47:17.677 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@1fe4206] - Set int - assuming LONG
2016-04-04 21:47:17.678 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@1bb7508] - Set int - assuming LONG
2016-04-04 21:47:17.680 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@1b290a2] - Set int - assuming LONG
2016-04-04 21:47:17.681 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@1e7f85c] - Set int - assuming LONG
2016-04-04 21:47:17.683 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@de6a94] - Set int - assuming LONG
2016-04-04 21:47:17.685 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@cb58f2] - Set int - assuming LONG
2016-04-04 21:47:17.686 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@1c7fb49] - Set int - assuming LONG
2016-04-04 21:47:17.688 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@1a8d5f5] - Set int - assuming LONG
2016-04-04 21:47:17.689 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@738f1e] - Set int - assuming LONG
2016-04-04 21:47:17.691 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@815baa] - Set int - assuming LONG
2016-04-04 21:47:17.693 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@3cfa00] - Set int - assuming LONG
2016-04-04 21:47:17.694 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@1a89bcf] - Set int - assuming LONG
2016-04-04 21:47:17.696 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@1bbe69b] - Set int - assuming LONG
2016-04-04 21:47:17.697 [ERROR] [.z.i.config.ZWaveConfiguration] - Error with parameter type for [org.openhab.binding.zwave.internal.config.ZWaveDbLabel@197bb0d] - Set int - assuming LONG
2016-04-04 21:50:59.773 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 52, ignoring report.
2016-04-04 21:50:59.828 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 53, ignoring report.
2016-04-04 21:50:59.893 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 54, ignoring report.
2016-04-04 21:51:39.188 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 52, ignoring report.
2016-04-04 21:51:39.253 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 53, ignoring report.
2016-04-04 21:51:39.320 [ERROR] [veMultiLevelSensorCommandClass] - NODE 2: Unknown Sensor Type = 54, ignoring report.
2016-04-04 21:52:53.224 [WARN ] [o.b.w.i.parser.CommonIdHandler] - CommonId not found: CommonIdHandler[provider=YAHOO,id=<null>,icon=<null>]

Any suggestions on what could be the problem?

The sensor is reporting the temperature, light (lux) and battery status correctly. The PIR and movement sensors are not working.

Thanks

**Comment by cdjackson** [comment]
I don’t think this issue is related to the database problem (I thought there was a different issue opened) - but in any case, we’d need to see a debug log. I also suspect some sort of corruption since these don’t look like normal frames.

**Comment by Harphme** [comment]
Hi. I'm new here, so please forgive me if I'm not so used with the practice in github.
When I read this issue, I thought I can give you some more information: The behavior described by LeoVe I can confirm. I also use two Fibaro multisensors FGMS001. One with deviceID=1001 and deviceType=800, the other one with deviceID=1001 and deviceType=801.
The first one is working correctly. The second one, with deviceType=801 behaves like LeoVe described: it reports temp and lux, but doesn't report motion and tamper.
Maybe somthing with the new deviceType=801 is wrong in the database...

**Comment by cdjackson** [comment]
Which version of the binding are you using? As I think is stated elsewhere, this device is not included in the 1.8.2 database - it's not wrong, it's just not included.

If the device isn't reporting some sensors, then this is probably a configuration issue with the device and I'd recommend raising this on the forum as people will be able to advise on how best to configure the device.

**Comment by LeoVe** [comment]
I update to z-wave version 1.9Snapshot, in the log after using the binding through habmin it still reports this error:
10:49:21.882 [ERROR] [.s.container.ContainerResponse:419  ] - The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
java.lang.NullPointerException: null
        at org.openhab.binding.zwave.internal.config.ZWaveConfiguration.getConfiguration(ZWaveConfiguration.java:128) ~[bundlefile:na]
        at org.openhab.io.habmin.services.zwave.ZWaveConfigResource.getConfig(ZWaveConfigResource.java:73) ~[na:na]
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) [jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [jersey-server-1.18.1.jar:1.18.1]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [jersey-server-1.18.1.jar:1.18.1]

Nb. The multisensor is better supported by version 1.9-snapshot of the binding, although I still don't have motion detection or alarm working,
Snapshot link: https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.zwave/target/org.openhab.binding.zwave-1.9.0-SNAPSHOT.jar

**Comment by Harphme** [comment]
I'm using z-wave binding 1.8.2.
I thought it might be a problem in the database, because before, when I was using 1.8.1, openhab/habmin didn't even recognize the device with deviceType=801.
And the other point is, that the configuration for this device is exactly the same as for the device with deviceType=800. So I think the configuration should be ok.

**Comment by cdjackson** [comment]
Fibaro uses a lot of different IDs for their devices. Each time a new ID pops up, we need to add it to the database - it points to the same configuration, but it still needs to be added. It's not a "problem" with the database - it simply needs to be added. It's not possible to update the database in the binding, so you need to upgrade to a newer version.

**Comment by Harphme** [comment]
Ok, trank you for this explanation

**Comment by teichsta** [comment]
ok, so it seems we can remove the critical tag and the relevance for 1.8 … did i recall this correctly?

**Comment by LeoVe** [comment]
The zwave binding, v1.9, still crashes when adressed through habmin.

**Comment by bodiroga** [comment]
I thought this was going to be fixed in v1.8.3, but I have upgraded my openHAB installation some minutes ago and the problem is still there :cry:

**Comment by cdjackson** [comment]
Unfortunately this got missed so the zwave binding in 1.8.3 is still not working I guess. The database still needs to be updated before the next release.
