### ISSUE TITLE
Homegear/Homatic binding and FS20 binding on one CUL possible? Can't open cul device!

### ISSUE THREAD

**Issue by IT-Berater** [openhab/openhab#4262]
Hi,
openHAB (1.8.1) run with Homegar / Homatic with CUL (CUL_V3 V 1.66 CUL868) on /dev/ttyACM0 nice.

I need FS20 (KSE) Device include.

I have install FS20-Binding ( https://github.com/openhab/openhab/wiki/FS20-Binding) and set the rights to all:

crwxrwxrwx 1 homegear dialout 166, 0 Apr 5 19:26 /dev/ttyACM0

It is possible two bindings use the *same*  /dev/ttyACM0 ?

Or there is a bug in FS20 Binding?

This is the error which always comes:

```
 [ERROR] [.o.b.fs20.internal.FS20Binding:81   ] - Can't open cul device
org.openhab.io.transport.cul.CULDeviceException: gnu.io.NoSuchPortException
    at org.openhab.io.transport.cul.internal.CULSerialHandlerImpl.openHardware(CULSerialHandlerImpl.java:269) ~[na:na]
    at org.openhab.io.transport.cul.internal.AbstractCULHandler.open(AbstractCULHandler.java:154) ~[na:na]
    at org.openhab.io.transport.cul.CULManager.createNewHandler(CULManager.java:170) ~[bundlefile:na]
    at org.openhab.io.transport.cul.CULManager.getOpenCULHandler(CULManager.java:89) ~[bundlefile:na]
    at org.openhab.binding.fs20.internal.FS20Binding.getCULHandler(FS20Binding.java:78) [bundlefile:na]
    at org.openhab.binding.fs20.internal.FS20Binding.updateDeviceSettings(FS20Binding.java:72) [bundlefile:na]
    at org.openhab.binding.fs20.internal.FS20Binding.updated(FS20Binding.java:200) [bundlefile:na]
    at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
    at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
Caused by: gnu.io.NoSuchPortException: null
    at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:273) ~[na:na]
    at org.openhab.io.transport.cul.internal.CULSerialHandlerImpl.openHardware(CULSerialHandlerImpl.java:244) ~[na:na]
    ... 8 common frames omitted
```

**Comment by steve-bate** [comment]
This could be a problem with the rxtx installation. However, I'm not the CUL binding maintainer.

You may get more feedback by discussing this at the [community forum](https://community.openhab.org/). After you determine if this is a bug or a feature request, please update the issue with a link to the forum discussion. Thanks.
