### ISSUE TITLE
Can not invoke Astro action interfaces in rules

### ISSUE THREAD

**Issue by davidlballenger** [openhab/openhab#4305]
## Expected Behavior

I'm trying to use the interfaces defined in the Astro Action in some of my rules. However, I get errors when the rule is invoked. To attempt to narrow the problem context I copied the example form the action description at: [https://github.com/openhab/openhab/wiki/Actions#astro-actions](https://github.com/openhab/openhab/wiki/Actions#astro-actions) to its own rule file.  I then set the trigger to "System started" and set the latitude and longitude to the values from my openhab.cfg.

I should get the sunrise and sunset times in the log, but instead get an error.
## Current Behavior

The error is:
Executing startup rule 'Astro Action Example'
Error during the execution of startup rule 'Astro Action Example': Could not invoke method: org.openhab.action.astro.internal.Astro.getAstroSunriseStart(java.util.Date,double,double) on instance: null
## Steps to Reproduce (for bugs)

1. Copy example from [https://github.com/openhab/openhab/wiki/Actions#astro-actions](https://github.com/openhab/openhab/wiki/Actions#astro-actions)
2. Change trigger to something that will cause it to run, e.g. System started.
3. Change lat and lon variables to valid latitude and longitude. 
4. Add file to rules and watch log file for error.
## Your Environment

- Version used: openhab, astro action, astro binding all 1.8.2 installed via apt
- Environment name and version 
  java version "1.7.0_95"
  OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-1~deb8u1)
  OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
- Operating System and version: Debian 8 on intel
##

**Comment by 9037568** [comment]
Please include your rule file. The one you're referencing from the wiki is incomplete, so I assume you enhanced it to be correct?

**Comment by 9037568** [comment]
There are other reports of flakiness on "system started" rules.

I couldn't reproduce this problem, but I'm running the standard Sun JDK on a Windows machine.

I used this "when" clause:

>when
    System started or
    Time cron "15 * * * * ?"

And got the expected output with no errors:

>2016-04-21 22:01:14.960 [INFO ] [runtime.busevents             ] - Sunset_Time state updated to 2016-04-21T09:00:00
2016-04-21 22:01:14.961 [INFO ] [runtime.busevents             ] - Sunrise_Time state updated to 2016-04-20T19:46:00
2016-04-21 22:01:17.781 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'my.rules'
2016-04-21 22:01:18.093 [INFO ] [.o.model.script.sunRiseStart: ] - 2016-04-20T19:51:00
2016-04-21 22:01:18.133 [INFO ] [nhab.model.script.sunRiseEnd: ] - 2016-04-20T19:53:00
2016-04-21 22:01:18.175 [INFO ] [hab.model.script.sunSetStart: ] - 2016-04-21T08:58:00
2016-04-21 22:01:18.208 [INFO ] [enhab.model.script.sunSetEnd: ] - 2016-04-21T09:01:00

**Comment by davidlballenger** [comment]
I will check into this more tomorrow and try out the Time cron trigger.

**Comment by davidlballenger** [comment]
Okay.  I've made some changes to log more detail, i.e. the arguments to the getAstro* calls. Here is what I'm using now:

```
import org.openhab.core.library.types.*
  import java.util.Date

  rule "Astro Action Example"
  when
      System started or
      Time cron "15 * * * * ?"
  then
      var Date current = now.toDate
      var double lat = {{local_gps.latitude}}
      var double lon = {{local_gps.longitude}}
      
      logInfo("AstroActionExample", String::format("current:      %s", current.toString)
      logInfo("AstroActionExample", String::format("lat:          %f", lat))
      logInfo("AstroActionExample", String::format("lon:          %f", lon))
      logInfo("AstroActionExample", String::format("sunRiseStart: %s", new DateTimeType(getAstroSunriseStart(current, lat, lon)).toString)
      logInfo("AstroActionExample", String::format("sunRiseEnd:   %s", new DateTimeType(getAstroSunriseEnd(current, lat, lon)).toString)
      logInfo("AstroActionExample", String::format("sunSetStart:  %s", new DateTimeType(getAstroSunsetStart(current, lat, lon)).toString)
      logInfo("AstroActionExample", String::format("sunSetEnd:    %s", new DateTimeType(getAstroSunsetEnd(current, lat, lon)).toString)
  end
```
I'm still get the error on the call to `getAstroSunriseStart() `, but the previous 3 log messages print the appropriate messages.  To me the error seems to indicate that the getAstro* calls should be attached to an instance of an Astro object. Since these are static methods of the Astro class I tried `Astro::getAstroSunriseStart(current, lat, lon)`, but that got another error:

```
08:35:57.552 [DEBUG] [m.r.internal.engine.RuleEngine:273  ] - Not all required items in place yet for rule Astro Action Example, trying again later: The name 'getAstroSunriseStart(<XFeatureCallImplCustom>,<XFeatureCallImplCustom>,<XFeatureCallImplCustom>)' cannot be resolved to an item or type.
```

Here's the log output from the code example above:

```
08:19:15.003 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob:53   ] - Executing scheduled rule 'Astro Action Example'
08:19:15.007 [INFO ] [odel.script.AstroActionExample:53   ] - current:      Fri Apr 22 08:19:15 PDT 2016
08:19:15.009 [INFO ] [odel.script.AstroActionExample:53   ] - lat:          33.712992
08:19:15.011 [INFO ] [odel.script.AstroActionExample:53   ] - lon:          -116.387831
08:19:15.017 [ERROR] [.o.m.r.i.engine.ExecuteRuleJob:57   ] - Error during the execution of rule Astro Action Example
java.lang.IllegalStateException: Could not invoke method: org.openhab.action.astro.internal.Astro.getAstroSunriseStart(java.util.Date,double,double) on instance: null
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeOperation(XbaseInterpreter.java:738) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._featureCallOperation(XbaseInterpreter.java:713) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) ~[na:na]
	at org.openhab.model.script.interpreter.ScriptInterpreter.internalFeatureCallDispatch(ScriptInterpreter.java:69) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateAbstractFeatureCall(XbaseInterpreter.java:658) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:218) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluateArgumentExpressions(XbaseInterpreter.java:751) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateConstructorCall(XbaseInterpreter.java:510) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:218) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateMemberFeatureCall(XbaseInterpreter.java:545) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:218) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluateArgumentExpressions(XbaseInterpreter.java:767) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._featureCallOperation(XbaseInterpreter.java:712) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) ~[na:na]
	at org.openhab.model.script.interpreter.ScriptInterpreter.internalFeatureCallDispatch(ScriptInterpreter.java:69) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateAbstractFeatureCall(XbaseInterpreter.java:658) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:218) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluateArgumentExpressions(XbaseInterpreter.java:751) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._featureCallOperation(XbaseInterpreter.java:712) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) ~[na:na]
	at org.openhab.model.script.interpreter.ScriptInterpreter.internalFeatureCallDispatch(ScriptInterpreter.java:69) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateAbstractFeatureCall(XbaseInterpreter.java:658) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:218) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateBlockExpression(XbaseInterpreter.java:321) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:218) ~[na:na]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluate(XbaseInterpreter.java:204) ~[na:na]
	at org.openhab.model.script.internal.engine.ScriptImpl.execute(ScriptImpl.java:59) ~[na:na]
	at org.openhab.model.rule.internal.engine.ExecuteRuleJob.execute(ExecuteRuleJob.java:55) ~[na:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-all-2.1.7.jar:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [quartz-all-2.1.7.jar:na]
Caused by: java.lang.IllegalArgumentException: null
	at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeOperation(XbaseInterpreter.java:729) ~[na:na]
	... 62 common frames omitted
```

**Comment by davidlballenger** [comment]
I switched to using Oracle's Java 8 and still have the same problem. Am I missing an import?

**Comment by 9037568** [comment]
I reproduced this problem. It may be related to the issue found in #831.

In my run, I found this in the log, which led me to realize one of the parameters in getAstroSunRiseStart was not of the expected type:
````
    Caused by: java.lang.IllegalArgumentException: argument type mismatch
````

I verified that the call to getAstroSunRiseStart failed as you described if one of the lat/lon values was negative and had been specified thusly:
````
    var double lat = 38.04
    var double lon = -84.50
````

When I changed the negative value to be specified this way, the call was successful:
````
    var double lat = 38.04
    var lon = Double::parseDouble("-84.55")
````
