### ISSUE TITLE
Failed to connect to Hue bridge: HTTP request timed out+Communication error with Insteon Hub @192.168.1.106:25105 java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by lamiastella** [openhab/openhab#4319]
I am getting the following errors for both Philips Hue and Insteon homekit (Dimmer LampLinc) 2245-222 hub. Philips hue was working previously:
```

pi@raspberrypi:/opt/openhab $ sudo ./start.sh 
Launching the openHAB runtime...
osgi> 2016-04-26 02:07:49.115 [INFO ] [.o.core.internal.CoreActivator] - openHAB runtime has been started (v1.8.1).
2016-04-26 02:07:51.906 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl] - mDNS service has been started
2016-04-26 02:07:52.043 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl] - Service Discovery initialization completed.
2016-04-26 02:07:57.227 [INFO ] [penhab.io.rest.RESTApplication] - Started REST API at /rest
2016-04-26 02:08:00.995 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'iotpi.sitemap'
2016-04-26 02:08:01.444 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'rrd4j.persist'
2016-04-26 02:08:01.505 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'logging.persist'
2016-04-26 02:08:01.524 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'db4o.persist'
2016-04-26 02:08:01.538 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'exec.persist'
2016-04-26 02:08:01.659 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'demo.script'
2016-04-26 02:08:01.938 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'iotpi.items'
2016-04-26 02:08:02.910 [INFO ] [.o.u.w.i.servlet.WebAppServlet] - Started Classic UI at /classicui/openhab.app
2016-04-26 02:08:07.179 [INFO ] [.service.AbstractActiveService] - NTP Refresh Service has been started
2016-04-26 02:08:07.180 [INFO ] [insteonplm.InsteonPLMActivator] - Insteon PLM binding has been started.
2016-04-26 02:08:07.359 [INFO ] [.p.rrd4j.internal.RRD4jService] - Removing invalid defintion component = null heartbeat = 0 min/max = 0.0/0.0 step = 0 0 archives(s) = [] 0 items(s) = []
2016-04-26 02:08:07.552 [INFO ] [.service.AbstractActiveService] - HTTP Refresh Service has been started
2016-04-26 02:08:08.091 [WARN ] [.h.internal.hardware.HueBridge] - Failed to connect to Hue bridge: HTTP request timed out.
2016-04-26 02:08:08.093 [INFO ] [.service.AbstractActiveService] - Hue Refresh Service has been started
2016-04-26 02:08:08.099 [WARN ] [.h.internal.hardware.HueBridge] - Failed to connect to Hue bridge: HTTP request timed out.
2016-04-26 02:08:08.100 [WARN ] [inding.hue.internal.HueBinding] - Hue settings were null, maybe misconfigured bridge IP.
2016-04-26 02:08:08.114 [INFO ] [.service.AbstractActiveService] - InsteonHub Refresh Service has been started
2016-04-26 02:08:08.131 [ERROR] [.i.h.a.s.InsteonHubSerialProxy] - Communication error with Insteon Hub @192.168.1.106:25105
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_77]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_77]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_77]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_77]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_77]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_77]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_77]
	at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_77]
	at java.net.Socket.<init>(Socket.java:211) ~[na:1.8.0_77]
	at org.openhab.binding.insteonhub.internal.hardware.api.serial.InsteonHubSerialProxy$Connecter.run(InsteonHubSerialProxy.java:156) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
2016-04-26 02:08:08.133 [INFO ] [.i.h.a.s.InsteonHubSerialProxy] - Will retry connection in 30 seconds...
2016-04-26 02:08:18.105 [WARN ] [.h.internal.hardware.HueBridge] - Failed to connect to Hue bridge: HTTP request timed out.
2016-04-26 02:08:18.107 [WARN ] [inding.hue.internal.HueBinding] - Hue settings were null, maybe misconfigured bridge IP.
2016-04-26 02:08:28.112 [WARN ] [.h.internal.hardware.HueBridge] - Failed to connect to Hue bridge: HTTP request timed out.
2016-04-26 02:08:28.114 [WARN ] [inding.hue.internal.HueBinding] - Hue settings were null, maybe misconfigured bridge IP.
```

Also I have the following in the openhab.cfg file for insteon. Is that wrong?
```
insteonhub:host=192.168.1.106
insteonhub:port=25105
insteonhub:user=the username with which I logon to insteon mobile app
insteonhub:pass=the password with which I logon to insteon mobile app
```

and also in the addons folder I have the following:
```
pi@raspberrypi:/opt/openhab/addons $ ls
org.openhab.binding.http-1.8.1.jar        org.openhab.binding.ntp-1.8.1.jar
org.openhab.binding.hue-1.8.1.jar         org.openhab.persistence.logging-1.8.1.jar
org.openhab.binding.insteonhub-1.8.1.jar  org.openhab.persistence.rrd4j-1.8.1.jar
org.openhab.binding.insteonplm-1.8.1.jar  README.TXT
```

Any help is really appreciated! I found the Insteon IP and port by browsing to the following website:
http://connect.insteon.com/getinfo.asp

**Comment by 9037568** [comment]
You should try posting this question in the [community forum](http://community.openhab.org).
