### ISSUE TITLE
pilight 1.9.0 not running in actual openhab2-online-snapshot

### ISSUE THREAD

**Issue by LukaNoah** [openhab/openhab#4441]
I'm running the actual openhab2-online-snapshot on a pi with jessie. The pilight1.9.0(#1248) addon don't work anymore. I got the following message:

`2016-06-04 15:04:35.214 [ERROR] [nding.AbstractGenericBindingProvider] - Binding org.openhab.binding.pilight.internal.PilightBinding threw an exception: 
java.lang.NullPointerException
	at org.openhab.binding.pilight.internal.PilightBinding.checkItemState(PilightBinding.java:401)[10:org.openhab.binding.pilight:1.9.0.201606040111]
	at org.openhab.binding.pilight.internal.PilightBinding.bindingChanged(PilightBinding.java:369)[10:org.openhab.binding.pilight:1.9.0.201606040111]
	at org.openhab.model.item.binding.AbstractGenericBindingProvider.notifyListeners(AbstractGenericBindingProvider.java:124)[190:org.openhab.core.compat1x:2.0.0.201605220102]
	at org.openhab.model.item.binding.AbstractGenericBindingProvider.addBindingConfig(AbstractGenericBindingProvider.java:118)[190:org.openhab.core.compat1x:2.0.0.201605220102]
	at org.openhab.binding.pilight.internal.PilightGenericBindingProvider.processBindingConfiguration(PilightGenericBindingProvider.java:79)[10:org.openhab.binding.pilight:1.9.0.201606040111]
	at org.openhab.core.binding.internal.BindingConfigReaderDelegate.processBindingConfiguration(BindingConfigReaderDelegate.java:48)[190:org.openhab.core.compat1x:2.0.0.201605220102]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:378)[117:org.eclipse.smarthome.model.item:0.8.0.201605311814]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:350)[117:org.eclipse.smarthome.model.item:0.8.0.201605311814]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:168)[117:org.eclipse.smarthome.model.item:0.8.0.201605311814]
	at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:404)[117:org.eclipse.smarthome.model.item:0.8.0.201605311814]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:201)[116:org.eclipse.smarthome.model.core:0.8.0.201605311814]
	at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:97)[116:org.eclipse.smarthome.model.core:0.8.0.201605311814]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:240)[116:org.eclipse.smarthome.model.core:0.8.0.201605311814]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.notifyUpdateToModelRepo(FolderObserver.java:169)[116:org.eclipse.smarthome.model.core:0.8.0.201605311814]
	at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.updated(FolderObserver.java:150)[116:org.eclipse.smarthome.model.core:0.8.0.201605311814]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1444)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1400)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)[7:org.apache.felix.configadmin:1.8.8]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)[7:org.apache.felix.configadmin:1.8.8]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]`

The items for pilight are not touched since any month's. What can I do?

**Comment by idserda** [comment]
Thanks for reporting this, I'll look into it asap.

**Comment by LukaNoah** [comment]
No Problem ;)

**Comment by LukaNoah** [comment]
No Chance to fix it? I need so much this binding .....

**Comment by idserda** [comment]
Can you try upgrading to the latest nightly of both openHAB2 and of the binding? I wasn't able to reproduce this error when I tried last week.

**Comment by LukaNoah** [comment]
Where ca I found the nightlies ?

**Comment by LukaNoah** [comment]
I have now installed the actual nightly from openhab2 and the pilight-binding, but it doesn't work.
log1 - first run from oh2 without any items, without pilight-binding
log2 - second run of oh2, pilight-binding where active
log3 - third run of oh2, pilight-binding active, all my items active
what's wrong?

[openhab2.zip](https://github.com/openhab/openhab/files/339545/openhab2.zip)

**Comment by LukaNoah** [comment]
next try
- download actual oh2-online
- updated with script from oh2-tools
- start without any configuration -> log1
- add pilight to addons and start oh2 again -> log2
- put my pilight items to items and start oh2 again -> log3
- copy all my config's and mapdb, start oh2 again -> log4
any idea's?
thx

[openhab2_1.zip](https://github.com/openhab/openhab/files/339693/openhab2_1.zip)

**Comment by LukaNoah** [comment]
I got the error. My pilight.cfg was corrupt on the raspberry ;(
Now it works again.

thx for your support.
LN

**Comment by ACE2xxx** [comment]
Hi LukaNoh,
what was corrupt? I'm struggling with the same issue and can't figure it out...
Cheerz
Tony

**Comment by LukaNoah** [comment]
Hi Tony, 
My json.config-file was corrupt. 
File-System was damaged. 

Cu
LN
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 25.02.17, 14:42, ACE2xxx <notifications@github.com> schrieb:

  
    
      Hi LukaNoh,
      what was corrupt? I'm struggling with the same issue and can't figure it out...
      Cheerz
      Tony

**Comment by ACE2xxx** [comment]
Thanks for your reply, but my pilight '.json config seems to be correct and
running!

2017-02-25 22:22 GMT+01:00 LukaNoah <notifications@github.com>:

>
>
> Hi Tony,
> My json.config-file was corrupt.
> File-System was damaged.
>
> Cu
> LN
> --
> Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail
