### ISSUE TITLE
Netatmo Binding - Welcome Camera issue

### ISSUE THREAD

**Issue by RosaEinhorn** [openhab/openhab#4444]
Hi everyone,
I just got a Netatmo Welcome and installed it (already had a weather station).
I followed all the steps of netatmo pre-setup and requested access to the welcome camera, the refresh token seems to work, I could receive updates for the  weather station.
Then I migrated my netatmo binding (apt-get version - I guess 1.8.3) to binding version 1.9.0 SNAPSHOT to make use of the camera.

Unfortunately, when I try to request information of the camera, I am getting the following error:

`Error while executing background thread Netatmo Refresh Service
org.openhab.binding.netatmo.internal.NetatmoException: Could not parse JSON from URL 'https://api.netatmo.net/oauth2/token' content='grant_type=refresh_token&refresh_token=54ac5573485a880b635a364e|68d601d3ce3fff09cba0dda6827d952b&client_id=574b664e2baa3cac1b8b522b&client_secret=zkEPacSmtL3O3sP2BJdcEKTUmTEs72O7&scope=read_station read_camera' json='{"error":"invalid_request"}'
	at org.openhab.binding.netatmo.internal.messages.AbstractRequest.newException(AbstractRequest.java:50) ~[na:na]
	at org.openhab.binding.netatmo.internal.authentication.RefreshTokenRequest.execute(RefreshTokenRequest.java:88) ~[na:na]
	at org.openhab.binding.netatmo.internal.authentication.OAuthCredentials.refreshAccessToken(OAuthCredentials.java:145) ~[na:na]
	at org.openhab.binding.netatmo.internal.NetatmoBinding.execute(NetatmoBinding.java:114) ~[na:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
Caused by: org.codehaus.jackson.map.JsonMappingException: Can not instantiate value of type [simple type, class org.openhab.binding.netatmo.internal.messages.NetatmoError] from JSON String; no single-String constructor/factory method (through reference chain: org.openhab.binding.netatmo.internal.authentication.RefreshTokenResponse["error"])
	at org.codehaus.jackson.map.deser.std.StdValueInstantiator._createFromStringFallbacks(StdValueInstantiator.java:379) ~[na:na]
	at org.codehaus.jackson.map.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:268) ~[na:na]
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromString(BeanDeserializer.java:759) ~[na:na]
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:585) ~[na:na]
	at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299) ~[na:na]
	at org.codehaus.jackson.map.deser.SettableBeanProperty$FieldProperty.deserializeAndSet(SettableBeanProperty.java:579) ~[na:na]
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697) ~[na:na]
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580) ~[na:na]
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2723) ~[na:na]
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1854) ~[na:na]
	at org.openhab.binding.netatmo.internal.authentication.RefreshTokenRequest.execute(RefreshTokenRequest.java:84) ~[na:na]
	... 4 common frames omitted
`

This is how my Item-Configuration looks like:
String Welcome_Home "Home [%s]" (Welcome) {netatmo="camera=5752ee8c49c75f1e618b475e#Name"}
Switch Welcome_P1_AtHome "P1 is home [%s]" (Welcome) {netatmo="camera=if-of-the-house#person-id#OutOfSight"}
Switch Welcome_P2_AtHome "P2 is home [%s]" (Welcome) {netatmo="camera=id-of-the-house#person2-id#OutOfSight"}

Thanks a lot in advance! :-)

**Comment by lolodomo** [comment]
@RosaEinhorn : you should update your previous message to mask your identiants.
I have myself a Welcome camera but I have not yet tested the binding with it. I will do it soon. I will let you know if I encounter the same problem.

**Comment by RosaEinhorn** [comment]
Hi everybody,
after one day I did all the steps from netatmo pre-setup from the wiki page again and made sure that my application has access to the camera. I also requested a new refresh token. After restarting openhab camera access works fine. So this must have been an error with either the application permissions or the refresh token.

**Comment by 9037568** [comment]
Glad to hear you got it working.
