### ISSUE TITLE
[Classic UI] Server Error 500 when using Slider element with Group item

### ISSUE THREAD

**Issue by polarathene** [openhab/openhab#4493]
## Expected Behavior
UI should render without throwing the provided error.

## Current Behavior
Accessing Classic UI with a Slider element mapped to a Group item throws the following error:
```
HTTP ERROR 500

Problem accessing /classicui/app. Reason:

    Server Error
Caused by:

java.lang.NullPointerException
	at org.eclipse.smarthome.ui.classic.internal.render.AbstractWidgetRenderer.getStateAsNumber(AbstractWidgetRenderer.java:192)
	at org.eclipse.smarthome.ui.classic.internal.render.SliderRenderer.renderWidget(SliderRenderer.java:59)
	at org.eclipse.smarthome.ui.classic.internal.render.PageRenderer.renderWidget(PageRenderer.java:166)
	at org.eclipse.smarthome.ui.classic.internal.render.PageRenderer.processChildren(PageRenderer.java:123)
	at org.eclipse.smarthome.ui.classic.internal.render.PageRenderer.processChildren(PageRenderer.java:144)
	at org.eclipse.smarthome.ui.classic.internal.render.PageRenderer.processPage(PageRenderer.java:86)
	at org.eclipse.smarthome.ui.classic.internal.servlet.WebAppServlet.service(WebAppServlet.java:142)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

## Steps to Reproduce (for bugs)
bug.items:
```
Group gBug "Breaks Classic UI when used with Slider element"
// Some item that adds itself to gBug group.
```

bug_sitemap.sitemap:
```
sitemap bug_sitemap label="This won't render"
{
    Slider item=gBug
}
```

1. Use above configs with an item, in my case I used a Color item with Hue Bulb.
2. Try to access the sitemap on Classic UI, get error provided above instead.
3. Try other UIs such as Basic UI or HABmin, these work fine.

## Context
It was a brightness slider, I also have a Switch and ColorPicker using the group(these work fine) to control all hue lights. The slider works fine in other UI, just breaks in Classic. It works fine if I use an actual light item instead of a group item.

## Your Environment

* Version used: openHAB2-beta3 Docker, addons(HABmin2, KNX, Hue, Sonos, ZWave)
* Environment name and version: Chrome 51, Docker 1.11.2, all other environment such as Java provided via official openHAB Docker Image
* Operating System and version: Arch Linux x86_64

**Comment by 9037568** [comment]
The NPE is coming from the first return in this block. Looks like the call to getStateAs(PercentType) is returning null...

StackTrace appears to indicate this is in ESH. Can someone confirm?

```
        protected String getStateAsNumber(Widget w) {
        String itemName = w.getItem();
        if (itemName != null) {
            try {
                Item item = itemUIRegistry.getItem(itemName);
                if (item.getAcceptedDataTypes().contains(PercentType.class)) {
                    return escapeURLPath(item.getStateAs(PercentType.class).toString());
                } else {
                    return escapeURLPath(item.getStateAs(DecimalType.class).toString());
                }
            } catch (ItemNotFoundException e) {
                logger.error("Cannot retrieve item '{}' for widget {}",
                        new Object[] { itemName, w.eClass().getInstanceTypeName() });
            }
        }
        return "NULL";
}
```

**Comment by 9037568** [comment]
Further investigation appears to indicate that the ```item=``` parameter for a Slider is not allowed to be a group reference.

See [this file](https://github.com/eclipse/smarthome/blob/a84caa9b61a0cd689b87c6add2d592dd8d1effa0/bundles/model/org.eclipse.smarthome.model.sitemap/src/org/eclipse/smarthome/model/Sitemap.xtext).

This is my inference; need someone with more experience to confirm...

**Comment by watou** [comment]
> java.lang.NullPointerException  at org.eclipse.smarthome.ui.classic.internal.render.AbstractWidgetRenderer.getStateAsNumber(AbstractWidgetRenderer.java:192)

This issue should be copied to eclipse/smarthome and closed here.

**Comment by polarathene** [comment]
@9037568 I'm still trying to understand how ESH fits in with openHAB2. As this is specific to Classic UI and I had no problem with the slider on Basic UI and others that I could use it on, is it due to the UI itself or OH/ESH? I guess some UIs are designed to not be affected or are calling different APIs where this usage works with those UI?

**Comment by kaikreuzer** [comment]
> I'm still trying to understand how ESH fits in with openHAB2

This image should give you an idea: http://docs.openhab.org/overview.html#openhab-structure

The Classic UI is part of ESH, so the issue indeed must be reported there.

**Comment by 9037568** [comment]
Here's the reason why the classic UI and basic UI respond differently here: the SliderRenderer uses different methods of getting the value.

Classic: snippet = StringUtils.replace(snippet, "%state%", getStateAsNumber(s));
Basic: snippet = StringUtils.replace(snippet, "%state%", itemUIRegistry.getState(s).toString());
