### ISSUE TITLE
Astro Binding throws exception on June 21st.

### ISSUE THREAD

**Issue by juelicher** [openhab/openhab#4530]
```
On June 21st he astro binding threw the following exception, which is probably related to changing from spring to summer:

2016-06-21 00:35:00.059 ERROR org.quartz.core.JobRunShell[:222]- Job Astro.Season threw an unhandled Exception: 
java.lang.NullPointerException: null
	at java.util.Hashtable.put(Hashtable.java:459)
	at org.openhab.core.internal.events.EventPublisherImpl.createUpdateEvent(EventPublisherImpl.java:86)
	at org.openhab.core.internal.events.EventPublisherImpl.postUpdate(EventPublisherImpl.java:78)
	at org.openhab.binding.astro.internal.job.ItemJob.executeJob(ItemJob.java:25)
	at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:45)
--
--
	at org.openhab.core.internal.events.EventPublisherImpl.createUpdateEvent(EventPublisherImpl.java:86)
	at org.openhab.core.internal.events.EventPublisherImpl.postUpdate(EventPublisherImpl.java:78)
	at org.openhab.binding.astro.internal.job.ItemJob.executeJob(ItemJob.java:25)
	at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:45)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)


2016-06-21 00:35:00.098 ERROR org.quartz.core.ErrorLogger[:2361]- Job (Astro.Season threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:224)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
--
	at org.quartz.core.JobRunShell.run(JobRunShell.java:224)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.lang.NullPointerException: null
	at java.util.Hashtable.put(Hashtable.java:459)
	at org.openhab.core.internal.events.EventPublisherImpl.createUpdateEvent(EventPublisherImpl.java:86)
	at org.openhab.core.internal.events.EventPublisherImpl.postUpdate(EventPublisherImpl.java:78)
	at org.openhab.binding.astro.internal.job.ItemJob.executeJob(ItemJob.java:25)
	at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:45)
```

**Comment by watou** [comment]
@gerrieg, could this stacktrace be due to [this line](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/JobScheduler.java#L181 ) which results in scheduling an ItemJob, but there was no item name in the JobDataMap?  Should it not instead schedule a SeasonJob?  It would be great if you could take a look! 🌞

**Comment by gerrieg** [comment]
@watou 
yes you are right. Fixed with https://github.com/openhab/openhab/pull/4536
