### ISSUE TITLE
OpenHAB Rspberry Pi not starting 

### ISSUE THREAD

**Issue by surisetty** [openhab/openhab#4612]
I freshly Installed openhab on Raspberry pi. Not able to start the sererver 

I followed this link for installation 

http://www.instructables.com/id/Installing-OpenHAB-on-Raspberry-Pi/step4/Step-4-Configuration-of-MQTT-broker-connections-MQ/

I got the below error 
-------------------------------------------------------------------------

java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.xtext.resource.XtextResourceSet$1
	at org.eclipse.xtext.resource.XtextResourceSet.getURIConverter(XtextResourceSet.java:170) ~[na:na]
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:136) ~[na:na]
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:23) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.getResource(ModelRepositoryImpl.java:153) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:71) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) ~[na:na]
17:03:05.013 [ERROR] [.o.m.c.i.folder.FolderObserver:105  ] - An unexpected exception has occured
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.xtext.resource.XtextResourceSet$1
	at org.eclipse.xtext.resource.XtextResourceSet.getURIConverter(XtextResourceSet.java:170) ~[na:na]
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:136) ~[na:na]
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:23) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.getResource(ModelRepositoryImpl.java:153) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:71) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) ~[na:na]
17:03:15.065 [ERROR] [.o.m.c.i.folder.FolderObserver:105  ] - An unexpected exception has occured
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.xtext.resource.XtextResourceSet$1
	at org.eclipse.xtext.resource.XtextResourceSet.getURIConverter(XtextResourceSet.java:170) ~[na:na]
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:136) ~[na:na]
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:23) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.getResource(ModelRepositoryImpl.java:153) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:71) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) ~[na:na]
17:03:25.122 [ERROR] [.o.m.c.i.folder.FolderObserver:105  ] - An unexpected exception has occured
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.xtext.resource.XtextResourceSet$1
	at org.eclipse.xtext.resource.XtextResourceSet.getURIConverter(XtextResourceSet.java:170) ~[na:na]
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:136) ~[na:na]
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:23) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.getResource(ModelRepositoryImpl.java:153) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:71) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) ~[na:na]
17:03:35.174 [ERROR] [.o.m.c.i.folder.FolderObserver:105  ] - An unexpected exception has occured
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.xtext.resource.XtextResourceSet$1
	at org.eclipse.xtext.resource.XtextResourceSet.getURIConverter(XtextResourceSet.java:170) ~[na:na]
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:136) ~[na:na]
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:23) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.getResource(ModelRepositoryImpl.java:153) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:71) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) ~[na:na]
17:03:45.249 [ERROR] [.o.m.c.i.folder.FolderObserver:105  ] - An unexpected exception has occured
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.xtext.resource.XtextResourceSet$1
	at org.eclipse.xtext.resource.XtextResourceSet.getURIConverter(XtextResourceSet.java:170) ~[na:na]
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:136) ~[na:na]
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:23) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.getResource(ModelRepositoryImpl.java:153) ~[na:na]
	at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:71) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) ~[na:na]
	at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) ~[na:na]

----------------------------------------------------

What could be the wrong ? Let me know if any more logs required.

**Comment by 9037568** [comment]
You should start by updating to the latest version of OpenHAB.  Then, if
you still have issues, you should post your query in the community forum.
