### ISSUE TITLE
[insteonplm] Does not connect with Insteon Hub 2245-222

### ISSUE THREAD

**Issue by larizzo** [openhab/openhab#4630]
Using binding org.openhab.binding.insteonplm-1.9.0-SNAPSHOT.jar the binding will not connect to my Insteon Hub 2245-222. It is not able to download the modem database or communicate with the hub.

 It does seem to work for the USB PLM as mentioned in this thread [4573](https://github.com/openhab/openhab/pull/4573#issuecomment-238106983) but there is at least one other [person](https://github.com/openhab/openhab/pull/4573#issuecomment-239878895) reporting the same issue as [myself](https://github.com/openhab/openhab/pull/4573#issuecomment-238573507).

This issue is happening in openhab 1.8.3 and OH 2. I've only uploaded the logs for openhab 1.8.3 but I could upload for 2 if needed.

When I drop back to the 1.8.3 binding I have no issue, I'm not exactly sure which PR caused the issue but it wasn't the latest one as I tried the 1.9.0 snapshot from before the PR and have the same issue.

Related converstation: [https://github.com/openhab/openhab/pull/4573](https://github.com/openhab/openhab/pull/4573)

Logs:
[insteonplm-2016-09-08.txt](https://github.com/openhab/openhab/files/462536/insteonplm-2016-09-08.txt)
[openhab-2016-09-08.txt](https://github.com/openhab/openhab/files/462537/openhab-2016-09-08.txt)
##

**Comment by tpett** [comment]
I did a little bit of digging in git to try and help out. Just looking at the diff between v1.8.3 and master is way too much because someone touched pretty much every line in every file when they did some code format cleanup (b85c6575ad8565807a2ee9b6a82e4e4669188c4d). I filtered that commit out though and there aren't that many interesting changes to filter through.

Here are the commands I ran. I don't know if it is possible to do this using Github UI, but it is trivial in git command line:

```
git diff v1.8.3..5a845a94e02e7cf9daf7c0a40ecbdaf898190e43 bundles/binding/org.openhab.binding.insteonplm
git diff 03b62452009363556bcecb7da8e6a97cbf92ef01..master bundles/binding/org.openhab.binding.insteonplm
```

To make things easier I exported patches for each of these diffs and put them in a gist here: https://gist.github.com/tpett/f55d42b7d7f48afeaeb68a0a1416c6c7

I don't know the codebase well enough to spot the problem, but a developer experienced with this binding might know where to dig right away. I hope this helps!

**Comment by larizzo** [comment]
@tpett Wow great work! Hopefully that does help someone spot the difference.

**Comment by watou** [comment]
I read through the entire output of diffing 1.8.3 against master:
```bash
git diff -b --diff-algorithm=minimal v1.8.3..master bundles/binding/org.openhab.binding.insteonplm
```
I did not see a possible problem introduced by renaming OldHubIOStream to TcpIOStream (#4521), or embedding the http client JAR so the binding works on OH2 (#4573) (but a problem with 1.9.0-SNAPSHOT was reported before #4573 was even merged).  

When the code was reformatted after 1.8.3, explicit casts of bytes to ints were removed, and I wonder if this is changing sign extension or having some other side effect.  Some places where this happened:  [here](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java#L195)  and  [here](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java#L246) and [here](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java#L256) and [here](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java#L296) and [here](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java#L297) and [here](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java#L504) and [here](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java#L571) and [here](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/MessageHandler.java#L619)  (there are a few more of these). 

[Here](https://stackoverflow.com/questions/4872206/most-elegant-way-to-convert-a-byte-to-an-int-in-java) is a discussion of the fun of dealing with signed bytes, conversion to and from ints, etc.

**Comment by larizzo** [comment]
I reinstalled OH2 and manually put the jar from [4573](https://github.com/openhab/openhab/pull/4573) and this is what I'm seeing:
2016-09-20 14:41:51.841 [INFO ] [g.insteonplm.InsteonPLMActiveBinding] - dead device timeout set to 3000s
2016-09-20 14:41:51.844 [INFO ] [g.insteonplm.InsteonPLMActiveBinding] - config: port_0 -> /hub2/XXXXXXXX:XXXXXXXX@10.0.0.15:25105,poll_time=1000
2016-09-20 14:41:51.853 [INFO ] [b.core.service.AbstractActiveService] - InsteonPLM has been started
2016-09-20 14:41:51.867 [INFO ] [g.insteonplm.InsteonPLMActiveBinding] - devices:   0 configured,   0 polling, msgs received:     0
2016-09-20 14:41:51.881 [INFO ] [g.insteonplm.InsteonPLMActiveBinding] - config: service.pid -> org.openhab.insteonplm
2016-09-20 14:43:51.987 [WARN ] [onplm.internal.device.ModemDBBuilder] - modem database download unsuccessful, restarting!

 Exception in thread "Thread-43" java.lang.NoSuchMethodError: org.apache.http.impl.client.DefaultHttpClient.execute(Lorg/apache/http/client/methods/HttpUriRequest;)Lorg/apache/http/client/methods/CloseableHttpResponse;
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.getURL(HubIOStream.java:213)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.bufferStatus(HubIOStream.java:108)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.poll(HubIOStream.java:156)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.run(HubIOStream.java:226)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "/hub2/Thomas50:Hsa30lnM@10.0.0.15:25105,poll_time=1000 Writer" java.lang.NoSuchMethodError: org.apache.http.impl.client.DefaultHttpClient.execute(Lorg/apache/http/client/methods/HttpUriRequest;)Lorg/apache/http/client/methods/CloseableHttpResponse;
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.getURL(HubIOStream.java:213)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.bufferStatus(HubIOStream.java:108)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.poll(HubIOStream.java:156)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.write(HubIOStream.java:139)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream$HubOutputStream.flushBuffer(HubIOStream.java:308)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream$HubOutputStream.write(HubIOStream.java:302)
        at java.io.OutputStream.write(Unknown Source)
        at org.openhab.binding.insteonplm.internal.driver.IOStream.write(IOStream.java:67)
        at org.openhab.binding.insteonplm.internal.driver.Port$IOStreamWriter.run(Port.java:421)
        at java.lang.Thread.run(Unknown Source)

**Comment by watou** [comment]
@larizzo [This report](https://github.com/openhab/openhab/pull/4573#issuecomment-238106983) showed success with it, so I'm wondering if somehow you have a different JAR running.  Could you `bundle:list` to see which one it is, `bundle:uninstall` it if it might be the wrong one, and put the test JAR in your addons folder?

**Comment by larizzo** [comment]
@watou It's not clear if he's using the usb/serial plm though he never mentioned what he's actually using. @bradleywehmeier Can you confirm if you are using a Insteon Hub and which one?

bundle:list shows no insteon binding because I manually put in in the addons folder. I'm sure I grab the jar you put in the fix but I just deleted it and re-downloaded it just in case and I still doesn't download the database. I'd love for the issue to be on my side but I just don't know what else to try... It should be straight forward.

**Comment by watou** [comment]
I think the test JAR I supplied was dated back in August?  Could you bundle:uninstall 198 and then add the test JAR to your addons folder?

**Comment by larizzo** [comment]
I just tried with the latest nightly also:
```
openhab> bundle:list |grep -i inste
196 | Active   |  80 | 1.9.0.201609200111    | openHAB Insteon PLM Binding
openhab> [Fatal Error] :1:3: The markup in the document preceding the root element must be well-formed.
[Fatal Error] :1:3: The markup in the document preceding the root element must be well-formed.
Exception in thread "Thread-43" java.lang.NoSuchMethodError: org.apache.http.impl.client.DefaultHttpClient.execute(Lorg/apache/http/client/methods/HttpUriRequest;)Lorg/apache/http/client/methods/CloseableHttpResponse;
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.getURL(HubIOStream.java:213)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.bufferStatus(HubIOStream.java:108)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.poll(HubIOStream.java:156)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.run(HubIOStream.java:226)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "/hub2/Thomas50:Hsa30lnM@10.0.0.15:25105,poll_time=1000 Writer" java.lang.NoSuchMethodError: org.apache.http.impl.client.DefaultHttpClient.execute(Lorg/apache/http/client/methods/HttpUriRequest;)Lorg/apache/http/client/methods/CloseableHttpResponse;
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.getURL(HubIOStream.java:213)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.bufferStatus(HubIOStream.java:108)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.poll(HubIOStream.java:156)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.write(HubIOStream.java:139)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream$HubOutputStream.flushBuffer(HubIOStream.java:308)
        at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream$HubOutputStream.write(HubIOStream.java:302)
        at java.io.OutputStream.write(Unknown Source)
        at org.openhab.binding.insteonplm.internal.driver.IOStream.write(IOStream.java:67)
        at org.openhab.binding.insteonplm.internal.driver.Port$IOStreamWriter.run(Port.java:421)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by watou** [comment]
Hi @larizzo, I think I took a positive report of the test JAR as meaning my change had made the binding work, but I think that user wasn't exercising the part of the code that mattered.  Please try [this test JAR](https://dl.dropboxusercontent.com/u/4286376/insteonplm-http-libs-2/org.openhab.binding.insteonplm-1.9.0-SNAPSHOT.jar) which has grown in size, but is more likely to work for you.

**Comment by larizzo** [comment]
@watou I tried that and I'm getting a different error maybe I'm missing a dependency?

```
openhab> bundle:list |grep -i inste
198 | Resolved |  80 | 1.9.0.201609220638    | openHAB Insteon PLM Binding

2016-09-22 07:35:54.294 [INFO ] [org.openhab.binding.insteonplm      ] - FrameworkEvent INFO - org.openhab.binding.insteonplm
org.osgi.framework.BundleException: The bundle class path entry "lib/httpmime-4.1.3.jar." could not be found for the bundle "osgi.identity; osgi.identity="org.openhab.binding.insteonplm"; type="osgi.bundle"; version:Version="1.9.0.201609220638""
2016-09-22 07:36:01.176 [ERROR] [org.openhab.binding.insteonplm      ] - FrameworkEvent ERROR - org.openhab.binding.insteonplm
Caused by: java.lang.ClassNotFoundException: org.openhab.binding.insteonplm.InsteonPLMActivator cannot be found by org.openhab.binding.insteonplm_1.9.0.201609220638
```

**Comment by bradleywehmeier** [comment]
I have both versions of the hub but I was pretty sure my test was against the newer 2245-222 over an HTTP connection. I had some issues getting the JAR loaded at first too so maybe I screwed that up. When I get a chance I will re-test.

**Comment by watou** [comment]
@larizzo Sorry it's still having issues.  I'm sadly very short on time these days but I will look again as soon as I can.

@bradleywehmeier Your re-test would be very helpful; thanks!

**Comment by tpett** [comment]
@watou I think I found a typo in the META-INF/MANIFEST.MF

```
23 Bundle-ClassPath: lib/httpclient-4.1.3.jar,lib/httpclient-cache-4.1.3.
24  jar,lib/httpcore-4.1.4.jar,lib/httpmime-4.1.3.jar.
```

I think that trailing `.` on line 24 is causing the issues. I tried removing that `.` and loading the JAR by typing `bundle:install file:///opt/openhab2/addons/org.openhab.binding.insteonplm-1.9.0-SNAPSHOT.jar` followed by a `bundle:start XXX`, but I think I'm screwing something up along the way. It silently loads ands starts without failure, but then nothing happens. Also the `bundle:list` command output shows that it wasn't able to read the meta info properly:

```
202 | Active   |  80 |                       | file:///opt/openhab2/addons/org.openhab.binding.insteonplm-1.9.0-SNAPSHOT.jar
```

Let me know if there's anything I can do to help debug. Thanks!

**Comment by watou** [comment]
Thanks @tpett for your looking it over.  You are right; I had forgotten a comma. I've now fixed the JAR [at this link](https://dl.dropboxusercontent.com/u/4286376/insteonplm-http-libs-2/org.openhab.binding.insteonplm-1.9.0-SNAPSHOT.jar), so please try it again.  Sorry for missing that before!

**Comment by larizzo** [comment]
Thanks @watou for continuing to work on this! I'm getting a different error it's posted below:

```
openhab> bundle:list |grep -i inste
196 | Active   |  80 | 1.9.0.201609230624    | openHAB Insteon PLM Binding

openhab.log:
2016-09-23 07:32:35.038 [INFO ] [nding.insteonplm.InsteonPLMActivator] - Insteon PLM binding has been started.
2016-09-23 07:32:35.223 [INFO ] [g.insteonplm.InsteonPLMActiveBinding] - dead device timeout set to 3000s
2016-09-23 07:32:35.229 [INFO ] [g.insteonplm.InsteonPLMActiveBinding] - config: port_0 -> /hub2/XXXXXXX:XXXXXXX@10.0.0.15:25105,poll_time=1000
2016-09-23 07:32:35.239 [INFO ] [b.core.service.AbstractActiveService] - InsteonPLM has been started
2016-09-23 07:32:35.253 [INFO ] [g.insteonplm.InsteonPLMActiveBinding] - devices:   0 configured,   0 polling, msgs received:     0
2016-09-23 07:32:35.281 [INFO ] [g.insteonplm.InsteonPLMActiveBinding] - config: service.pid -> org.openhab.insteonplm
2016-09-23 07:32:35.326 [ERROR] [org.apache.felix.configadmin] - [org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService, id=290, bundle=196/file:/opt/openhab2/addons/org.openhab.binding.insteonplm-1.9.0-SNAPSHOT.jar]: Unexpected problem updating configuration org.openhab.insteonplm
java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
at org.apache.http.impl.client.AbstractHttpClient.<init>(AbstractHttpClient.java:182)
at org.apache.http.impl.client.DefaultHttpClient.<init>(DefaultHttpClient.java:150)
at org.openhab.binding.insteonplm.internal.driver.hub.HubIOStream.open(HubIOStream.java:72)
at org.openhab.binding.insteonplm.internal.driver.Port.start(Port.java:153)
at org.openhab.binding.insteonplm.internal.driver.Driver.startAllPorts(Driver.java:103)
at org.openhab.binding.insteonplm.InsteonPLMActiveBinding.initialize(InsteonPLMActiveBinding.java:379)
at org.openhab.binding.insteonplm.InsteonPLMActiveBinding.updated(InsteonPLMActiveBinding.java:276)
at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[7:org.apache.felix.configadmin:1.8.8]
at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[7:org.apache.felix.configadmin:1.8.8]
at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[7:org.apache.felix.configadmin:1.8.8]
at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1444)[7:org.apache.felix.configadmin:1.8.8]
at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1400)[7:org.apache.felix.configadmin:1.8.8]
at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)[7:org.apache.felix.configadmin:1.8.8]
at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)[7:org.apache.felix.configadmin:1.8.8]
at java.lang.Thread.run(Unknown Source)[:1.8.0_92]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory cannot be found by org.openhab.binding.insteonplm_1.9.0.201609230624
at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
at java.lang.ClassLoader.loadClass(Unknown Source)[:1.8.0_92]
... 15 more
```

**Comment by billmans** [comment]
Hello @larizzo 

Any chance you got this working on OH2?  I have tried and I am getting the same errors you report?  Any solution or way to get this working in OH2 at the moment?

B

**Comment by robnielsen** [comment]
This defect is fixed and can be closed.

**Comment by jonni83** [comment]
I have an Insteon Hub 2245-222.  I have a fresh install of Ubuntu and Openhab 2 (unstable).  I installed the Insteon PLM Binding (v1.9.0.5) through the Paper UI.  When I navigate to "Configuration > Bindings" Insteon does not show up.  The log files only show: 

```
[INFO ] [nding.insteonplm.InsteonPLMActivator ] - Insteon PLM binding has been started.
[INFO ] [smarthome.event.ExtensionEvent           ] - Extension 'binding-insteonplm1' has been installed.
```

Maybe the update isn't available in the unstable channel yet?  I'd love to do some testing on this!  In contrast, I installed the Sonos Binding, and it shows up in the Configuration Bindings page without any issues.

**Comment by robnielsen** [comment]
You need to manually configure it from the command line, not via the Paper UI.

**Comment by jonni83** [comment]
Thanks for the reply!  I know this isn't the proper forum to ask, but do you have any suggestions for documentation on the do's and don'ts of making configs for openhab2?

**Comment by robnielsen** [comment]
http://docs.openhab.org/ or https://community.openhab.org/

**Comment by jonni83** [comment]
hah! you're funny.  I've looked all over without much luck.  I'm sure it's there, hiding in plain sight.  I guess I'll just have to wait for the newb fog to wear off.

**Comment by watou** [comment]
Find, or create insteonplm.cfg as described in wiki but without the `insteonplm:` prefixes in the file.

**Comment by jonni83** [comment]
Thank you, kind sir!

**Comment by jonni83** [comment]
Is v1.9.0.5b5 the latest build?  I'm not sure how to verify.
