### ISSUE TITLE
Sitemap formatting not updating when items change OH2 build 469

### ISSUE THREAD

**Issue by swampyclark** [openhab/openhab#4631]
Items on the sitemap loose their formatting when the underlying item changes.  Setpoint broke with some browsers.

All from a clean install of offline build Snapshot2.0.0 build 469

I read something on the forums that made it sound like this was fixed but its not.

items
Number  t "time [MAP(time.map):%s]"
DateTime Date "Date and Time: [%1$tA, %1$td.%1$tm.%1$tY %1$tT]" <calendar>{mqtt=">[MQB:Time:state:*:${state}]", channel="ntp:ntp:local:dateTime" }

sitemap
Setpoint item=t minValue=0 maxValue=1440 step=1
Text item=Date

part of map

0=00:00
1=00:01
2=00:02
3=00:03
4=00:04
5=00:05
6=00:06
7=00:07

Using Crome Win 10  Refreshing the page displays the correct format
Time before and after NTP update
Setpoint before and after click 
![screenshot 404](https://cloud.githubusercontent.com/assets/22090230/18374430/cbf8149a-761a-11e6-801f-462efcc2fcb9.png)

![screenshot 405](https://cloud.githubusercontent.com/assets/22090230/18374429/cbf7b018-761a-11e6-9689-1ee3737faf73.png)

![screenshot 406](https://cloud.githubusercontent.com/assets/22090230/18374432/cbf993d8-761a-11e6-8fc5-0b493c942e69.png)

![screenshot 407](https://cloud.githubusercontent.com/assets/22090230/18374431/cbf95b3e-761a-11e6-846b-755cb445f944.png)

On Android app
Time formatting works correctly and the setpoint does not work at all

On Microsoft Edge
Time looses format and setpoint throws error and warning
2016-09-08 22:56:10.573 [ERROR] [ersey.server.ServerRuntime$Responder] - An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: org.eclipse.jetty.io.EofException
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:92)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:329)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)[149:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)[149:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)[149:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)[149:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)[149:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)[11:com.eclipsesource.jaxrs.publisher:5.3.1.201602281253]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)[79:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[79:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)[165:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[77:org.eclipse.jetty.security:9.2.14.v20151106]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)[165:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[79:org.eclipse.jetty.servlet:9.2.14.v20151106]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[165:org.ops4j.pax.web.pax-web-jetty:4.2.4]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.Server.handle(Server.java:499)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[70:org.eclipse.jetty.io:9.2.14.v20151106]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[81:org.eclipse.jetty.util:9.2.14.v20151106]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[81:org.eclipse.jetty.util:9.2.14.v20151106]
	at java.lang.Thread.run(Unknown Source)[:1.8.0_73]
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)[70:org.eclipse.jetty.io:9.2.14.v20151106]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)[70:org.eclipse.jetty.io:9.2.14.v20151106]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302)[70:org.eclipse.jetty.io:9.2.14.v20151106]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129)[70:org.eclipse.jetty.io:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:694)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246)[81:org.eclipse.jetty.util:9.2.14.v20151106]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208)[81:org.eclipse.jetty.util:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:471)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:763)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:801)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:147)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:140)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:383)[78:org.eclipse.jetty.server:9.2.14.v20151106]
	at java.io.OutputStream.write(Unknown Source)[:1.8.0_73]
	at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.write(ResponseWriter.java:320)[149:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
	at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:218)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:294)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
	at com.eclipsesource.jaxrs.provider.gson.GsonProvider.writeTo(GsonProvider.java:69)[10:com.eclipsesource.jaxrs.provider.gson:2.3.0.201506221200]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:106)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)[151:org.glassfish.jersey.core.jersey-common:2.22.2]
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:86)[152:org.glassfish.jersey.core.jersey-server:2.22.2]
	... 41 more
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.writev0(Native Method)[:1.8.0_73]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source)[:1.8.0_73]
	at sun.nio.ch.IOUtil.write(Unknown Source)[:1.8.0_73]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source)[:1.8.0_73]
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:172)[70:org.eclipse.jetty.io:9.2.14.v20151106]
	... 64 more
2016-09-08 22:56:12.097 [WARN ] [thome.io.rest.core.item.ItemResource] - Received HTTP POST request at 'items/t' with an invalid status value 'NaN'.

**Comment by 9037568** [comment]
This would appear to be an Smarthome or OH2 problem.
