### ISSUE TITLE
JDBC Persistence tries to store switch as number item

### ISSUE THREAD

**Issue by juelicher** [openhab/openhab#4660]
This is I strange problem, I observed a few days ago, but now I am able to reproduce it in a test installation (obenHAB 1.8.3 with the snapshot of the JDBC persistence biding)

I have an item with the following definition:
`Steckdosen_Bibliothek_Heizung_II    "Bibliothek Heizung II"    (gBibliothek, gSteckdosen_EG)       { knx="5/1/203+<5/7/203" }`

Persistence definition for JDBC for this item:

```
strategies {
    // for rrd charts, we need a cron strategy
    everyMinute : "0 * * * * ?"
    everyDay    : "0 0 0 * * ?"
}
...
gBibliothek*: strategy = everyChange, everyDay
...
```

This night at 1s past midnight everything was fine:

```
2016-09-23 00:00:01.325 DEBUG o.o.p.jdbc.internal.JdbcMapper[:134]- JDBC::storeItemValue: Item=Steckdosen_Bibliothek_Heizung_II (Type=SwitchItem, State=OFF)
2016-09-23 00:00:01.325 DEBUG o.o.p.jdbc.internal.JdbcMapper[:240]- JDBC::getTable: no Table found for itemName=Steckdosen_Bibliothek_Heizung_II in sqlTables
2016-09-23 00:00:01.325 DEBUG o.o.p.jdbc.internal.JdbcMapper[:73]- JDBC::createNewEntryInItemsTable
2016-09-23 00:00:01.325 DEBUG o.o.p.jdbc.db.JdbcBaseDAO[:275]- JDBC::doCreateNewEntryInItemsTable sql=INSERT INTO items (ItemName) VALUES ('Steckdosen_Bibliothek_Heizung_II')
2016-09-23 00:00:01.331 DEBUG o.o.p.jdbc.internal.JdbcMapper[:251]- JDBC::getTable: getTableName with rowId=123 itemName=Steckdosen_Bibliothek_Heizung_II
2016-09-23 00:00:01.332 DEBUG o.o.p.jdbc.db.JdbcBaseDAO[:561]- JDBC::getItemType: Try to use ItemType SWITCHITEM for Item Steckdosen_Bibliothek_Heizung_II
2016-09-23 00:00:01.332 DEBUG o.o.p.jdbc.model.ItemVO[:38]- JDBC:ItemVO tableName=item0123; newTableName=Steckdosen_Bibliothek_Heizung_II; 
2016-09-23 00:00:01.332 DEBUG o.o.p.jdbc.internal.JdbcMapper[:126]- JDBC::createItemTable
2016-09-23 00:00:01.338 DEBUG o.o.p.jdbc.internal.JdbcMapper[:265]- JDBC::getTable: Table created for item 'Steckdosen_Bibliothek_Heizung_II' with dataType VARCHAR(6) in SQL database.
2016-09-23 00:00:01.339 DEBUG o.o.p.jdbc.model.ItemVO[:38]- JDBC:ItemVO tableName=item0123; newTableName=null; 
2016-09-23 00:00:01.339 DEBUG o.o.p.jdbc.db.JdbcBaseDAO[:561]- JDBC::getItemType: Try to use ItemType SWITCHITEM for Item Steckdosen_Bibliothek_Heizung_II
2016-09-23 00:00:01.339 DEBUG o.o.p.jdbc.db.JdbcBaseDAO[:398]- JDBC::storeItemValueProvider: item 'Steckdosen_Bibliothek_Heizung_II' as Type 'SWITCHITEM' in 'item0123' with state 'OFF'
2016-09-23 00:00:01.339 DEBUG o.o.p.jdbc.db.JdbcBaseDAO[:402]- JDBC::storeItemValueProvider: getState: 'OFF'
2016-09-23 00:00:01.339 DEBUG o.o.p.jdbc.model.ItemVO[:47]- JDBC:ItemVO setValueTypes dbType=VARCHAR(6); javaType=class java.lang.String;
2016-09-23 00:00:01.339 DEBUG o.o.p.jdbc.db.JdbcBaseDAO[:458]- JDBC::storeItemValueProvider: other: item.getState().toString(): 'OFF'
2016-09-23 00:00:01.339 DEBUG o.o.p.jdbc.db.JdbcSqliteDAO[:100]- JDBC::doStoreItemValue sql=INSERT OR IGNORE INTO item0123 (TIME, VALUE) VALUES( strftime('%Y-%m-%d %H:%M:%f' , 'now' , 'localtime'), CAST( ? as VARCHAR(6)) ) value='OFF'
2016-09-23 00:00:01.342 DEBUG o.o.p.j.i.JdbcPersistenceService[:134]- JDBC: Stored item 'Steckdosen_Bibliothek_Heizung_II' as 'OFF' in SQL database at Fri Sep 23 00:00:01 CEST 2016 in 17ms.
```

This entry is written correctly to the database:
`2016-09-23 00:00:01.339 OFF`

A second later the item is persisted again (I don't know why) and an exception is thrown, as the binding tries to persist it as a number value:

```
2016-09-23 00:00:02.453 DEBUG o.o.p.jdbc.internal.JdbcMapper[:134]- JDBC::storeItemValue: Item=Steckdosen_Bibliothek_Heizung_II (Type=NumberItem, State=OFF)
2016-09-23 00:00:02.453 DEBUG o.o.p.jdbc.model.ItemVO[:38]- JDBC:ItemVO tableName=item0123; newTableName=null; 
2016-09-23 00:00:02.454 DEBUG o.o.p.jdbc.db.JdbcBaseDAO[:561]- JDBC::getItemType: Try to use ItemType NUMBERITEM for Item Steckdosen_Bibliothek_Heizung_II
2016-09-23 00:00:02.454 DEBUG o.o.p.jdbc.db.JdbcBaseDAO[:398]- JDBC::storeItemValueProvider: item 'Steckdosen_Bibliothek_Heizung_II' as Type 'NUMBERITEM' in 'item0123' with state 'OFF'
2016-09-23 00:00:02.454 DEBUG o.o.p.jdbc.db.JdbcBaseDAO[:402]- JDBC::storeItemValueProvider: getState: 'OFF'
2016-09-23 00:00:02.454 DEBUG o.o.p.jdbc.model.ItemVO[:47]- JDBC:ItemVO setValueTypes dbType=DOUBLE; javaType=class java.lang.Double;
2016-09-23 00:00:02.455 ERROR org.quartz.core.JobRunShell[:222]- Job jdbc.everyDay threw an unhandled Exception: 
java.lang.ClassCastException: org.openhab.core.library.types.OnOffType cannot be cast to org.openhab.core.library.types.DecimalType
    at org.openhab.persistence.jdbc.db.JdbcBaseDAO.storeItemValueProvider(JdbcBaseDAO.java:410)
    at org.openhab.persistence.jdbc.db.JdbcSqliteDAO.doStoreItemValue(JdbcSqliteDAO.java:95)
    at org.openhab.persistence.jdbc.internal.JdbcMapper.storeItemValue(JdbcMapper.java:141)
    at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.store(JdbcPersistenceService.java:133)
    at org.openhab.core.persistence.internal.PersistItemsJob.execute(PersistItemsJob.java:55)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
2016-09-23 00:00:02.457 ERROR org.quartz.core.ErrorLogger[:2361]- Job (jdbc.everyDay threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
    at org.quartz.core.JobRunShell.run(JobRunShell.java:224)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.lang.ClassCastException: org.openhab.core.library.types.OnOffType cannot be cast to org.openhab.core.library.types.DecimalType
    at org.openhab.persistence.jdbc.db.JdbcBaseDAO.storeItemValueProvider(JdbcBaseDAO.java:410)
    at org.openhab.persistence.jdbc.db.JdbcSqliteDAO.doStoreItemValue(JdbcSqliteDAO.java:95)
    at org.openhab.persistence.jdbc.internal.JdbcMapper.storeItemValue(JdbcMapper.java:141)
    at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.store(JdbcPersistenceService.java:133)
    at org.openhab.core.persistence.internal.PersistItemsJob.execute(PersistItemsJob.java:55)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
2016-09-23 00:00:05.466 INFO  o.o.b.f.i.FritzboxTr064Binding[:230]- Callmonitor Thread [1344] attempting connection to FritzBox on 192.168.10.45:1012..
2016-09-23 00:00:05.467 INFO  o.o.b.f.i.FritzboxTr064Binding[:246]- Connected to FritzBox on 192.168.10.45:1012
2016-09-23 00:00:50.133 ERROR o.o.m.r.i.e.ExecuteRuleJob[:57]- Error during the execution of rule Test to long rule
java.lang.RuntimeException: The name 'RRolladen_Schlafen_vorne_Tuer' cannot be resolved to an item or type.
    at org.openhab.model.script.interpreter.ScriptInterpreter.internalFeatureCallDispatch(ScriptInterpreter.java:67)
    at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateAbstractFeatureCall(XbaseInterpreter.java:658)
    at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291)
```

The item, which is persisted immediately before the error was a number item, maybe this is no coincidence?

This error occurs only once, although I have several similar switch items in the groups in question.

A few days ago I observed it with an other item in my productive system. If I am not mistaken, the item which was persisted before the error was a number item too. In my productive system it also  occurred during the daily persistence at midnight, there was no error during the day, although I have a lot of switch items which change during the day.

In my productive system I also observed a database locked error, which might or might not be related:

```
016-09-19 00:00:09.534 ERROR org.knowm.yank.Yank[:432]- Error in SQL query!!!
            java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked) Query: INSERT OR IGNORE INTO Item124 (TIME, VALUE) VALUES( DATETIME('now'), CAST( ? as VARCHAR(6)) ) Parameters: [OFF]
                at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:392)
                at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:491)
                at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:457)
                at org.knowm.yank.Yank.execute(Yank.java:136)
                at org.openhab.persistence.jdbc.db.JdbcSqliteDAO.doStoreItemValue(JdbcSqliteDAO.java:88)
                at org.openhab.persistence.jdbc.internal.JdbcMapper.storeItemValue(JdbcMapper.java:134)
```
##

**Comment by watou** [comment]
@lewie, any thoughts on this strange issue?

**Comment by juelicher** [comment]
A little update: Tonight the exactly same behavior with the same item "Steckdosen_Bibliothek_Heizung_II". All other items are fine.

**Comment by lewie** [comment]
Some thoughts: 
1. When the database file is locked this could be a performance problem.
2. When there are other Errors in Scripts around, java has to handle a lot off things at the same time.
3. Same Item, only at night at around 00:00:00 any not working Script?

Alternatively test it with h2 and/or HSQLDB database if this effect is the same?!

No direct Idea... :-(

**Comment by juelicher** [comment]
Hi, 

I have done some debugging on my test system, but I am still not able to find the cause of the problem. In fact I am not even sure, if it is an JDBC problem, or an problem with the underlying openhab core. I added some logging to getItemType(Item i) in JsbcBaseDOA.java, beside others a 
`logger.debug("JDBC::getItemType: !!!! 6- Persisting item {}", item.toString());`

Even that writes the wrong item type to the log:
`2016-10-03 00:00:01.624 DEBUG o.o.p.jdbc.db.JdbcBaseDAO[:520]- JDBC::getItemType: !!!! 6- Persisting item Steckdosen_Bibliothek_Heizung_I (Type=NumberItem, State=OFF)`

If I am understanding the code correctly, item.toString is a function from the underlying openhab core?! 

My next test will be to remove the items in question from all groups and define persistence for them directly. I already tested creating new tables in the database and moving the table in the database.

By the way: I do not know, why the item which caused the problem has changed from Steckdosen_Bibliothek_Heizung_II to Steckdosen_Bibliothek_Heizung_I, this happened after a restart during my tests.

To answer your questions:

> 1. When the database file is locked this could be a performance problem.

That might be possible, although my test system runs on a quite capable  system. Maybe this might be related to locking performed by SQLite. I have not seen this error in the last few days and I do not believe, that booth errors are related.

> 2. When there are other Errors in Scripts around, java has to handle a lot off things at the same time.

No other errors but because of the "once a day" rule, there are a lot of items persisted at this time.

> Same Item, only at night at around 00:00:00 any not working Script?

Yes, it is always the same item it it is always at during the "once a day" persistence. But I could try to change the item more often and see if I can provoke the error.

> Alternatively test it with h2 and/or HSQLDB database if this effect is the same?!

Currently I am using db4o and mysql (with the mysql binding), but I could try to use jdbc with one of the other databases. I have to check, how to install them on my mac, therefore the tests will take a few days until I find the time.

**Comment by juelicher** [comment]
I did some more testing and I am sorry, but the problem was probably completely my  fault. Because of an Copy & Paste error in my items definition the two items Steckdosen_Bibliothek_Heizung_I and Steckdosen_Bibliothek_Heizung_II were defined twice, a switch and  additionally as a number item.

I do not know, why I missed this, I was sure, that I checked the definition and why I never noticed any problems (I added booth items more than a year ago and could use switch the outlets without any problem). Also no other persistence service or the designer reported an error (With these items I am using mysql and db4o).

So after all, the JDBC binding seems to handle things a bit different from the other persistence services, but the bug was on my side. 

After changing the definition there where no more "cast" errors, only the "database locked" problem remains once in a while, interestingly not at midnight, when a lot of items are persisted, but at random times. If I find some time I will try some more debugging.

Sorry again!

**Comment by lewie** [comment]
@juelicher, I think you can close this now?! ;-)

**Comment by juelicher** [comment]
Yes, as I wrote, this was caused by a bug in my configuration and not by the binding.

I am quite surprised, that I never got an error with this configuration, the bug was present for more than a year, but that clearly is out of the scope of the persistence services.

Thanks again for all your help!
