### ISSUE TITLE
NoClassDefFoundError: org/openhab/core/library/types/OnOffType

### ISSUE THREAD

**Issue by otbe** [openhab/openhab#4661]
Hi

I recently upgraded my openhab2 installation from 2.0.0~20160906221424 to 2.0.0~20160923010346. Since this time I get the following exception on every usage of a Switch item:

```
2016-09-24 13:39:06.062 [ERROR] [ore.internal.events.OSGiEventManager] - Dispatching/filtering event for subscriber 'org.eclipse.smarthome.core.events.EventSubscriber' failed: java.lang.NoClassDefFoundError: org/openhab/core/library/types/OnOffType
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/openhab/core/library/types/OnOffType
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_101]
...
```

I use the openhab2-online package on a raspberry 2 (raspbian).
All seems to work very well but this exceptions makes me a bit nervous :)

Thanks!

**Comment by kaikreuzer** [comment]
Would you have a few more lines of the stacktrace, so that we can see, which code actually throws this exception? What binding do you have installed and does the message go away if you deinstall them?

**Comment by kaikreuzer** [comment]
Btw, in general you should better report such issues at https://github.com/openhab/openhab-distro/issues (unless they are clearly related to an OH1 add-on).

**Comment by otbe** [comment]
This is the full stacktrace. I cant see any specific binding, so I dont tried to uninstall some OH1 bindings...
```
2016-09-24 18:15:38.369 [ERROR] [ore.internal.events.OSGiEventManager] - Dispatching/filtering event for subscriber 'org.eclipse.smarthome.core.events.EventSubscriber' failed: java.lang.NoClassDefFoundError: org/openhab/core/library/types/OnOffType
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/openhab/core/library/types/OnOffType
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_101]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_101]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:186)[96:org.eclipse.smarthome.core:0.9.0.201609151119]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:79)[96:org.eclipse.smarthome.core:0.9.0.201609151119]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:63)[96:org.eclipse.smarthome.core:0.9.0.201609151119]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager.dispatchESHEvent(OSGiEventManager.java:188)[96:org.eclipse.smarthome.core:0.9.0.201609151119]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:163)[96:org.eclipse.smarthome.core:0.9.0.201609151119]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager.handleEvent(OSGiEventManager.java:146)[96:org.eclipse.smarthome.core:0.9.0.201609151119]
	at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415)[3:org.apache.karaf.services.eventadmin:4.0.4]
	at org.apache.felix.eventadmin.impl.tasks.HandlerTask.run(HandlerTask.java:90)[3:org.apache.karaf.services.eventadmin:4.0.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: org/openhab/core/library/types/OnOffType
	at org.openhab.core.compat1x.internal.TypeMapper.mapToOpenHABType(TypeMapper.java:43)
	at org.openhab.core.events.internal.EventBridge.constructProperties(EventBridge.java:101)
	at org.openhab.core.events.internal.EventBridge.receive(EventBridge.java:135)
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:177)
	... 4 more
```

**Comment by kaikreuzer** [comment]
I have honestly no clue on how this could happen. I would assume that this issue is due to the upgrade. Could you try wiping your userdata/cache folder to see if this makes a difference?

**Comment by otbe** [comment]
I always execute this script before upgrading:
```
#!/bin/bash

USER_DATA=/var/lib/openhab2
RUNTIME=/usr/share/openhab2/runtime

rm -rf $RUNTIME
rm -r $USER_DATA/tmp/*
rm -r $USER_DATA/cache/*
```

But I think this issue can be closed...after a restart (of the PI) the exception is gone.
