### ISSUE TITLE
Installation of persistence-jdbc-postgresql-1.9.0.b4 via PaperUI fails

### ISSUE THREAD

**Issue by brstein** [openhab/openhab#4682]
As suggested by kaikreuzer this issue was moved here from https://github.com/openhab/openhab2-addons/issues/1293

Test setup: Genuine freshly unzipped v2.0.0.b4 #477 (offline). Only change in conf/services/jdbc.cfg: Adding of the database parameters:

`url=jdbc:postgresql://localhost:5432/hab2`
`user=hab`
`password=xxx`

Installing persistence-jdbc-postgresql-1.9.0.b4 via PaperUI > Extensions > Persistence > JDBC Persistence PostgreSQL > Install

The installation does not complete (The wait icon remains spinning) and the log states the following exception:

`[ERROR] [st.core.extensions.ExtensionResource] - Exception while installing extension: org.apache.karaf.features.internal.util.MultiException: Error restarting bundles`

Afterwards when restarting openhab the following exception appears in the log:

`[ERROR] [org.postgresql.jdbc41               ] - FrameworkEvent ERROR - org.postgresql.jdbc41
org.osgi.framework.BundleException: Exception in org.postgresql.osgi.PGBundleActivator.start() of bundle org.postgresql.jdbc41.
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:792)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.Module.doStart(Module.java:571)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.Module.start(Module.java:439)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
Caused by: java.lang.NoClassDefFoundError: org/osgi/service/jdbc/DataSourceFactory
        at org.postgresql.osgi.PGBundleActivator.start(PGBundleActivator.java:32)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_91]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        ... 12 more
Caused by: java.lang.ClassNotFoundException: org.osgi.service.jdbc.DataSourceFactory cannot be found by org.postgresql.jdbc41_9.4.0.build-1206
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_91]
        ... 17 more
`

Kind regards,
brstein.
##

**Comment by watou** [comment]
@lewie, would you have any thoughts about this issue?

**Comment by jotihojr** [comment]
This may be caused by https://github.com/pgjdbc/pgjdbc/issues/497. I'll throw the lastest postgresql jdbc driver into addons and see if that works.

Should probably bump the version in internal/JdbcConfiguration.java

**Comment by jotihojr** [comment]
Being I'm a newbie to openhab and OSGi in general, it took a while to til I got this right... But posgresql in the version 1211 works fine, albeit being simply too noisy...

After executing the following, jdb:postgresql seemingly works fine:
1. Perform the steps as brstein above.
2. Drop postgresql 1211 into addons.
3. Enter _bundle:uninstall <bundle id of postgresql 1206>_ at the openhab prompt.
4. Restart openhab and enter _log:set DEBUG org.openhab.persistence.jdbc_ at the prompt ASAP.
5. _tail -f userdata/logs/openhab.log_ in a seperate console and watch openhab do it's work.
`2016-10-21 16:01:06.423 [DEBUG] [org.openhab.persistence.jdbc        ] - BundleEvent STARTING - org.openhab.persistence.jdbc
2016-10-21 16:01:06.428 [DEBUG] [org.openhab.persistence.jdbc        ] - ServiceEvent REGISTERED - {org.openhab.core.persistence.PersistenceService, org.openhab.core.persistence.QueryablePersistenceService}={url=jdbc:postgresql://db.holland.int:5432/openhab, component.name=org.openhab.persistence.jdbc, jdbc.maximumPoolSize=10, service.config.category=persistence, service.config.description.uri=persistence:jdbc, user=openhab, service.pid=org.openhab.jdbc, service.config.label=JDBC Persistence, component.id=169, jdbc.minimumIdle=2, password=, service.id=294, service.bundleid=195, service.scope=bundle} - org.openhab.persistence.jdbc
2016-10-21 16:01:06.433 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::setItemRegistry
2016-10-21 16:01:06.441 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::activate: persistence service activated
2016-10-21 16:01:06.442 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::updateConfig
2016-10-21 16:01:06.445 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::JdbcConfiguration
2016-10-21 16:01:06.449 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: configuration.size = 11
2016-10-21 16:01:06.456 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: mandatory user=openhab
2016-10-21 16:01:06.461 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: mandatory password=<masked> password.length=10
2016-10-21 16:01:06.461 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: mandatory url=jdbc:postgresql://db.holland.int:5432/openhab
2016-10-21 16:01:06.462 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: found serviceName = 'none'
2016-10-21 16:01:06.462 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: Init Data Access Object Class: 'org.openhab.persistence.jdbc.db.JdbcPostgresqlDAO'
2016-10-21 16:01:06.481 [DEBUG] [nhab.persistence.jdbc.db.JdbcBaseDAO] - JDBC::initSqlTypes: Initialize the type array
2016-10-21 16:01:06.482 [DEBUG] [nhab.persistence.jdbc.db.JdbcBaseDAO] - JDBC::initSqlQueries: 'JdbcPostgresqlDAO'
2016-10-21 16:01:06.482 [DEBUG] [ersistence.jdbc.db.JdbcPostgresqlDAO] - JDBC::initSqlQueries: 'JdbcPostgresqlDAO'
2016-10-21 16:01:06.482 [DEBUG] [ersistence.jdbc.db.JdbcPostgresqlDAO] - JDBC::initSqlTypes: Initialize the type array sqlTypes=[SMALLINT, VARCHAR, VARCHAR, VARCHAR, NOW(), TIMESTAMP, TIMESTAMP, VARCHAR, VARCHAR, VARCHAR, SMALLINT, DOUBLE PRECISION]
2016-10-21 16:01:06.483 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: dBDAO ClassName=org.openhab.persistence.jdbc.db.JdbcPostgresqlDAO
2016-10-21 16:01:06.484 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: enableLogTime false
2016-10-21 16:01:06.489 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: load JDBC-driverClass was successful: 'org.postgresql.Driver'
2016-10-21 16:01:06.489 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: configuration complete. service=jdbc
2016-10-21 16:01:06.489 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::pingDB
2016-10-21 16:01:06.490 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::openConnection isDriverAvailable: true
2016-10-21 16:01:06.490 [INFO ] [persistence.jdbc.internal.JdbcMapper] - JDBC::openConnection: Driver is available::Yank setupDataSource
2016-10-21 16:01:06.625 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::setDbConnected true
2016-10-21 16:01:06.625 [DEBUG] [nhab.persistence.jdbc.db.JdbcBaseDAO] - JDBC::initAfterFirstDbConnection: Initializing step, after db is connected.
2016-10-21 16:01:06.653 [DEBUG] [ab.persistence.jdbc.utils.DbMetaData] - dbMajorVersion = '9'
2016-10-21 16:01:06.653 [DEBUG] [ab.persistence.jdbc.utils.DbMetaData] - dbMinorVersion = '4'
2016-10-21 16:01:06.654 [DEBUG] [ab.persistence.jdbc.utils.DbMetaData] - driverMajorVersion = '9'
2016-10-21 16:01:06.654 [DEBUG] [ab.persistence.jdbc.utils.DbMetaData] - driverMinorVersion = '4'
2016-10-21 16:01:06.654 [DEBUG] [ab.persistence.jdbc.utils.DbMetaData] - dbProductName = 'PostgreSQL'
2016-10-21 16:01:06.654 [DEBUG] [ab.persistence.jdbc.utils.DbMetaData] - dbProductVersion = '9.4.9'
2016-10-21 16:01:06.654 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::pingDB asking db for name as absolutely first db action, after connection is established.
2016-10-21 16:01:06.690 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::checkDBAcessability, first try connection: true
2016-10-21 16:01:06.702 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::createItemsTableIfNot
2016-10-21 16:01:06.702 [DEBUG] [ersistence.jdbc.db.JdbcPostgresqlDAO] - JDBC::doCreateItemsTableIfNot sql=CREATE TABLE IF NOT EXISTS items (itemid SERIAL NOT NULL, itemname VARCHAR(500) NOT NULL, CONSTRAINT items_pkey PRIMARY KEY (itemid))
2016-10-21 16:01:06.706 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::getItemIDTableNames
2016-10-21 16:01:06.707 [DEBUG] [nhab.persistence.jdbc.db.JdbcBaseDAO] - JDBC::doGetItemIDTableNames sql=SELECT itemid, itemname FROM items
2016-10-21 16:01:06.713 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::getName: returning name 'jdbc' for queryable persistence service.
2016-10-21 16:01:06.714 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::updateConfig: configuration complete for service=jdbc.
2016-10-21 16:01:06.714 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::getName: returning name 'jdbc' for queryable persistence service.
2016-10-21 16:01:06.715 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::getName: returning name 'jdbc' for queryable persistence service.
2016-10-21 16:01:06.716 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::getName: returning name 'jdbc' for queryable persistence service.
2016-10-21 16:01:06.716 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::getName: returning name 'jdbc' for queryable persistence service.
2016-10-21 16:01:06.716 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::getName: returning name 'jdbc' for queryable persistence service.
2016-10-21 16:01:06.716 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::getName: returning name 'jdbc' for queryable persistence service.
2016-10-21 16:01:06.719 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::getName: returning name 'jdbc' for queryable persistence service.
2016-10-21 16:01:06.724 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::getName: returning name 'jdbc' for queryable persistence service.
2016-10-21 16:01:06.731 [DEBUG] [org.openhab.persistence.jdbc        ] - BundleEvent STARTED - org.openhab.persistence.jdbc`

Therefore, I recommend bumbing the postgresql version in the openhab/openhab superpom.xml to 9.4.1211 and internal/JdbcConfiguration.java to 9.4.1208. If I may, I could do the work...
