### ISSUE TITLE
[http] timeout setting for "sendHttpGetRequest"

### ISSUE THREAD

**Issue by binderth** [openhab/openhab#4835]
## Expected Behavior
In the config-file (here http.cfg, openHAB2) you can define the timeout for http-binding:
```
# timeout in milliseconds for the http requests (optional, defaults to 5000)
timeout=20000
```
This timeout should be applied to every function/method of the binding, in my case also for `sendHttpGetRequest`.

## Current Behavior
Current Behaviour is, the timeout doesn't apply to the `sendHttpGetRequest` call.
I use the function in a rule:
```
	postUpdate(Nuki_EG_door_locked, OFF) 
	sendHttpGetRequest("http://192.168.xx.xx:8080/lockaction?token=xx&nukiid=xx&action=3")
```
at first, the item is changed, then the http-request ist sent (in this case a Nuki Smartlock, which holds the latch open for 5secs).
This is the result in the logfile:
```
2016-11-28 12:13:16.530 [INFO ] [.eclipse.smarthome.model.script.Nuki] - Der Zustand von Nuki wurde geändert: ON
2016-11-28 12:13:21.523 [ERROR] [.smarthome.model.script.actions.HTTP] - Fatal transport error: {}
java.io.IOException: java.util.concurrent.TimeoutException
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:236)
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:130)
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:86)
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:65)
	at org.eclipse.smarthome.model.script.actions.HTTP.sendHttpGetRequest(HTTP.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_111]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeOperation(XbaseInterpreter.java:1085)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeOperation(XbaseInterpreter.java:1060)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._invokeFeature(XbaseInterpreter.java:1046)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeFeature(XbaseInterpreter.java:991)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.smarthome.model.script.interpreter.ScriptInterpreter.invokeFeature(ScriptInterpreter.java:114)[127:org.eclipse.smarthome.model.script:0.9.0.201611191809]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:901)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:864)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:223)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:446)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:227)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:459)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:243)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:446)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:227)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:463)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:243)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:446)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:227)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluate(XbaseInterpreter.java:189)[143:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
	at org.eclipse.smarthome.model.script.runtime.internal.engine.ScriptImpl.execute(ScriptImpl.java:77)[128:org.eclipse.smarthome.model.script.runtime:0.9.0.201611191809]
	at org.eclipse.smarthome.model.script.engine.ScriptExecutionThread.run(ScriptExecutionThread.java:42)[127:org.eclipse.smarthome.model.script:0.9.0.201611191809]
Caused by: java.util.concurrent.TimeoutException
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:109)
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:655)
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:219)
	... 35 more
```
From my point of view, there's a timeout after 5secs, if I didn't configure something different...

## Possible Solution
1. apply the timeout of the config-file to all functions and methods within the binding
2. put in more arguments for those functions, which could be used freely, like `sendHttpGetRequest` and enable different timeouts depending on Code
3. both! :)

## Steps to Reproduce (for bugs)

1. define timeout >5000ms in config
2. use `sendHttpGetRequest` on a page loading longer than 5000ms
3. see timeout in log

## Context
In my case it's nothing broken, as the Nuki Smartlock is receiving the signals and behaving like intended. But there's ugly ERRORs in the logfile. In the Long run, I'd like to have an error-free log, so I can have notifications if there are any with an logfile-analyzer.
So, I could make a workaround using e.g. curl with `executeCommandLine`, so there's no more ERRORs in the logfile, but if there would be some problem with the Nuki-Call, it's a bit more complicated to get the answer (INFO or ERROR) in the openhab.log - if at all. I must check the system logs for ERRORs of curl also.
Plus, I could parse the answer of the requested URL  (in this case the Nuki Smartlock) for a success statement (in this case the answer is JSON and also tells me if the batteries are running low, which could then be updating an item, telling me to change them... ;) )

## Your Environment
* Version used: openHAB2, http-binding 1.9
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): JAVA8
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Rasbian Jessie (openHAB2 Image starter)

**Comment by watou** [comment]
Hi, the HTTP binding is not part of Eclipse SmartHome.  The `sendHttp*` actions built into ESH ought to have configurable timeouts (or perhaps arguments, but that seems inconvenient).  With that in mind, please re-open your issue over at the eclipse/smarthome issue tracker and close this one.

**Comment by binderth** [comment]
oh, sure. I'm sorry, I'm new to github and openHAB in a way.
I did a short search on the openhab repo and did find sendHttpGetRequest here:
* https://github.com/openhab/openhab-core/blob/8a7f5561b1652d1c080d2a7fdc823c8d4bf93b31/bundles/org.openhab.core.compat1x/src/main/java/org/openhab/io/net/actions/HTTP.java 

and now I also find it in the eclipse/smarthome repo here:
* https://github.com/eclipse/smarthome/blob/6dd1df77136a70ec55da6746be05bf65b78ba15b/bundles/model/org.eclipse.smarthome.model.script/src/org/eclipse/smarthome/model/script/actions/HTTP.java

sorry if this question is stupid: but which class is used, if invoked from within e.g. an openHAB rule?

**Comment by watou** [comment]
openHAB 2 is built on Eclipse SmartHome, which is itself partially based on the openHAB 1.x runtime.  Since there are no more 1.x runtime updates (only addons), it can only be changed in Eclipse SmartHome, to be used in a future openHAB 2 distro.

**Comment by binderth** [comment]
thanks! understood!

**Comment by binderth** [comment]
see: https://github.com/eclipse/smarthome/issues/2553

**Comment by kaikreuzer** [comment]
> sorry if this question is stupid: but which class is used, if invoked from within e.g. an openHAB rule?

Not stupid at all! The one in openhab-core (which IS part of openHAB 2) is only for backward compatibility reasons, since a couple of openHAB 1 bindings are using this class (in the org.openhab namespace), so it was not possible to remove it, but it had to be kept as part of the (optional) compatibility layer.

The HTTP class in eclipse/smarthome is indeed the one that is used when you create scripts and rules, so this is indeed the right one to adapt for your use case.

**Comment by szymic1** [comment]
Is there any workaround to this problem? In my rule I get data from weather service and from time to time I've got timeout :(
