### ISSUE TITLE
[onkyo binding] Event listener invoking error

### ISSUE THREAD

**Issue by hniemann** [openhab/openhab#4865]
Onkyo TX-NR609
OpenHub 1.8.3 + 1.8.3 addons 

Every time PWRQSTN is send I get the Event listener invoking error with a NullPointerException.

00:11:38.999 [DEBUG] [o.b.onkyo.internal.eiscp.Eiscp:563  ] - Test connection to 192.168.33.33:60128
00:11:38.999 [DEBUG] [o.b.onkyo.internal.eiscp.Eiscp:271  ] - Send command: PWRQSTN to 192.168.33.33:60128 (Socket[addr=/192.168.33.33,port=60128,localport=61554])
00:11:39.066 [ERROR] [o.b.onkyo.internal.eiscp.Eiscp:462  ] - Event listener invoking error
java.lang.NullPointerException: null
	at org.openhab.binding.onkyo.internal.OnkyoBinding.findDevice(OnkyoBinding.java:326) ~[bundlefile:na]
	at org.openhab.binding.onkyo.internal.OnkyoBinding.statusUpdateReceived(OnkyoBinding.java:338) ~[bundlefile:na]
	at org.openhab.binding.onkyo.internal.eiscp.Eiscp.waitStateMessages(Eiscp.java:457) [bundlefile:na]
	at org.openhab.binding.onkyo.internal.eiscp.Eiscp.access$1(Eiscp.java:329) [bundlefile:na]
	at org.openhab.binding.onkyo.internal.eiscp.Eiscp$DataListener.run(Eiscp.java:493) [bundlefile:na]

**Comment by 9037568** [comment]
Line 326 in [OnkyoBinding ](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoBinding.java#L326)isn't safe:
````
if (deviceConfig.getHost().equals(ip))
````

Can you provide a full log and your configurations?

**Comment by 9037568** [comment]
My analysis above was applied to the 1.8 branch code. Looking at the latest code in the master branch, this error should no longer occur with the latest snapshot.
