### ISSUE TITLE
Cannot use Alsa for audio in OH2

### ISSUE THREAD

**Issue by DaAwesomeP** [openhab/openhab#4907]
With `javasound` (no sound produced with both commands):
```
openhab> smarthome:audio play doorbell.mp3
openhab> smarthome:audio play test.wav
Exception in thread "Thread-1498" java.lang.UnsatisfiedLinkError: no icedtea-sound in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.classpath.icedtea.pulseaudio.SecurityWrapper.loadNativeLibrary(SecurityWrapper.java:66)
        at org.classpath.icedtea.pulseaudio.EventLoop.<clinit>(EventLoop.java:97)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:654)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
        at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:94)
        at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:75)
        at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:90)
        at org.eclipse.smarthome.io.javasound.internal.AudioPlayer.run(AudioPlayer.java:63)
openhab> smarthome:voice say Test
Exception in thread "Thread-82" java.lang.NoClassDefFoundError: Could not initialize class org.classpath.icedtea.pulseaudio.EventLoop
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:654)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
        at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:94)
        at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:75)
        at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:90)
        at org.eclipse.smarthome.io.javasound.internal.AudioPlayer.run(AudioPlayer.java:63)
```

With `enhancedjavasound` (no sound produced with both commands):
```
openhab> smarthome:audio play doorbell.mp3
openhab> smarthome:audio play test.wav
Exception in thread "Thread-1507" java.lang.NoClassDefFoundError: Could not initialize class org.classpath.icedtea.pulseaudio.EventLoop
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:654)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
        at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:94)
        at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:75)
        at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:90)
        at org.eclipse.smarthome.io.javasound.internal.AudioPlayer.run(AudioPlayer.java:63)
openhab> smarthome:voice say Test
Exception in thread "Thread-78" java.lang.UnsatisfiedLinkError: no icedtea-sound in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.classpath.icedtea.pulseaudio.SecurityWrapper.loadNativeLibrary(SecurityWrapper.java:66)
        at org.classpath.icedtea.pulseaudio.EventLoop.<clinit>(EventLoop.java:97)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:654)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
        at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:94)
        at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:75)
        at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:90)
        at org.eclipse.smarthome.io.javasound.internal.AudioPlayer.run(AudioPlayer.java:63)
```
I am running Debian Jessie headless with only Alsa installed (not PuslseAudio). PulseAudio was much harder to set up headless. I can use VLC headless and `aplay` just fine. I have `openjdk-8-jdk-headless` and `openjdk-8-jre-headless` v1.8.0u111.

So, there seems to be two problems: 1) a plugin for a browser plugin is missing, and 2) it assumes that I am using PulseAudio.

My goal is to get the new voice command system up and running.

**Comment by DaAwesomeP** [comment]
I just tried installing `libpulse-java` to no avail. I have a feeling that the headless version of OpenJDK does not include `icedtea-sound`. Is there any way around this? OpenHAB really ought to be able to be run headless. I've had no other problems so far.

**Comment by 9037568** [comment]
I don't believe this is an OH issue.

**Comment by 9037568** [comment]
If there is a defect here, it would appear to be in [ESH](http://github.com/eclipse/smarthome/issues).

I would suggest discussing on the [community forum](http://community.openhab.org).
