### ISSUE TITLE
Homekit Binding Bug with Color tag

### ISSUE THREAD

**Issue by semaf** [openhab/openhab#4964]
Getting Error with the item:

`Color TVLedLight  "Bed Color" <colorlight> (All) ["Lighting"]`

Log:
`2017-01-04 23:16:30.473 [ERROR] [lfe.hap.impl.connections.HttpSession] - Could not handle request
java.lang.NullPointerException
	at com.beowulfe.hap.characteristics.FloatCharacteristic.getValue(FloatCharacteristic.java:72)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.makeBuilder(BaseCharacteristic.java:71)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at com.beowulfe.hap.characteristics.FloatCharacteristic.makeBuilder(FloatCharacteristic.java:48)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at com.beowulfe.hap.characteristics.BaseCharacteristic.toJson(BaseCharacteristic.java:61)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at com.beowulfe.hap.impl.json.AccessoryController.toJson(AccessoryController.java:73)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at com.beowulfe.hap.impl.json.AccessoryController.listing(AccessoryController.java:39)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at com.beowulfe.hap.impl.connections.HttpSession.handleAuthenticatedRequest(HttpSession.java:70)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:47)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:15)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[186:org.openhab.io.homekit:2.0.0.201612301947]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]`

**Comment by 9037568** [comment]
This is an [OH2 issue](http://github.com/openhab/openhab2-addons/issues).

It appears to have already been logged there as [issue 1651](https://github.com/openhab/openhab2-addons/issues/1651).
