### ISSUE TITLE
percent-sign anywhere in OpenHAB path causes nullpointer exception error on linux 

### ISSUE THREAD

**Issue by ghost** [openhab/openhab#623]
If a percent-sign is in the path to openhab, even if it's is in the openhab root folder itself, causes the following error:

<pre><code>
user@machine:~/AnyPath/OpenHAB/Test%System$ ./start.sh 
Launching the openHAB runtime...
An exception occurred while writing to the platform log:
java.lang.NullPointerException
	at org.eclipse.equinox.launcher.Main.openLogFile(Main.java:2495)
	at org.eclipse.equinox.launcher.Main.log(Main.java:2328)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1449)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
Logging to the console instead.
!ENTRY org.eclipse.equinox.launcher 4 0 2013-12-01 17:58:04.836
!MESSAGE Exception launching the Eclipse Platform:
An exception occurred while writing to the platform log:
java.lang.NullPointerException
	at org.eclipse.equinox.launcher.Main.openLogFile(Main.java:2495)
	at org.eclipse.equinox.launcher.Main.log(Main.java:2328)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
Logging to the console instead.
!STACK
java.lang.IllegalArgumentException
	at sun.net.www.ParseUtil.decode(ParseUtil.java:202)
	at sun.net.www.protocol.file.Handler.openConnection(Handler.java:80)
	at sun.net.www.protocol.file.Handler.openConnection(Handler.java:72)
	at java.net.URL.openConnection(URL.java:971)
	at java.net.URL.openStream(URL.java:1037)
	at org.eclipse.equinox.launcher.Main.load(Main.java:1992)
	at org.eclipse.equinox.launcher.Main.loadProperties(Main.java:1964)
	at org.eclipse.equinox.launcher.Main.loadConfiguration(Main.java:1947)
	at org.eclipse.equinox.launcher.Main.processConfiguration(Main.java:1758)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:556)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

An error has occurred and could not be logged: 
null
</code></pre>

Obvious workaround: remove percent-sign from path

Issue is related to Ubuntu 13.10 64bit with OpenJDK:

java version "1.7.0_25"
OpenJDK Runtime Environment (IcedTea 2.3.10) (7u25-2.3.10-1ubuntu0.12.10.2)
OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)

Maybe someone could test it with the Oracle JDK.

**Comment by teichsta** [comment]
According to the POSIX portable filename spec (see http://stackoverflow.com/questions/2304221/what-character-sequence-should-i-not-allow-in-a-filename) '%' and '$'.

**Comment by teichsta** [comment]
closed due to inactivity …
