### ISSUE TITLE
Homematic Binding Problem with XMLRpc Connection to CCU

### ISSUE THREAD

**Issue by fasa01** [openhab/openhab#838]
Hi,

in the moment when a actor from the CCU side is not reacheable, it's looks as the complete XMLRpc stops working, i'm not sure if the communication runs later (after a CCU reconnect). Pls. have a look at this point.

The version i've tested: openhab 1.4 8.2.14, CCU2 2.7.16.

17:40:11.562 ERROR o.o.b.h.i.d.c.AbstractHMChannel[:99]- Exception occured.
org.openhab.binding.homematic.internal.xmlrpc.HomematicBindingException: org.apache.xmlrpc.XmlRpcException: Failure
        at org.openhab.binding.homematic.internal.xmlrpc.XmlRpcConnection.executeRPC(XmlRpcConnection.java:238)
        at org.openhab.binding.homematic.internal.xmlrpc.XmlRpcConnection.setValue(XmlRpcConnection.java:229)
        at org.openhab.binding.homematic.internal.device.channel.AbstractHMChannel.setValue(AbstractHMChannel.java:97)
        at org.openhab.binding.homematic.internal.bus.HomematicBinding.setStateOnDevice(HomematicBinding.java:241)
        at org.openhab.binding.homematic.internal.bus.HomematicBinding.internalReceiveCommand(HomematicBinding.java:171)
        at org.openhab.core.binding.AbstractBinding.receiveCommand(AbstractBinding.java:96)
org.apache.xmlrpc.XmlRpcException: Failure
        at org.openhab.binding.homematic.internal.xmlrpc.SameEncodingXmlRpcSun15HttpTransport.readResponse(SameEncodingXmlRpcSun15HttpTransport.java:57)
        at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:156)
        at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
        at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
        at org.apache.xmlrpc.client.XmlRpcClientWorker$1.run(XmlRpcClientWorker.java:80)
        at java.lang.Thread.run(Thread.java:744)
17:40:11.565 ERROR o.o.b.h.i.d.c.AbstractHMChannel[:100]- Could not setValue false of type class java.lang.Boolean on parameter KEQ0237515:1#STATE. Accepted value type: BOOL.
17:40:18.020 INFO  o.openhab.model.script.Startup[:53]- Startup executed
17:42:48.198 INFO  o.o.m.c.i.ModelRepositoryImpl[:97]- Refreshing model 'geraberg.rules'
17:42:52.574 ERROR o.o.b.h.i.d.c.AbstractHMChannel[:99]- Exception occured.
org.openhab.binding.homematic.internal.xmlrpc.HomematicBindingException: org.apache.xmlrpc.XmlRpcException: Failure
        at org.openhab.binding.homematic.internal.xmlrpc.XmlRpcConnection.executeRPC(XmlRpcConnection.java:238)
        at org.openhab.binding.homematic.internal.xmlrpc.XmlRpcConnection.setValue(XmlRpcConnection.java:229)
        at org.openhab.binding.homematic.internal.device.channel.AbstractHMChannel.setValue(AbstractHMChannel.java:97)
        at org.openhab.binding.homematic.internal.bus.HomematicBinding.setStateOnDevice(HomematicBinding.java:241)
        at org.openhab.binding.homematic.internal.bus.HomematicBinding.internalReceiveCommand(HomematicBinding.java:171)
        at org.openhab.core.binding.AbstractBinding.receiveCommand(AbstractBinding.java:96)
org.apache.xmlrpc.XmlRpcException: Failure
        at org.openhab.binding.homematic.internal.xmlrpc.SameEncodingXmlRpcSun15HttpTransport.readResponse(SameEncodingXmlRpcSun15HttpTransport.java:57)
        at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:156)
        at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
        at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
        at org.apache.xmlrpc.client.XmlRpcClientWorker$1.run(XmlRpcClientWorker.java:80)
        at java.lang.Thread.run(Thread.java:744)
17:42:52.577 ERROR o.o.b.h.i.d.c.AbstractHMChannel[:100]- Could not setValue false of type class java.lang.Boolean on parameter KEQ0237515:1#STATE. Accepted value type: BOOL.
17:42:58.926 INFO  o.openhab.model.script.Startup[:53]- Startup executed
17:43:17.931 ERROR org.quartz.core.JobRunShell[:222]- Job DEFAULT.2014-02-08T17:43:17.902+01:00: Proxy for org.eclipse.xtext.xbase.lib.Procedures$Procedure0: org.eclipse.xtext.xbase.impl.XClosureImplCustom@119627 (explicitSyntax: true) threw an unhandled Exception:
java.lang.RuntimeException: The name '<unkown>' cannot be resolved to an item or type.
        at org.openhab.model.script.interpreter.ScriptInterpreter.internalFeatureCallDispatch(ScriptInterpreter.java:67)
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateAbstractFeatureCall(XbaseInterpreter.java:658)
        at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291)
17:43:17.953 ERROR org.quartz.core.ErrorLogger[:2361]- Job (DEFAULT.2014-02-08T17:43:17.902+01:00: Proxy for org.eclipse.xtext.xbase.lib.Procedures$Procedure0: org.eclipse.xtext.xbase.impl.XClosureImplCustom@119627 (explicitSyntax: true) threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:224)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.lang.RuntimeException: The name '<unkown>' cannot be resolved to an item or type.
        at org.openhab.model.script.interpreter.ScriptInterpreter.internalFeatureCallDispatch(ScriptInterpreter.java:67)
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._evaluateAbstractFeatureCall(XbaseInterpreter.java:658)
        at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291)
17:44:39.060 INFO  o.o.m.c.i.ModelRepositoryImpl[:97]- Refreshing model 'geraberg.rules'
17:44:43.209 ERROR o.o.b.h.i.d.c.AbstractHMChannel[:99]- Exception occured.
org.openhab.binding.homematic.internal.xmlrpc.HomematicBindingException: org.apache.xmlrpc.XmlRpcException: Failure
        at org.openhab.binding.homematic.internal.xmlrpc.XmlRpcConnection.executeRPC(XmlRpcConnection.java:238)
        at org.openhab.binding.homematic.internal.xmlrpc.XmlRpcConnection.setValue(XmlRpcConnection.java:229)
        at org.openhab.binding.homematic.internal.device.channel.AbstractHMChannel.setValue(AbstractHMChannel.java:97)
        at org.openhab.binding.homematic.internal.bus.HomematicBinding.setStateOnDevice(HomematicBinding.java:241)
        at org.openhab.binding.homematic.internal.bus.HomematicBinding.internalReceiveCommand(HomematicBinding.java:171)
        at org.openhab.core.binding.AbstractBinding.receiveCommand(AbstractBinding.java:96)
org.apache.xmlrpc.XmlRpcException: Failure
        at org.openhab.binding.homematic.internal.xmlrpc.SameEncodingXmlRpcSun15HttpTransport.readResponse(SameEncodingXmlRpcSun15HttpTransport.java:57)
        at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:156)
        at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
        at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
        at org.apache.xmlrpc.client.XmlRpcClientWorker$1.run(XmlRpcClientWorker.java:80)
        at java.lang.Thread.run(Thread.java:744)
17:44:43.212 ERROR o.o.b.h.i.d.c.AbstractHMChannel[:100]- Could not setValue false of type class java.lang.Boolean on parameter KEQ0237515:1#STATE. Accepted value type: BOOL.

**Comment by itheiss** [comment]
@teichsta I am reviewing some issues to get the numer down. Could you please close this issue as  XML-RPC support was removed see https://github.com/openhab/openhab/wiki/Homematic-Binding

**Comment by teichsta** [comment]
according to @gerrieg this issue is outdated …
