### ISSUE TITLE
Support for Oregon Scientific UVN800

### ISSUE THREAD

**Issue by automaten** [openhab/openhab#868]
I would be glad if support for Oregon Scientific UVN800 (UV meter) was added to the RFXCOM binding.

Please see example below for exceptions thrown by the RFXCOM binding when receiving packet from UVN800 :

17:07:53.572 ERROR o.o.b.r.internal.RFXComBinding[:279] - Error occured during packet receiving, data: 095702F34500003E4F79
org.openhab.binding.rfxcom.internal.RFXComException: Message UV not implemented
        at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:120)
        at org.openhab.binding.rfxcom.internal.RFXComBinding$MessageLister.packetReceived(RFXComBinding.java:231)
        at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector$SerialReader.run(RFXComSerialConnector.java:202)
Caused by: java.lang.ClassNotFoundException: org.openhab.binding.rfxcom.internal.messages.RFXComUVMessage
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:190)
        at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.getMessageInterface(RFXComMessageFactory.java:115)
        ... 2 common frames omitted

The corresponding message in RFXmngr (not the same frame though):
------------------------------------------------
0957020B840000CA0070
Packettype    = UV
Subtype       = UV2 - UVN800
Sequence nbr  = 11
ID            = 33792
UV Level      = 0
Description = Low
Signal level  = 7
Battery       = Low
------------------------------------------------

If I can be of any help for testing, please let me know.

**Comment by Speederc** [comment]
Added by #3137. Can be closed.
