### ISSUE TITLE
Null Pointer Exception when multiplying

### ISSUE THREAD

**Issue by juelicher** [openhab/openhab#882]
I have the following code, which worked without errors for several month:

import org.openhab.core.library.types.*
import org.openhab.model.script.actions.*
import java.lang.Math
import java.util.Calendar
import java.util.Date
import java.util.TimeZone

val int LampsNightInterval   = 1800 
val int LampsMorningInterval =  900
val int StudyDelay           =   20 

rule "Switch lamps off in the morning"
when
	Item Gate_Light_Bright changed from OFF to ON or
	Time cron "15 50 07 * * ?"
then
	var int randomOffsetLamps
	...
        randomOffsetLamps = (Math::random()*LampsMorningInterval).intValue()
        ...
end

This morning I got the following exception:

2014-02-22 07:39:48.973 ERROR o.o.c.s.ScriptExecutionThread[:48]- Error during the execution of rule 'Switch lamps off in the morning'
java.lang.NullPointerException: null
	at org.openhab.model.script.lib.NumberExtensions.operator_multiply(NumberExtensions.java:42)
	at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeOperation(XbaseInterpreter.java:729)
	at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._featureCallOperation(XbaseInterpreter.java:713)

Sporadically I have seen similar exceptions when multiplying values in the past, but can not reproduce them.

**Comment by teichsta** [comment]
closed due to inactivity …
