### ISSUE TITLE
Homematic: Exception while trying to set temperature on HM-CC-RT-DN

### ISSUE THREAD

**Issue by itheiss** [openhab/openhab#957]
While trying to set the temperature via setpoint for the wireless thermostat HM-CC-RT-DN I get the following exception:

```
08:31:18.675 ERROR o.o.b.h.i.d.c.AbstractHMChannel[:99]- Exception occured.
org.openhab.binding.homematic.internal.xmlrpc.HomematicBindingException: org.apache.xmlrpc.XmlRpcException: Failure
	at org.openhab.binding.homematic.internal.xmlrpc.XmlRpcConnection.executeRPC(XmlRpcConnection.java:238)
	at org.openhab.binding.homematic.internal.xmlrpc.XmlRpcConnection.setValue(XmlRpcConnection.java:229)
	at org.openhab.binding.homematic.internal.device.channel.AbstractHMChannel.setValue(AbstractHMChannel.java:97)
	at org.openhab.binding.homematic.internal.bus.HomematicBinding.setStateOnDevice(HomematicBinding.java:241)
	at org.openhab.binding.homematic.internal.bus.HomematicBinding.internalReceiveCommand(HomematicBinding.java:171)
	at org.openhab.core.binding.AbstractBinding.receiveCommand(AbstractBinding.java:96)
Caused by: org.apache.xmlrpc.XmlRpcException: Failure
	at org.openhab.binding.homematic.internal.xmlrpc.SameEncodingXmlRpcSun15HttpTransport.readResponse(SameEncodingXmlRpcSun15HttpTransport.java:57)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:156)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
	at org.apache.xmlrpc.client.XmlRpcClientWorker$1.run(XmlRpcClientWorker.java:80)
	at java.lang.Thread.run(Thread.java:724)
08:31:18.676 ERROR o.o.b.h.i.d.c.AbstractHMChannel[:100]- Could not setValue 18.0 of type class java.lang.Double on parameter KEQ0515462:4#SET_TEMPERATURE. Accepted value type: FLOAT.
```

In my sitemap I have the following Setpoint defined
```Setpoint item=FF_BR_Heating_Setpoint minValue=5 maxValue=30 step=0.5```

And the corresponding item definition
```
Number FF_BR_Heating_Setpoint   "Sollwert - Schlafzimmer [%.1f °C]"   <temperature>   (gFF_Bedroom, gGR_LR_Heating)    {homematic="id=KEQ0515462, channel=4, parameter=SET_TEMPERATURE"}
```

I am using openHAB 1.5 from daily snapshots.

**Comment by itheiss** [comment]
Closing as everything ist working with the new HomeMatic binding by gerrieg.
